addons/rose/addon/components/rose/dialog/index.hbs
addons/rose/addon/components/rose/dialog/index.stories.mdx
addons/rose/addon/styles/rose/components/_dialog.scss

chore: 🤖 add support for dialog style and button text options

---

addons/rose/addon/components/rose/dialog/index.hbs
addons/rose/addon/components/rose/dialog/index.js
ui/core/app/components/pending-confirmations/index.hbs
ui/core/app/routes/application.js
ui/core/app/services/confirm.js
ui/core/app/templates/application.hbs
ui/core/tests/acceptance/projects-test.js
ui/core/translations/actions/en-us.yaml
ui/core/translations/en-us.yaml

Feautre abandon confirm

---

ui/desktop/electron-app/package.json
ui/desktop/electron-app/src/index.js
ui/desktop/electron-app/yarn.lock

Remove unmaintained devtron electron plugin

chore: Update electron to latest 9.3.2 version

---

ui/core/app/templates/scopes/scope.hbs
ui/core/mirage/scenarios/default.js

This PR exposes global scope IAM resources within the UI.

feat: 🎸 expose IAM resources in the global scope

---

addons/api/addon/models/host-set.js
addons/api/addon/models/role.js
addons/api/addon/serializers/role.js
addons/api/tests/unit/models/role-test.js
addons/api/tests/unit/serializers/role-test.js
ui/core/app/components/form/role/grants/index.hbs
ui/core/app/components/form/role/grants/index.js
ui/core/app/routes/scopes/scope/roles/role/grants.js
ui/core/mirage/config.js

fix: 🐛 fixes issue where grant strings become corrupted in ui

---

addons/api/addon/generated/models/role.js
addons/api/tests/unit/serializers/role-test.js
addons/rose/addon/components/rose/dropdown/index.hbs
addons/rose/addon/components/rose/dropdown/index.stories.mdx
addons/rose/addon/components/rose/form/radio/group/index.stories.mdx
addons/rose/addon/components/rose/form/radio/radio/index.hbs
addons/rose/addon/components/rose/form/radio/radio/index.stories.mdx
addons/rose/addon/styles/rose/components/dropdown/_index.scss
addons/rose/addon/styles/rose/components/dropdown/_item.scss
addons/rose/addon/styles/rose/components/form/_radio.scss
addons/rose/tests/dummy/app/templates/index.hbs
addons/rose/tests/integration/components/rose/form/radio/radio-test.js
ui/core/app/components/form/role/index.hbs
ui/core/app/components/form/role/index.js
ui/core/app/routes/scopes/scope/roles/role/index.js
ui/core/app/styles/app.scss
ui/core/app/templates/scopes/scope/roles/role/index.hbs
ui/core/mirage/factories/role.js
ui/core/package.json
ui/core/tests/acceptance/roles-test.js
ui/core/translations/form/en-us.yaml
yarn.lock

This PR introduces grant scope field support on roles via a radio select in the role form.

Feature role grant scope

---

addons/rose/addon/components/rose/form/radio/radio/index.hbs
addons/rose/addon/styles/rose/components/dropdown/_item.scss
addons/rose/tests/dummy/app/templates/index.hbs
ui/core/app/components/form/role/index.hbs
ui/core/app/styles/app.scss

Improves the appearance of radio fields that appear within a dropdown.

chore: 🤖 style dropdown radios with selection bg and checkmark

---

yarn.lock

Hopefully this addresses dependabot alerts

chore: reinstall with yarn

---

ui/desktop/app/styles/app.scss
ui/desktop/app/templates/application.hbs
ui/desktop/electron-app/src/index.js

style: 💄 make window title pretty and draggable

---

ui/admin/app/styles/_notify.scss
ui/desktop/app/styles/_notify.scss

fix: 🐛 super hacky fix to override notify styles

---

ui/desktop/app/routes/origin.js
ui/desktop/app/templates/origin.hbs
ui/desktop/app/templates/scopes/scope/authenticate/method.hbs
ui/desktop/config/environment.js
ui/desktop/package.json
yarn.lock

This PR improves both UX and DX.  Firstly, origin and auth fields get autofocus.  And in development, the origin field is auto populated with the current origin.  This allows developers to simply press enter twice to onboard.

Feature breezy onboarding

---

ui/desktop/app/routes/scopes/scope/projects/targets.js
ui/desktop/app/services/ipc.js
ui/desktop/electron-app/src/handlers.js
ui/desktop/electron-app/src/ipc-handler.js
ui/desktop/tests/unit/services/ipc-test.js

Introduces improved IPC handling for ipc-main.  Handlers are now allowed to throw errors, which are automatically passed back to the renderer as an IPC rejection.

Feature ipc errors

---

ui/admin/ember-cli-build.js
ui/desktop/ember-cli-build.js

app.js:  -201.99 kB (-9.83 kB gzipped)
vendor.js:  -0.11 mB (-5.53 kB gzipped)
Desktop size reduction
app.js:  -36.95 kB (-4.26 kB gzipped)
vendor.js:  -0.1 mB (-5.93 kB gzipped)

chore: minor tweak to reduce build sizes

---

ui/desktop/app/services/origin.js
ui/desktop/electron-app/package.json
ui/desktop/electron-app/src/content-security-policy.js
ui/desktop/electron-app/src/handlers.js
ui/desktop/electron-app/src/index.js
ui/desktop/electron-app/src/origin.js
ui/desktop/electron-app/src/runtime-settings.js
ui/desktop/electron-app/yarn.lock

This PR introduces a strict content security policy to the renderer process.  It also handles updating the CSP to dynamically allow the origin in `content-src`.

Feature csp

---

ui/desktop/app/routes/scopes/scope/projects/targets.js
ui/desktop/app/routes/scopes/scope/projects/targets/target/hosts.js
ui/desktop/app/templates/scopes/scope/projects/targets/index.hbs
ui/desktop/electron-app/package.json
ui/desktop/electron-app/src/boundary-cli.js
ui/desktop/electron-app/src/handlers.js
ui/desktop/electron-app/yarn.lock

This PR sanitizes/escapes input to the CLI and errors if values are not base62.  It also consolidates the multiple connect actions in the UI.

chore: 🤖 sanitize and validate input to CLI

---

ui/desktop/app/templates/scopes/scope/authenticate.hbs

style: Fix auth border expanding to bottom of screen

---

addons/core/translations/errors/en-us.yaml

chore: Add missing origin validation message

---

ui/desktop/app/controllers/scopes/scope/projects/targets/target/sessions.js
ui/desktop/app/routes/scopes/scope/projects/targets/target.js
ui/desktop/app/routes/scopes/scope/projects/targets/target/hosts.js
ui/desktop/app/routes/scopes/scope/projects/targets/target/sessions.js
ui/desktop/app/templates/scopes/scope/projects/targets/target/-actions.hbs
ui/desktop/app/templates/scopes/scope/projects/targets/target/-header.hbs
ui/desktop/app/templates/scopes/scope/projects/targets/target/sessions.hbs
ui/desktop/tests/unit/controllers/scopes/scope/projects/targets/target/sessions-test.js

Introduces sessions controller to handle sorting and filtering target sessions for current user.

refactor: Sort and filter active sessions in a target

---

ui/desktop/electron-app/config/forge.config.js
ui/desktop/electron-app/src/boundary-cli.js

Adds app version and commit; improves whitespace.

Chore about version

---

ui/desktop/app/templates/scopes/scope/projects/targets/index.hbs
ui/desktop/app/templates/scopes/scope/projects/targets/target/-header.hbs

chore: 🤖 tweak target "active" badge appearance

---

ui/desktop/electron-app/src/index.js
ui/desktop/electron-app/src/menu.js

chore: Hide devtools in production menu

---

ui/desktop/electron-app/src/index.js

Moving from 1024x768 to 1280x760

fix: Make default window size larger

---

CHANGELOG.md
ui/desktop/CHANGELOG.md

Proposed changelog takes the same approach as Boundary.

docs: add changelog

---

yarn.lock

Re-run yarn install to address some dependabot alerts.

chore: 🤖 rerun yarn install to update deps

---

ui/desktop/CHANGELOG.md
ui/desktop/electron-app/package.json
ui/desktop/electron-app/src/origin.js
ui/desktop/electron-app/yarn.lock

Use Electron's net request feature to validate the Boundary origin, rather than Axios.

Use Electron net request

---

ui/admin/app/routes/application.js
ui/admin/tests/acceptance/authentication-test.js
ui/desktop/app/routes/application.js

This resolves deprecation warnings from simple auth.

chore: 🤖 rip out deprecated route mixin

---

.github/workflows/ui-release-trigger.yml

Fixing tag issue to tigger release job

Fixing the TAG issue

---

.github/workflows/ui-release-trigger.yml

Fixing tag issue to tigger release job

Fix a tag parameter for the release pipeline

---

ui/desktop/app/controllers/scopes/scope/projects/sessions/index.js
ui/desktop/app/routes/scopes/scope/projects/sessions.js
ui/desktop/app/routes/scopes/scope/projects/targets.js

This PR adds API-based filtering of targets and sessions in desktop, removing some of the client-side filtering logic.

Feature desktop filtering - ICU-1169 ICU-1071

---

ui/desktop/CHANGELOG.md
ui/desktop/app/routes/scopes/scope/projects/targets.js

This ensures that the targets views (list and detail) are "live" and update as changes in the backend occur.

Chore poll targets - ICU-1103

---

addons/api/addon/adapters/application.js

chore: 🤖 remove getwithdefault

---

CONTRIBUTING.md

Inspired by https://github.com/hashicorp/boundary/pull/1014
@randallmorey @gsusmi You may want to add additional language in here for where to open PR's/Issues as it pertains to this repo (I think we're pointing folks over to hashicorp/boundary right now?).

docs: add contributing guide with pronoun expectations

---

addons/api/addon/generated/models/auth-method.js
addons/api/addon/generated/models/scope.js
addons/api/addon/models/auth-method.js
addons/api/addon/serializers/auth-method.js
addons/api/app/serializers/auth-method.js
addons/api/mirage/config.js
addons/api/mirage/scenarios/default.js
addons/api/mirage/serializers/auth-method.js
addons/api/tests/unit/serializers/auth-method-test.js
addons/core/addon/decorators/confirm.js
addons/core/translations/resources/en-us.yaml
addons/core/translations/states/en-us.yaml
addons/rose/addon/styles/rose/components/_badge.scss
ui/admin/app/controllers/scopes/scope/auth-methods/index.js
ui/admin/app/routes/scopes/scope/auth-methods.js
ui/admin/app/routes/scopes/scope/auth-methods/index.js
ui/admin/app/templates/application.hbs
ui/admin/app/templates/scopes/scope/auth-methods/auth-method/-actions.hbs
ui/admin/app/templates/scopes/scope/auth-methods/auth-method/-header.hbs
ui/admin/app/templates/scopes/scope/auth-methods/index.hbs
ui/admin/config/environment.js
ui/admin/package.json
ui/admin/tests/acceptance/auth-methods-test.js
ui/admin/tests/unit/controllers/scopes/scope/auth-methods/index-test.js
yarn.lock

Support for a **primary** auth method is coming soon as part of OIDC.  With primary support, only one auth method per scope will auto-vivify users.  While today all auth methods auto-vivify, in the future it's possible for _none_ to, which could lead to login failures.  It's important for users to understand the impact of the primary auth method and to elect one if needed.
Users may specify a primary auth method via the auth method form under "Manage".  A primary auth method may be removed as primary in the same dropdown.  When no primary is detected for the scope, a warning is issued to users of admin UI.  Lastly, the primary auth method is presented first at authentication time.
This feature is disabled by a feature flag until API support is released.  To test locally, enable the …

Feature primary auth method

---

addons/core/translations/actions/en-us.yaml
addons/core/translations/en-us.yaml
addons/rose/.storybook/main.js
addons/rose/addon/components/rose/frame/index.hbs
addons/rose/addon/components/rose/frame/index.stories.mdx
addons/rose/addon/styles/rose/components/_frame.scss
addons/rose/addon/styles/rose/components/_index.scss
addons/rose/app/components/rose/frame.js
addons/rose/package.json
addons/rose/tests/dummy/app/templates/index.hbs
addons/rose/tests/integration/components/rose/frame-test.js
ui/admin/app/templates/scopes/scope/authenticate.hbs
ui/admin/package.json
yarn.lock

This PR introduces a new component `Rose::Frame`, which is applied to the admin auth form per latest designs.

Style auth form

---

addons/core/translations/actions/en-us.yaml
ui/admin/app/routes/authentication-error.js
ui/admin/app/templates/authentication-error.hbs

feat: 🎸 show copyable error details in error page

---

README.md

Add documentation on how to connect Boundary UI, admin and desktop
version, to a Boundary local instance.

docs: ✏️ Connect Boundary UI to Boundary local instance

---

addons/rose/addon/components/rose/form/fieldset/index.hbs
addons/rose/addon/components/rose/form/fieldset/index.js
addons/rose/addon/components/rose/form/fieldset/index.stories.mdx
addons/rose/addon/styles/rose/components/form/_fieldset.scss
addons/rose/addon/styles/rose/components/form/_index.scss
addons/rose/app/components/rose/form/fieldset.js
addons/rose/tests/integration/components/rose/form/fieldset-test.js

Add a simple form fieldset component, basic storybook page and tests.
✅ Closes: ICU-1428

feat: 🎸 Add Form fieldset component

---

addons/api/mirage/scenarios/ipc.js
ui/desktop/CHANGELOG.md
ui/desktop/app/routes/application.js
ui/desktop/app/styles/app.scss
ui/desktop/app/templates/application.hbs
ui/desktop/electron-app/package.json
ui/desktop/electron-app/src/cli/index.js
ui/desktop/electron-app/src/cli/path.js
ui/desktop/electron-app/src/helpers/app-updater.js
ui/desktop/electron-app/src/helpers/spawn-promise.js
ui/desktop/electron-app/src/index.js
ui/desktop/electron-app/src/ipc/handlers.js
ui/desktop/electron-app/src/models/session.js
ui/desktop/electron-app/yarn.lock
ui/desktop/tests/acceptance/authentication-test.js
ui/desktop/tests/acceptance/projects-test.js
ui/desktop/tests/acceptance/targets-test.js
ui/desktop/tests/helpers/window-mock-ipc.js
yarn.lock

Todo:
- [Windows] ~~Run tests for killing spawned process on app quit~~
- [MacOS] Test _everything_

Use frameless desktop shell on Windows OS

---

ui/admin/package.json
ui/desktop/package.json
yarn.lock

Upgrade ember-a11y-testing package version

chore: 🤖 Upgrade ember-a11y-testing version

---

package.json
yarn.lock

Update resolution version for trim-newlines transitive dependency.

chore: 🤖 Update resolutions for trim-newlines

---

package.json
yarn.lock

Update resolution version for css-what transitive dependency.

chore: 🤖 Update resolutions for css-what

---

ui/desktop/electron-app/src/cli/path.js
ui/desktop/electron-app/src/config/menu.js
ui/desktop/electron-app/src/helpers/spawn-promise.js

This resolves a bug where the about dialog was not displaying in macOS desktop.

fix: about dialog should display properly

---

ui/desktop/electron-app/config/cli.js

Bump artifact version for 0.3.0 release

Bump artifact version for 0.3.0 release

---

addons/api/addon/models/session.js
addons/core/translations/actions/en-us.yaml
addons/core/translations/resources/en-us.yaml
addons/core/translations/states/en-us.yaml
ui/desktop/app/components/dialog-detail/index.hbs
ui/desktop/app/routes/scopes/scope/projects/targets.js
ui/desktop/app/styles/app.scss
ui/desktop/app/templates/application.hbs
ui/desktop/app/templates/scopes/scope/projects/targets.hbs
ui/desktop/electron-app/src/config/menu.js
ui/desktop/tests/acceptance/projects/targets-test.js
ui/desktop/tests/acceptance/projects/targets/hosts-test.js
ui/desktop/tests/acceptance/projects/targets/sessions-test.js
ui/desktop/tests/acceptance/scopes-test.js
ui/desktop/tests/integration/components/dialog-detail-test.js
yarn.lock

Assumptions:
- I Am just using a s simple dialog that eventually will be swap for the component. Even I created the component (at least the view) I am not using it yet, the dialog is the base of the component tho.
- The component does not have a route or model and I think it needs one.
- I discover and issue with the z-index within the dialog component. I will work on that later it is not blocking for now.

First iteration of connect dialog component

---

addons/core/translations/resources/en-us.yaml
ui/desktop/app/styles/app.scss
ui/desktop/app/templates/scopes/scope/projects/targets.hbs

PR to hook-in all recently created/updated components for connect dialog.

chore: Update components in connect dialog to latest

---

addons/rose/addon/styles/rose/components/table/_table.scss
ui/desktop/app/styles/app.scss
ui/desktop/app/templates/scopes/scope/projects/targets.hbs

Add hidden secret component within the view and delete duplicate code
(perhaps from a rebase)

feat: 🎸 Add Hidden secret component within the view

---

ui/desktop/app/styles/app.scss

style: Update z-index for connect dialog and overlay

---

package.json
yarn.lock

Update resolutions field in package json to avoid security vulnerability with glob-parent older versions.

chore: 🤖 Update resolutions for glob-parent

---

package.json
yarn.lock

Add normalize-url to resolutions due to security vulnerability.
**How I tested this?**
- Running build scripts (with all the varians) to make sure this change does not brake anything.

chore: 🤖 Add normalize-url to resolutions

---

package.json
yarn.lock

Update prismjs version in resolutions to avoid a security vulnerability.
How I tested this?
Running build scripts (with all the variants) to make sure this change does not brake anything.

chore: 🤖 Update prismjs version in resolutions

---

package.json
yarn.lock

Add minimist to resolutions to avoid a security vulnerability.
**How I tested this?**
Running build scripts (with all the variants) to make sure this change does not brake anything.

chore: 🤖 Update resolutions for minimist

---

package.json
yarn.lock

Add mem to resolutions to avoid a security vulnerability.
**How I tested this?**
Running build scripts (with all the variants) to make sure this change does not brake anything.

chore: 🤖 Add mem to resolutions

---

ui/admin/config/environment.js

This would enable conditional check in templates for credential feature: `{{#if (feature-flag 'credential-store')}}`

feat: Enable credential feature flag in dev mode for admin

---

ui/admin/app/styles/app.scss
ui/desktop/app/components/hidden-secret/index.hbs
ui/desktop/app/components/hidden-secret/index.js
ui/desktop/app/styles/app.scss
ui/desktop/app/templates/scopes/scope/projects/targets.hbs

Add toggle secret feature to the hidden secret component.
Secret hidden
Secret shown

feat: 🎸 Add toggle secret feature

---

.gitignore
addons/api/mirage/config.js
ui/admin/app/components/form/credential-store/index.hbs
ui/admin/app/controllers/scopes/scope/credential-stores/credential-store.js
ui/admin/app/router.js
ui/admin/app/routes/scopes/scope/credential-stores.js
ui/admin/app/routes/scopes/scope/credential-stores/credential-store.js
ui/admin/app/routes/scopes/scope/credential-stores/credential-store/index.js
ui/admin/app/templates/scopes/scope/credential-stores/credential-store.hbs
ui/admin/app/templates/scopes/scope/credential-stores/credential-store/-header.hbs
ui/admin/app/templates/scopes/scope/credential-stores/credential-store/-navigation.hbs
ui/admin/app/templates/scopes/scope/credential-stores/credential-store/index.hbs
ui/admin/app/templates/scopes/scope/credential-stores/index.hbs
ui/admin/config/environment.js
ui/admin/tests/unit/controllers/scopes/scope/credential-stores/credential-store-test.js
ui/admin/tests/unit/routes/scopes/scope/credential-stores/credential-store/index-test.js

Edit credential store

---

addons/rose/addon/styles/rose/components/form/_fieldset.scss

This pr updates the fieldset font size

style: 💄 update rose fieldset font-size

---

addons/core/translations/resources/en-us.yaml
ui/admin/app/router.js
ui/admin/app/routes/scopes/scope/credential-stores/credential-store/credential-libraries.js
ui/admin/app/routes/scopes/scope/credential-stores/credential-store/credential-libraries/index.js
ui/admin/app/templates/scopes/scope/credential-stores/credential-store/-navigation.hbs
ui/admin/app/templates/scopes/scope/credential-stores/credential-store/credential-libraries.hbs
ui/admin/app/templates/scopes/scope/credential-stores/credential-store/credential-libraries/index.hbs
ui/admin/tests/unit/routes/scopes/scope/credential-stores/credential-store/credential-libraries-test.js
ui/admin/tests/unit/routes/scopes/scope/credential-stores/credential-store/credential-libraries/index-test.js

feat: List credential libraries in a credential store

---

addons/rose/addon/components/rose/form/checkbox/index.hbs
addons/rose/addon/components/rose/form/checkbox/index.stories.mdx
addons/rose/addon/components/rose/form/radio/group/index.hbs
addons/rose/addon/components/rose/form/radio/group/index.stories.mdx
addons/rose/addon/components/rose/form/radio/radio/index.hbs
addons/rose/addon/components/rose/form/radio/radio/index.stories.mdx
addons/rose/addon/styles/rose/components/form/_checkbox.scss
addons/rose/addon/styles/rose/components/form/_radio.scss

This pr adds inline alignment support to radio and checkbox comp

feat: 🎸 add inline alignment support to checkbox and radio

---

addons/rose/addon/components/rose/form/index.hbs
ui/admin/app/components/form/credential-library/index.hbs

apologies for the PR spam. had issues with rebase and history so had to close the initial [PR](https://github.com/hashicorp/boundary-ui/pull/656)

fieldset usage

---

ui/admin/app/components/form/credential-library/index.hbs
ui/admin/app/router.js
ui/admin/app/routes/scopes/scope/credential-stores/credential-store/credential-libraries/credential-library.js
ui/admin/app/routes/scopes/scope/credential-stores/credential-store/credential-libraries/credential-library/index.js
ui/admin/app/templates/scopes/scope/credential-stores/credential-store/credential-libraries/credential-library.hbs
ui/admin/app/templates/scopes/scope/credential-stores/credential-store/credential-libraries/credential-library/-header.hbs
ui/admin/app/templates/scopes/scope/credential-stores/credential-store/credential-libraries/credential-library/-navigation.hbs
ui/admin/app/templates/scopes/scope/credential-stores/credential-store/credential-libraries/credential-library/index.hbs
ui/admin/app/templates/scopes/scope/credential-stores/credential-store/credential-libraries/index.hbs
ui/admin/tests/unit/routes/scopes/scope/credential-stores/credential-store/credential-libraries/credential-library-test.js
ui/admin/tests/unit/routes/scopes/scope/credential-stores/credential-store/credential-libraries/credential-library/index-test.js

Credential Library - Read

---

addons/api/package.json
yarn.lock

Update ember-fetch
**Risk:** [following the changelog](https://github.com/ember-cli/ember-fetch/blob/master/CHANGELOG.md) I see no risks.

chore: 🤖 Update ember-fetch

---

addons/core/translations/resources/en-us.yaml
ui/admin/app/controllers/scopes/scope/targets/target/credential-libraries.js
ui/admin/app/router.js
ui/admin/app/routes/scopes/scope/targets/target/credential-libraries.js
ui/admin/app/templates/scopes/scope/targets/target/-navigation.hbs
ui/admin/app/templates/scopes/scope/targets/target/credential-libraries.hbs
ui/admin/tests/unit/controllers/scopes/scope/targets/target/credential-libraries-test.js
ui/admin/tests/unit/routes/scopes/scope/targets/target/credential-libraries-test.js

List Credential Libraries in a Target

---

ui/admin/app/routes/scopes/scope/targets/target/credential-libraries.js
ui/admin/app/templates/scopes/scope/targets/target/credential-libraries.hbs
ui/admin/tests/acceptance/credential-library/credential-library-test.js
ui/admin/tests/acceptance/targets/credential-libraries-test.js

feat: Remove a Credential Library Added to a Target

---

addons/api/mirage/factories/account.js
addons/api/mirage/helpers/permissions.js
ui/admin/app/components/form/account/oidc/index.hbs
ui/admin/app/components/form/account/password/index.hbs
ui/admin/app/templates/scopes/scope/auth-methods/auth-method/accounts/account/-actions.hbs
ui/admin/app/templates/scopes/scope/auth-methods/auth-method/accounts/index.hbs
ui/admin/tests/acceptance/accounts/delete-test.js
ui/admin/tests/acceptance/accounts/read-test.js
ui/admin/tests/acceptance/accounts/update-test.js
yarn.lock

This PR applies base capabilities to singular accounts (`read`, `update`, `delete`, and `save`).

feat: 🎸 apply base singular capabilities to account

---

package.json
yarn.lock

I applied a change for this same library days ago. Apparently the pattern I provided to resolve versions is not correct. So there is no other solution but resolve just one version.

chore: 🤖 Update tar resolutions

---

ui/desktop/electron-app/package.json
yarn.lock

Add jszip to the resolutions to solve security vulnerability.

chore: 🤖 Add jszip to resolutions

---

addons/api/mirage/factories/role.js
ui/admin/app/components/form/role/index.hbs
ui/admin/app/templates/scopes/scope/roles/index.hbs
ui/admin/app/templates/scopes/scope/roles/role/-actions.hbs
ui/admin/jsconfig.json
ui/admin/tests/acceptance/roles-test.js
ui/admin/tests/acceptance/roles/delete-test.js
ui/admin/tests/acceptance/roles/read-test.js
ui/admin/tests/acceptance/roles/update-test.js
ui/desktop/jsconfig.json
yarn.lock

this pr adds read/delete/update capabilities to roles

feat: 🎸 role capabilities

---

addons/api/package.json
addons/auth/package.json
addons/core/package.json
addons/rose/package.json
ui/admin/package.json
ui/desktop/package.json
yarn.lock

Update ember-cli version to the latest stable version

chore: 🤖 Update ember-cli version

---

ui/desktop/electron-app/config/forge.config.js

@randallmorey , circling back with pre release feedback on cleaning up electron forge's config checks.

refactor: Add forge config checks into electron forge

---

ui/desktop/electron-app/package.json
ui/desktop/electron-app/yarn.lock

chore: 🤖 Update electron minor version

---

ui/desktop/electron-app/package.json
ui/desktop/electron-app/yarn.lock

Reverts hashicorp/boundary-ui#778 due to not tested build artifacts procedure.

Revert "chore: 🤖 Update electron-forge for desktop client"

---

addons/api/addon/abilities/target.js
addons/api/mirage/factories/target.js
addons/api/tests/unit/abilities/target-test.js
ui/admin/app/templates/scopes/scope/targets/target/credential-sources.hbs
ui/admin/app/templates/scopes/scope/targets/target/host-sources.hbs
ui/admin/tests/acceptance/targets/credential-sources-test.js
ui/admin/tests/acceptance/targets/host-sources-test.js

Adds an ability check for target remove *-sources.

Feature remove sources capability

---

addons/auth/package.json
yarn.lock

Fix ember-fetch unmet dependency warning from Yarn.

chore: 🤖 Fix ember-fetch unmet dependency

---

addons/api/addon/abilities/account.js
addons/api/addon/abilities/target.js
addons/api/app/abilities/account.js
addons/api/mirage/factories/account.js
addons/api/tests/unit/abilities/account-test-.js
ui/admin/app/templates/scopes/scope/auth-methods/auth-method/accounts/account/-navigation.hbs
ui/admin/tests/acceptance/accounts/set-password-test.js

Feature account capabilities

---

addons/rose/package.json
yarn.lock

Fix storybook/addoncs unmet peer dependency in Rose.

fix: 🐛 Fix rose storybook/addons unmet dependency

---

addons/api/addon/abilities/role.js
addons/api/app/abilities/role.js
addons/api/mirage/factories/role.js
addons/api/tests/unit/abilities/role-test.js
ui/admin/app/components/form/role/grants/index.hbs
ui/admin/app/templates/scopes/scope/roles/role/-actions.hbs
ui/admin/app/templates/scopes/scope/roles/role/principals.hbs
ui/admin/tests/acceptance/roles/grants-test.js
ui/admin/tests/acceptance/roles/principals-test.js

Adds perms UI for set-grants, add-principals, and remove-principals.

Feature role capabilities

---

ui/admin/app/templates/scopes/scope/sessions/index.hbs
ui/admin/config/environment.js
ui/desktop/config/environment.js

This pr integration toolbar onto sessions admin and enables feature flags in dev and test for both admin and desktop
Checkboxes will be integrated in the upcoming PRs

feat: 🎸 integrate toolbar onto session admin

---

addons/core/translations/resources/en-us.yaml
ui/admin/app/router.js
ui/admin/app/routes/scopes/scope/auth-methods/auth-method/managed-groups.js
ui/admin/app/routes/scopes/scope/auth-methods/auth-method/managed-groups/index.js
ui/admin/app/templates/scopes/scope/auth-methods/auth-method/-navigation.hbs
ui/admin/app/templates/scopes/scope/auth-methods/auth-method/accounts/index.hbs
ui/admin/app/templates/scopes/scope/auth-methods/auth-method/managed-groups.hbs
ui/admin/app/templates/scopes/scope/auth-methods/auth-method/managed-groups/index.hbs
ui/admin/config/environment.js
ui/admin/tests/unit/routes/scopes/scope/auth-methods/auth-method/managed-groups-test.js
ui/admin/tests/unit/routes/scopes/scope/auth-methods/auth-method/managed-groups/index-test.js

Add basic managed-groups list within auth methods.

Add managed-groups basic list route to admin

---

ui/admin/tests/acceptance/managed-groups/read-test.js

Add acceptance test to read managed groups

test: 💍 Add acceptance test to read managed groups

---

ui/admin/tests/acceptance/managed-groups/delete-test.js
ui/admin/tests/acceptance/managed-groups/read-test.js

Add acceptance test to delete managed groups.

test: 💍 Add acceptance test to delete managed groups

---

ui/admin/tests/acceptance/managed-groups/list-test.js

Add capabilities acceptance tests to list managed groups.

test: 💍 Add acceptance test to list managed groups

---

ui/admin/app/routes/scopes/scope/sessions.js
ui/desktop/app/routes/scopes/scope/projects/sessions.js

this pr adds default filters to both admin and desktop sessions
desktop:
admin: 
[admin](https://boundary-ui-vvbsp8hs9-hashicorp.vercel.app/scopes/s_xk1i4dk50v2/sessions)

Add default filters

---

ui/desktop/electron-app/package.json
ui/desktop/electron-app/yarn.lock

Add jsonpointer desktop resolution as per dependabot alert.

chore: 🤖 Add jsonpointer desktop resolutions

---

ui/desktop/electron-app/package.json
ui/desktop/electron-app/yarn.lock

Add json-schema to desktop resolution as per dependabot alert.

chore: 🤖 Add json-schema to desktop resolutions

---

package.json
yarn.lock

Add json-schema to global resolutions (root package.json). Apart from
our direct dependency within electron, in the admin, json-schema is a
dependency of a dependency.

chore: 🤖 Add json-schema to global resolutions

---

addons/api/package.json
addons/auth/package.json
addons/core/package.json
addons/rose/package.json
package.json
ui/admin/package.json
ui/desktop/package.json
yarn.lock

chore: 🤖 upgrade babel deps

---

addons/api/package.json
addons/auth/package.json
addons/core/package.json
addons/rose/package.json
package.json
ui/admin/app/routes/scopes/scope/authenticate/method/oidc.js
ui/admin/app/routes/scopes/scope/sessions.js
ui/admin/config/environment.js
ui/admin/package.json
ui/admin/tests/acceptance/authentication-test.js
ui/admin/tests/acceptance/sessions-test.js
ui/desktop/app/routes/scopes/scope/authenticate/method/oidc.js
ui/desktop/app/routes/scopes/scope/projects/sessions.js
ui/desktop/app/routes/scopes/scope/projects/targets.js
ui/desktop/package.json
ui/desktop/tests/acceptance/authentication-test.js
ui/desktop/tests/acceptance/projects/sessions-test.js
ui/desktop/tests/acceptance/projects/targets-test.js
yarn.lock

[Ember concurrency](https://www.npmjs.com/package/ember-concurrency) is notoriously complex and difficult to test.  Additionally, it uses deprecated APIs that prevent applications from fully upgrading Ember.
This PR replaces ember-concurrency with [ember-pollster](https://github.com/randallmorey/ember-pollster).  Ember Pollster is a lightweight alternative for simple polling use cases that is easy to test and compatible with Ember v4.0.  Our application poling code is now far simpler.
Previously, an ember-concurrency-based polling route might look like this:
```js
import { task, timeout } from 'ember-concurrency';
@task(function * () {
while(true) {
yield timeout(POLL_TIMEOUT_SECONDS * 1000);
yield this.refresh();
}
/* eslint-disable-next-line prettier/prettier */
}).drop() poller; …
```

Replace ember-concurrency with ember-pollster

---

ui/admin/app/routes/application.js

This PR refactors the `willTransition` method in the application route to a router event instead, due to this deprecation:  https://deprecations.emberjs.com/v3.x/#toc_deprecate-router-events

refactor: 💡 refactor due to router events deprecations

---

addons/rose/package.json
yarn.lock

chore: 🤖 Update flight icons to 2.0

---

addons/rose/package.json
yarn.lock

Fix unmeet peer dependency for @storybook/core-events.
Warning before the fix:
No warning after the fix:

fix: 🐛 Fix unmet peer dependency

---

addons/rose/package.json
yarn.lock

Fix storybook theming unmet peer dependency.
Warning before the fix:
No warning after the fix:

fix: 🐛 Fix storybook theming unmet peer dependency

---

addons/api/package.json
addons/auth/package.json
addons/core/package.json
addons/rose/package.json
ui/admin/package.json
ui/desktop/package.json

Update ember-cli-htmlbars.
No risk on the update [as per their changelog](https://github.com/ember-cli/ember-cli-htmlbars/blob/master/CHANGELOG.md)

chore: 🤖 Update ember cli htmlbars

---

addons/api/package.json
addons/auth/package.json
addons/core/package.json
addons/rose/package.json
ui/admin/package.json
ui/desktop/package.json

Reverts hashicorp/boundary-ui#915

Revert "chore: 🤖 Update ember cli htmlbars"

---

addons/api/addon/generated/models/host-set.js
addons/api/addon/models/host-set.js
addons/api/mirage/factories/host-set.js
addons/api/mirage/generated/factories/host-set.js
addons/api/tests/unit/models/host-set-test.js

Add basic type support for host-set.

feat: 🎸 Add basic type support for host-set

---

addons/api/addon/generated/models/host.js
addons/api/addon/models/host.js
addons/api/mirage/factories/host.js
addons/api/mirage/generated/factories/host.js
addons/api/tests/unit/models/host-test.js

feat: 🎸 Add host type basic support

---

addons/api/addon/generated/models/host-set.js
addons/api/addon/models/host-set.js
addons/api/addon/serializers/host-set.js
addons/api/mirage/factories/host-set.js
addons/api/tests/unit/serializers/host-set-test.js

Add new fields to host-set model.

feat: 🎸 Add new fields to host-set model

---

addons/core/translations/form/en-us.yaml
ui/admin/app/components/form/host-catalog/aws/index.hbs
ui/admin/app/components/form/host-catalog/azure/index.hbs
ui/admin/app/components/form/host-catalog/static/index.hbs
ui/admin/tests/acceptance/host-catalogs/host-sets/hosts-test.js

this pr moves provider translations from resource to form to be used across the resources.

Consolidate plugin provider translations

---

addons/api/mirage/factories/host.js
addons/api/mirage/generated/factories/host.js

Add host new fields to mirage.

feat: 🎸 Add host fields to mirage

---

ui/admin/app/components/form/host-set/aws/index.hbs
ui/admin/app/components/form/host-set/azure/index.hbs
ui/admin/app/components/form/host-set/index.hbs
ui/admin/app/routes/scopes/scope/host-catalogs/host-catalog/host-sets/host-set.js
ui/admin/app/routes/scopes/scope/host-catalogs/host-catalog/host-sets/index.js
ui/admin/app/routes/scopes/scope/host-catalogs/host-catalog/host-sets/new.js
ui/admin/app/templates/scopes/scope/host-catalogs/host-catalog/host-sets/host-set/index.hbs
ui/admin/app/templates/scopes/scope/host-catalogs/host-catalog/host-sets/new.hbs

This pr enables filter fields on both AWS and Azure host

updates to host-set plugin filters

---

addons/core/translations/en-us.yaml
ui/admin/app/components/form/host/aws/index.hbs
ui/admin/app/components/form/host/azure/index.hbs

This pr shows `ip_address` field on host AWS and Azure

chore: 🤖 show ip_address in host aws and azure

---

addons/api/package.json
addons/auth/package.json
addons/core/package.json
addons/rose/package.json
ui/admin/package.json
ui/desktop/package.json

Reverts hashicorp/boundary-ui#987

Revert "chore: 🤖 Update ember-cli-htmlbars"

---

addons/rose/package.json
yarn.lock

Update flight icons to the latest version.

chore: 🤖 Update flight icons

---

package.json
yarn.lock

Add `nanoid` to resolutions due to [dependabot alert](https://github.com/hashicorp/boundary-ui/security/dependabot/13).

chore: 🤖 Add nanoid to resolutions

---

package.json
yarn.lock

Update prismjs version in resolution as per [dependabot alert](https://github.com/hashicorp/boundary-ui/security/dependabot/23).

chore: 🤖 Update prism js resolutions version

---

ui/admin/config/environment.js

chore: 🤖 add ssh-target feature flag for admin

---

ui/desktop/electron-app/package.json
ui/desktop/electron-app/yarn.lock

Add plist dependency to resolutions in desktop client, as per [dependabot security vulnerability](https://github.com/hashicorp/boundary-ui/security/dependabot/25).

chore: 🤖 Add plist to desktop resolutions

---

package.json
yarn.lock

Add plist to resolutions, as per [dependabot alert to avoid security vulnerability](https://github.com/hashicorp/boundary-ui/security/dependabot/24).

chore: 🤖 Add plist to resolutions

---

package.json
yarn.lock

Add ansi-html to resolutions, as [per dependabot alert](https://github.com/hashicorp/boundary-ui/security/dependabot/26).

chore: 🤖 Resolutions ansi-html

---

package.json
yarn.lock

Add minimist to admin resolutions as per [dependabot alert](https://github.com/hashicorp/boundary-ui/security/dependabot/27).

chore: 🤖 Add minimist to admin resolutions

---

ui/desktop/electron-app/package.json
ui/desktop/electron-app/yarn.lock

Add minimist to desktop resolutions as per [dependabot alert](https://github.com/hashicorp/boundary-ui/security/dependabot/28).

chore: 🤖 Add minimist to desktop resolutions

---

addons/api/addon/generated/models/target.js
addons/api/tests/unit/serializers/target-test.js

✅ Closes: ICU-3887
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-3887)
Add `worker_filter` attribute to target model and matching tests

feat: 🎸 Add "worker_filter" attribute to target model

---

ui/admin/app/routes/scopes/scope/sessions.js

Reverts hashicorp/boundary-ui#1057

Revert "disable polling in admin UI"

---

ui/desktop/app/routes/scopes/scope/projects/sessions.js

Reverts hashicorp/boundary-ui#1058

Revert "fix: 🐛 Disable polling for sessions on Desktop"

---

ui/desktop/app/routes/scopes/scope/projects/targets.js
ui/desktop/app/templates/scopes/scope/projects/targets/index.hbs

✅ Closes: ICU-4024
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-4024)
:desktop_computer: [Desktop preview](https://boundary-ui-desktop-git-icu-4024-refresh-polli-de04d8-hashicorp.vercel.app/scopes/global/projects/targets)

feat: 🎸 refresh targets list view in desktop

---

ui/desktop/electron-app/src/index.js

Fix desktop client not correctly loading ember app url

fix: 🐛 Desktop client not correctly loading ember app url

---

addons/rose/addon/styles/rose/components/_icon.scss
ui/admin/app/styles/app.scss
ui/desktop/app/styles/app.scss

Add animation styles to refresh button while loading
:desktop_computer: [Desktop preview](https://boundary-ui-desktop-git-refresh-button-spinner-styles-hashicorp.vercel.app/scopes/global/projects/targets)

style: 💄 Update Refresh Button to animate when loading

---

addons/rose/addon/components/rose/toolbar/index.hbs
addons/rose/addon/components/rose/toolbar/index.stories.mdx
addons/rose/addon/styles/rose/components/toolbar/_toolbar.scss
addons/rose/package.json
addons/rose/tests/dummy/app/controllers/index.js
addons/rose/tests/dummy/app/templates/index.hbs
ui/admin/app/styles/app.scss
ui/admin/app/templates/scopes/scope/sessions/index.hbs
ui/desktop/app/styles/app.scss
ui/desktop/app/templates/scopes/scope/projects/sessions/index.hbs
ui/desktop/app/templates/scopes/scope/projects/targets/index.hbs

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-4198)
Created a regions toolbar so the refresh button can be aligned to the right
Admin:
Desktop:

Add toolbar regions to align refresh button to the right

---

ui/admin/config/environment.js

Update polling interval to 300 seconds (5 minutes)
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-4233)

Update polling interval to 300 seconds (5 minutes)

---

ui/desktop/electron-app/src/index.js

✅ Closes: ICU-4037
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-4037)
See [docs](https://www.electronjs.org/docs/latest/api/web-contents#contentssetwindowopenhandlerhandler) for more information about the handler
:desktop_computer: [Desktop preview](https://boundary-ui-desktop-o3ueblqr6-hashicorp.vercel.app/)

refactor: 💡 Update deprecated new window handler

---

ui/admin/app/router.js
ui/admin/app/routes/onboarding/quick-setup/choose-path.js
ui/admin/app/routes/onboarding/quick-setup/create-resources.js
ui/admin/app/routes/onboarding/quick-setup/success.js
ui/admin/app/templates/onboarding/quick-setup/choose-path.hbs
ui/admin/app/templates/onboarding/quick-setup/create-resources.hbs
ui/admin/app/templates/onboarding/quick-setup/success.hbs
ui/admin/tests/unit/routes/onboarding/quick-setup/choose-path-test.js
ui/admin/tests/unit/routes/onboarding/quick-setup/create-resources-test.js
ui/admin/tests/unit/routes/onboarding/quick-setup/success-test.js

This PR introduces route stubs for the onboarding/quick-setup flow.

chore: 🤖 stub out onboarding routes

---

ui/admin/app/routes/scopes/scope/sessions.js
ui/desktop/app/routes/scopes/scope/projects/sessions.js

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-4651)
Admin and Desktop now send a `include_terminated=true` query parameter when the terminated status filter is selected.

Chore include terminated

---

addons/core/translations/en-us.yaml
ui/admin/app/routes/onboarding/quick-setup/create-resources/success.js
ui/admin/app/styles/app.scss
ui/admin/app/templates/onboarding/quick-setup/create-resources/success.hbs
ui/admin/tests/acceptance/onboarding/success-test.js

✅ Closes: ICU-4785
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-4785)

feat: 🎸 Add Controller URL component to Success screen

---

ui/admin/config/environment.js
ui/desktop/config/environment.js

This will disable all SSH related work.

chore: 🤖 Disable ssh feature work

---

addons/rose/addon/styles/rose/components/header/_dropdown.scss
addons/rose/addon/styles/rose/components/layout/_global.scss
addons/rose/addon/styles/rose/components/layout/_sidebar.scss
addons/rose/addon/styles/rose/components/nav/_sidebar.scss

This PR applies darker sidebar styles to Boundary.

chore: apply darker color theme to sidebar

---

ui/admin/app/routes/onboarding/quick-setup/create-resources.js
ui/admin/tests/acceptance/onboarding/create-resource-test.js

✅ Closes: ICU-4821
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-4821)

refactor: 💡 Update routing to use project id in quick-start

---

addons/core/translations/en-us.yaml
ui/admin/app/routes/onboarding/quick-setup/create-resources.js
ui/admin/app/styles/app.scss
ui/admin/app/templates/onboarding/quick-setup/create-resources/success.hbs

Chore add onboarding role

---

addons/api/addon/models/role.js
ui/admin/app/components/form/role/index.hbs
ui/admin/app/components/form/role/index.js

Fixes a bug with the role grant scope field where it would not allow changes to grant scope.

fix: grant scope field should be functional

---

ui/admin/app/templates/onboarding/quick-setup/create-resources.hbs

Before:
`<title>Create Resources | CreateResources | Onboarding | Boundary</title>`
After:
`<title>Create Resources | Onboarding | Boundary</title>`
Before:
After:

refactor: 💡 Remove template file to fix onboarding flow titles

---

ui/desktop/electron-app/package.json
ui/desktop/electron-app/yarn.lock

**Why a batch upgrade?**
Upgrading dependencies for Desktop client is very time consuming and to make sure nothing breaks after the update, need to also run the CI (aproximetly 30 minutes). So decided to repeat that process per each dependency (which appear in this PR as commits) and also, repeat the whole process once all the dependency changes are within the branch.
Update a batch of dependencies within `ui/desktop/electron-app`:
- `@electron-forge/*`.
- `electron-is-dev`.
- `node-html-parser`.
- `electron-devtools-installer`.
Every commit is a dependency update. Each commit has been tested individually with:
- Run local dev environment.
- Build locally to validate nothing brakes.
- Entire Circle CI run. (provided screenshots)
Tested following the process described above with all the …

Chore upgrade desktop dependencies

---

.husky/pre-commit
.husky/prepare-commit-msg
README.md
addons/api/.eslintrc.js
addons/api/package.json
addons/auth/.eslintrc.js
addons/auth/package.json
addons/core/.eslintrc.js
addons/core/package.json
addons/rose/.eslintrc.js
addons/rose/package.json
package.json
ui/admin/.eslintrc.js
ui/admin/package.json
ui/desktop/.eslintrc.js
ui/desktop/.stylelintrc.json
ui/desktop/package.json
yarn.lock

Added pre-commit hook and disabled style rules that conflict with prettier.
Also ran the CLI tools for eslint and stylelint to confirm there were no conflicting rules, see [this](https://github.com/prettier/eslint-config-prettier#cli-helper-tool) and [this](https://github.com/prettier/eslint-config-prettier#cli-helper-tool)
You can test it by just doing another `yarn install`

Use precommit hooks

---

yarn.lock

fix: 🐛 Lock file discrepancy

---

addons/api/package.json
addons/rose/package.json
ui/admin/package.json
yarn.lock

chore: 🤖 Upgrade @babel/core

---

ui/admin/tests/acceptance/onboarding/success-test.js

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-5011)

test: 💍 onboarding tests

---

yarn.lock

Fix a yarn.lock file discrepancy

fix: 🐛 Fix lock file discrepancy

---

package.json
yarn.lock

Add `shell-quote` to resolutions as per [dependabot complain](https://github.com/hashicorp/boundary-ui/security/dependabot/44).

fix: 🐛 Add shell-quote to resolutions

---

addons/core/translations/README.md

✅ Closes: ICU-3872
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-3872)
This is the start of translation refactor work. We wanted to start with the README to define what each translation file is and what should live there. I wrote a brief overview for each category but feedback from the team would be great to have a consensus now to better help future changes to our translation files.

docs: ✏️ Create README for translations

---

ui/admin/app/routes/scopes/scope/roles/role/index.js

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-5304)
This PR resolves an issue where roles on projects may not be viewable in admin.

fix: 🐛 roles and principals on projects should be visible

---

addons/api/mirage/factories/credential-store.js
addons/api/mirage/factories/credential.js
addons/api/mirage/generated/factories/credential.js
addons/api/mirage/models/credential.js
addons/api/mirage/serializers/credential.js

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-5232)
Added credential mirage mocks.

Icu 5232 credential mirage mocks

---

addons/api/addon/generated/models/credential.js
addons/api/addon/serializers/credential.js
addons/api/mirage/config.js
addons/api/mirage/serializers/credential.js

Add missing mirage config GET and POST urls for credentials

fix: 🐛 Add missing mirage config urls for credentials

---

ui/admin/app/routes/scopes/scope/roles/role/index.js
ui/admin/tests/acceptance/credential-store/create-test.js
ui/admin/tests/acceptance/credential-store/delete-test.js
ui/admin/tests/acceptance/credential-store/read-test.js
ui/admin/tests/acceptance/credential-store/update-test.js

✅ Closes: ICU-5329
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-5329)
Acceptance tests revised to test both static and vault types of credential stores.

test: 💍 credential store CRUDL tests

---

addons/api/mirage/config.js

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-5388)
This pr adds support for delete and edit credentials when mirage is used
[credentials](https://boundary-ui-git-icu-5388-create-mirage-mock-fo-28503f-hashicorp.vercel.app/scopes/s_1sheljmjgm/credential-stores/cs_20nu3mgl4y/credentials)

chore: 🤖 add delete and patch mirage request for credential

---

addons/api/mirage/route-handlers/auth.js
addons/api/mirage/scenarios/default.js

Fixes a problem where the change password route may not be reachable.

fix: 🐛 change password route should not error

---

ui/admin/app/components/form/credential-store/index.hbs

:technologist: [Admin preview](https://boundary-ui-git-fix-new-credential-store-routi-c5c598-hashicorp.vercel.app/scopes/s_1sheljmjgm/credential-stores/new)

fix: 🐛 Fix routing issue for new credential stores

---

package.json
yarn.lock

fixes per [dependabot alert](https://github.com/hashicorp/boundary-ui/security/dependabot/40)

chore: 🤖 jpeg-js dependebot update

---

ui/admin/app/templates/scopes/scope.hbs
ui/admin/config/environment.js

Add a feature flag for the BYOW work.

fix: 🐛 Add feature flag for BYOW

---

addons/api/addon/serializers/host-set.js
addons/api/mirage/factories/host-set.js

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-5616)
Fixes normalization intended to support both string and array typed `filters` fields.
Closes hashicorp/boundary#2103

fix: 🐛 fixes host set attributes field types

---

ui/admin/app/components/auth-methods/auth-method/actions/index.hbs
ui/admin/app/components/auth-methods/auth-method/header/index.hbs
ui/admin/app/templates/scopes/scope/auth-methods/index.hbs
ui/admin/config/environment.js
ui/admin/tests/acceptance/auth-methods/create-test.js

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-5596)
Remove the primary_auth_method feature flag and its references

chore: 🤖 remove primary_auth_method feature flag

---

ui/admin/app/templates/scopes/scope/auth-methods/index.hbs
ui/admin/config/environment.js

✅ Closes: ICU-5597
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-5597)

chore: 🤖 remove oidc-crud feature flag

---

ui/admin/app/components/auth-methods/auth-method/actions/index.hbs
ui/admin/app/components/auth-methods/auth-method/nav/index.hbs
ui/admin/config/environment.js

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-5600)
removes managed_groups feature flag

chore: 🤖 remove managed_groups feature flag

---

ui/admin/app/templates/scopes/scope/sessions/index.hbs
ui/admin/config/environment.js
ui/desktop/app/templates/scopes/scope/projects/sessions/index.hbs
ui/desktop/app/templates/scopes/scope/projects/targets/index.hbs

✅ Closes: ICU-5599
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-5599)
🧑‍💻 [Admin Preview](https://boundary-ui-git-icu-5599-remove-filter-feature-flag-hashicorp.vercel.app/scopes/s_1sheljmjgm/sessions)

chore: 🤖 remove filter feature flag

---

addons/api/addon/generated/models/credential.js
addons/api/addon/serializers/credential.js
addons/api/tests/unit/models/credential-test.js

✅ Closes: ICU-5645
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-5645)

feat: 🎸 Update credential model with ssh private key attributes

---

addons/api/addon/models/target.js
addons/api/addon/serializers/target.js
addons/api/mirage/config.js
addons/api/mirage/serializers/target.js
addons/api/tests/unit/models/target-test.js
addons/api/tests/unit/serializers/application-test.js
addons/api/tests/unit/serializers/target-test.js
ui/admin/app/controllers/scopes/scope/targets/target/add-credential-sources.js
ui/admin/app/routes/scopes/scope/targets/target/credential-sources.js

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-5554)
This pr renames `application_credential_source_ids` to `brokered_credential_source_ids` within the target model, serializer, and related tests and mirage

chore: 🤖 Introduce brokered_credential_sources

---

addons/api/mirage/config.js
addons/auth/addon/authenticators/base.js
addons/auth/tests/unit/authenticators/base-test.js
addons/core/addon/authenticators/password.js

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-5455)
Changes the deauth request from a POST at `/scopes/{id}:deauthenticate` to a DELETE at `/auth-tokens/{id}`.

refactor: 💡 deauth should delete the auth token

---

addons/api/mirage/factories/credential.js
addons/api/mirage/serializers/credential.js
addons/core/translations/resources/en-us.yaml

✅ Closes: ICU-5647
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-5647)
Update mirage to mock SSH Private key credential types

feat: 🎸 Add SSH Private Key mirage support

---

ui/admin/app/components/form/credential/index.hbs
ui/admin/app/controllers/scopes/scope/credential-stores/credential-store/credentials/new.js
ui/admin/app/routes/scopes/scope/credential-stores/credential-store/credentials/new.js
ui/admin/app/templates/scopes/scope/credential-stores/credential-store/credentials/new.hbs

✅ Closes: ICU-5649
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-5649)
🧑‍💻 [Admin Preview](https://boundary-ui-git-icu-5649-create-new-route-for-b1ba89-hashicorp.vercel.app/scopes/s_1sheljmjgm/credential-stores/cs_20nu3mgl4y/credentials/new)
Add query param to the credential route in order to support the new ssh
private key type

feat: 🎸 Update the credential route to support both types

---

addons/api/addon/serializers/credential.js

tested against boundary instance

fix: 🐛 disable scope serialization for username_password credential type

---

addons/api/addon/abilities/target.js
addons/api/addon/models/target.js
addons/api/mirage/config.js
addons/api/tests/unit/abilities/target-test.js
addons/api/tests/unit/models/target-test.js
addons/core/translations/resources/en-us.yaml
ui/admin/app/components/form/target/add-brokered-credential-sources/index.hbs
ui/admin/app/components/form/target/add-brokered-credential-sources/index.js
ui/admin/app/components/targets/target/actions/index.hbs
ui/admin/app/components/targets/target/nav/index.hbs
ui/admin/app/controllers/scopes/scope/targets/target/add-brokered-credential-sources.js
ui/admin/app/controllers/scopes/scope/targets/target/brokered-credential-sources.js
ui/admin/app/router.js
ui/admin/app/routes/scopes/scope/targets/target/add-brokered-credential-sources.js
ui/admin/app/routes/scopes/scope/targets/target/brokered-credential-sources.js
ui/admin/app/templates/scopes/scope/targets/target/add-brokered-credential-sources.hbs
ui/admin/app/templates/scopes/scope/targets/target/brokered-credential-sources.hbs
ui/admin/tests/acceptance/targets/credential-sources-test.js
ui/admin/tests/unit/controllers/scopes/scope/targets/target/credential-sources-test.js
ui/admin/tests/unit/routes/scopes/scope/targets/target/add-credential-sources-test.js
ui/admin/tests/unit/routes/scopes/scope/targets/target/credential-sources-test.js

Jira- https://hashicorp.atlassian.net/browse/ICU-5575
This pr updates the existing `credential source` to `brokered credential source`.  
https://boundary-ui-git-refactor-credential-sources-to-9feb14-hashicorp.vercel.app/scopes/s_1sheljmjgm/targets/t_2p8vm6smug

Refactor credential sources to brokered credential sources

---

addons/api/addon/serializers/credential.js
addons/api/tests/unit/serializers/credential-test.js

✅ Closes: ICU-5731
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-5731)
update credential serializer to delete password attribute if empty
string or null allowing the user to update just the username if needed.

refactor: 💡 update credential serializer to delete password

---

addons/core/translations/resources/en-us.yaml
ui/admin/app/router.js

This pr adds new translation strings for injected application cred sources and new routes

Add injected application credential support

---

ui/admin/config/environment.js

✅ Closes: ICU-5952
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-5952)
Enable Static Credentials flag for Production

feat: 🎸 Enable Static Credentials flag for Production

---

addons/api/mirage/factories/credential-store.js

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-5990)

Icu 5990 api add worker filter attribute to credential store mirage mock

---

addons/core/translations/resources/en-us.yaml
ui/admin/app/templates/scopes/scope/workers/index.hbs

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-6044)
- Update workers list view to include header and data for `release_version`

ICU-6044 Update workers list view

---

addons/api/addon/generated/models/credential-store.js
addons/api/mirage/factories/credential-store.js
addons/api/tests/unit/serializers/credential-store-test.js

Add worker_filter attribute to vault type credential store model
✅ Closes: ICU-5988
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-5988)
Mirage and serializer PRs to follow

refactor: 💡 Add worker_filter to vault credential stores

---

addons/api/addon/generated/models/worker.js
addons/api/mirage/generated/factories/worker.js
addons/core/translations/form/en-us.yaml
addons/core/translations/resources/en-us.yaml
ui/admin/app/components/form/worker/index.hbs
ui/admin/app/templates/scopes/scope/workers/index.hbs

Update worker modeel for `release_version` field
✅ Closes: ICU-6044
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-6044)
- Updated worker model to obtain `release_version` field

feat: 🎸 Update worker model

---

ui/admin/config/environment.js

✅ Closes: ICU-6054
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-6054)

chore: 🤖 Add new flag for vault-worker-filter, ENT/HCP only

---

ui/admin/config/environment.js
ui/desktop/config/environment.js

Disables features which are not ready yet.

chore: 🤖 disable features

---

addons/core/translations/resources/en-us.yaml
ui/admin/app/components/form/credential-store/vault/index.hbs
ui/admin/config/environment.js

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-5991)
[admin-ui](https://boundary-ui-git-icu-5991-ui-add-worker-filter-9fe9ca-hashicorp.vercel.app/scopes/s_1sheljmjgm/credential-stores/cs_ucau082vov)
doc link is added [here](https://github.com/hashicorp/boundary/pull/2447)

Icu 5991 UI add worker filter form field for vault type credential stores

---

ui/admin/app/routes/onboarding/quick-setup/create-resources.js

✅ Closes: ICU-6094
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-6094)

refactor: 💡 Update Quick Setup resource names

---

addons/core/translations/form/en-us.yaml
addons/core/translations/resources/en-us.yaml

✅ Closes: ICU-6107
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-6107)
:technologist: [Admin preview](https://boundary-ui-git-icu-6107-host-catalog-updates-hashicorp.vercel.app/scopes/s_1sheljmjgm/host-catalogs/new?type=azure)

refactor: 💡 Update Host Catalog form labels and help text

---

addons/rose/addon/components/rose/dropdown/index.stories.mdx
addons/rose/addon/components/rose/dropdown/section/index.hbs

Add the ability to include an optional icon for dropdown sections.

feat: 🎸 Add optional icon for dropdown section

---

addons/api/addon/models/worker.js
ui/admin/app/routes/scopes/scope/workers/index.js
ui/admin/app/templates/scopes/scope/workers/index.hbs

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-6036)
:technologist: [Admin preview](https://boundary-ui-git-icu-6036-update-filter-dropdow-cff8ec-hashicorp.vercel.app/)
Change the dropdown filter to support filtering down by key/value pairs for the tags.
Still depends on #1335. Will rebase once it makes it in.

Icu 6036 update filter dropdown for tags in list view

---

ui/admin/config/environment.js

chore: 🤖 Enable BYOW feature

---

addons/api/addon/models/credential.js
addons/api/tests/unit/models/credential-test.js
ui/admin/app/templates/scopes/scope/targets/target/brokered-credential-sources.hbs
ui/admin/app/templates/scopes/scope/targets/target/injected-application-credential-sources.hbs

✅ Closes: ICU-6155
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-6155)
:technologist: [Admin preview](https://boundary-ui-git-icu-6155-cannot-navigate-to-us-5a5c71-hashicorp.vercel.app/scopes/s_1sheljmjgm/targets/t_b35k0n6ks4/brokered-credential-sources)

refactor: 💡 fix routing for static credentials from targets

---

addons/api/addon/serializers/credential-store.js
addons/api/tests/unit/serializers/credential-store-test.js
ui/admin/app/components/form/credential-store/vault/index.hbs

https://hashicorp.atlassian.net/browse/ICU-6228

fix: 🐛 clear token on normalization

---

ui/admin/app/styles/app.scss

Fix SCSS lint issues
CI failing because the lint issues before the changes:

fix: 🐛 Fix SCSS lint issues

---

addons/core/translations/en-us.yaml

style: 💄 Fix 2 translation typos

---

addons/rose/addon/modifiers/code-mirror.js
addons/rose/addon/modifiers/on-click-inside.js
addons/rose/addon/modifiers/on-click-outside.js
addons/rose/package.json
ui/admin/package.json
ui/desktop/package.json
yarn.lock

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-6353)
Update `ember-modifier` to the latest v3 `3.2.7` in preparation for `ember-modifier` v4 and ember 4 upgrade.
Refactored `code-mirror` modifier to a functional approach following [migration notes](https://github.com/ember-modifier/ember-modifier/blob/master/MIGRATIONS.md#migrations) from [ember-modifier project](https://github.com/ember-modifier/ember-modifier).
For testing checkout creating a new worker page and validate still working as before.

Chore update ember modifier

---

ui/admin/app/styles/app.scss
ui/desktop/app/styles/app.scss

Reverts hashicorp/boundary-ui#1381

Revert "feat: 🎸 remove animation when user specifies reduced motion"

---

yarn.lock

fix: 🐛 Fix missing yarn lock

---

addons/core/translations/resources/en-us.yaml
ui/admin/app/controllers/scopes/scope/credential-stores/credential-store/credentials/new.js
ui/admin/app/templates/scopes/scope/credential-stores/credential-store/credentials/new.hbs
yarn.lock

:tickets: [✅ Closes: icu-6725](https://hashicorp.atlassian.net/browse/icu-6725)
:technologist: [Admin preview](https://boundary-ui-git-chore-credentials-new-context-hashicorp.vercel.app/scopes/s_1sheljmjgm/credential-stores/cs_20nu3mgl4y/credentials/new)

chore: 🤖 improve credentials/new titling - icu-6725

---

addons/core/tests/integration/helpers/relative-datetime-live-test.js

Fixes flakey relative datetime render tests.

fix: 🐛 fix broken relative datetime live render tests

---

addons/api/mirage/config.js

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-6747)
Before:
After:
[Auth method](https://boundary-pwf6aobs9-hashicorp.vercel.app/scopes/s_id6ozx3wue/auth-methods)

fix: 🐛 add state to oidc form

---

ui/admin/app/styles/app.scss

https://hashicorp.atlassian.net/browse/ICU-7028

chore: 🤖 quick setup layout

---

addons/auth/.ember-cli
addons/auth/.eslintignore
addons/auth/.eslintrc.js
addons/auth/.npmignore
addons/auth/.prettierignore
addons/auth/config/ember-try.js
addons/auth/package.json
addons/auth/tests/dummy/app/index.html
addons/auth/tests/dummy/config/ember-cli-update.json
addons/auth/tests/dummy/config/environment.js
addons/auth/tests/helpers/index.js
addons/auth/tests/index.html
yarn.lock

**Be aware this merges to `refactor-upgrade-ember-4` long living branch.**
Upgrade from Ember 3.x to Ember 4.4 LTS within `addons/auth`.

Ember upgrade 4.4 LTS addons/auth

---

ui/admin/tests/acceptance/targets/create-test.js
ui/admin/tests/acceptance/targets/delete-test.js
ui/admin/tests/acceptance/targets/host-sources-test.js
ui/admin/tests/acceptance/targets/list-test.js
ui/admin/tests/acceptance/targets/update-test.js

✅ Closes: ICU-6974
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-6974)
Refactor acceptance tests in targets folder.

refactor: 💡 acceptance tests in targets folder

---

addons/core/.ember-cli
addons/core/.eslintignore
addons/core/.eslintrc.js
addons/core/.npmignore
addons/core/.prettierignore
addons/core/package.json
addons/core/tests/dummy/app/index.html
addons/core/tests/dummy/config/ember-cli-update.json
addons/core/tests/dummy/config/environment.js
addons/core/tests/helpers/index.js
addons/core/tests/index.html
addons/core/tests/integration/helpers/format-date-iso-human-test.js
addons/core/tests/integration/helpers/format-date-iso-test.js
addons/core/tests/integration/helpers/relative-datetime-live-test.js
yarn.lock

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-6813)
Upgrade to Ember 4.4 within `addon/core`

Refactor upgrade ember 4 addon core

---

ui/admin/tests/acceptance/credential-store/credentials/list-test.js

✅ Closes: ICU-6807
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-6807)

test: 💍 update list credential tests

---

ui/admin/app/components/form/role/index.hbs
ui/admin/tests/acceptance/roles/create-test.js
ui/admin/tests/acceptance/roles/update-test.js

chore: 🤖 update role form fields to hds

---

.husky/pre-commit

Removed `yarn test` from commit hooks

chore: 🤖 Remove yarn test from commit hook

---

addons/core/translations/form/en-us.yaml
addons/rose/package.json
ui/admin/app/components/form/target/details/index.hbs
ui/admin/tests/acceptance/targets/create-test.js
ui/admin/tests/acceptance/targets/update-test.js
yarn.lock

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-7512)
Migrate Target form to use HDS components
Added this [addon](https://github.com/mainmatter/ember-test-selectors) for testing purposes. This allows us to use `data-test-*` attributes for testing and will remove these attributes in production environments.
:technologist: [Admin preview](https://boundary-ui-git-icu-7512-target-form-hds-migration-hashicorp.vercel.app/scopes/s_1sheljmjgm/targets/new)

refactor: 💡 Migrate Target form to use HDS components

---

addons/api/.prettierrc.js
addons/auth/.prettierrc
addons/auth/.prettierrc.js
addons/core/.prettierrc.js
addons/rose/.prettierrc
addons/rose/.prettierrc.js
ui/admin/.prettierrc
ui/admin/.prettierrc.js
ui/desktop/.prettierrc
ui/desktop/.prettierrc.js

✅ Closes: ICU-6851
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-6851)
Clean up prettier config files.

refactor: 💡 Clean up prettier config files

---

addons/core/translations/resources/en-us.yaml
ui/admin/app/components/form/target/details/index.hbs
ui/admin/app/components/form/target/details/index.js
ui/admin/app/styles/app.scss
ui/admin/tests/acceptance/targets/create-test.js
ui/admin/tests/acceptance/targets/read-test.js
ui/admin/tests/acceptance/targets/update-test.js

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-7381)
Adds the deprecation message for worker filters and disables the field. New egress and ingress filter fields will be add in following stories.

UI target worker filter deprecation message

---

addons/api/addon/serializers/credential.js
addons/api/tests/unit/serializers/credential-test.js
ui/admin/app/routes/scopes/scope/credential-stores/credential-store/credentials/new.js
ui/admin/tests/acceptance/credential-store/credentials/create-test.js

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-7550)
Remove json_object from payload for non-json type credentials

fix: 🐛 Remove json_object from payload for non-json credentials

---

ui/admin/config/environment.js

✅ Closes: ICU-7547
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-7547)
Add feature flag for vault ssh certificate work. We currently will only be supporting injected application credentials so for now only need it in admin.

feat: 🎸 Add feature flag for vault ssh certificate

---

addons/core/translations/resources/en-us.yaml
ui/admin/app/components/ordered-series-diagram/index.hbs
ui/admin/app/components/worker-diagram/index.hbs
ui/admin/app/components/worker-diagram/single-filter/index.hbs
ui/admin/tests/integration/components/worker-diagram/index-test.js
ui/admin/tests/integration/components/worker-diagram/single-filter/index-test.js

✅ Closes: ICU-7579
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-7579)
Create Worker Diagram for OSS
**Note: Not being rendered on any screen yet.**

feat: 🎸 create Worker Diagram for OSS

---

ui/admin/config/environment.js

✅ Closes: ICU-6832
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-6832)
Enable json-credential feature-flag for 0.12 release

chore: 🤖 enable feature flag

---

ui/admin/app/templates/application.hbs
ui/admin/tests/acceptance/authentication-test.js
ui/desktop/app/templates/application.hbs
ui/desktop/tests/acceptance/authentication-test.js

:tickets: [✅ Closes: icu-7597](https://hashicorp.atlassian.net/browse/icu-7597)
Fixes flaky acceptance tests where selecting the default system color theme sometimes fails.

test: 💍 fixes flaky theme selection test

---

ui/admin/app/components/form/worker/create-worker-led/index.js

Update HCP binary download instructions to reflect 0.12.0 version
✅ Closes: ICU-7603
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-7603)
Until we can get #1582 PR approved, we will still need to hard code the version update for the  create worker in HCP instructions.

refactor: 💡 update hcp worker instructions

---

ui/admin/app/components/form/worker/create-worker-led/index.js

Fix incorrect HCP worker ui download instructions that still referenced old version.

chore: 🤖 fix incorrect url

---

ui/admin/app/routes/scopes/scope/auth-methods/auth-method/managed-groups/managed-group/members.js

[jira](https://hashicorp.atlassian.net/browse/ICU-7733)

fix: 🐛 empty member ids within managed groups

---

ui/admin/app/components/form/target/details/index.hbs
ui/admin/app/components/form/target/worker-filter/index.hbs
ui/admin/tests/acceptance/targets/create-test.js
ui/admin/tests/integration/components/form/target/worker-filter-test.js

add ingress worker filter tests

test: 💍 add ingress worker filter tests

---

ui/admin/tests/acceptance/targets/create-test.js
ui/admin/tests/integration/components/form/target/details-test.js

create target details integration tests

test: 💍 create target details integration tests

---

addons/core/translations/resources/en-us.yaml
ui/admin/app/components/worker-diagram/dual-filter/hcp/index.hbs
ui/admin/app/components/worker-diagram/dual-filter/index.hbs

fix missing translation error for egress filter on in the HCP env

refactor: 💡 fix missing translation error

---

ui/admin/app/components/form/target/details/index.hbs
ui/admin/app/components/ordered-series-diagram/index.hbs
ui/admin/app/styles/app.scss

[targets](https://boundary-i1c11nn2n-hashicorp.vercel.app/scopes/s_1sheljmjgm/targets/t_nfp0up1fqj)

fix: 🐛 worker section margin and reduce layout shift

---

ui/admin/config/environment.js

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-7304)
Enable Multi-hop feature

chore: 🤖 Enable Multi-hop & Network Address for Targets feature

---

ui/admin/config/environment.js

Enable the feature for enterprise and HCP only.

feat: 🎸 Enable feature flag for vault ssh cert work

---

addons/core/translations/resources/en-us.yaml

Quick change to update the grammar of the popup when there's only 1 host source.

style: 💄 Cleanup grammar of target address modal

---

.github/workflows/test-release-trigger.yml
.github/workflows/ui-release-trigger.yml

See new release worklfow - https://github.com/hashicorp/boundary-ui-releases/pull/44
This PR should be merged after the above PR is merged into boundary-ui-releases.

update release triggers to call new GHA workflow

---

addons/core/translations/form/en-us.yaml
addons/core/translations/resources/en-us.yaml
ui/admin/app/components/form/credential-store/vault/index.hbs
ui/admin/app/components/form/target/details/index.hbs

✅ Closes: ICU-8192
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-8192)
Update the description of the vault worker filter help text and the link URL.
Associated [PR](https://github.com/hashicorp/dev-portal/pull/1702) to update the URL.

fix: 🐛 Fix vault worker filter description

---

addons/core/translations/actions/en-us.yaml
addons/core/translations/en-us.yaml
ui/admin/app/abilities/credential-library.js
ui/admin/app/components/form/credential-library/vault-generic/index.hbs
ui/admin/app/components/form/target/worker-filter/index.hbs
ui/admin/app/controllers/application.js
ui/admin/app/instance-initializers/feature-edition.js
ui/admin/app/routes/application.js
ui/admin/app/routes/scopes/scope/credential-stores/credential-store/credential-libraries/new.js
ui/admin/app/services/feature-edition.js
ui/admin/app/templates/application.hbs
ui/admin/config/environment.js
ui/admin/tests/acceptance/credential-library/create-test.js
ui/admin/tests/acceptance/credential-library/read-test.js
ui/admin/tests/acceptance/develop-test.js
ui/admin/tests/acceptance/targets/create-test.js
ui/admin/tests/acceptance/targets/update-test.js
ui/admin/tests/e2e/tests/credential-store-static.spec.js
ui/admin/tests/e2e/tests/credential-store-vault.spec.js
ui/admin/tests/e2e/tests/dynamic-host-catalog.spec.js
ui/admin/tests/e2e/tests/target.spec.js
ui/admin/tests/unit/abilities/credential-library-test.js
ui/admin/tests/unit/instance-initializers/feature-edition-test.js
ui/admin/tests/unit/services/feature-edition-test.js

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-8382)
This PR introduces dynamic runtime enabling of feature editions (OSS, HCP, Enterprise).  This allows for dynamic runtime edition toggling during development for a more rapid and realistic experience.

Refactor edition enablement

---

ui/admin/tests/e2e/helpers/boundary-cli.js
ui/admin/tests/e2e/helpers/boundary-ui.js
ui/admin/tests/e2e/tests/target.spec.js

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-8420)
This PR creates a new UI test that does the following:
- Prepares test data: org, project
- Creates a target with an address directly added to it
- Connects to the target
- Cancels the connection
- Deletes test org

test(admin/e2e): Add create target with address test

---

ui/admin/tests/e2e/tests/credential-store-vault.spec.js

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-8950)
This PR fixes the Vault Credential Store (User & Key Pair) test by defining expected private key value

test(admin/e2e): Define expected private key for vault credential store test

---

ui/admin/tests/e2e/helpers/boundary-cli.js
ui/admin/tests/e2e/helpers/boundary-ui.js
ui/admin/tests/e2e/tests/credential-store-static.spec.js
ui/admin/tests/e2e/tests/target.spec.js

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-8564)
This PR creates new UI tests:
- to validate user/password credentials creation and brokering
- to validate JSON credentials creation and brokering

test: 💍 (admin-e2e): Add test to create different credentials

---

documentation/README.md

Add Boundary developer conventions document, start with i18n conventions.

docs: ✏️ Add i18n documentation

---

addons/rose/addon/styles/hds/overrides.scss
ui/admin/app/styles/app.scss
ui/admin/app/templates/scopes/scope/auth-methods/index.hbs
ui/admin/tests/acceptance/auth-methods/create-test.js
ui/admin/tests/acceptance/auth-methods/read-test.js

This pr updates auth method list table, dropdown and notification components to HDS
Before: (Rose)
After:(HDS)

chore: Use HDS components in auth methods list view

---

addons/api/addon/generated/models/target.js
addons/api/addon/models/target.js
addons/api/mirage/generated/factories/target.js
addons/api/tests/unit/serializers/target-test.js
addons/core/translations/form/en-us.yaml
addons/core/translations/resources/en-us.yaml
ui/admin/app/components/form/target/details/index.hbs

✅ Closes: ICU-9299
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-9299)
Added default client port to targets. See this [thread](https://hashicorp.slack.com/archives/C012GTH1C4E/p1685468575205089) for more detail.

feat: 🎸 Add default client port to targets

---

ui/admin/app/templates/scopes/scope/workers/index.hbs

✅ Closes: ICU-9539
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-9539)
Current Workers table:
New Workers table:

refactor: 💡 remove type column from Workers table in Admin UI

---

ui/admin/app/templates/scopes/scope.hbs

Delete old comment code, seems isn't used for a couple of years.

style: 💄 Delete old comment code

---

addons/api/mirage/factories/session.js
addons/api/mirage/scenarios/default.js
ui/desktop/app/routes/scopes/scope/projects/sessions.js
ui/desktop/app/routes/scopes/scope/projects/targets.js
ui/desktop/app/styles/app.scss
ui/desktop/tests/acceptance/projects/targets/hosts-test.js
ui/desktop/tests/acceptance/projects/targets/sessions-test.js
ui/desktop/tests/acceptance/scopes-test.js
ui/desktop/tests/acceptance/targets-test.js

:tickets: [icu-9554](https://hashicorp.atlassian.net/browse/icu-9554)
Improves performance of Desktop API queries:
- Removes unnecessary supplemental queries
- Removes bexpr filter expressions, filtering instead on the client
- Disables polling to reduce number of queries originating from Desktop

Optimise Desktop API queries

---

.copywrite.hcl

add config for copywrite tool and compliance scan
Please let me know if we should make any changes.

chore: 🤖 add config for copywrite tool and compliance scan

---

ui/admin/app/components/form/account/oidc/index.hbs
ui/admin/app/components/form/account/password/index.hbs
ui/admin/app/components/form/auth-method/oidc/index.hbs
ui/admin/app/components/form/auth-method/password/index.hbs
ui/admin/app/components/form/credential-store/static/index.hbs
ui/admin/app/components/form/credential-store/vault/index.hbs
ui/admin/app/components/form/credential/json/index.hbs
ui/admin/app/components/form/credential/ssh_private_key/index.hbs
ui/admin/app/components/form/credential/username_password/index.hbs
ui/admin/app/components/form/group/index.hbs
ui/admin/app/components/form/host-catalog/aws/index.hbs
ui/admin/app/components/form/host-catalog/azure/index.hbs
ui/admin/app/components/form/host-catalog/static/index.hbs
ui/admin/app/components/form/host-set/aws/index.hbs
ui/admin/app/components/form/host-set/azure/index.hbs
ui/admin/app/components/form/host-set/static/index.hbs
ui/admin/app/components/form/host/static/index.hbs
ui/admin/app/components/form/managed-group/index.hbs
ui/admin/app/components/form/user/index.hbs
ui/admin/app/components/form/worker/index.hbs
ui/admin/tests/acceptance/credential-store/credentials/create-test.js

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-9881)
remove use of rose form textarea from admin UI
This pull request will unblock the pull request to [retire rose textarea.](https://github.com/hashicorp/boundary-ui/pull/1735)

Icu 9881 remove use of rose form textarea from admin UI

---

README.md

Add projects information and links to their respective docs within main Readme.

docs: ✏️ Add Projects info to main readme

---

addons/api/addon/generated/models/account.js
ui/desktop/electron-app/yarn.lock

✅ Closes: ICU-10050
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-10050)

refactor: 💡 update accounts model with ldap account attributes

---

ui/admin/tests/integration/components/session-recording/player-test.js

test: 💍 fix flaky session recording player assertion

---

addons/api/addon/generated/models/managed-group.js
addons/api/addon/serializers/managed-group.js
addons/api/tests/unit/serializers/managed-group-test.js

[jira](https://hashicorp.atlassian.net/browse/ICU-10058)
updated string to string-array for group_names in model
[domain model](https://developer.hashicorp.com/boundary/docs/concepts/domain-model/managed-groups#ldap-managed-group-information-and-attributes-beta)

chore: 🎸 add support for ldap managed group in serializer

---

addons/core/translations/form/en-us.yaml
ui/admin/app/components/form/account/ldap/index.hbs
ui/admin/tests/acceptance/accounts/create-test.js

[jira](https://hashicorp.atlassian.net/browse/ICU-10082)

Icu 10082 ldap account creation form

---

addons/api/mirage/factories/auth-method.js
addons/api/mirage/factories/managed-group.js
addons/api/mirage/scenarios/default.js

✅ Closes: ICU-10284
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-10284)
Refactor `LDAP/managed-groups` factory to only return specific `auth-method` type

refactor: 💡 refactor mirage factory

---

addons/core/addon/helpers/truncate-list.js
addons/core/app/helpers/truncate-list.js
addons/core/tests/dummy/app/controllers/index.js
addons/core/tests/dummy/app/templates/index.hbs
addons/core/tests/integration/helpers/truncate-list-test.js
addons/core/translations/actions/en-us.yaml

[](url):tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-10307)

Icu 10307 create a new helper

---

ui/desktop/config/environment.js

✅ Closes: ICU-10269
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-10269)
add post connection workflow feature flag and merge into LLB for post connection workflow

chore: 🤖 add post connection workflow feature flag

---

addons/api/mirage/generated/factories/auth-method.js
addons/core/translations/resources/en-us.yaml
ui/admin/app/components/form/auth-method/ldap/index.hbs

✅ Closes: ICU-10064
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-10064)
Originally this ticket was supposed to change the details view to support HMAC, but we have decided not to show the HMAC field.  This PR will serve as a quick fix for some mirage data for `client_certificate_key`

feat: 🎸 Create LDAP CRUD:read

---

addons/api/addon/models/managed-group.js
addons/api/addon/serializers/managed-group.js
addons/core/translations/resources/en-us.yaml
ui/admin/app/components/auth-methods/auth-method/actions/index.hbs
ui/admin/app/components/auth-methods/auth-method/managed-groups/managed-group/nav/index.hbs
ui/admin/app/components/auth-methods/auth-method/nav/index.hbs
ui/admin/app/components/form/managed-group/index.hbs
ui/admin/app/components/form/managed-group/ldap/index.hbs
ui/admin/app/components/form/managed-group/ldap/index.js
ui/admin/app/components/form/managed-group/oidc/index.hbs
ui/admin/app/routes/scopes/scope/auth-methods/auth-method/managed-groups/managed-group.js
ui/admin/app/templates/scopes/scope/auth-methods/auth-method/accounts/index.hbs
ui/admin/app/templates/scopes/scope/auth-methods/auth-method/managed-groups/index.hbs
ui/admin/app/templates/scopes/scope/auth-methods/auth-method/managed-groups/managed-group/index.hbs
ui/admin/app/templates/scopes/scope/auth-methods/auth-method/managed-groups/managed-group/members.hbs
ui/admin/app/templates/scopes/scope/auth-methods/auth-method/managed-groups/new.hbs
ui/admin/tests/acceptance/managed-groups/create-test.js
ui/admin/tests/acceptance/managed-groups/delete-test.js
ui/admin/tests/acceptance/managed-groups/list-test.js
ui/admin/tests/acceptance/managed-groups/read-test.js

✅ Closes: ICU-10100
✅ Closes: ICU-10099
✅ Closes: ICU-10101
✅ Closes: ICU-10102
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-10100)
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-10099)
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-10101)
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-10102)
Adds crudl capabilities for managed groups. Apologies for the chunky PR, I will do better next time at separating it into different PRs.
:technologist: [Admin preview](https://boundary-ui-git-icu-10100-ldap-managed-group-create-hashicorp.vercel.app/scopes/global/auth-methods/am_ec8st2tp51/managed-groups)

feat: 🎸 CRUDL capabilites for ldap managed-group

---

ui/desktop/app/templates/scopes/scope/projects/targets/target.hbs

✅ Closes: ICU-10280
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-10280)
add base layout to target details screen (text is just placeholder and border added to show sections)

refactor: 💡 add base layout to target details screen

---

ui/desktop/app/styles/app.scss
ui/desktop/app/templates/scopes/scope/projects/targets/target.hbs

✅ Closes: ICU-10243
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-10243)
Update Target Details header
:desktop_computer: [Desktop preview](https://boundary-ui-desktop-kvdatmugl-hashicorp.vercel.app/scopes/global/projects/targets/t_l5fhet6083)

refactor: 💡 Update Target Details header

---

addons/core/translations/resources/en-us.yaml
ui/desktop/app/templates/scopes/scope/projects/targets/target.hbs

✅ Closes: ICU-10283
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-10283)
add "Connect for more info" panel to target details
:desktop_computer: [Desktop preview](https://boundary-ui-desktop-assto8ci1-hashicorp.vercel.app/scopes/global/projects/targets/t_l5fhet6083)

refactor: 💡 add "Connect for more info" panel to target details

---

ui/desktop/app/templates/scopes/scope/projects/targets/target.hbs

✅ Closes: ICU-10513
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-10513)
remove unneeded div for layout of target details

refactor: 💡 remove unneeded div for layout of target details

---

ui/desktop/.ember-cli
ui/desktop/README.md

specify port to 4201 for desktop development

chore: 🤖 specify port to 4201 for desktop development

---

ui/desktop/app/routes/scopes/scope/projects/sessions/session.js
ui/desktop/app/styles/app.scss
ui/desktop/app/templates/scopes/scope/projects/sessions/session.hbs
ui/desktop/app/templates/scopes/scope/projects/targets/target.hbs

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-10495)
add target details to session detail sidebar content
_**WARNING**_ this may change when we refactor the actual "Connect" workflow
:desktop_computer: [Desktop preview](https://boundary-ui-desktop-git-icu-10495-session-deta-3a1b51-hashicorp.vercel.app/scopes/global/projects/sessions/ss_hobyn5hnhq)

Icu 10495 session detail sidebar content

---

ui/desktop/app/routes/scopes/scope/projects/sessions.js
ui/desktop/app/routes/scopes/scope/projects/targets.js

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-10677)
enable loading status bar for target connect and cancel actions in the desktop client
:desktop_computer: [Desktop preview](https://boundary-ui-desktop-git-icu-10677-re-enable-lo-bb9356-hashicorp.vercel.app/scopes/global/projects/targets)
When you click connect and/or cancel you should see a blue bar at the top of the screen to indicate it is loading

Icu 10677 re enable loading status for desktop client

---

addons/api/addon-test-support/helpers/indexed-db.js
addons/api/addon/handlers/indexed-db-handler.js
addons/api/addon/services/indexed-db.js
addons/api/addon/services/store.js
addons/api/app/services/indexed-db.js
addons/api/app/services/store.js
addons/api/package.json
addons/api/tests/unit/services/indexed-db-test.js
addons/api/tests/unit/services/store-test.js
ui/admin/ember-cli-build.js
ui/desktop/app/routes/application.js
ui/desktop/app/routes/scopes/scope/authenticate.js
ui/desktop/app/services/session.js
ui/desktop/tests/unit/services/session-test.js
yarn.lock

Initial setup of indexedDB with dexie to sit in front of our normal API.

feat: 🎸 Initial setup of indexedDb

---

ui/desktop/app/routes/scopes/scope/projects/sessions/session.js
ui/desktop/electron-app/src/index.js
ui/desktop/electron-app/src/ipc/handlers.js
ui/desktop/electron-app/src/preload.js
ui/desktop/package.json

Moved the creation of the pty to a handler so a user can spawn multiple processes that are independent from each other in one browser window.

feat: 🎸 Allow creating multiple terminals

---

ui/desktop/electron-app/src/preload.js

This method can be used later on to remove a specific channel.

Chore remove method

---

addons/core/translations/en-us.yaml
addons/core/translations/resources/en-us.yaml
ui/desktop/app/components/session/terminal-tabs/index.hbs
ui/desktop/app/components/session/terminal-tabs/index.js
ui/desktop/app/routes/scopes/scope/projects/sessions/session.js
ui/desktop/app/templates/scopes/scope/projects/sessions/session.hbs

Multiple terminal tabs is difficult with the current HDS tabs component. We have a meeting to discuss this more and other possible design patterns but for now we're just limiting to one terminal.

feat: 🎸 Clean up terminal tab

---

ui/desktop/app/components/session/terminal-tabs/index.js
ui/desktop/electron-app/src/ipc/handlers.js
ui/desktop/electron-app/src/preload.js

Added resizing functionality so the xterm and underlying pty are in sync with their sizes.

feat: 🎸 Handle resizing xterm and node-pty

---

ui/desktop/app/components/session/terminal-tabs/index.js
ui/desktop/electron-app/src/ipc/handlers.js
ui/desktop/electron-app/src/preload.js

Cleaned up the event handlers on the browser and in electron to properly dispose of terminals.

feat: 🎸 Clean up killing terminals

---

addons/rose/package.json
yarn.lock

No breaking changes listed in [release notes](https://github.com/hashicorp/design-system/releases/tag/%40hashicorp%2Fdesign-system-components%402.11.0).

chore: 🤖 bump HDS to 2.11.0

---

ui/desktop/app/routes/scopes/scope/projects/targets/target.js
ui/desktop/app/templates/scopes/scope/projects/targets/target.hbs

✅ Closes: ICU-10431
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-10431)
Allow for connection for target with single host. Next we will [show a modal of host](https://hashicorp.atlassian.net/browse/ICU-10432) to pick from when trying to establish a connection. This is only the happy path and tests will be updated once the flow for multiple hosts has been started.
Mirage does not have targets with only a single host so please refer to gif below.

feat: 🎸 allow for connection for target with single host

---

addons/api/addon/models/session.js
addons/core/translations/resources/en-us.yaml
addons/rose/app/styles/rose/components/metadata-list/_index.scss
ui/desktop/app/routes/scopes/scope/projects/targets/target.js
ui/desktop/app/styles/app.scss
ui/desktop/app/templates/scopes/scope/projects/sessions/session.hbs
ui/desktop/app/templates/scopes/scope/projects/targets/target.hbs
ui/desktop/tests/acceptance/projects/sessions/session-test.js

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-10282)
Before:
After:
Not testable via mirage yet. See screenshot above

feat: 🎸 add host details to session details screen if present

---

ui/desktop/electron-app/src/ipc/handlers.js

A quick change to use user shell by default.

Chore terminal tweaks

---

ui/desktop/app/components/session/tabs/index.hbs
ui/desktop/app/templates/scopes/scope/projects/sessions/session.hbs

✅ Closes: ICU-10961
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-10961)
Before:
After:
Click Connect for the 3rd target and switch between the Details and Shell tabs.

refactor: 💡 move sidebar into session details tab

---

ui/desktop/app/components/session/tabs/index.hbs
ui/desktop/app/templates/scopes/scope/projects/targets/target.hbs

✅ Closes: ICU-10980
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-10980)
Before:
After:
Click on the third target in the list. That target has an address instead of hosts.

feat: 🎸 display target address in sidebar if present

---

ui/desktop/electron-app/yarn.lock

fix: 🐛 Fix outdated yarn lock

---

ui/desktop/app/styles/app.scss

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-11057)
Add `border-radius` and `padding` to desktop client shell terminal
Before:
After:
Start a session and click on the Shell tab

Icu 11057 update shell styles

---

addons/api/addon/models/host.js
addons/api/tests/unit/models/host-test.js
addons/core/translations/resources/en-us.yaml
ui/desktop/app/components/target/host-modal/index.hbs
ui/desktop/app/controllers/scopes/scope/projects/targets/target.js
ui/desktop/app/routes/scopes/scope/projects/targets/target.js
ui/desktop/app/styles/app.scss
ui/desktop/app/templates/scopes/scope/projects/targets/target.hbs
ui/desktop/tests/integration/components/target/host-modal-test.js

✅ Closes: ICU-10432
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-10432)
Before: `N/A`
After:
https://github.com/hashicorp/boundary-ui/assets/29386339/420c1e6a-269d-441f-9455-160e42375c26
Click on `Connect` or `Quick Connect` buttons for the first target. Either from the targets list screen or the target details screen.
:desktop_computer: [Desktop preview](https://boundary-ui-desktop-lko7pe5xo-hashicorp.vercel.app/scopes/global/projects/targets/t_l5fhet6083?isConnecting=true)

feat: 🎸 create Host Modal for connecting to specific modal

---

ui/desktop/app/styles/app.scss

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-11063)
Before:
https://github.com/hashicorp/boundary-ui/assets/29386339/b74935f5-cf66-446f-848e-0f4e85dd7194
After:
https://github.com/hashicorp/boundary-ui/assets/29386339/e45a6638-c24a-4d0d-bf15-d43788dc5995
Click Connect on the first target and the host modal should appear. Hover over a host item and it should give visual indication that you are hovering over an actionable item.

refactor: 💡 add host modal hover indication

---

ui/admin/tests/acceptance/storage-buckets/create-test.js

Add extra test to ensure we select the right credential type

test: 💍 add extra test for credentialType

---

ui/desktop/app/components/session/tabs/index.js
ui/desktop/electron-app/src/ipc/handlers.js

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-11109)
Add a check to prevent automatically sending the SSH command on windows. 
~- [ ] I have added before and after screenshots for UI changes~
~- [ ] I have added steps to reproduce and test for bug fixes in the description~

feat: 🎸 Prevent automatically sending SSH command on windows

---

addons/api/addon/generated/models/auth-method.js
addons/api/addon/models/auth-method.js
addons/api/tests/unit/serializers/auth-method-test.js
addons/core/translations/resources/en-us.yaml
ui/admin/app/components/form/auth-method/ldap/index.hbs
ui/admin/app/components/form/auth-method/ldap/index.js

jira - https://hashicorp.atlassian.net/browse/ICU-11105,  https://hashicorp.atlassian.net/browse/ICU-11106
This PR adds two new fields that the API now supports - `maximum_page_size` and `dereference_aliases`
UI:
model:

feat: (LDAP) add attributes to model and component

---

ui/desktop/app/components/session/tabs/index.js
ui/desktop/app/styles/app.scss
ui/desktop/package.json
yarn.lock

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-11081)
Start a session and start a shell for that session. 
**_Must use a binary created locally to test this as a production build._**

fix: 🐛 xterm csp policy violation

---

ui/desktop/app/components/session/tabs/index.hbs
yarn.lock

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-10981)
Before:
After:
Connect to a target that has hosts associated with it.

Icu 10981 show host address in host details sidebar

---

ui/desktop/app/styles/app.scss

Before: (look closely at right side of terminal for cut off text)
After:
Start a session and navigate to the Shell tab

Fix canvas styles

---

addons/core/translations/resources/en-us.yaml

✅ Closes: ICU-11155
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-11155)
Refactor message description to be shorter.
~- [ ] I have added steps to reproduce and test for bug fixes in the description~
~- [ ] I have commented on my code, particularly in hard-to-understand areas~
~- [ ] My changes generate no new warnings~

refactor: 💡 Simplify cannot-connect message

---

ui/desktop/electron-app/config/forge.config.js
ui/desktop/electron-app/package.json
ui/desktop/electron-app/src/cli/path.js
ui/desktop/electron-app/yarn.lock

Fix builds that got broken by using ASAR.
Am also generating new builds on the CI.

fix: 🐛 Fix usage of spawn statements with boundary and node-pty

---

ui/admin/ember-cli-build.js
ui/desktop/ember-cli-build.js

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-11211)
Add polyfill for randomUUID that EmberData started using in v4.6

fix: 🐛 add polyfill for randomUUID

---

addons/core/translations/resources/en-us.yaml

✅ Closes: ICU-11217
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-11217)
Fix translations for `role_external_id` helper text
- Create a storage bucket and scroll down to the `role_external_id` input.

fix: 🐛 Fix translations

---

addons/api/addon/models/role.js
ui/admin/app/routes/scopes/scope/roles/role/add-principals.js

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-11262)
This PR adds support for LDAP managed groups in role/principals route across all scopes
Before: [ldap managed groups aren't shown in the add-principals route]
After:
[project scope]
[global scope]
- create a new managed group within LDAP auth method
-  this should be shown in the add-principals route across all scopes

fix: 🐛 allow ldap managed groups in role/principals route

---

.github/scripts/merge.sh

Backport of the script changes from ent repo with a cherry pick

backport: 🤖 Fix usage of deprecated hub cli

---

.github/workflows/build-admin-ui.yaml

Add release name to workflow to fix expired artifacts 

fix: 🐛 release name

---

.github/workflows/build-admin-ui.yaml

fix: 🐛 name

---

.github/workflows/build-admin-ui.yaml

Manually trigger admin ui build

---

addons/api/addon/models/session.js
addons/api/tests/unit/models/session-test.js
ui/admin/app/templates/scopes/scope/sessions/index.hbs
ui/desktop/app/components/session/tabs/index.hbs
ui/desktop/app/controllers/scopes/scope/projects/sessions/index.js
ui/desktop/app/controllers/scopes/scope/projects/targets/target/sessions.js
ui/desktop/app/routes/scopes/scope/projects/sessions/session.js
ui/desktop/app/routes/scopes/scope/projects/targets/target.js
ui/desktop/app/templates/scopes/scope/projects/sessions/index.hbs
ui/desktop/tests/acceptance/projects/sessions/session-test.js

Session permissions issue

---

ui/admin/app/routes/scopes/scope/sessions.js
ui/desktop/app/controllers/scopes/scope/projects/sessions/index.js

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-11787)
Refactor to remove unnecessary sorting. API will change to sorting by `create_time` descending as part of pagination changes. Therefore, additional sorting done for sessions can be removed. The API changes have not been implemented yet. Though, they are clearly outlined in RFC ICU-110. Also reference this [slack thread](https://hashicorp.slack.com/archives/C05DR8P3N5T/p1700001953848019?thread_ts=1699988343.314999&cid=C05DR8P3N5T).
- ~[ ] I have added steps to reproduce and test for bug fixes in …

refactor: 💡 remove unnecessary sorting due to pagination change

---

ui/admin/app/routes/scopes/scope/session-recordings.js
ui/admin/app/routes/scopes/scope/sessions.js
ui/desktop/app/controllers/scopes/scope/projects/sessions/index.js

✅ Closes: https://hashicorp.atlassian.net/browse/ICU-11861
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-11861)
Add sorting to session recording & add sorting back in for sessions. 
Go to session-recordings route and validate that they are displayed by newest first (created time desc).

Icu 11861 add sorting to session recording

---

addons/core/addon/decorators/debounce.js
addons/core/app/decorators/debounce.js
ui/desktop/app/controllers/scopes/scope/projects/targets/index.js
ui/desktop/app/routes/scopes/scope/projects/targets/index.js

✅ Closes: https://hashicorp.atlassian.net/browse/ICU-11851
Created a new decorator to debounce the search actions.

feat: 🎸 Add debouncing for the search bar

---

addons/rose/package.json
yarn.lock

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/HDS-2827)
If merged, this PR updates the Helios design system components (@hashicorp/design-system-components) to the latest version (^3.2.0)

HDS-2827 Bump HDS to latest version

---

addons/api/addon/handlers/client-daemon-handler.js
ui/desktop/app/controllers/scopes/scope/projects/targets/index.js
ui/desktop/app/routes/scopes/scope/projects/targets/index.js
ui/desktop/app/templates/scopes/scope/projects/targets/index.hbs

✅ Closes: https://hashicorp.atlassian.net/browse/ICU-11743
Add support for pagination from the client daemon handler.

feat: 🎸 Add pagination support to client daemon handler

---

ui/desktop/electron-app/package.json
ui/desktop/electron-app/yarn.lock

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-11961)
Upgrade electron-forge to the latest version. More infor within the  Jira ticket link above.
- Run succesfully build desktop procedure in local dev env.
- Run succesfully `boundary-ui-release` within these changes. Test run available here.
- ~~[ ] I have added before and after screenshots for UI changes~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~

chore: 🤖 Upgrade electron-forge

---

addons/api/addon/adapters/application.js

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-11789)
`refresh_token` has been renamed to `list_token` 
-~ [ ] I have added JSON response output for API changes~

chore: 🤖 field name update

---

ui/admin/app/templates/scopes/scope/auth-methods/auth-method/accounts/index.hbs

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-12003)
- navigate to OIDC auth method->account
- click on the ID field 
- it should be copied

fix: 🐛 oidc account id

---

addons/api/addon/models/auth-method.js
addons/core/translations/resources/en-us.yaml
ui/admin/app/components/form/auth-method/oidc/index.hbs
ui/admin/app/components/form/auth-method/oidc/index.js
ui/admin/app/styles/app.scss
ui/admin/tests/acceptance/auth-methods/create-test.js
ui/admin/tests/acceptance/auth-methods/update-test.js

We now show a toggle called `skip prompts` instead of `none` option in the checkbox select list. Refer to [thread](https://hashicorp.slack.com/archives/C012GTH1C4E/p1701988097985639) for more details
before: 
AFTER:
-  [x] My changes generate no new warnings

chore: 🤖 add skip prompts toggle

---

addons/rose/app/styles/rose/components/layout/_index.scss

✅ Closes: ICU-11960
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-11960)
Refactor main element padding to achieve consistency within all our UI's. This is a quick solution until we adopt app-frame and follow the same layouting pattern within all our UI's.
- Open Admin UI from this PR ([user vercel](https://boundary-ui-git-chore-icu-11960-update-main-el-361014-hashicorp.vercel.app/)) and open Admin UI before changes ([use vercel](https://boundary-ui.vercel.app/)) and you should see difference within sides (left and right) margins.
- ~~[ ] I have added steps to reproduce and test for bug fixes in the description~~
- ~~[ ] My changes …

chore: 🤖 Refactor main element padding

---

ui/admin/app/styles/app.scss
ui/admin/app/templates/scopes/scope/sessions/index.hbs

✅ Closes: https://hashicorp.atlassian.net/browse/ICU-11732
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-11732)
- Refactor `sessions-list` to use `Hds::Table` instead of `Rose::table`
---
---
:technologist: [Admin preview](https://boundary-ui-git-icu-11732-admin-ui-use-hds-tab-c933e2-hashicorp.vercel.app/)

refactor: 💡 Refactor `sessions-list` to use `Hds::Table`

---

addons/core/addon/components/dropdown/index.hbs
addons/core/translations/en-us.yaml
addons/core/translations/resources/en-us.yaml
ui/desktop/app/controllers/scopes/scope/projects/sessions/index.js
ui/desktop/app/controllers/scopes/scope/projects/targets/index.js
ui/desktop/app/routes/scopes/scope/projects/sessions/index.js
ui/desktop/app/templates/scopes/scope/projects/sessions/index.hbs
ui/desktop/app/templates/scopes/scope/projects/targets/index.hbs
ui/desktop/tests/acceptance/projects/sessions/index-test.js

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-12066)
Add target filtering on sessions list view page.
https://github.com/hashicorp/boundary-ui/assets/107949262/8a800dee-9276-483e-b507-c805424ecf0a
1. Use llb-pagination-2 be branch and start boundary dev
2. Copy newly made binary into ui/desktop/electron-app/cli
3. Checkout this branch and run ENABLE_MIRAGE=false BYPASS_CLI_SETUP=true yarn start:desktop

feat: 🎸 filter sessions by target

---

addons/core/addon/components/dropdown/index.hbs
addons/core/tests/integration/components/dropdown/index-test.js

uncomment on click handler for dropdown component

refactor: 💡 uncomment on click handler for dropdown component

---

addons/api/addon/transforms/object.js

fix: 🐛 transform

---

ui/admin/app/templates/scopes/scope/credential-stores/index.hbs

✅ Closes: https://hashicorp.atlassian.net/browse/ICU-11723
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-11723)
- Refactor `credential-stores-list` to use `Hds::Tables`
- Migrated Copyable components to Hds::Copy::Snippet component
- Migrated p and unwrapped elements with Hds::Text component
--- 
--- 
- Click on Vercel link for Admin UI or pull down PR and run it locally using `yarn start`
- Click on any "Orgs" card created by mirage
- Click on any "Projects" card created by mirage and "Host Catalogs" will appear in the sidebar navigation.
- Click on "Credential Stores" in the sidebar navigation and view list.
- Ensure clicking on a `credential` will take you to details page view of credential.
- Ensure clicking on `copy` icon in listwill copy the id of  `credential` …

refactor: 💡 Refactor `credential-stores-list` to use `Hds`

---

addons/api/addon/abilities/scope.js
addons/api/app/abilities/scope.js
addons/api/mirage/factories/scope.js
addons/api/tests/unit/abilities/scope-test.js
ui/admin/app/abilities/scope.js
ui/admin/tests/unit/abilities/scope-test.js

✅ Closes: https://hashicorp.atlassian.net/browse/ICU-12150
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-12150)
This PR adds the required permissions in the scope model 

chore: 🤖 add attach and detach storage policy permissions

---

ui/admin/app/templates/scopes/scope/host-catalogs/host-catalog/host-sets/index.hbs
ui/admin/app/templates/scopes/scope/host-catalogs/host-catalog/hosts/index.hbs
ui/admin/app/templates/scopes/scope/host-catalogs/index.hbs
ui/admin/app/templates/scopes/scope/policies/index.hbs
ui/admin/app/templates/scopes/scope/session-recordings/index.hbs
ui/admin/app/templates/scopes/scope/session-recordings/session-recording/channels-by-connection/index.hbs
ui/admin/app/templates/scopes/scope/sessions/index.hbs
ui/admin/app/templates/scopes/scope/storage-buckets/index.hbs
ui/admin/app/templates/scopes/scope/targets/index.hbs
ui/admin/app/templates/scopes/scope/workers/index.hbs

✅ Closes: https://hashicorp.atlassian.net/browse/ICU-12168
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-12168)
- Added middle alignment using `@valign='middle'` to all `Hds::Tables`

refactor: 💡 Added middle alignment to all `Hds::Table`s

---

addons/api/addon/handlers/client-daemon-handler.js
addons/api/addon/utils/mql-query.js
addons/api/app/utils/mql-query.js
addons/api/tests/unit/utils/mql-query-test.js

Added tests for generating MQL expressions. There was a small bug with all of the greater/less than operators when working with non strings. We don't use any of them yet but I changed how we sanitize. 

test: 💍 Add tests for MQL expression generator

---

addons/core/translations/resources/en-us.yaml
ui/desktop/app/controllers/scopes/scope/projects/targets/index.js

Change wording of "Active sessions" filter options to be more clear.
[slack thread](https://hashicorp.slack.com/archives/C0647GX0TLJ/p1705951933909539) for context
https://github.com/hashicorp/boundary-ui/assets/107949262/f6e7cb6b-49ab-4356-b697-09e2d91b0035

refactor: 💡 change active sessions filter options wording

---

addons/core/translations/resources/en-us.yaml
ui/admin/app/routes/scopes/scope/session-recordings.js
ui/admin/app/routes/scopes/scope/session-recordings/session-recording/channels-by-connection.js

this pr toggles the translation message based on states
shots (if appropriate):
1. use ENT binary, go to session recording
2. the recording state and completed state should show correct messages after reapply

chore: 🤖 toggle translation based on state

---

addons/api/addon/handlers/client-daemon-handler.js

Added some logic to handle the scenario where a user could get `403`s from the client daemon. We can try to re-authenticate with the daemon as part of error handling.
Run the desktop client and then kill the client daemon and restart it. You should still be able to use the desktop client normally and search and filter.

fix: 🐛 Handle when requests to client daemon are returning 403

---

addons/core/translations/actions/en-us.yaml
ui/admin/app/styles/app.scss
ui/admin/app/templates/scopes/scope/add-storage-policy/create.hbs
ui/admin/app/templates/scopes/scope/add-storage-policy/index.hbs
ui/admin/app/templates/scopes/scope/edit.hbs
ui/admin/app/templates/scopes/scope/policies/index.hbs
ui/admin/app/templates/scopes/scope/policies/new.hbs
ui/admin/app/templates/scopes/scope/policies/policy/index.hbs
ui/admin/config/environment.js

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-12179)
Adds mappings for the doc links for the storage policy resource. Also adds the doc link for the "Global Settings" page.
[PR that adds the redirects](https://github.com/hashicorp/web/pull/1140)
[scopes/{scope}/policies](https://boundary-ui-git-icu-12179-add-doc-links-for-st-dbb74d-hashicorp.vercel.app/scopes/global/policies)
[scopes/{scope}/policies/new](https://boundary-ui-git-icu-12179-add-doc-links-for-st-dbb74d-hashicorp.vercel.app/scopes/global/policies/new)
[scopes/{scope}/policies/{policy}](https://boundary-ui-git-icu-12179-add-doc-links-for-st-dbb74d-hashicorp.vercel.app/scopes/global/policies/pst_97qa1m021z)
[scopes/global/edit](https://boundary-ui-git-icu-12179-add-doc-links-for-st-dbb74d-hashicorp.vercel.ap …

Icu 12179 add doc links for storage policies

---

addons/api/addon/handlers/client-daemon-handler.js
ui/desktop/electron-app/src/cli/index.js
ui/desktop/electron-app/src/helpers/spawn-promise.js
ui/desktop/electron-app/src/services/client-daemon-manager.js

✅ Closes: https://hashicorp.atlassian.net/browse/ICU-12365
Fix client daemon usage on windows.

fix: 🐛 Fix client daemon usage on windows

---

ui/desktop/CHANGELOG.md

Remove dev only bug fix in changelog

docs: ✏️ remove dev only bug fix from changelog

---

addons/api/addon/handlers/client-daemon-handler.js

Refactor this so that any errors that are caused by add-token cmd are caught.

refactor: 💡 move token call to be inside try-catch block

---

ui/admin/app/components/form/auth-method/oidc/index.hbs

- `client_secret` attribute needed to be `@type` instead of `type`.  
- Create new OIDC auth-method and scroll to `Client Secret` field
- Ensure that as you type the text is not visible.

refactor: 💡 Quick fix for `client_secret` type argument

---

addons/api/mirage/config.js
addons/api/mirage/serializers/credential-library.js

move config processing to serializer 

fix: 🐛 move config processing to mirage serializer

---

addons/core/addon/components/dropdown/index.hbs
ui/admin/app/controllers/scopes/scope/targets/index.js
ui/admin/app/routes/scopes/scope/targets.js
ui/admin/app/routes/scopes/scope/targets/index.js
ui/admin/app/templates/scopes/scope/targets/index.hbs
ui/admin/tests/acceptance/targets/delete-test.js
ui/admin/tests/acceptance/targets/list-test.js
ui/admin/tests/acceptance/targets/read-test.js
ui/admin/tests/acceptance/targets/update-test.js
ui/admin/tests/unit/controllers/scopes/scope/targets/index-test.js

✅ Closes: https://hashicorp.atlassian.net/browse/ICU-12193
Initial support for filter/search in targets for admin ui.

feat: 🎸 Add filtering/pagination for admin ui targets

---

addons/api/addon/services/indexed-db.js
ui/admin/app/controllers/scopes/scope/users/index.js
ui/admin/app/routes/scopes/scope/users.js
ui/admin/app/routes/scopes/scope/users/index.js
ui/admin/app/templates/scopes/scope/users/index.hbs
ui/admin/tests/acceptance/users/delete-test.js
ui/admin/tests/acceptance/users/list-test.js
ui/admin/tests/acceptance/users/read-test.js
ui/admin/tests/acceptance/users/update-test.js
ui/admin/tests/unit/controllers/scopes/scope/users/index-test.js

✅ Closes: https://hashicorp.atlassian.net/browse/ICU-12589
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-12589)
Add search and pagination comp. to users list view.

feat: 🎸 add search & pagination support for users

---

addons/api/mirage/scenarios/default.js
addons/core/translations/en-us.yaml
addons/core/translations/resources/en-us.yaml
ui/admin/app/components/form/alias/index.hbs
ui/admin/app/controllers/scopes/scope/aliases/index.js
ui/admin/app/routes/scopes/scope/aliases.js
ui/admin/app/routes/scopes/scope/aliases/alias/index.js
ui/admin/app/styles/app.scss
ui/admin/app/templates/scopes/scope/aliases/alias/index.hbs
ui/admin/app/templates/scopes/scope/aliases/index.hbs
ui/admin/tests/acceptance/aliases/list-test.js

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-12925) and https://hashicorp.atlassian.net/browse/ICU-12927
This PR covers list view, edit, and delete functionality(note: delete doesn't have the modal popup yet, which means we can't clear the aliases yet)
- get the latest main from BE, run make install and start the controller
- create an alias by providing `target id host id, and a value`
- After successfully creation, you should now see the alias on the list view
- create another alias, but this time, don't provide the optional fields- `target id` and `hostid`
- After successfully creation, you should now see the alias on the list view, and the target column would show as `not set`
:desktop_computer: [Desktop …

chore: 🤖 aliases list view

---

addons/api/addon/services/indexed-db.js
addons/api/mirage/config.js
ui/admin/app/controllers/scopes/scope/roles/index.js
ui/admin/app/routes/scopes/scope/roles.js
ui/admin/app/routes/scopes/scope/roles/index.js
ui/admin/app/routes/scopes/scope/targets/index.js
ui/admin/app/routes/scopes/scope/users/index.js
ui/admin/app/templates/scopes/scope/roles/index.hbs
ui/admin/app/templates/scopes/scope/targets/index.hbs
ui/admin/app/templates/scopes/scope/users/index.hbs
ui/admin/tests/acceptance/roles/create-test.js
ui/admin/tests/acceptance/roles/list-test.js
ui/admin/tests/acceptance/roles/principals-test.js
ui/admin/tests/acceptance/roles/read-test.js
ui/admin/tests/unit/controllers/scopes/scope/roles/index-test.js

✅ Closes: https://hashicorp.atlassian.net/browse/ICU-12590
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-12590)
Add search & pagination to roles.
* start boundary dev instance
* navigate to roles page
* use search box to find roles using id, name, or description

Icu 12590 add filtering pagination support for roles

---

ui/admin/app/services/session.js

Indexed db wasn't getting properly setup when logging in. 

fix: 🐛 Fix setting up indexed db when user logins first time

---

addons/api/addon/services/indexed-db.js
addons/api/mirage/config.js
ui/admin/app/controllers/scopes/scope/groups/index.js
ui/admin/app/routes/scopes/scope/groups.js
ui/admin/app/routes/scopes/scope/groups/index.js
ui/admin/app/templates/scopes/scope/groups/index.hbs
ui/admin/tests/acceptance/groups/create-test.js
ui/admin/tests/acceptance/groups/list-test.js
ui/admin/tests/unit/controllers/scopes/scope/groups/index-test.js

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-12591)
Adds pagination and searching to the groups resource
Before:
After:
Searching:
No Results:
Start `boundary dev` and navigate to groups and create a few groups. After creating multiple groups, you can search the groups by name, description, and id.

Icu 12591 add filtering pagination support for groups

---

addons/core/addon/components/dropdown/index.hbs
addons/core/tests/integration/components/dropdown/index-test.js
ui/admin/app/templates/scopes/scope/credential-stores/index.hbs
ui/admin/app/templates/scopes/scope/sessions/index.hbs
ui/admin/app/templates/scopes/scope/targets/index.hbs
ui/admin/tests/acceptance/credential-store/list-test.js
ui/admin/tests/acceptance/sessions/list-test.js
ui/admin/tests/acceptance/targets/list-test.js
ui/desktop/app/templates/scopes/scope/projects/sessions/index.hbs
ui/desktop/app/templates/scopes/scope/projects/targets/index.hbs

✅ Closes: https://hashicorp.atlassian.net/browse/ICU-13336
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-13336)
update Dropdown component to have name & @toggleText
Go to any Admin UI list view that has search and filter with a dropdown filter option. Inspect the dropdown to see that the `name` attribute has a different value than the text displayed in the toggle button of the dropdown.
:technologist: [Admin preview](https://boundary-ui-git-icu-13336-update-dropdown-comp-8f9951-hashicorp.vercel.app/scopes/s_1sheljmjgm/targets)

refactor: 💡 update Dropdown component to have name & toggleText

---

ui/admin/app/controllers/scopes/scope/credential-stores/index.js
ui/admin/app/routes/scopes/scope/credential-stores/index.js
ui/admin/app/routes/scopes/scope/groups/index.js
ui/admin/app/routes/scopes/scope/host-catalogs/index.js
ui/admin/app/routes/scopes/scope/roles/index.js
ui/admin/app/routes/scopes/scope/users/index.js

✅ Closes: https://hashicorp.atlassian.net/browse/ICU-13356
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-13356)
move query inside list permission check

fix: 🐛 move query inside list permission check

---

addons/api/addon/handlers/indexed-db-handler.js
ui/admin/app/routes/scopes/scope/credential-stores/index.js
ui/admin/app/routes/scopes/scope/groups/index.js
ui/admin/app/routes/scopes/scope/host-catalogs/index.js
ui/admin/app/routes/scopes/scope/roles/index.js
ui/admin/app/routes/scopes/scope/scopes/index.js
ui/admin/app/routes/scopes/scope/targets/index.js
ui/admin/app/routes/scopes/scope/users/index.js
ui/admin/app/templates/scopes/scope/targets/index.hbs

✅ Closes: https://hashicorp.atlassian.net/browse/ICU-13251
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-13251)
Add flag to skip network request, when we want to query cached data.
1. start boundary dev env
2. navigate to any of the routes with the flag enabled (ex: cred stores)
3. validate that when search/filtering returns no results, no additional network request is made.

refactor: 💡 reduce network requests & call indexedDB directly

---

addons/api/addon/handlers/indexed-db-handler.js
addons/api/addon/models/role.js
ui/admin/app/routes/scopes/scope/groups/group/add-members.js
ui/admin/app/routes/scopes/scope/groups/group/members.js
ui/admin/app/routes/scopes/scope/roles/index.js
ui/admin/app/routes/scopes/scope/roles/role/add-principals.js
ui/admin/app/routes/scopes/scope/roles/role/principals.js
ui/admin/app/routes/scopes/scope/users/index.js
ui/admin/app/templates/scopes/scope/roles/index.hbs
ui/admin/app/templates/scopes/scope/targets/index.hbs
ui/admin/app/templates/scopes/scope/users/index.hbs
ui/admin/tests/acceptance/groups/members-test.js
ui/admin/tests/acceptance/roles/principals-test.js
ui/desktop/app/templates/scopes/scope/projects/sessions/index.hbs
ui/desktop/app/templates/scopes/scope/projects/targets/index.hbs

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-13359)
Refactor query requests to users, and groups to use indexedDB.
No new UI changes. 
1. start boundary dev instance
2. navigate to roles -> role -> principals and validate that correct principals are showing.
3. navigate to roles -> role -> add principals and validate it works properly.
4. navigate to groups -> group -> members and validate correct members are showing.
5. navigate to groups ->  group -> add members and validate it works properly.

Icu 13359 refactor query requests for resources added to indexed db

---

ui/admin/app/templates/scopes/scope/groups/index.hbs
ui/admin/app/templates/scopes/scope/workers/index.hbs

update groups and workers "new" button to HDS
Before
After
Before
After
Navigate to groups and workers route to see new HDS buttons 

refactor: 💡 update groups and workers "new" button to HDS

---

addons/api/addon/initializers/deprecations.js
addons/api/app/initializers/deprecations.js
addons/api/tests/unit/initializers/deprecations-test.js
addons/api/tests/unit/utils/indexed-db-query-test.js

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-13218)
Silence deprecation warnings and add test cases for bool fields.
before:
after:
Run unit tests and make sure no deprecation warnings are shown in dev tools console

Icu 13218 update indexed db parser unit tests to test for filtering on boolean fields

---

ui/admin/app/routes/scopes/scope/targets/target/add-brokered-credential-sources.js
ui/admin/app/routes/scopes/scope/targets/target/add-injected-application-credential-sources.js

fix: 🐛 add missing scope_id from credential sources for targets
Add a brokered or injected credential source to a target and it shouldn't error out.

fix: 🐛 add missing scope_id from credential sources for targets

---

ui/admin/app/templates/scopes/scope/aliases/index.hbs

title plural fix 
after
before:

fix: 🐛 plural title

---

addons/api/addon-test-support/handlers/client-daemon-search.js
addons/api/addon/adapters/application.js
addons/api/addon/handlers/client-daemon-handler.js
addons/api/addon/models/target.js
addons/api/app/handlers/client-daemon-handler.js
ui/desktop/app/routes/scopes/scope/projects/targets/index.js
ui/desktop/app/templates/scopes/scope/projects/targets/index.hbs
ui/desktop/tests/acceptance/projects/sessions/index-test.js
ui/desktop/tests/acceptance/projects/targets/index-test.js
ui/desktop/tests/acceptance/projects/targets/target-test.js
ui/desktop/tests/acceptance/scopes-test.js

✅ Closes: https://hashicorp.atlassian.net/browse/ICU-13487
Add aliases to list view. 
This needs to also be tested on an older version of the CLI where aliases aren't in the client daemon to make sure it's working correctly.

feat: 🎸 Add aliases to list view

---

ui/admin/app/templates/scopes/scope/aliases/index.hbs
ui/admin/app/templates/scopes/scope/aliases/new.hbs
ui/admin/app/templates/scopes/scope/targets/target/create-alias.hbs
ui/admin/config/environment.js

Adds doc links for aliases
see [PR](https://github.com/hashicorp/web/pull/1452) which adds the redirects
- ~[ ] I have added tests that prove my fix is effective or that my feature works

chore: 🤖 add doc links for aliases

---

ui/admin/app/templates/scopes/scope/policies/index.hbs

This PR fixes the policy title 

fix: 🐛 policy title

---

addons/core/translations/en-us.yaml
addons/core/translations/resources/en-us.yaml
ui/admin/app/components/form/alias/index.hbs
ui/admin/app/controllers/scopes/scope/aliases/index.js
ui/admin/app/routes/scopes/scope/targets.js
ui/admin/app/routes/scopes/scope/targets/target/create-alias.js
ui/admin/app/templates/scopes/scope/aliases/alias/index.hbs
ui/admin/app/templates/scopes/scope/aliases/index.hbs
ui/admin/app/templates/scopes/scope/targets/target/create-alias.hbs
ui/admin/app/templates/scopes/scope/targets/target/manage-alias.hbs
ui/admin/tests/acceptance/aliases/delete-test.js
ui/admin/tests/acceptance/aliases/update-test.js
ui/admin/tests/acceptance/targets/create-alias-test.js
ui/admin/tests/acceptance/targets/manage-alias-test.js
ui/desktop/app/templates/scopes/scope/projects/targets/target.hbs
ui/desktop/tests/acceptance/projects/targets/target-test.js

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-13525)
This pr fixes a few things - 
1. Hides alias sidebar container when there are no associated aliases in DC 
2. Hides target ID from alias form creation/update within a target
3. Adds confirmation messages for delete and clear aliases 
read-only in new form
editable in edit state

fix: 🐛 aliasing bugs

---

ui/admin/app/templates/scopes/scope/targets/target/manage-alias.hbs

This PR adds details subsection to the manage alias page 

fix: 🐛 add details

---

ui/admin/app/controllers/scopes/scope/auth-methods/index.js

Fixes auth-methods bug where `scopeModel` in actions resets to undefined on page refresh.
https://github.com/hashicorp/boundary-ui/assets/107949262/28a55e55-ae15-4b14-a8cf-1d60ea12ff00
Create an auth method in an org
In the Auth Method details page, reload the page (refresh, F5, cmd+R, etc.)
Select Manage > Make Primary
Observe the error
Note: Repeat steps for "Remove as Primary" and "Delete" actions

fix: 🐛 action errors on auth-method refresh

---

ui/admin/app/controllers/scopes/scope/targets/target/index.js
ui/admin/app/routes/scopes/scope/targets.js
ui/admin/app/routes/scopes/scope/targets/target/index.js
ui/admin/app/styles/app.scss
ui/admin/app/templates/scopes/scope/targets/target/index.hbs
ui/admin/app/templates/scopes/scope/targets/target/manage-alias.hbs
ui/admin/tests/acceptance/targets/manage-alias-test.js
ui/admin/tests/acceptance/targets/read-test.js

this pr fixes permission based bugs 
no delete permiision
no update permission
1. user without update perm, can't edit the alias form, and won't see the manage dropdown 
2. user without create perm, will not see `add an alias` if there's no associated alias 

fix: 🐛 permissions

---

addons/core/translations/resources/en-us.yaml

Fix storage bucket empty state message
Navigate to storage bucket page with no storage buckets to reproduce empty state.
~- [ ] I have commented on my code, particularly in hard-to-understand areas~
~- [ ] My changes generate no new warnings~

Fix storage bucket empty state message

---

addons/core/translations/resources/en-us.yaml

Update label and description because of new storage bucket type addition.
Go to enable session recording page for ssh targets and see updated label and description.

fix: 🐛 update label & description

---

ui/desktop/electron-app/config/cli.js
ui/desktop/electron-app/package.json
ui/desktop/electron-app/yarn.lock
yarn.lock

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-13758)
Stop using `decompress` and start using `unzipper`.
- Run a successful windows build within `boundary-ui-releases`.
- Successful test run, [can be found here](https://github.com/hashicorp/boundary-ui-releases/actions/runs/8990936542/job/24697695225).

Fix icu 13758 refactor node decompress

---

ui/desktop/README.md

I wanted to add the troubleshooting help for node-gyp issues while it was still fresh in my mind. I also fixed some of the linter issues in the README.

Doc update desktop readme

---

addons/api/addon/serializers/target.js

This PR fixes target patch when there is with_aliases field
https://github.com/hashicorp/boundary-ui/assets/15043878/f3594ede-871a-4047-b93e-ec877123bced
if appropriate)
- create. a target with aliases 
- after successful submit, edit the form and update any of the fields 
- it should patch successfully and the network payload should not include `with_aliases` attr

fix: 🐛 target patch with_Aliases field

---

LICENSE

The [copywrite job](https://github.com/hashicorp/copyright-notice-automation) can't find the license key. I suspect it is due to the quotes in the text file. Unfortunately, there's no way to test with just a branch name here, so I will have to merge this onto the repo

fix: quotes

---

LICENSE

recreate LICENSE file

---

ui/admin/app/controllers/scopes/scope/targets/target/add-host-sources.js
ui/admin/app/controllers/scopes/scope/targets/target/brokered-credential-sources.js
ui/admin/app/controllers/scopes/scope/targets/target/create-alias.js
ui/admin/app/controllers/scopes/scope/targets/target/enable-session-recording/index.js
ui/admin/app/controllers/scopes/scope/targets/target/host-sources.js
ui/admin/app/controllers/scopes/scope/targets/target/injected-application-credential-sources.js
ui/admin/app/controllers/scopes/scope/targets/target/manage-alias.js
ui/admin/app/controllers/scopes/scope/users/new.js
ui/admin/app/controllers/scopes/scope/users/user/accounts.js
ui/admin/app/controllers/scopes/scope/users/user/add-accounts.js
ui/admin/app/controllers/scopes/scope/users/user/index.js
ui/admin/app/controllers/scopes/scope/workers/index.js
ui/admin/app/controllers/scopes/scope/workers/new.js
ui/admin/app/controllers/scopes/scope/workers/worker/index.js
ui/admin/tests/unit/controllers/scopes/scope/targets/target/add-host-sources-test.js
ui/admin/tests/unit/controllers/scopes/scope/targets/target/brokered-credential-sources-test.js
ui/admin/tests/unit/controllers/scopes/scope/targets/target/create-alias-test.js
ui/admin/tests/unit/controllers/scopes/scope/targets/target/enable-session-recording/index-test.js
ui/admin/tests/unit/controllers/scopes/scope/targets/target/host-sources-test.js
ui/admin/tests/unit/controllers/scopes/scope/targets/target/injected-application-credential-sources-test.js
ui/admin/tests/unit/controllers/scopes/scope/targets/target/manage-alias-test.js
ui/admin/tests/unit/controllers/scopes/scope/users/new-test.js
ui/admin/tests/unit/controllers/scopes/scope/users/user/accounts-test.js
ui/admin/tests/unit/controllers/scopes/scope/users/user/add-accounts-test.js
ui/admin/tests/unit/controllers/scopes/scope/users/user/index-test.js
ui/admin/tests/unit/controllers/scopes/scope/workers/index-test.js
ui/admin/tests/unit/controllers/scopes/scope/workers/new-test.js

chore: 🤖 headers update

---

README.md

I went and updated the supported versions of Node.js from v16 and v18 to v20 to account for updates in Node.js usage
- ~~[ ] I have added before and after screenshots for UI changes~~
- ~~[ ] I have added steps to reproduce and test for bug fixes in the description~~
- ~~[ ] My changes generate no new warnings~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~

Readme update to change Node supported versions

---

ui/admin/app/components/form/auth-method/ldap/index.hbs

fix: 🐛 labels were changed during the refactor

---

README.md

- ~~[ ] I have added before and after screenshots for UI changes~~
- ~~[ ] I have added steps to reproduce and test for bug fixes in the description~~

Fixed Markdown in Node supported versions

---

addons/rose/addon/styles/addon.scss
addons/rose/index.js
addons/rose/package.json
package.json
ui/admin/app/components/form/auth-method/oidc/index.hbs
ui/admin/app/components/form/credential-library/vault-generic/index.hbs
ui/admin/app/templates/scopes/scope/credential-stores/index.hbs
ui/admin/app/templates/scopes/scope/groups/index.hbs
ui/admin/app/templates/scopes/scope/host-catalogs/index.hbs
ui/admin/app/templates/scopes/scope/roles/index.hbs
ui/admin/app/templates/scopes/scope/scopes/index.hbs
ui/admin/app/templates/scopes/scope/session-recordings/session-recording/channels-by-connection/channel/index.hbs
ui/admin/app/templates/scopes/scope/targets/index.hbs
ui/admin/app/templates/scopes/scope/users/index.hbs
yarn.lock

closes: https://hashicorp.atlassian.net/browse/ICU-14064 
Resolution added to package.json, [slack msg](https://hashicorp.slack.com/archives/C7KTUHNUS/p1718644636513669) for details.
Check out the hds [upgrade release guide](https://github.com/hashicorp/design-system/releases/tag/%40hashicorp%2Fdesign-system-components%404.0.0) for details.
1. navigate to ui/admin
2. run yarn start
3. verify ui is rendering with no errors in console and no styles missing
4. repeat steps for ui/desktop

chore: 🤖 udate hds from v3.5 to v4

---

ui/desktop/app/routes/scopes/scope/projects.js
ui/desktop/app/routes/scopes/scope/projects/sessions/session.js
ui/desktop/app/routes/scopes/scope/projects/targets/index.js
ui/desktop/electron-app/src/utils/jsonify.js

feat: 🎸 Add more logging for desktop client

---

ui/desktop/electron-app/package.json
ui/desktop/electron-app/src/index.js
ui/desktop/electron-app/yarn.lock

✅ Closes: https://hashicorp.atlassian.net/browse/ICU-13697
I have updated electron to v31. I've gone through the electron breaking [changes](https://www.electronjs.org/docs/latest/breaking-changes) and fixed one breaking change that affected us.  
[Here's](https://github.com/hashicorp/boundary-ui-releases/actions/runs/9570586017) a build in our CI of this electron upgrade.
Confirm that the app runs. Note that this includes the client-daemon to cache-daemon changes which the currently CLI hasn't updated yet so you'll see errors for that.
- ~[ ] I have commented on my code, particularly in …

chore: 🤖 upgrade electron

---

addons/api/addon/models/role.js
addons/api/tests/unit/models/role-test.js
addons/core/translations/resources/en-us.yaml
addons/rose/addon/components/rose/header/brand/index.hbs
addons/rose/addon/components/rose/pagination/index.hbs
ui/admin/app/components/form/role/manage-custom-scopes/index.hbs
ui/admin/app/components/form/role/manage-custom-scopes/index.js
ui/admin/app/components/form/role/manage-scopes/index.hbs
ui/admin/app/components/form/role/manage-scopes/index.js
ui/admin/app/controllers/scopes/scope/roles/role/manage-scopes/index.js
ui/admin/app/controllers/scopes/scope/roles/role/manage-scopes/manage-custom-scopes.js
ui/admin/app/router.js
ui/admin/app/routes/scopes/scope/roles/role/manage-scopes/index.js
ui/admin/app/routes/scopes/scope/roles/role/manage-scopes/manage-custom-scopes.js
ui/admin/app/styles/app.scss
ui/admin/app/templates/scopes/scope/roles/role/manage-scopes.hbs
ui/admin/app/templates/scopes/scope/roles/role/manage-scopes/index.hbs
ui/admin/app/templates/scopes/scope/roles/role/manage-scopes/manage-custom-scopes.hbs
ui/admin/app/templates/scopes/scope/roles/role/scopes.hbs
ui/admin/tests/acceptance/roles/scopes-test.js
ui/admin/tests/unit/controllers/scopes/scope/roles/role/manage-scopes/index-test.js
ui/admin/tests/unit/controllers/scopes/scope/roles/role/manage-scopes/manage-custom-scopes-test.js
ui/admin/tests/unit/routes/scopes/scope/roles/role/manage-scopes-test.js
ui/admin/tests/unit/routes/scopes/scope/roles/role/manage-scopes/index-test.js
ui/admin/tests/unit/routes/scopes/scope/roles/role/manage-scopes/manage-custom-scopes-test.js

✅ Closes: https://hashicorp.atlassian.net/browse/ICU-13881
Manage custom scopes route and view.
https://github.com/hashicorp/boundary-ui/assets/107949262/84800765-a708-475d-aaf7-5dbdd3aa995e

feat: 🎸 create manage custom scopes route and view

---

ui/admin/app/routes/scopes/scope/roles/role/index.js
ui/admin/app/templates/scopes/scope/roles/role/index.hbs

refactor: 💡 remove old unused code

---

ui/admin/app/routes/scopes/scope/roles/role/manage-scopes.js
ui/admin/app/routes/scopes/scope/roles/role/scopes.js
ui/admin/tests/unit/routes/scopes/scope/roles/role/scopes-test.js

chore: 🤖 add missing headers in llb

---

addons/api/addon/models/worker.js
addons/core/translations/resources/en-us.yaml
ui/admin/app/controllers/scopes/scope/workers/worker/tags.js
ui/admin/app/templates/scopes/scope/workers/worker/tags.hbs
ui/admin/tests/acceptance/workers/tags-test.js

✅ Closes: https://hashicorp.atlassian.net/browse/ICU-14331
Add tooltip to config tags in table
Navigate to `workers/worker/tags` route and hover over `config` in the table and you should see the tooltip appear.

feat: 🎸 add tooltip to config tags in table

---

addons/api/mirage/factories/role.js
ui/admin/app/components/form/role/manage-scopes/index.hbs
ui/admin/app/controllers/scopes/scope/roles/role/manage-scopes/index.js
ui/admin/app/controllers/scopes/scope/roles/role/manage-scopes/manage-custom-scopes.js
ui/admin/app/controllers/scopes/scope/roles/role/manage-scopes/manage-org-projects.js
ui/admin/app/controllers/scopes/scope/roles/role/scopes.js
ui/admin/app/routes/scopes/scope/roles/role/manage-scopes.js
ui/admin/app/routes/scopes/scope/roles/role/manage-scopes/index.js
ui/admin/app/routes/scopes/scope/roles/role/scopes.js
ui/admin/app/templates/scopes/scope/roles/role/manage-scopes/index.hbs
ui/admin/app/templates/scopes/scope/roles/role/scopes.hbs
ui/admin/tests/acceptance/roles/global-scope-test.js
ui/admin/tests/acceptance/roles/org-scope-test.js
ui/admin/tests/unit/controllers/scopes/scope/roles/role/manage-scopes/index-test.js
ui/admin/tests/unit/controllers/scopes/scope/roles/role/scopes-test.js
ui/admin/tests/unit/controllers/scopes/scope/targets/index-test.js
ui/admin/tests/unit/routes/scopes/scope/roles/role/scopes-test.js

✅ Closes: https://hashicorp.atlassian.net/browse/ICU-13886
https://github.com/hashicorp/boundary-ui/assets/107949262/99366dd2-d41a-400c-b174-07f11cb6f3cc

feat: 🎸 add search and filtering to scopes tab in a role

---

addons/core/translations/resources/en-us.yaml
ui/admin/app/controllers/scopes/scope/roles/index.js
ui/admin/app/templates/scopes/scope/roles/index.hbs
ui/admin/tests/acceptance/roles/list-test.js

add "yes" or  "no" badge to grant scopes applied column
https://github.com/hashicorp/boundary-ui/assets/107949262/34e44983-9c52-48e6-ba90-8d16ba94eab1

refactor: 💡 add grant scopes applied badge

---

addons/core/translations/resources/en-us.yaml
ui/admin/app/components/form/role/manage-scopes/index.hbs
ui/admin/app/styles/app.scss

update button text to "Manage custom scopes" to better match other language used in this new workflow.
before:
after:
Navigate to `/scopes/global/roles/<ROLE_ID>/manage-scopes` and button should now say "Manage custom scopes"

refactor: 💡 update button text to Manage custom scopes

---

addons/core/translations/resources/en-us.yaml
ui/admin/app/templates/scopes/scope/workers/worker/create-tags.hbs

add link to worker docs for create-tags view
before:
after:
On the create tags page, the link in the description should direct the user to https://developer.hashicorp.com/boundary/docs/configuration/worker

feat: 🎸 add link to worker docs for create-tags view

---

ui/admin/app/components/form/worker/index.hbs
ui/admin/app/styles/app.scss
ui/admin/tests/acceptance/workers/create-test.js

Remove old tag information in the detail view of a worker
before:
after:
Visit `/scopes/global/workers/<WORKER_ID>` and verify that no worker tags are visible in the details page of a worker.

refactor: 💡 remove worker tags from detail view of worker

---

addons/core/translations/resources/en-us.yaml
ui/admin/app/components/form/role/manage-org-projects/index.hbs
ui/admin/app/controllers/scopes/scope/roles/role/manage-scopes/index.js
ui/admin/app/controllers/scopes/scope/roles/role/manage-scopes/manage-custom-scopes.js
ui/admin/app/controllers/scopes/scope/roles/role/manage-scopes/manage-org-projects.js

update text in alerts and a button
1. go to a role
2. click on manage scopes
3. make sure alert text after saving on every page is accurate

refactor: 💡 update messages & update button to match new change

---

ui/admin/app/components/form/role/manage-scopes/index.hbs
ui/admin/app/templates/scopes/scope/roles/role/manage-scopes/index.hbs
ui/admin/app/templates/scopes/scope/roles/role/manage-scopes/manage-custom-scopes.hbs
ui/admin/app/templates/scopes/scope/roles/role/manage-scopes/manage-org-projects.hbs
ui/admin/config/environment.js

Add doc links to new pages for multi scope grants.
Make sure the doc links lead to correct page.

docs: ✏️ add doclinks for multi-scope grant work

---

addons/api/addon/handlers/cache-daemon-handler.js
ui/desktop/app/routes/scopes/scope/projects.js
ui/desktop/app/routes/scopes/scope/projects/sessions/session.js
ui/desktop/app/routes/scopes/scope/projects/targets/index.js
ui/desktop/electron-app/src/helpers/app-updater.js
ui/desktop/electron-app/src/helpers/request-promise.js
ui/desktop/electron-app/src/index.js
ui/desktop/electron-app/src/ipc/handlers.js
ui/desktop/electron-app/src/services/cache-daemon-manager.js
ui/desktop/electron-app/src/services/client-agent-daemon-manager.js
ui/desktop/electron-app/src/utils/generateErrorPromise.js
ui/desktop/electron-app/src/utils/jsonify.js

Added some logging to log the version info on startup. Also changed errors to be more uniform and return a message consistently. Stopped logging error objects so we don't log any stacktraces. 
Start up desktop client and confirm version info is in logs. Try and generate errors either by throwing errors in code or creating situations in desktop client.

refactor: 💡 Remove stack traces and add logs for version info

---

ui/admin/app/routes/scopes/scope/workers/index.js
ui/admin/app/styles/app.scss
ui/admin/app/templates/scopes/scope/workers/index.hbs
ui/admin/tests/acceptance/workers/list-test.js

update workers tags filter to include api_tags
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-14436)
https://github.com/user-attachments/assets/468f2a78-8d03-4dc2-8ee4-0b151f9470e4
Go to workers route and you should be able to filter by config and/or api tags now.

feat: 🎸 update workers tags filter to include api_tags

---

ui/desktop/app/controllers/scopes/scope/projects/settings/index.js
ui/desktop/app/router.js
ui/desktop/app/routes/scopes/scope/projects/settings.js
ui/desktop/app/routes/scopes/scope/projects/settings/index.js
ui/desktop/app/templates/scopes/scope/projects.hbs
ui/desktop/app/templates/scopes/scope/projects/settings.hbs
ui/desktop/app/templates/scopes/scope/projects/settings/index.hbs
ui/desktop/tests/acceptance/projects/settings/index-test.js
ui/desktop/tests/unit/controllers/scopes/scope/projects/settings/index-test.js
ui/desktop/tests/unit/routes/scopes/scope/projects/settings-test.js
ui/desktop/tests/unit/routes/scopes/scope/projects/settings/index-test.js

✅ Closes: https://hashicorp.atlassian.net/browse/ICU-14398
This PR adds a skeleton for the settings page, note this does not include any functionality. 
- ~[x] My changes generate no new warnings

feat: 🎸 settings page

---

ui/desktop/app/routes/scopes/scope/projects.js
ui/desktop/app/routes/scopes/scope/projects/sessions/session.js
ui/desktop/config/environment.js

Added feature flag for the client agent work. 
Make a build locally and confirm no calls to the client agent occur. They should still be enabled in dev.

chore: 🤖 Add feature flag for client-agent work

---

ui/admin/app/templates/scopes/scope/workers/worker/create-tags.hbs
ui/admin/config/environment.js

add doc link for create tags view
The doc link should direct to [worker tags doc](https://developer.hashicorp.com/boundary/docs/concepts/filtering/worker-tags)
https://github.com/user-attachments/assets/6f15d8f5-57e2-4192-9779-70c55035d361
Navigate to `/scopes/global/workers/<WORKER_ID>/create-tags` and click on the doc link next to "Create new tags"

feat: 🎸 add doc link for create tags view

---

ui/admin/app/templates/scopes/scope/roles/role/scopes.hbs
ui/admin/tests/acceptance/roles/global-scope-test.js
ui/admin/tests/acceptance/roles/org-scope-test.js
ui/admin/tests/acceptance/roles/project-scope-test.js

Remove search & pagination for project roles since it serves no purpose.
before:
after:

fix: 🐛 hide search & pagination for project role grant scopes

---

addons/api/mirage/scenarios/ipc.js
addons/core/translations/en-us.yaml
addons/core/translations/errors/en-us.yaml
addons/core/translations/states/en-us.yaml
ui/desktop/app/components/settings-card/index.hbs
ui/desktop/app/controllers/scopes/scope/projects/settings/index.js
ui/desktop/app/router.js
ui/desktop/app/routes/scopes/scope/projects/settings/index.js
ui/desktop/app/styles/app.scss
ui/desktop/app/templates/scopes/scope/projects/settings.hbs
ui/desktop/app/templates/scopes/scope/projects/settings/index.hbs
ui/desktop/electron-app/src/ipc/handlers.js
ui/desktop/tests/acceptance/projects/settings/index-test.js
ui/desktop/tests/integration/components/settings-card-test.js

https://hashicorp.atlassian.net/browse/ICU-14400
This PR adds application information section on the user settings page in DC
with no daemon:

Icu 14400 add a section for version info cli and dc

---

addons/core/translations/en-us.yaml
ui/desktop/app/controllers/application.js
ui/desktop/app/controllers/scopes/scope/projects/settings/index.js
ui/desktop/app/routes/application.js
ui/desktop/app/templates/application.hbs
ui/desktop/app/templates/scopes/scope/projects/settings/index.hbs
ui/desktop/tests/acceptance/authentication-test.js
ui/desktop/tests/acceptance/projects/settings/index-test.js

this PR removes theme selection from menu bar and moves to settings page
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-14452)  

chore: move theme selection to user settings page

---

addons/core/translations/en-us.yaml
ui/desktop/app/controllers/application.js
ui/desktop/app/controllers/scopes/scope/projects/settings/index.js
ui/desktop/app/routes/application.js
ui/desktop/app/templates/application.hbs
ui/desktop/app/templates/scopes/scope/projects/settings/index.hbs
ui/desktop/tests/acceptance/authentication-test.js
ui/desktop/tests/acceptance/projects/settings/index-test.js

this was previously approved and merged into llb, but I made a mistake while rebasing llb and force-pushed it before I could pull in the new commit in llb.

Add theme selection

---

ui/admin/app/components/host-catalogs/host-catalog/host-sets/host-set/actions/index.hbs
ui/admin/tests/acceptance/host-catalogs/host-sets/delete-test.js
ui/admin/tests/acceptance/host-catalogs/host-sets/hosts-test.js

✅ Closes: https://hashicorp.atlassian.net/browse/ICU-14600
Updated the manage dropdown in host-sets to reflect HDS design
1. Select Orgs from sidebar
2. Select Projects and select a project resource
3. Select host-catalogs from sidebar
4. Select host-sets from table and select a host-set resource
5. HDS design should on the manage dropdown
~- [ ] I have added JSON response output for API changes
~- [ ] I have added steps to reproduce and test for bug fixes in the description
~- [ ] I have commented on my code, particularly in hard-to-understand areas
~- [ ] I have added tests that prove my fix is effective or that my feature works

refactor: 💡 Updated Manage Dropdown in host-sets to HDS design

---

ui/admin/app/templates/scopes/scope/credential-stores/credential-store/credential-libraries/credential-library/index.hbs
ui/admin/tests/acceptance/credential-library/delete-test.js

✅ Closes: https://hashicorp.atlassian.net/browse/ICU-14601
Updated Manage Dropdown present in credential-library to reflect new HDS design
1. Select orgs
2. Select project
3. Select credential stores w/vault type then credentials library in sub-menu
4. HDS design should be reflected
~- [ ] I have added JSON response output for API changes
~- [ ] I have added steps to reproduce and test for bug fixes in the description
~- [ ] I have commented on my code, particularly in hard-to-understand areas

refactor: 💡 Updated Manage Dropdown in credential-library

---

ui/admin/app/components/auth-methods/auth-method/accounts/account/actions/index.hbs
ui/admin/tests/acceptance/accounts/delete-test.js

✅ Closes: https://hashicorp.atlassian.net/browse/ICU-14599
Updated Manage Dropdown in auth-methods account form to HDS
1. Navigate to Auth methods
2. Select auth method resource
3. Select account tab
4. Select account from tab
5. HDS Design should reflect in dropdown
~- [ ] I have added JSON response output for API changes
~- [ ] I have added steps to reproduce and test for bug fixes in the description
~- [ ] I have commented on my code, particularly in hard-to-understand areas
~- [X ] My changes generate no new warnings

refactor: 💡 Updated Manage Dropdown in auth-methods accounts

---

addons/core/translations/en-us.yaml
ui/desktop/app/components/settings-card/application/index.hbs
ui/desktop/app/components/settings-card/logs/index.hbs
ui/desktop/app/components/settings-card/logs/index.js
ui/desktop/app/components/settings-card/user/index.hbs
ui/desktop/app/routes/scopes/scope/projects/settings/index.js
ui/desktop/app/styles/app.scss
ui/desktop/app/templates/scopes/scope/projects/settings/index.hbs
ui/desktop/electron-app/package.json
ui/desktop/electron-app/src/index.js
ui/desktop/electron-app/src/ipc/handlers.js
ui/desktop/electron-app/src/services/electron-store-manager.js
ui/desktop/electron-app/yarn.lock
ui/desktop/tests/integration/components/settings-card-test.js
ui/desktop/tests/integration/components/settings-card/logs-test.js
ui/desktop/tests/integration/components/settings-card/user-test.js

✅ Closes: https://hashicorp.atlassian.net/browse/ICU-14403
Added card to be able to change log levels of app as well as show where the logs are saved. 
Start desktop client and confirm that changing log levels works. Debug should show search request times. Confirm the log location is correct as well. 
Confirm that log level config is saved correctly, it should be located at: `~/Library/Application Support/Boundary/config.json`

Icu 14403 add dropdown to select and save log verbosity

---

ui/desktop/app/components/session/tabs/index.js
ui/desktop/ember-cli-build.js
ui/desktop/package.json
yarn.lock

Migrate `xterm` to `@xterm` and addons.
[Successful boundary-ui-release run after upgrade](https://github.com/hashicorp/boundary-ui-releases/actions/runs/10462098131/job/28971943342)
[Jira ticket](https://hashicorp.atlassian.net/browse/ICU-14449)
- Run the desktop client build process locally.
- Run the boundary-ui-releases successfully.

chore: 🤖 Migrate xterm to @xterm

---

addons/api/mirage/scenarios/ipc.js
addons/core/translations/en-us.yaml
ui/desktop/app/components/settings-card/index.hbs
ui/desktop/app/components/settings-card/server/index.hbs
ui/desktop/app/components/settings-card/server/index.js
ui/desktop/app/routes/scopes/scope/projects/settings/index.js
ui/desktop/app/styles/app.scss
ui/desktop/app/templates/scopes/scope/projects/settings/index.hbs
ui/desktop/tests/integration/components/settings-card/server-test.js

Adds server information https://hashicorp.atlassian.net/browse/ICU-14781
HCP:

Icu 14781 add a section for server information

---

README.md
ui/admin/README.md

This PR updates the repo READMEs by replacing a broken link and pointing to correct tutorials page, adding hyperlinks to improve readability, and small language updates
N/A

docs: ✏️ replace broken links, add hyperlinks, language updates

---

ui/desktop/app/routes/scopes/scope/projects.js
ui/desktop/app/routes/scopes/scope/projects/sessions/session.js
ui/desktop/config/environment.js

Removes the client agent feature flag. 

chore: 🤖 Remove client agent feature flag

---

ui/admin/app/templates/scopes/scope/edit.hbs
ui/admin/tests/acceptance/scopes/delete-test.js
ui/admin/tests/acceptance/scopes/read-test.js

Updated Manage Dropdown in Projects form to reflect HDS Design
:tickets: : https://hashicorp.atlassian.net/browse/ICU-14870
**Before**
**After**
1. Start up Boundary client
2. Select "Orgs from sidebar and select an org resource
3. Select "Projects" from sidebar and select a project resource
4. Navigate to projects settings on sidebar
5. Change should be reflected in HDS
~- [ ] I have added steps to reproduce and test for bug fixes in the description~
~- [ ] I have commented on my code, particularly in hard-to-understand areas~
~- [ ] My changes generate no new warnings~

ICU-14870 Update Manage Dropdown for Projects form

---

ui/admin/app/templates/scopes/scope/credential-stores/credential-store/credentials/credential/index.hbs
ui/admin/tests/acceptance/credential-store/credentials/delete-test.js

✅ Closes: https://hashicorp.atlassian.net/browse/ICU-14665
Updates Manage dropdown in credentials form to reflect HDS Design
**Before**
**After**
1. Start up server/instance and select org tab
2. Select an org resource
3. Select a project
4. Select a credential store
5. Select a credential stored in the table
6. HDS dropdown should be reflected on top right.
~- [ ] I have added steps to reproduce and test for bug fixes in the description~
~- [ ] I have commented on my code, particularly in hard-to-understand areas~
~- [ ] My changes generate no new warnings~

refactor: 💡 Update Manage dropdown in Credentials form

---

ui/desktop/electron-app/src/helpers/spawn-promise.js

There was a change where we manually timeout requests to client agent status as currently it can take too long. However, it turns out out on windows, when a `SIGTERM` was sent to the client agent status it didn't actually return anything. On mac an error response was returned on `stderr` but because nothing was returned on windows, our handler for `spawn` was waiting indefinitely for a response. 
This change seeks to at least always resolve the promise if the child process ends so a caller isn't waiting forever. 
Run DC in windows without client agent running and it should not hang up when logging in and going to settings page.
- ~[ ] I have added tests that prove my …

fix: 🐛 Fix windows hanging when client agent isn't running

---

addons/rose/package.json
yarn.lock

✅ Closes: https://hashicorp.atlassian.net/browse/ICU-14204
**NOTE: This PR is to be merged after [ember-cli-mirage upgrade ](https://github.com/hashicorp/boundary-ui/pull/2458). I'll update this branch and run tests again just to make sure.**
Fixes dependabot issue [#149](https://github.com/hashicorp/boundary-ui/security/dependabot/149)
Upgrade `jest` in rose addon which removed dependency that `jsdom` had on `ws`
Note: jest was originally added to fix peer dependency missing warning. Upgrading to v28 removed downstream dependency on ws. After verifying that worked. I upgraded to latest version.
Forcing `socket.io-adapter` to resolve to v2.5.5 caused the `ws` dependency to update to `~8.17.1` and that fixes the vulnerability.
Dependency paths:
use `yarn why <dependency name>`
1. ws@^7.4.6 …

chore: 🤖 upgrade to ws v8.17.1 to remove vulnerability

---

ui/admin/tests/e2e/playwright.config.mjs
ui/admin/tests/e2e/tests/alias-ent.spec.mjs
ui/admin/tests/e2e/tests/alias.spec.mjs
ui/admin/tests/e2e/tests/auth-method-ldap.spec.mjs
ui/admin/tests/e2e/tests/auth-method-password.spec.mjs
ui/admin/tests/e2e/tests/credential-store-static-ent.spec.mjs
ui/admin/tests/e2e/tests/credential-store-static.spec.mjs
ui/admin/tests/e2e/tests/credential-store-vault.spec.mjs
ui/admin/tests/e2e/tests/delete-resources-ent.spec.mjs
ui/admin/tests/e2e/tests/delete-resources.spec.mjs
ui/admin/tests/e2e/tests/dynamic-host-catalog-aws.spec.mjs
ui/admin/tests/e2e/tests/global-settings.spec.mjs
ui/admin/tests/e2e/tests/group-role.spec.mjs
ui/admin/tests/e2e/tests/login.spec.mjs
ui/admin/tests/e2e/tests/pagination.spec.mjs
ui/admin/tests/e2e/tests/session-recording-aws-ent.spec.mjs
ui/admin/tests/e2e/tests/session-recording-minio-ent.spec.mjs
ui/admin/tests/e2e/tests/ssh-certificate-injection-vault-ent.spec.mjs
ui/admin/tests/e2e/tests/ssh-credential-injection-vault-ent.spec.mjs
ui/admin/tests/e2e/tests/target-ent.spec.mjs
ui/admin/tests/e2e/tests/target.spec.mjs
ui/admin/tests/e2e/tests/worker-ent.spec.mjs
ui/admin/tests/e2e/tests/worker.spec.mjs

This PR does some refactoring in the Admin UI test suite to use fixtures for environment variables. 
https://hashicorp.atlassian.net/browse/ICU-14759

refact(e2e): Use fixtures for environment variables

---

ui/admin/tests/acceptance/accounts/change-password-test.js
ui/admin/tests/acceptance/roles/global-scope-test.js
ui/admin/tests/acceptance/roles/org-scope-test.js
ui/admin/tests/acceptance/scopes/read-test.js
ui/admin/tests/acceptance/session-recordings/read-test.js
ui/admin/tests/acceptance/targets/workers-test.js
ui/admin/tests/acceptance/workers/read-test.js
ui/desktop/tests/acceptance/projects/sessions/index-test.js
ui/desktop/tests/acceptance/projects/targets/index-test.js
ui/desktop/tests/acceptance/scopes-test.js

@calcaide had a good suggestion to include the ICU ticket in the TODO. So a small PR to make that update.

chore: 🤖 update TODO to with ICU ticket

---

README.md
ui/desktop/README.md

Small README update to let users know they will need full permissions when trying to build the desktop client locally.

small update to desktop README

---

addons/api/addon-test-support/handlers/cache-daemon-search.js
addons/api/addon/handlers/cache-daemon-handler.js
addons/core/addon/components/loading-button/index.hbs
addons/core/addon/components/toolbar-refresher/index.hbs
addons/core/addon/components/toolbar-refresher/index.js
addons/core/addon/styles/addon.scss
addons/core/tests/integration/components/loading-button-test.js
addons/core/translations/states/en-us.yaml
ui/admin/app/templates/scopes/scope/sessions/index.hbs
ui/desktop/app/controllers/scopes/scope/projects/sessions/index.js
ui/desktop/app/controllers/scopes/scope/projects/targets/index.js
ui/desktop/app/routes/scopes/scope/projects/sessions/index.js
ui/desktop/app/routes/scopes/scope/projects/targets/index.js
ui/desktop/app/templates/scopes/scope/projects/sessions/index.hbs
ui/desktop/app/templates/scopes/scope/projects/targets/index.hbs
ui/desktop/electron-app/src/helpers/request-promise.js
ui/desktop/tests/acceptance/projects/sessions/index-test.js
ui/desktop/tests/acceptance/projects/targets/index-test.js
ui/desktop/tests/acceptance/projects/targets/target-test.js
ui/desktop/tests/acceptance/scopes-test.js

Merge of the workday changes in the LLB back to main.

Desktop client updates to support cache daemon changes

---

addons/api/package.json
addons/auth/addon/authenticators/base.js
addons/auth/addon/authenticators/oidc.js
addons/auth/addon/authenticators/password.js
addons/auth/package.json
ui/admin/app/instance-initializers/feature-edition.js
ui/desktop/tests/acceptance/projects/settings/index-test.js
yarn.lock

✅ Closes: https://hashicorp.atlassian.net/browse/ICU-15189
1. Fixes dependabot alert [#165](https://github.com/hashicorp/boundary-ui/security/dependabot/165). Which also fixes corresponding code scanning alert [#112](https://github.com/hashicorp/boundary-ui/security/code-scanning/112) & [#113](https://github.com/hashicorp/boundary-ui/security/code-scanning/113).
2. Forced `rollup@^2.50.0` to resolve to `v2.79.2` which patches the security vulnerability.
3. Resolution on `rollup@^0.57.1` could not be forced since it caused build errors. Resolution on `broccoli-rollup` to v5 caused runtime errors. None of these could be resolved. Therefore, only other option is to remove dependency on `ember-fetch` which is fairly easy to accomplish.
* `rollup@^0.57.1 -> broccoli-rollup@^2.1.1 -> …

chore: 🤖 resolve rollup vulnerability by removing ember-fetch

---

addons/core/translations/resources/en-us.yaml
ui/admin/app/controllers/scopes/scope/session-recordings/session-recording/channels-by-connection/index.js
ui/admin/app/routes/scopes/scope/session-recordings/index.js

✅ Closes: https://hashicorp.atlassian.net/browse/ICU-15236
Fixes transition aborted errors when re-applying and deleteing.
https://github.com/user-attachments/assets/0344df34-0ba2-488c-b2b3-1bec6e4fb5d9
1. create a session recording
2. create storage policy to allow deletion and apply in "Global settings"
3. Reapply policy to session recording
4. Delete session recording.

fix: 🐛 deleting session recording causes error

---

addons/api/addon/generated/models/host-catalog.js
addons/api/addon/serializers/host-catalog.js
addons/api/mirage/factories/host-catalog.js
addons/api/tests/unit/serializers/host-catalog-test.js
addons/core/translations/resources/en-us.yaml
ui/admin/app/components/form/host-catalog/aws/index.hbs

[jira](https://hashicorp.atlassian.net/browse/ICU-15257)
API changes:
UI changes: 
before: 
after:
error:
1.  use staged build 
2. pull this branch down and click on new host catalog
3. you should be able to add worker filter for AWS type host catalog [reach out to me if you need creds for AWS]
4. you should not see this option for static or Azure type host catalog 
5. you should be able to update/delete worker filter once created and save successfully

Add worker type dynamic host catalog

---

addons/api/addon/generated/models/host-catalog.js
addons/api/addon/models/host-catalog.js
addons/api/addon/serializers/host-catalog.js
addons/api/mirage/factories/host-catalog.js
addons/api/tests/unit/serializers/host-catalog-test.js
addons/core/translations/resources/en-us.yaml
ui/admin/app/components/form/host-catalog/aws/index.hbs
ui/admin/app/components/form/host-catalog/aws/index.js
ui/admin/app/components/form/host-catalog/index.hbs
ui/admin/app/components/form/storage-bucket/aws/index.hbs
ui/admin/app/controllers/scopes/scope/host-catalogs/index.js
ui/admin/app/templates/scopes/scope/host-catalogs/new.hbs

This pr adds assumerole to dynamic AWS host catalogs
jira - https://hashicorp.atlassian.net/browse/ICU-15258
before: 
after: 
when dynamic is selected: 
when static is selected: 
with assumerole:
in edit view: 
API Response:
for dynamic aws credentials:
for static aws credentials:
- happy to share credentials to test this PR

Types for aws host catalogs

---

addons/api/addon/serializers/host-catalog.js
addons/core/translations/resources/en-us.yaml
ui/admin/app/components/form/host-catalog/aws/index.hbs
ui/admin/app/styles/app.scss
ui/admin/config/features.js
ui/admin/tests/acceptance/host-catalogs/create-test.js

this PR fixes a few changes - 
1. Introduce a flag to hide/show worker filter (we only show this field in enterprise)
2. disable and add helper text for disable_cred_rotation when dynamic cred is selected
3. role_Arn text update
- ~ [ ] I have added steps to reproduce and test for bug fixes in the description

fix: 🐛 minor UI changes, ent flag for worker filter

---

ui/admin/app/styles/app.scss

add bottom border back to ListWrapper component
I initially removed this bottom-border to make the ListWrapper component look closer to designs for the worker tag improvements made recently. However, it made the spacing between the labels and input look too large and looks a little off when adding multiple rows which all have the bottom-border between each row. The ListWrapper component is used in many places so I only added screenshots for a few of the places it is used. Please use the vercel build to click around and check during testing.
Create New Tags
Before:
After:
Auth Method: LDAP
Before:
After:
Credential Library
Before:
After:

fix: 🐛 add bottom border back to ListWrapper component

---

ui/admin/app/controllers/scopes/scope/targets/index.js
ui/admin/app/controllers/scopes/scope/targets/target/add-brokered-credential-sources.js
ui/admin/app/controllers/scopes/scope/targets/target/add-host-sources.js
ui/admin/app/controllers/scopes/scope/targets/target/add-injected-application-credential-sources.js
ui/admin/tests/unit/controllers/scopes/scope/targets/target/add-host-sources-test.js

✅ Closes: https://hashicorp.atlassian.net/browse/ICU-15296
Alias information disappears when adding a filter, host, or cred.
https://github.com/user-attachments/assets/c8d255d5-a86b-4b1d-8cc5-b603ffaad9af
1. create a target w/ an alias
2. navigate to target details page
3. Add a worker filter and save -> on target details, alias info should be visible.
4.  Add a host source and save -> on target details, alias info should be visible.
5.  Add a brokered credential and save -> on target details, alias info should be visible.
6. Add a injected credential and save -> on target details, alias info should be visible.

fix: 🐛 alias disappearing on target details page

---

ui/admin/tests/acceptance/accounts/create-test.js
ui/admin/tests/acceptance/accounts/selectors.js
ui/admin/tests/helpers/selectors.js

✅ Closes: https://hashicorp.atlassian.net/browse/ICU-14037
selectors refactor for accounts create & some other general improvements

test: 💍 selectors refactor for accounts create

---

addons/api/package.json
addons/auth/package.json
addons/core/package.json
addons/rose/package.json
ui/admin/package.json
ui/desktop/package.json
yarn.lock

✅ Closes: https://hashicorp.atlassian.net/browse/ICU-15393
chore: 🤖 upgrade ember-cli version
This upgrade should resolve a few different security alerts that we have. I will address those in a separate PR as I want to keep changes in packages low as we run tests, build, test locally, and test the release pipeline.
[Release test run](https://github.com/hashicorp/boundary-ui-releases/actions/runs/11468678848)

chore: 🤖 upgrade ember-cli version

---

ui/admin/tests/acceptance/accounts/create-test.js
ui/admin/tests/acceptance/accounts/delete-test.js
ui/admin/tests/acceptance/accounts/selectors.js

✅ Closes: https://hashicorp.atlassian.net/browse/ICU-14038
update test selectors for accounts delete

test: 💍 update test selectors for accounts delete

---

ui/admin/app/components/auth-methods/auth-method/accounts/account/actions/index.hbs
ui/admin/app/components/auth-methods/auth-method/actions/index.hbs
ui/admin/tests/acceptance/accounts/list-test.js
ui/admin/tests/acceptance/accounts/read-test.js
ui/admin/tests/acceptance/accounts/selectors.js
ui/admin/tests/acceptance/accounts/set-password-test.js
ui/admin/tests/acceptance/auth-methods/create-test.js
ui/admin/tests/acceptance/auth-methods/delete-test.js
ui/admin/tests/acceptance/managed-groups/create-test.js
ui/admin/tests/acceptance/managed-groups/list-test.js

Update test selectors for accounts list, read, and set-password test
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/14039) <-- list
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/14040) <-- read
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/14041) <-- set-password

Icu 14039 accounts list, read, and set-password test

---

ui/admin/tests/acceptance/groups/list-test.js
ui/admin/tests/acceptance/groups/read-test.js

✅ Closes: https://hashicorp.atlassian.net/browse/ICU-15481 and 
https://hashicorp.atlassian.net/browse/ICU-15484
- ~[ ] I have added before and after screenshots for UI changes

Icu 15481 groups read and list test

---

ui/admin/tests/integration/components/worker-filter/index-test.js

test: 💍 clean up worker filter component tests

---

addons/core/translations/en-us.yaml
ui/admin/app/components/worker-filter/index.hbs
ui/admin/app/components/worker-filter/index.js
ui/admin/app/styles/app.scss
ui/admin/tests/integration/components/worker-filter/index-test.js

This PR adds the workflow for creating a tag specific worker filter
https://github.com/user-attachments/assets/68185c0d-b113-47e8-ad75-e43e6a3e0f74
1. Go to the workers tab on a Target, toggle the "show generator" toggle
2. Enter in the key and value
3. Should be able to copy the formatted result

Icu 15743 tag workflow

---

e2e-tests/admin/tests/credential-store-vault-ent.spec.js
e2e-tests/admin/tests/credential-store-vault.spec.js
e2e-tests/admin/tests/group-role.spec.js
e2e-tests/admin/tests/ssh-certificate-injection-vault-ent.spec.js
e2e-tests/admin/tests/ssh-credential-injection-vault-ent.spec.js
e2e-tests/admin/tests/worker-tags.spec.js
e2e-tests/package.json
yarn.lock

Fixed some of the linting errors that were present in our e2e tests.

refactor: 💡 Fix linting errors in e2e

---

yarn.lock

I had unintentional changes that weren't intended in the yarn.lock file after adding a new package. This reverts them.

fix: 🐛 Fix unintentional changes to yarn lock

---

ui/admin/app/components/form/storage-bucket/aws/index.hbs
ui/admin/app/components/form/storage-bucket/minio/index.hbs
ui/admin/app/components/worker-filter-generator/index.hbs
ui/admin/app/styles/app.scss
ui/admin/tests/acceptance/storage-buckets/create-test.js
ui/admin/tests/acceptance/storage-buckets/selectors.js
ui/admin/tests/acceptance/storage-buckets/update-test.js
ui/admin/tests/acceptance/targets/enable-session-recording/create-storage-bucket-test.js

✅ Closes: https://hashicorp.atlassian.net/browse/ICU-15737
update worker filter field to use code editor
Before:
https://github.com/user-attachments/assets/4916d5a2-b068-44f4-9c57-b412c15ea9f2
After:
https://github.com/user-attachments/assets/c6f4d791-b639-4aa5-9821-7f1ae7955e6d

feat: 🎸 update worker filter field to use code editor

---

ui/desktop/app/styles/app.scss

fix overlay bug
https://github.com/user-attachments/assets/ebe32993-1bba-4b5a-8f72-1eec983b9fe3

style: 💄 fix z-index for rose-dialog modal

---

ui/admin/tests/acceptance/storage-buckets/create-test.js
ui/admin/tests/acceptance/storage-buckets/selectors.js
ui/admin/tests/acceptance/storage-buckets/update-test.js

✅ Closes: https://hashicorp.atlassian.net/browse/ICU-15739
Added new test and assertions for storage buckets

test: 💍 update tests for new worker filter field

---

ui/admin/package.json
ui/desktop/package.json
yarn.lock

Delete ember-cli-app-version.
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-15799)
- Run the Admin and the desktop app successfully.

chore: 🤖 Delete ember-cli-app-version

---

addons/api/mirage/route-handlers/auth.js
addons/rose/addon/utilities/component-auto-id.js
addons/rose/package.json
ui/admin/package.json
ui/admin/tests/integration/components/form/worker/create-worker-led-test.js
yarn.lock

Migrate ember-uuid to uuid to consolidate since we are already using uuid but ember-uuid only within rose
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-15818)
- Run unit tests within rose.
- Run unit tests within Admin.

refactor: 💡 Migrate ember-uuid to uuid

---

e2e-tests/README.md
package.json

Updated readme to explain how to test admin UI against a local branch.

docs: ✏️ Add to readme how to run admin e2e against local branch

---

ui/admin/tests/acceptance/host-catalogs/hosts/create-test.js
ui/admin/tests/acceptance/host-catalogs/hosts/list-test.js
ui/admin/tests/acceptance/host-catalogs/hosts/selectors.js

Refactor host-catalog host list acceptance test selectors.
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-15501)
- Run `admin` test suite successfully.

test: 💍 Refactor host list test selectors

---

addons/core/translations/en-us.yaml
ui/admin/app/components/worker-filter-generator/index.hbs
ui/admin/app/components/worker-filter-generator/index.js
ui/admin/tests/integration/components/worker-filter-generator/index-test.js

Apply feedback from design sync
https://github.com/user-attachments/assets/756c5a7c-71ce-4d6e-b9e4-ea8780fb4ab2
1. go to target/vault cred. store/storage bucket
2. validate worker filter generator is toggled on by default.

refactor: 💡 Update name radio option label & set toggle default to on

---

ui/admin/app/components/form/credential-store/vault/index.hbs
ui/admin/tests/acceptance/credential-store/create-test.js
ui/admin/tests/acceptance/credential-store/selectors.js

Added commonSelectors and selectors to credential stores acceptance tests along with a few quality of life improvements.

Icu 15470 credential store create test

---

addons/api/addon/generated/models/host-set.js
addons/api/addon/serializers/host-set.js
addons/api/mirage/factories/host-catalog.js
addons/api/mirage/factories/host-set.js
addons/api/mirage/factories/host.js
addons/core/addon/styles/addon.scss
addons/core/translations/resources/en-us.yaml
ui/admin/app/components/form/host-set/aws/index.hbs
ui/admin/app/components/form/host-set/azure/index.hbs
ui/admin/app/components/form/host-set/gcp/index.hbs
ui/admin/app/components/form/host/aws/index.hbs
ui/admin/app/components/form/host/azure/index.hbs
ui/admin/app/components/form/host/gcp/index.hbs
ui/admin/app/controllers/scopes/scope/host-catalogs/host-catalog/host-sets/index.js
ui/admin/tests/acceptance/host-catalogs/host-sets/create-test.js
ui/admin/tests/acceptance/host-catalogs/host-sets/update-test.js

✅ Closes: https://hashicorp.atlassian.net/browse/ICU-15994
This adds support for GCP host sets and hosts. I also updated the styles for the host page in all 3 dynamic catalogs to add some space to the dynamic inputs. Will add tests.
Host Set page:
Host List page:
Host page:
AWS host page: 
AWS before:

feat: 🎸 Added GCP host sets and hosts

---

addons/core/translations/resources/en-us.yaml

This PR fixes the text to include GCP plugin 

fix: 🐛 include GCP plugin text

---

addons/api/addon/utils/flatten-nested-object.js
addons/api/tests/unit/utils/flatten-nested-object-test.js
ui/desktop/app/components/hidden-secret/index.js

update hidden secrets and flatten-nested-object logic
Before:
https://github.com/user-attachments/assets/53fece78-8290-41c2-9cc7-062783db53a6
After:
https://github.com/user-attachments/assets/e67b1801-2d81-432f-bdba-53941c5b130f
Create a JSON credential with varying types of values like 0, false, true, null, and '' (empty string). Only null and '' values should be filtered out. All secrets are still displayed when viewing the API output.

fix: 🐛 update hidden secrets and flatten-nested-object logic

---

ui/desktop/CHANGELOG.md

update desktop release date in CHANGELOG

chore: 🤖 update desktop release date in CHANGELOG

---

e2e-tests/README.md

Update e2e docs to highlight that only certain tests are supported by certain scenarios
N/A
~~- [ ] My changes generate no new warnings~~

update e2e docs with supported enos scenarios

---

.github/ISSUE_TEMPLATE/bug_report.md

Update to our bug report template that will ask the user for common information that we need when debugging issues.

docs: ✏️ update bug report template

---

ui/admin/tests/acceptance/users/create-test.js
ui/admin/tests/acceptance/users/delete-test.js
ui/admin/tests/acceptance/users/read-test.js
ui/admin/tests/acceptance/users/selectors.js

Test selector refactor for users tests:
[create](https://hashicorp.atlassian.net/browse/ICU-16441)
[read](https://hashicorp.atlassian.net/browse/ICU-16442)
[delete](https://hashicorp.atlassian.net/browse/ICU-16444)

Refactor: 💡 User acceptance tests - create, delete and read

---

ui/admin/app/components/credential-stores/credential-store/actions/index.hbs
ui/admin/app/components/credential-stores/credential-store/nav/index.hbs
ui/admin/app/components/form/credential-store/vault/index.hbs
ui/admin/app/components/form/host-catalog/aws/index.hbs
ui/admin/app/components/form/host-catalog/gcp/index.hbs
ui/admin/app/components/worker-diagram/dual-filter/hcp/index.hbs
ui/admin/app/components/worker-diagram/index.hbs
ui/admin/app/templates/scopes/scope/targets/target/workers.hbs
ui/admin/config/features.js
ui/admin/tests/acceptance/credential-store/create-test.js
ui/admin/tests/acceptance/credential-store/update-test.js
ui/admin/tests/acceptance/host-catalogs/create-test.js
ui/admin/tests/acceptance/targets/workers-test.js
ui/admin/tests/integration/components/worker-diagram/dual-filter/hcp/index-test.js
ui/admin/tests/integration/components/worker-diagram/dual-filter/index-test.js
ui/admin/tests/integration/components/worker-diagram/index-test.js

This PR refactors worker-filter feature flags and removes redundant ones 
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-16190) 
Adding screenshot for one of the examples in all three environments
oss:
ent:
hcp:

refactor: 💡 worker filter feature flags

---

ui/admin/tests/acceptance/sessions/list-test.js
ui/admin/tests/helpers/selectors.js

I have a few `tbody tr` selectors with TODOs for when this [PR](https://github.com/hashicorp/boundary-ui/pull/2719/files) is merged in. I will keep this PR as a draft until that is ready.
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/[ICU-16426)

chore: 🤖 update session list tests with selectors

---

ui/admin/tests/acceptance/host-catalogs/create-test.js
ui/admin/tests/acceptance/host-catalogs/selectors.js

This PR uses test selectors in host catalog create file
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-15486) 

Icu 15486 host catalogs create test

---

ui/admin/tests/acceptance/auth-methods/create-test.js
ui/admin/tests/acceptance/auth-methods/selectors.js
ui/admin/tests/acceptance/storage-buckets/list-test.js
ui/admin/tests/acceptance/storage-buckets/selectors.js
ui/admin/tests/helpers/selectors.js

These are 2 small changes that I mentioned in this [PR](https://github.com/hashicorp/boundary-ui/pull/2727).
Adds a more specific name to the original `SIDEBAR_NAV_LINK` selector and moves `TABLE_FIRST_ROW_ACTION_DROPDOWN` into the common selectors.

Small test selector updates

---

ui/admin/tests/acceptance/host-catalogs/delete-test.js
ui/admin/tests/acceptance/host-catalogs/read-test.js
ui/admin/tests/acceptance/host-catalogs/selectors.js
ui/admin/tests/acceptance/host-catalogs/update-test.js

[read](https://hashicorp.atlassian.net/browse/ICU-15487)
[delete](https://hashicorp.atlassian.net/browse/ICU-15489)
[update](https://hashicorp.atlassian.net/browse/ICU-15488)

refactor: 💡 use test selector in host-catalog read, delete and update

---

ui/admin/tests/acceptance/policy/delete-test.js
ui/admin/tests/acceptance/policy/list-test.js
ui/admin/tests/helpers/selectors.js

Test selector refactor for Policy tests:
[list](https://hashicorp.atlassian.net/browse/ICU-16403)
[delete](https://hashicorp.atlassian.net/browse/ICU-16404)

Refactor: Policy tests - list and delete

---

ui/admin/tests/acceptance/workers/create-test.js
ui/admin/tests/acceptance/workers/delete-test.js
ui/admin/tests/acceptance/workers/read-test.js
ui/admin/tests/acceptance/workers/selectors.js
ui/admin/tests/acceptance/workers/update-test.js

Test selector refactor for Workers tests:
[create](https://hashicorp.atlassian.net/browse/ICU-16447)
[delete](https://hashicorp.atlassian.net/browse/ICU-16450)
[update](https://hashicorp.atlassian.net/browse/ICU-16449)
[read](https://hashicorp.atlassian.net/browse/ICU-16448)

Refactor: Worker tests - create, read, update and delete

---

ui/admin/app/components/form/role/index.hbs
ui/admin/app/components/roles/role/actions/index.hbs
ui/admin/tests/acceptance/accounts/update-test.js
ui/admin/tests/acceptance/roles/delete-test.js
ui/admin/tests/acceptance/roles/read-test.js
ui/admin/tests/acceptance/roles/selectors.js
ui/admin/tests/acceptance/roles/update-test.js

Make test selector refactors to the Roles:
[Read](https://hashicorp.atlassian.net/browse/ICU-16406)
[Update](https://hashicorp.atlassian.net/browse/ICU-16407)
[Delete](https://hashicorp.atlassian.net/browse/ICU-16408)
I also caught some old code in the accounts tests file and fixed that as well.

Icu 16406 roles read, update, delete

---

ui/admin/tests/acceptance/host-catalogs/list-test.js
ui/admin/tests/acceptance/host-catalogs/selectors.js

Use test selectors in host-catalog/list
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-15490) 

refactor: 💡 use test selector in host-catalog/list

---

ui/admin/tests/acceptance/workers/create-tags-test.js
ui/admin/tests/acceptance/workers/list-test.js
ui/admin/tests/acceptance/workers/selectors.js
ui/admin/tests/acceptance/workers/tags-test.js

Workers test refactor:
[create-tags](https://hashicorp.atlassian.net/browse/ICU-16452)
[list](https://hashicorp.atlassian.net/browse/ICU-16451)
[tags](https://hashicorp.atlassian.net/browse/ICU-16758)

Refactor: Workers test - Create-tags, list and tags

---

addons/rose/addon/components/rose/pagination/index.hbs
ui/admin/app/components/form/role/manage-scopes/index.hbs
ui/admin/tests/acceptance/roles/global-scope-test.js
ui/admin/tests/acceptance/roles/list-test.js
ui/admin/tests/acceptance/roles/selectors.js
ui/admin/tests/helpers/selectors.js

Test selector refactor for roles list & global-scope
Since global-scope was such a big file, I opted to just have these 2 files in this PR
:tickets: 
[List](https://hashicorp.atlassian.net/browse/ICU-16409)
[Global-Scope](https://hashicorp.atlassian.net/browse/ICU-16410)

Icu 16409 roles list & global-scope

---

addons/api/addon/handlers/indexed-db-handler.js
addons/api/package.json
addons/api/tests/unit/handlers/indexed-db-handler-test.js
yarn.lock

To support the upcoming sorting work this adds a few tests cases to test the baseline expectations for the indexedb handler. To avoid creating multiples of 10,000 records to test batch loading, it also makes the batch size configurable by the ember environment config.

Add tests for indexed db handler

---

yarn.lock

Update browserslist DB to avoid CLI alert when running the UI's
Run Admin or Desktop UI without seeing the alert for upgrading browserslist (screenshot above)

Update browserslist db

---

ui/admin/app/styles/app.scss

Due to recent hds upgrade to v4.18 borders are now visible in hds tables. This PR removes the borders only for our custom `ListWrapper` component.
Before Example:
After Example:
Check the following forms to verify the borders are no longer visible.
1. Ldap auth-method
2. Oidc auth-method
3. Vault generic secrets credential-library
4. Vault ssh-certificates credential-library
5. Aws host-catalog
6. Aws host-set
7. Azure host-set
8. Gcp host-set
9. Aws storage-bucket
10. Target
11. Create tags page for workers

style: 💄 remove table borders from list-wrapper component

---

ui/desktop/app/components/hidden-secret/index.hbs

✅ Closes: https://hashicorp.atlassian.net/browse/ICU-16956
use Hds::Text::Code in place of pre tag
Visit the vercel build of the desktop, connect to a target, toggle one of the secret credentials to reveal the actual value. That is the text that was replaced.

refactor: 💡 use Hds::Text::Code in place of pre tag

---

ui/desktop/CHANGELOG.md

Update changelog with release date.

chore: 🤖 update changelog with date

---

ui/admin/tests/acceptance/credential-store/credentials/list-test.js
ui/admin/tests/acceptance/credential-store/selectors.js

Refactor credentials list test selectors.
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-15479)
- Run acceptance test suite successfully.

Refactor credential-store/credentials list test selectors

---

addons/core/translations/resources/en-us.yaml
ui/admin/app/templates/scopes/scope/auth-methods/index.hbs

Small update to column header for 'Primary' in auth-methods table.

refactor: 💡 add title to primary column in auth-methods table

---

ui/admin/app/components/scope-picker/index.hbs
ui/admin/tests/acceptance/auth-methods/create-test.js
ui/admin/tests/acceptance/auth-methods/selectors.js
ui/admin/tests/acceptance/auth-methods/update-test.js
ui/admin/tests/acceptance/scopes-test.js
ui/admin/tests/helpers/selectors.js

Refactor scopes test selector refactor.
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-16455)
Run acceptance test suite successfully.

Refactor scopes test selectors

---

ui/admin/app/routes/scopes/scope/sessions/index.js

This fixes the bugs in the cache mentioned in https://github.com/hashicorp/boundary-ui/pull/2850 by removing the cache. The cache was determined not to be worth the added complexity. The "cache" here is referred to the stored references to `allSessions`, `associatedUsers`, and `associatedTargets` that were saved on the route for the current scope.
1. When visiting a project that has no sessions, visiting a different project with sessions should show those sessions
2. When visiting a project that has users associated with its sessions, visiting a different project with different users associated with its session should show the updated users in the users filter
2. When visiting a project that has targets associated with its sessions, visiting a different project with different targets …

Remove cached resources on sessions route

---

ui/admin/tests/acceptance/targets/create-alias-test.js
ui/admin/tests/acceptance/targets/enable-session-recording-test.js
ui/admin/tests/acceptance/targets/selectors.js

✅ Closes: https://hashicorp.atlassian.net/browse/ICU-16433
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-16434
Refactor test selectors.

test: 💍 refactor targets create alias & enable SR test selectors

---

ui/admin/tests/acceptance/aliases/delete-test.js
ui/admin/tests/acceptance/aliases/list-test.js
ui/admin/tests/acceptance/aliases/selectors.js

Refactor test selectors for aliases delete and list.
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-15457).
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-15458).
- Run tests successfully.

Refactor test selectors aliases

---

ui/admin/app/templates/scopes/scope/workers/index.hbs

✅ Closes: https://hashicorp.atlassian.net/browse/ICU-17305
Add last seen column to workers table.
https://github.com/user-attachments/assets/73a144cf-5de2-42a8-8527-75c2db663e42
Go to workers table and verify new column is visible with correct relative time.

refactor: 💡 add last seen time column to workers list view

---

ui/admin/tests/acceptance/managed-groups/members-test.js
ui/admin/tests/acceptance/roles/delete-test.js
ui/admin/tests/acceptance/roles/principals-test.js
ui/admin/tests/acceptance/users/accounts-test.js
ui/desktop/tests/acceptance/projects/sessions/index-test.js
ui/desktop/tests/acceptance/projects/targets/index-test.js
ui/desktop/tests/acceptance/scopes-test.js

Replace `this.server.db` for `this.server.schema` within tests.
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-16378)
- Run test suite successfully.

Replace this.server.db with this.server.schema

---

ui/admin/app/components/targets/target/actions/index.hbs
ui/admin/tests/acceptance/targets/host-sources-test.js
ui/admin/tests/acceptance/targets/selectors.js

✅ Closes: https://hashicorp.atlassian.net/browse/ICU-16435
Refactor test selectors for target host sources.

test: 💍 refactor target host sources test selectors

---

.github/workflows/test-e2e-desktop.yaml

Change the run condition for DC E2E tests to allow them to run in ent

chore: 🤖 Allow DC E2E tests to run in ent

---

ui/desktop/CHANGELOG.md

fix: 🐛 release date

---

ui/admin/tests/acceptance/targets/manage-alias-test.js
ui/admin/tests/acceptance/targets/selectors.js

✅ Closes: https://hashicorp.atlassian.net/browse/ICU-16437
Refactor test selectors for targets manage alias page.

test: 💍 refactor targets manage alias test selectors

---

ui/admin/README.md
ui/admin/testem.js
ui/desktop/README.md
ui/desktop/testem.js

for admin and desktop
This adds an environment variable `DARK_MODE` that will set the test browser appearance to dark. Our app "theme" selection by default is "system default". By changing the appearance of the browser, we can keep our existing test that verify the color theme changes when the user explicitly sets the theme to `light` or `dark`.
**Admin**
**Desktop**
cd to `ui/admin` and `ui/desktop` respectively and run both commands
run `ember test --server` to verify the test browser is in light mode (as long as system appearance is in light mode)
run `DARK_MODE=true ember test --server` to verify the test browser is in dark mode (even if your system appearance is in light mode)
Examples of changes to security controls include using new access control methods, adding or removing …

(HACK WEEK 2025) chore: 🤖 add DARK_MODE env variable to testem config

---

addons/rose/app/styles/rose/_typography.scss
ui/admin/config/environment.js
ui/admin/tests/test-helper.js
ui/desktop/config/environment.js
ui/desktop/tests/test-helper.js

This work adds the a dynamic runOption config for axe and our a11y tests. When the a11y tests are run in light mode (`pnpm test-a11y`), the full set of rules will be run specified by the tags we use. When the a11y tests are run in dark mode (`pnpm test-a11y:dark`), the only rule we need is `color-contrast`.
You can see this in the below screenshots. While in light mode, we have 2 violations but in dark mode we only have 1.
Light mode:
Dark mode:

(HACK WEEK 2025) Dark mode a11y audit rules

---

e2e-tests/helpers/boundary-api-client.ts

For tests that don't use `apiClientTestAfter` fixture it still has to be provided for any test that uses `apiClient` to fulfill the dependency. To work around this a noop function can be provided instead and then overridden in the `api-client.spec.js` test itself.
This was introduced in this [commit](https://github.com/hashicorp/boundary-ui/pull/2901/commits/c15562a7a30da21c61e15d0fdab6dfad55ce1d6d) when the `apiClientTestAfter` fixture was introduced. The `api-client.spec.js` tests were passing locally but I didn't test the effect of the `apiClientTestAfter` fixture on other e2e tests. The [PR](https://github.com/hashicorp/boundary-ui/pull/2901) that introduced this issue passed CI because desktop e2e tests weren't ran (even though those tests are currently not blocking, the check would …

fix: 🐛 fix e2e-tests api client fixture dependency on `apiClientTestAfter`

---

addons/api/addon/services/sqlite.js
addons/api/addon/workers/utils/schema.js

✅ Closes: https://hashicorp.atlassian.net/browse/ICU-17413
Added fts tables to groups to improve search speeds.
initial load and search is less than 100ms
Use this [cluster](http://boundary-alb-dvtowfcd-362873315.us-east-1.elb.amazonaws.com:9200/) (400k groups located at global level)

feat: 🎸 add fts tables to groups

---

addons/api/addon/services/sqlite.js
addons/api/addon/workers/utils/schema.js

✅ Closes: https://hashicorp.atlassian.net/browse/ICU-17417
Add sqlite support to host catalogs
Initial load after host catalogs are cached is <100ms
Use project containing 400k host-catalogs in this [cluster](http://boundary-alb-dvtowfcd-362873315.us-east-1.elb.amazonaws.com:9200)

feat: 🎸 Add sqlite support to host-catalogs

---

addons/api/addon/handlers/sqlite-handler.js
addons/api/addon/workers/sqlite-worker.js

It's possible for our DB to get into a corrupted state which would cause a user to just get stuck and no easy way to recover without clearing out their browser cache. If this happens, we should just manually clear the db and try again for them. 
It's hard to reproduce but try and visit a page that has a lot of resources to insert and immediately try and goto a different page from the browser (so it refreshes, not manually navigating, e.g. goto `http://localhost:4200` and hit enter in the browser). It won't happen every time but the console should still show the error but it should now recover. 
- ~[ ] I have added tests that prove my fix is effective or that my …

feat: 🎸 Handle corrupted sqlite DB

---

pnpm-lock.yaml

Upgrade `form-data` to resolve the reported security issue https://github.com/hashicorp/boundary-ui/security/code-scanning/189
It doesn't look like it affects us but there's a simple upgrade for it.

chore: 🤖 Update form-data dependency

---

addons/core/translations/resources/en-us.yaml
ui/admin/app/components/form/alias/index.hbs
ui/admin/config/environment.js

Aliases for windows machines should contain `.`, this pr helps inform those creating aliases in the UI by updating the text on the form. It also links out to the boundary docs for the bigger technical details.

docs: ✏️ update alias value helper text

---

ui/desktop/electron-app/src/models/session.js

✅ Closes: https://hashicorp.atlassian.net/browse/ICU-17645
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-16776
This fixes two different (but related) bugs. The first is on windows when logging out or quitting, clicking OK doesn't do anything and the user can't logout or exit. This is because the `this.#process.killed` condition wasn't getting properly tracked due to us using `treeKill`. It doesn't look like there's any issue with using the standard `kill()` so I swapped back to using it. 
The second bug on windows and linux was sessions not properly getting canceled even after clicking OK on the modal. It works fine on Mac. This seems to be because just killing the underlying process we used to start the session doesn't actually cancel on windows or linux. I just manually canceled …

fix: 🐛 Fix sessions not properly getting cleaned up
