- addons/api/addon/models/host-set.js
- addons/api/tests/unit/models/host-set-test.js
- ui/core/app/components/form/host-set/add-hosts/index.hbs
- ui/core/app/components/form/host-set/create-host/index.hbs
- ui/core/app/controllers/scopes/scope/projects/project/host-catalogs/host-catalog/host-sets/host-set/create-host.js
- ui/core/app/router.js
- ui/core/app/routes/scopes/scope/projects/project/host-catalogs/host-catalog/host-sets/host-set/create-host.js
- ui/core/app/templates/scopes/scope/projects/project/host-catalogs/host-catalog/host-sets/host-set/-actions.hbs
- ui/core/app/templates/scopes/scope/projects/project/host-catalogs/host-catalog/host-sets/host-set/create-host.hbs
- ui/core/app/templates/scopes/scope/projects/project/host-catalogs/host-catalog/host-sets/host-set/create-host/-header.hbs
- ui/core/app/templates/scopes/scope/projects/project/host-catalogs/host-catalog/host-sets/host-set/hosts.hbs
- ui/core/tests/acceptance/host-sets/hosts-test.js
- ui/core/tests/unit/controllers/scopes/scope/projects/project/host-catalogs/host-catalog/host-sets/host-set/create-host-test.js
- ui/core/tests/unit/routes/scopes/scope/projects/project/host-catalogs/host-catalog/host-sets/host-set/create-host-test.js
- ui/core/translations/form/en-us.yaml
- ui/core/translations/resources/en-us.yaml
Introduces ability to create a host and assign it to a host set automagically from within a host set. This removed the current need to navigate to a host catalog to create a host and then navigate into a host set to assign it. The current assignment of hosts in a host set workflow hasn't been changed.
> Add ability to create and assign host to a host set in one step

- .github/workflows/jira.yml
GitHub advised us that we were using a Jira workflow version with an interpolation-related code execution vulnerability ([GHSL-2020-207-hashicorp-boundary-ui-workflow.pdf](https://github.com/hashicorp/boundary-ui/files/5461210/GHSL-2020-207-hashicorp-boundary-ui-workflow.pdf)).
This moves to a newer version of that workflow in which the vulnerability is addressed.
> update gajira-comment action, addressing security vulnerability

- docker-compose-embedding.yml
Instead of using dockerhub (which will enforce rate limiting on anonymous image pulls starting Nov 1st), we're moving projects to our mirror at `docker.mirror.hashicorp.services`. We're updating CircleCI configs, docker compose, dockerfiles, and travis configs. Github actions are excluded, as Github is handling the issue on their end. LMK if you have any q's, otherwise feel free to approve and merge on your own!
> Use docker mirror

- addons/rose/addon/components/rose/dropdown/index.hbs
- addons/rose/addon/components/rose/dropdown/index.stories.mdx
- addons/rose/addon/components/rose/dropdown/section/index.hbs
- addons/rose/addon/components/rose/dropdown/section/index.js
- addons/rose/addon/components/rose/form/radio/group/index.hbs
- addons/rose/addon/components/rose/form/radio/group/index.stories.mdx
- addons/rose/addon/components/rose/form/radio/radio/index.hbs
- addons/rose/addon/components/rose/form/radio/radio/index.stories.mdx
- addons/rose/addon/styles/rose/components/card/_link.scss
- addons/rose/addon/styles/rose/components/dropdown/_dropdown.scss
- addons/rose/addon/styles/rose/components/dropdown/_index.scss
- addons/rose/addon/styles/rose/components/dropdown/_section.scss
- addons/rose/addon/styles/rose/components/header/_index.scss
- addons/rose/addon/styles/rose/variables/_opacity.scss
- addons/rose/addon/styles/rose/variables/color/_css.scss
- addons/rose/app/components/rose/dropdown/section.js
- addons/rose/tests/dummy/app/templates/index.hbs
- addons/rose/tests/integration/components/rose/dropdown/section-test.js
- addons/rose/tests/integration/components/rose/form/radio/group-test.js
- ui/core/app/routes/application.js
- ui/core/app/templates/application.hbs
- ui/core/tests/acceptance/authentication-test.js
- ui/core/translations/en-us.yaml
This PR introduces a color theme toggle to the header dropdown, persisted locally via the session service.
> Feature dark mode toggle

- addons/rose/addon/styles/rose/components/dropdown/_item.scss
- addons/rose/addon/styles/rose/components/dropdown/_section.scss
- ui/core/app/components/form/role/index.hbs
- ui/core/app/styles/app.scss
This PR implements minor style updates to dropdown radios to make them more obviously radio-like.
> Chore alternate dropdown radios

- package.json
- yarn.lock
Template linting was broken because of a yargs resolution, which itself was enabled to fix a security warning in GitHub.  As the template linting is higher priority, I'm removing the yargs resolution for now.
> fix: 🐛 fix yargs resolution that breaks template linting

- addons/core/package.json
- ui/admin/app/styles/_notify.scss
- ui/admin/package.json
- ui/desktop/app/styles/_notify.scss
- ui/desktop/package.json
- yarn.lock
This PR improves on the ember-notify style fix.  Previously we had duplicated styles and used `!important` to override.  The better approach was to bring the addon local to each app rather than providing it via core.
> fix: 🐛 fix ember-notify style dupe/override problem

- ui/desktop/app/routes/scopes/scope/projects/targets.js
- ui/desktop/electron-app/src/boundary-cli.js
- ui/desktop/electron-app/src/handlers.js
Plumbs the controller URL specified in the desktop client through to the CLI via the `-addr` option.
> fix: 🐛 desktop client should pass controller URL to CLI

- ui/desktop/electron-app/package.json
- ui/desktop/electron-app/yarn.lock
- ui/desktop/package.json
- yarn.lock
Project's `build:ui:desktop` task will now trigger desktop ember app to be build in production mode and then package it up using electron's dmg maker.
> Add electron build task to desktop build task

- addons/core/translations/actions/en-us.yaml
- addons/core/translations/en-us.yaml
- addons/core/translations/form/en-us.yaml
Minor refactor to address renaming of 'Controller URL' to 'Origin URL' to address vocab concerns.
> refactor: Update Controller URL to Origin URL

- README.md
- ui/desktop/README.md
- ui/desktop/electron-app/config/forge.config.js
- ui/desktop/electron-app/package.json
Extract electron config from package.json to be able to use prePackage hook to check for code signing.
Code signing will be based on finding `BOUNDARY_DESKTOP_SIGNING_IDENTITY` in env variables.
> Add code signing check for desktop

- ui/desktop/electron-app/config/forge.config.js
`osxSign` should be within `packagerConfig`, not the main `forgeConfig`.
Ref: https://www.electronjs.org/docs/tutorial/code-signing#electron-forge
> chore: Attach osx sign to packager config correctly

- ui/desktop/README.md
- ui/desktop/app/routes/scopes/scope/projects/targets.js
- ui/desktop/electron-app/.gitignore
- ui/desktop/electron-app/config/cli.js
- ui/desktop/electron-app/config/forge.config.js
- ui/desktop/electron-app/package.json
- ui/desktop/electron-app/src/boundary-cli.js
- ui/desktop/electron-app/src/handlers.js
- ui/desktop/electron-app/src/spawn-promise.js
- ui/desktop/electron-app/yarn.lock
- ui/desktop/package.json
- yarn.lock
As part of building and packaging of desktop client, download boundary artifact from releases.hashicorp.com and extract it into `cli` folder under electron app. CLI commands in Desktop Client have been updated to use this bundled cli path instead of checking PATH.
> Bundle Boundary CLI into Desktop Client

- ui/desktop/electron-app/config/forge.config.js
Use basic electronforge config example to view signing errors in console.
Ref: https://www.electronjs.org/docs/tutorial/code-signing#electron-forge
> chore: Use basic electronforge config to view signing errors

- addons/core/translations/resources/en-us.yaml
- ui/desktop/app/routes/scopes/scope/projects/targets.js
- ui/desktop/app/routes/scopes/scope/projects/targets/target.js
- ui/desktop/app/routes/scopes/scope/projects/targets/target/hosts.js
- ui/desktop/app/templates/scopes/scope/projects/targets/target.hbs
- ui/desktop/app/templates/scopes/scope/projects/targets/target/-actions.hbs
- ui/desktop/app/templates/scopes/scope/projects/targets/target/hosts.hbs
- ui/desktop/electron-app/src/boundary-cli.js
- ui/desktop/electron-app/src/handlers.js
Introduces button to connect to a specific host within a target.
TODO: There's bit of duplication between connecting to a host and connecting to a target. Good point of refactor for either a new decorator or a service.
> feat: Connect to a host within target

- ui/desktop/app/templates/scopes/scope/projects/targets/target/-actions.hbs
Issue: Using connect action in a target view raises following error:
It's caused by mismatched target model being passed in for connect action.
> fix: Connecting from a target view raises toString error

- ui/desktop/app/templates/scopes/scope/projects/targets/target/sessions.hbs
> Show session proxy details in active sessions in a target

- addons/api/addon/models/session.js
- addons/api/addon/models/target.js
- addons/api/mirage/config.js
- ui/desktop/app/controllers/scopes/scope/projects/sessions/index.js
- ui/desktop/app/routes/scopes/scope.js
- ui/desktop/app/routes/scopes/scope/projects.js
- ui/desktop/app/routes/scopes/scope/projects/sessions.js
- ui/desktop/app/routes/scopes/scope/projects/targets.js
- ui/desktop/app/templates/scopes/scope/projects/sessions/index.hbs
- ui/desktop/app/templates/scopes/scope/projects/targets/index.hbs
- ui/desktop/tests/unit/controllers/scopes/scope/projects/sessions/index-test.js
This PR updates desktop to use recursive queries for scopes, targets, and sessions.  It adds recursion support to mocks for the resources as well (and only these for now).  Also, session filtering and sorting is moved to the controller to simplify the route model.
> refactor: 💡 use recursive listing for desktop queries

- ui/desktop/app/templates/error.hbs
Shows user a common error message when errors occur. This prevents blank white screens on network errors.
> chore: Add a catchall error template

- addons/core/translations/resources/en-us.yaml
- ui/desktop/app/templates/scopes/scope/projects/sessions/index.hbs
- ui/desktop/app/templates/scopes/scope/projects/targets/index.hbs
- ui/desktop/app/templates/scopes/scope/projects/targets/target/hosts.hbs
- ui/desktop/app/templates/scopes/scope/projects/targets/target/sessions.hbs
I reused most of admin messages but we should consider tailoring messages to desktop client. Creating PR as draft to kickoff discussions.
> [WIP] feat: Show info messages when resources are empty

- addons/core/tests/integration/components/error/message-test.js
- addons/core/translations/actions/en-us.yaml
- addons/core/translations/errors/en-us.yaml
- ui/desktop/app/routes/application.js
- ui/desktop/app/services/origin.js
- ui/desktop/app/templates/error.hbs
- ui/desktop/electron-app/src/handlers.js
- ui/desktop/electron-app/src/origin.js
When an error occurs, it's difficult to know if it's recoverable.  The user may now choose to disconnect from their Boundary origin and reset the client.
> Add "disconnect" escape hatch to error page in desktop

- ui/desktop/app/controllers/scopes/scope/projects/sessions/index.js
- ui/desktop/app/controllers/scopes/scope/projects/targets/target/sessions.js
- ui/desktop/app/routes/scopes/scope/projects/targets/target/sessions.js
- ui/desktop/app/templates/scopes/scope/projects/targets/target/sessions.hbs
This fix ensures that target/sessions as well as overall sessions are properly updated when polling.
> fix: 🐛 target sessions should update on poll

- ui/desktop/CHANGELOG.md
- ui/desktop/app/styles/app.scss
Scrolling now occurs within columns individually so that sidebar and header remain visible when scrolling the application body.
> Chore scrolling

- ui/desktop/electron-app/src/handlers.js
- ui/desktop/electron-app/src/index.js
- ui/desktop/package.json
- yarn.lock
These occurrences have been manually checked and approved.  However, three [alerts could not be cleared due to a limitation in the disable feature](https://github.com/doyensec/electronegativity/issues/78#issuecomment-793143498).
> chore: 🤖 add electronegativity inline disable flags

- ui/desktop/CHANGELOG.md
- ui/desktop/electron-app/src/menu.js
- ui/desktop/tests/acceptance/origin-test.js
[Bug](https://github.com/electron/electron/issues/15496) in electron forces zoom-in shortcut to be defined for keyboard shortcut to work.
> Specify zoom-in shortcut

- ui/desktop/electron-app/src/index.js
- ui/desktop/tests/acceptance/origin-test.js
Clearing localstorage after each test didn't work. Moving position of 'can reset origin before authentication' in test seems to do the trick. I'm sure it's something obvious but I'm not seeing it. Could use 👀  on this. Ty!
> test: Fix flaky origin test in desktop

- addons/core/translations/en-us.yaml
- ui/admin/app/router.js
- ui/admin/app/routes/authentication-complete.js
- ui/admin/app/routes/authentication-error.js
- ui/admin/app/styles/app.scss
- ui/admin/app/templates/authentication-complete.hbs
- ui/admin/app/templates/authentication-error.hbs
- ui/admin/tests/unit/routes/authentication-complete-test.js
- ui/admin/tests/unit/routes/authentication-error-test.js
`/authentication-complete`
`/authentication-error`
> Add static auth callback pages to admin UI for notifying success or error.

- .github/workflows/test-release-trigger.yml
Team has requested an option to run a test release from development branches. 
For now this will be a separate file for testing signing and notarization.
Please see trigger example:
> Add workflow to trigger test release manually

- ui/desktop/CHANGELOG.md
- ui/desktop/app/services/origin.js
- ui/desktop/electron-app/yarn.lock
- ui/desktop/tests/unit/services/origin-test.js
- yarn.lock
This resolves an issue where Boundary Desktop may generate API endpoint URLs with double slashes if the origin includes a trailing slash.  The solution is to silently drop trailing slashes  should the user include them.  This ensures users may enter origins with or without a trailing slashes and Boundary Desktop will still work as expected.
> fix: 🐛 silently drop trailing slashes from origin input - ICU-1293

- ui/desktop/app/templates/scopes/scope/projects/targets/index.hbs
> fix: Show project id to copy in targets list in desktop

- addons/api/package.json
- addons/auth/package.json
- addons/core/package.json
- addons/rose/package.json
- package.json
- ui/admin/package.json
- ui/desktop/package.json
Update the node versions our UI's can use. These versions are specified
on the engines key in the package.json of each UI (admin and desktop).
Our UI's can run from node v10 to v14, we can not run on v15 because
ember-cli does not support it yet (info [here](https://github.com/ember-cli/ember-cli/blob/master/docs/node-support.md)).
**How to test?**
I use [nvm](https://github.com/nvm-sh/nvm) to switch node version in my dev environment.
- Run `yarn run start` using `node` version `10`, `12` and `14`, should run no problem.
- Run `yarn run start` using `node` version `15`, should not run. You should see in the terminal a message like this `The engine "node" is incompatible with this module. Expected version ">=10 <=14". Got "15.14.0"`
> chore: 🤖 Update node version engines

- package.json
- yarn.lock
Merge package has a security vulnerability that is fixed in a newer
version. We do not resolve merge directly, but as a dependecy of a
dependecy, so we especify a version range via selective dependecy
resolution.
> fix: 🐛 Fix merge package vulnerability

- addons/core/package.json
- ui/admin/app/routes/authentication-error.js
- ui/admin/app/routes/scopes/scope/authenticate/method.js
- ui/admin/app/services/window-manager.js
- ui/admin/tests/unit/services/window-manager-test.js
- yarn.lock
This simple PR migrates admin UI to CrowdStrike/ember-browser-services.  This allows us to treat the `window` as a service and will facilitate the admin inline flow.
Additionally, this PR introduces a service to admin UI `WindowManager`, which allows new window instances to be opened and closed in aggregate without retaining window references at the callsite.
> chore: 🤖 replace admin window usage with ember browser services

- ui/admin/app/routes/scopes/scope/authenticate/method.js
- ui/admin/app/routes/scopes/scope/authenticate/method/oidc.js
- ui/admin/app/services/window-manager.js
- ui/admin/app/styles/app.scss
- ui/admin/app/templates/scopes/scope/authenticate/method/oidc.hbs
- ui/admin/config/environment.js
- ui/admin/tests/acceptance/authentication-test.js
This PR improves auth UX by enabling an "inline" OIDC flow, such that users will be shifted back into the admin UI after successfully authenticating.  Previously, users would land on a success message, requiring them to manually navigate back to the admin window.
To test this PR:
- Spin up Boundary dev and then run the UI externally, pointing it to the dev instance
- Click the OIDC "authenticate" button
- Log in and observe the provider window is automatically closed.
- Repeat to test OIDC "cancel" and "retry" features of the pending authentication dialog.
https://user-images.githubusercontent.com/8390120/117494076-d539c480-af41-11eb-94fe-558e1ef0ecc3.mov
> Enable inline OIDC flow for admin

- package.json
- yarn.lock
Update the version we resolve of dependency package trim since older version has a security vulnerability.
Tests performed:
- Run all the tests suite.
- Run `yarn run build:ui:admin` and `yarn run build:ui:desktop` to make sure this does not brake anything.
> fix: 🐛 Update trim package version resolution

- addons/api/addon/initializers/fragment-string.js
- addons/api/addon/models/auth-method.js
- addons/api/addon/models/fragment-auth-method-attributes.js
- addons/api/addon/serializers/fragment-string.js
- addons/api/addon/serializers/host-set.js
- addons/api/app/initializers/fragment-string.js
- addons/api/app/serializers/fragment-string.js
- addons/api/mirage/generated/factories/auth-method.js
- addons/api/tests/unit/initializers/fragment-string-test.js
- addons/api/tests/unit/serializers/auth-method-test.js
- addons/api/tests/unit/serializers/fragment-string-test.js
This PR completes OIDC auth method modelling with the missing string array fields.  Unlike other string array fields so far, these are updated via conventional PUT/PATCH requests, rather than via custom methods.  Thus no field-specific serialization methods are required as are found in previous serializers
> Feature more oidc modeling

- addons/rose/addon/components/rose/form/checkbox/index.hbs
- addons/rose/addon/components/rose/form/checkbox/index.stories.mdx
- addons/rose/addon/components/rose/table/row/cell/index.js
- addons/rose/addon/styles/rose/components/form/_checkbox.scss
- addons/rose/addon/styles/rose/components/table/_table.scss
- addons/rose/tests/integration/components/rose/form/checkbox-test.js
This PR adds support for helper text to the checkbox component, bringing it in line with other form components that already support help.  Helper text is optional.
> feat: 🎸 add helper text option to checkbox component

- addons/rose/addon/components/rose/form/select/index.hbs
- addons/rose/addon/components/rose/form/select/index.stories.mdx
- addons/rose/addon/components/rose/form/textarea/index.hbs
- addons/rose/addon/components/rose/form/textarea/index.stories.mdx
- addons/rose/tests/integration/components/rose/form/select-test.js
- addons/rose/tests/integration/components/rose/form/textarea-test.js
This PR adds support for contextual usage of select and textarea components, bringing them in line with the input component.  Contextual usage allows labels and fields to be rendered in arbitrary locations by the developer, which is useful when rendering form fields within a table.
> feat: 🎸 textarea and select should support contexual usage

- package.json
- yarn.lock
Update the resolutions to resolve a version of WS that has no security
vulnerabilities.
> chore: 🤖 Fix WS security vulnerability

- addons/rose/package.json
- yarn.lock
Update the version of @storybook/ember-cli-storybook we are using.
Tested running storybook with no problem.
**Why this change?**
After running `$ yarn outdated` this package was a bit out of date and decided to bump the version.
> chore: 🤖 Update ember-cli-storybook

- addons/rose/addon/styles/rose/components/dropdown/_button.scss
- addons/rose/addon/styles/rose/components/dropdown/_item.scss
- addons/rose/addon/styles/rose/components/dropdown/_link.scss
- addons/rose/addon/styles/rose/components/dropdown/_section.scss
- addons/rose/addon/styles/rose/components/header/_link.scss
- addons/rose/addon/styles/rose/components/list/_key-value.scss
- addons/rose/addon/styles/rose/components/nav/_sidebar.scss
- addons/rose/addon/styles/rose/components/table/_table.scss
- addons/rose/addon/styles/rose/variables/_typography.scss
Deprecation of slash as division operator as we were getting warnings in the terminal about it. More info [here](https://sass-lang.com/documentation/breaking-changes/slash-div).
> fix: 🐛 Deprecate Slash as division operator

- docker-compose-embedding.yml
- package.json
This PR introduces a yarn command that runs a windows asset build inside a container, rather than directly on the host, in order to work around an issue with translations paths not building correctly in windows.
> Chore windows container build

- package.json
- yarn.lock
As per dependanbot alert, a transitive dependency is using a version of clean-css that has a security vulnerability, With this change we force to resolve a version of clean-css that has not such vulnerability.
> chore: 🤖 Update resolutions for clean-css

- package.json
- yarn.lock
Fix yarn warning due to a strict version declaration of `hosted-git-info`.
Now the yarn warning is gone when running `yarn install`.
> fix: 🐛 Fix yarn warning due to strict version declaration

- ui/desktop/electron-app/package.json
- ui/desktop/electron-app/yarn.lock
Bump node-html-parser dependency on desktop. The goal is to update the
package and solve the css-what security vulnerability. Node-html-arser
requires css-what via transitive dependency css-select. Upgrading to the
last version of node-html-parser brings the css-what version that solves
the security issue.
> chore: 🤖 Bump node-html-parser dependency

- addons/api/mirage/config.js
- addons/rose/addon/styles/rose/components/dropdown/_item.scss
- addons/rose/addon/styles/rose/components/dropdown/_section.scss
- addons/rose/tests/dummy/app/templates/index.hbs
This PR simplifies condensed dropdown item styles for consistency with existing Structure canon.
> chore: 🤖 simplify dropdown styles for consistency with Structure

- addons/rose/addon/components/rose/dropdown/index.hbs
- addons/rose/addon/styles/rose/components/dropdown/_dropdown.scss
- addons/rose/addon/styles/rose/components/dropdown/_item.scss
- addons/rose/addon/styles/rose/components/dropdown/_section.scss
- addons/rose/addon/styles/rose/components/form/_fieldset.scss
- addons/rose/tests/dummy/app/templates/index.hbs
First iteration to add a condensed style for dropdown.
✅ Closes: ICU-1431
Condensed dropdown close:
Condensed dropdown open:
- The dropdown button `<details>` has a background (light grey) when the dropdown is open. I am pretty sure we do not want that, but just to confirm. Should I remove that background? It is visible on the condensed dropdown open screenshot.
- I did not use `<dropdown.separator />` as a separator between `sections`. I just add a `border-bottom` at section level. As per figma design I understand this is a better approach for this use case, but happy to change approach and use the `<dropdown.separator />`. Let me know your thoughts on this.
- Within the dropdown content, I applied lateral padding per `<section>` rather than the div `.rose-dropdown-content`. Why? because …
> feat: 🎸 Add condensed style for dropdown

- addons/rose/addon/components/rose/dropdown/index.hbs
- addons/rose/addon/components/rose/dropdown/index.stories.mdx
- addons/rose/addon/components/rose/dropdown/key-value/index.hbs
- addons/rose/addon/styles/rose/components/dropdown/_index.scss
- addons/rose/addon/styles/rose/components/dropdown/_key-value.scss
- addons/rose/app/components/rose/dropdown/key-value.js
- addons/rose/tests/dummy/app/templates/index.hbs
- addons/rose/tests/integration/components/rose/dropdown/key-value-test.js
Simple key-value item for use in `Rose::Dropdown`. Supports `key` and `value` named blocks.
```js
<Rose::Dropdown
@text="Credential library details"
@showCaret={{true}}
as |dropdown|
>
<dropdown.key-value>
<:key>ID</:key>
<:value>cl_nbv9375hLHs</:value>
</dropdown.key-value>
<dropdown.separator />
<dropdown.key-value>
<:key>Name</:key>
<:value>Key/Value</:value>
</dropdown.key-value>
<dropdown.separator />
<dropdown.key-value>
<:key>Description</:key>
<:value>Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda illo ratione libero ducimus magnam, porro sed provident repellat mollitia a, repellendus placeat. Magni consequuntur cumque, debitis obcaecati dolores quasi natus?</:value>
</dropdown.key-value>
</Rose::Dropdown>
```
> feat: Add KeyValue Dropdown Item

- addons/api/addon/models/session.js
- addons/api/mirage/scenarios/ipc.js
- ui/desktop/app/templates/scopes/scope/projects/targets.hbs
This PR removes unused credential purpose property from UI and displays name in credential header (instead of purpose).
> fix: Use name in connect header

- ui/admin/app/components/form/auth-method/oidc/index.hbs
This resolves an issue where "add" buttons in the OIDC form for new auth methods were disabled.  For now, the logic is expressed in the template, which is not ideal.  In the future, forms should be refactored to have a computed `disabled` or `isDisabled` property where much of this logic can be encapsulated.
> fix: OIDC form add buttons should be enabled for new auth methods

- ui/admin/app/styles/app.scss
- ui/admin/package.json
This pr fixes the font color and weight to be in sync with the design  
Before:
After:
> fix: Update text font color and weight 

- addons/api/package.json
- addons/auth/package.json
- addons/core/package.json
- addons/rose/package.json
- ui/admin/package.json
- ui/desktop/package.json
- yarn.lock
Upgrade ember-cli version.
**Why?** After running `yarn outdated` this library could be updated.
**Risks:** after checking their [changelog](https://github.com/ember-cli/ember-cli/blob/master/CHANGELOG.md) looks safe to upgrade.
> chore: 🤖 Upgrade ember-cli version

- addons/api/package.json
- addons/auth/package.json
- addons/core/package.json
- addons/rose/package.json
- ui/admin/package.json
- ui/desktop/package.json
- yarn.lock
Upgrade ember-cli-inject-live-reload dependency.
**Risk:** As per their [changelog](https://github.com/ember-cli/ember-cli-inject-live-reload/blob/master/CHANGELOG.md) we should experience no issues.
> chore: 🤖 Upgrade ember-cli-inject-live-reload

- addons/core/translations/actions/en-us.yaml
- addons/core/translations/resources/en-us.yaml
- ui/desktop/app/components/hidden-secret/index.hbs
- ui/desktop/app/styles/app.scss
Fix style and accessibility issues for hidden secret component.
This PR fixes issues commented in old (already merged) PR, more info [here](https://github.com/hashicorp/boundary-ui/pull/637#pullrequestreview-710864720).
- Fix reveal icon not having clickable area. Made it a button with Icon:
- Fix color issues with reveal icon, secret mask, and secret value:
- Fix padding issues with copyable Icon:
- Fix accessibility issue, adding a description to the button:
> fix: 🐛 Fix style and accessibility issues for hidden secret

- ui/admin/app/components/form/credential-store/index.hbs
- ui/admin/tests/acceptance/credential-stores-test.js
Add acceptance tests for list, create and edit credential stores.
Missing Delete tests because the delete feature is not available yet.
> Test acceptance credential stores

- addons/rose/addon/styles/rose/components/form/_fieldset.scss
Updating `fieldset` weight to be in sync with the label style. conversation [here](https://github.com/hashicorp/boundary-ui/pull/656)
> fix: 🐛 update fieldset font weight

- ui/admin/package.json
- ui/desktop/package.json
- yarn.lock
Update ember-cli-app version dependency.
**Risks:** As [per their changelog](https://github.com/ember-cli/ember-cli-app-version/blob/master/CHANGELOG.md) I do not anticipate any risks.
> chore: 🤖 Update ember-cli-app version dependency

- addons/api/addon/generated/models/credential-library.js
- addons/api/mirage/factories/credential-library.js
- addons/api/tests/unit/serializers/credential-library-test.js
- addons/core/translations/resources/en-us.yaml
- ui/admin/app/components/form/credential-library/index.hbs
- ui/admin/app/components/form/target/add-credential-libraries/index.hbs
- ui/admin/app/routes/scopes/scope/credential-stores/credential-store/credential-libraries/new.js
- ui/admin/app/templates/scopes/scope/credential-stores/credential-store/credential-libraries/index.hbs
- ui/admin/app/templates/scopes/scope/credential-stores/index.hbs
- ui/admin/app/templates/scopes/scope/targets/target/credential-libraries.hbs
> fix: Add type field to Credential Library

- addons/core/translations/resources/en-us.yaml
- ui/admin/app/components/form/target/add-host-sets/index.hbs
- ui/admin/app/templates/scopes/scope/targets/target/-navigation.hbs
- ui/admin/app/templates/scopes/scope/targets/target/credential-libraries.hbs
- ui/admin/app/templates/scopes/scope/targets/target/host-sets.hbs
Rename to Target Host Sources and Target Credential Sources.
> refactor: Rename target host sets and credential libraries

- package.json
- yarn.lock
Update xmldom transitive dependency resolution to avoid a security vulnerability.
**Readme before reviews:**
The maintainer of the project is having an issue to publish the latest version on NPM, they are working on it, in the meantime they recommend to resolve the package against their GH repo. [More info about it here](https://github.com/xmldom/xmldom/issues/271).
I already set a reminder on my calendar to check this periodically until the issuue is resolved, then I will provide a PR to delete the resolution with gh in favour of npm.
> chore: 🤖 Update xmldom dependency resolution

- addons/api/mirage/scenarios/default.js
When viewing sessions in desktop client with mirage enabled, missing target information blocks view from rendering. This is due to sessions mock data being generated before targets. Fix is to generate target mock data before sessions so that sessions will have targets available for assignment.
Error:
```
vendor.js:80053 Uncaught (in promise) Error: Expected id to be a string or number, received null
at ensureStringId (vendor.js:80053)
at Store.peekRecord (vendor.js:88151)
at SessionModel.get target [as target] (vendor.js:95825)
at getPossibleMandatoryProxyValue (vendor.js:13974)
at _getProp (vendor.js:14039)
at vendor.js:46608
at vendor.js:46556
at track (vendor.js:55304)
at valueForRef (vendor.js:46555)
at vendor.js:46605
```
> chore: 🤖 Fix missing target in sessions scenarios in mirage

- addons/api/mirage/factories/account.js
- addons/api/mirage/helpers/permissions.js
- yarn.lock
This PR adds development time support for capabilities toggling on mock resources.  To use the toggle, add a query string to the URL, with as many resources and permissions as desired.  For convenience, these should persist even as you navigate through the application.  Example:
`?authorized_actions={"account": ["read"]}`
Note that this feature is provided as a convenience and does not come with rigorous tests.  As it is only intended for use by our Mirage mocks, it only needs to be just _good enough_ to solve the development use case (and not cause tests to fail).
> chore: 🤖 adds support for development capabilities toggle

- package.json
- yarn.lock
Update tar transitive dependency resolutions to avoid security vulnerability.
> chore: 🤖 Update tar dependency resolutions

- addons/api/addon/abilities/collection.js
- addons/api/app/abilities/collection.js
- addons/api/tests/unit/abilities/collection-test.js
- ui/admin/app/abilities/collection.js
- ui/admin/tests/unit/abilities/collection-test.js
- ui/desktop/app/abilities/collection.js
- ui/desktop/tests/unit/abilities/collection-test.js
This PR introduces ability models for collection capabilities `list`, `create`, and a composite capability `navigate`.
> Feature collection abilities

- package.json
- ui/desktop/electron-app/package.json
- yarn.lock
Delete xmldom transitive dependency from resolutions.
**Why this is happening?:** XLMDOM is a transitive dependency which we were forcing to resolve above certain version due to security vulnerabilities. This library now changed its name space in the NPM registry, so this will not work anymore. It will keep resolving a version with security vulnerabilities. [More information about their name space change](https://github.com/xmldom/xmldom/issues/271).
**What are next steps to solve this issue?** Because this is a transitive dependency, we are going to follow up what dependencies are bringing XLMDOM and updating them. Is the best we can do. I already checked `testem` one dependency that brings XLMDOM and they already update to the new namespace, [prove …
> chore: 🤖 Delete xmldom from resolutions

- ui/desktop/electron-app/package.json
- ui/desktop/electron-app/yarn.lock
Add ansi-regex transitive dependency to electron-app resolutions to avoid security vulnerability.
> chore: 🤖 Add ansi-regex to desktop resolutions

- package.json
- yarn.lock
Add ansi-regex transitive dependency to resolutions to avoid security vulnerability.
> chore: 🤖 Add ansi-regex transtitive dependency to resolutions

- ui/desktop/electron-app/package.json
- ui/desktop/electron-app/yarn.lock
Add nth-check, transitive dependency, to desktop resolutions to avoid security vulnerability
> chore: 🤖 Add nth-check desktop resolutions

- ui/desktop/electron-app/package.json
- ui/desktop/electron-app/yarn.lock
Update electron-forge and all the packages related to for desktop client.
@gsusmi mentioning you for visibility.
Updating: from 6.0.0-beta.54 to 6.0.0-beta.61
- @electron-forge/cli
- @electron-forge/maker-deb
- @electron-forge/maker-dmg
- @electron-forge/maker-squirrel
- @electron-forge/maker-zip
BUT all of them except cli and maker-deb are already resolving the 6.0.0-beta.61. Proof of this on the screenshot
> chore: 🤖 Update electron-forge for desktop client

- addons/rose/package.json
- yarn.lock
Bump package to 1.0.0 🚀 
I think dependabot will pick up future bumps with the `^` and we are following SemVer.
IS:
cc design systems folks @didoo @Dhaulagiri @MelSumner
> Bump @hashicorp/flight-icons to 1.0.0 with ^

- ui/admin/app/index.html
[Applies the `theme-color` meta](https://css-tricks.com/safari-15-new-ui-theme-colors-and-a-css-tricks-cameo/) to Boundary UI, which adds brand color to the latest versions of macOS and iOS Safari.
> feature: apply theme-color meta for more immersive UX

- addons/rose/package.json
- yarn.lock
Fix @babel-core unmet peer dependency in Rose.
Warning before fix:
No warning in Rose regarding `@babel-core`:
> fix: 🐛 Fix babel-core unmet peer dependency in Rose

- addons/api/tests/dummy/config/targets.js
- addons/auth/tests/dummy/config/targets.js
- addons/core/tests/dummy/config/targets.js
- addons/rose/tests/dummy/config/targets.js
- ui/admin/config/targets.js
- ui/desktop/config/targets.js
IE11 is no longer supported by many products, and Ember support will officially be removed soon.
> Drop IE11 support

- addons/rose/addon/components/rose/link-button/index.hbs
- ui/admin/tests/acceptance/accounts/create-test.js
- ui/admin/tests/acceptance/auth-methods/create-test.js
- ui/admin/tests/acceptance/credential-library/create-test.js
- ui/admin/tests/acceptance/credential-library/read-test.js
- ui/admin/tests/acceptance/credential-store/create-test.js
- ui/admin/tests/acceptance/groups/create-test.js
- ui/admin/tests/acceptance/host-catalogs/create-test.js
- ui/admin/tests/acceptance/host-catalogs/host-sets/create-test.js
- ui/admin/tests/acceptance/host-catalogs/hosts/create-test.js
- ui/admin/tests/acceptance/roles/create-test.js
- ui/admin/tests/acceptance/roles/list-test.js
- ui/admin/tests/acceptance/targets/create-test.js
- ui/admin/tests/acceptance/users/create-test.js
The LinkButton was silently broken due to a problem with a recent refactor.  This PR fixes that problem and updates the create acceptance tests in admin to test for the expected URLs in link buttons.
> fix: 🐛 fix broken LinkButton component and associated new tests

- addons/api/addon/adapters/application.js
- addons/api/mirage/config.js
- addons/api/mirage/scenarios/ipc.js
- addons/api/package.json
- addons/api/tests/unit/adapters/application-test.js
- addons/core/addon/helpers/app-name.js
- addons/core/addon/helpers/company-copyright.js
- addons/core/addon/helpers/company-name.js
- addons/core/addon/helpers/doc-url.js
- addons/core/addon/initializers/deprecations.js
- addons/core/addon/services/confirm.js
- addons/core/package.json
- addons/core/tests/integration/helpers/doc-url-test.js
- addons/rose/package.json
- addons/rose/tests/dummy/app/initializers/deprecations.js
- yarn.lock
Boundary UI used `ember-get-config` in multiple places, but this was ultimately unnecessary.  Removing our dependence on this addon brings us a step closer to adopting [Embroider](https://github.com/embroider-build/embroider).
> Remove ember-get-config

- addons/api/mirage/config.js
- ui/admin/app/routes/scopes/scope/auth-methods/auth-method/managed-groups.js
- ui/admin/app/templates/scopes/scope/auth-methods/auth-method/managed-groups/managed-group/-actions.hbs
Add delete CRUD operation to managed groups.
**[Preview link](https://boundary-ui-git-feature-managed-group-delete-hashicorp.vercel.app/scopes/global/auth-methods/auth-method-id-1/managed-groups/managed-groups-id-0)**
> feat: 🎸 Add managed groups delete CRUD operation

- ui/desktop/app/routes/scopes/scope/projects/sessions.js
- ui/desktop/app/templates/scopes/scope/projects/sessions/index.hbs
- ui/desktop/electron-app/src/index.js
This pr adds `toolbar` with filters to desktop sessions
**No results:**
**landing page:**
**active and terminated selected:**
> Feature desktop sessions filter

- addons/api/mirage/config.js
- ui/desktop/app/routes/scopes/scope/projects.js
- ui/desktop/app/routes/scopes/scope/projects/sessions.js
- ui/desktop/app/templates/scopes/scope/projects/sessions/index.hbs
This PR introduces dynamic filtering of sessions in Desktop by project.  This is useful UX enhancement because Desktop aggregates sessions across scopes.
[Demo link](https://boundary-ui-desktop-2136btvqm-hashicorp.vercel.app/scopes/global/projects/sessions?filter-project=%5B%22s_s9n819zgko7%22%2C%22s_xk1i4dk50v8%22%5D)
> Desktop sessions filtering

- ui/desktop/app/templates/scopes/scope/projects/targets/target/hosts.hbs
Add table header for hosts list within targets.
Also change the columns order to reflect latest design, [link here](https://www.figma.com/file/a8vdiYPLJqAw5RxGwpTMvM/Dynamic-Hosts-Catalog?node-id=305%3A9700)
[Direct link to desktop](https://boundary-ui-desktop-git-feature-add-targets-ho-66b587-hashicorp.vercel.app/scopes/global/projects/targets/1/hosts)
Before: No header
After:
> feat: 🎸 Add table header for hosts list within targets

- addons/api/addon/models/base.js
- addons/api/tests/unit/models/base-test.js
- ui/desktop/app/helpers/group-by.js
- ui/desktop/app/routes/scopes/scope/projects/sessions.js
- ui/desktop/app/styles/app.scss
- ui/desktop/app/templates/scopes/scope/projects/sessions/index.hbs
- ui/desktop/tests/integration/helpers/group-by-test.js
This PR improves the resource filtering experience in sessions by displaying project filters within their scope hierarchy:
[Demo link](https://boundary-ui-desktop-49a2yqc2m-hashicorp.vercel.app/scopes/global/projects/sessions?filter-project=%5B%22s_xk1i4dk50v2%22%2C%22s_tv6fv3yz8p6%22%5D&filter-status=%5B%5D)
> Improve project resource filtering for sessions in Desktop

- addons/api/addon/services/resource-filter-store.js
- addons/api/mirage/config.js
- addons/api/tests/unit/services/resource-filter-store-test.js
- ui/desktop/app/routes/scopes/scope/projects/sessions.js
- ui/desktop/app/routes/scopes/scope/projects/targets.js
- ui/desktop/app/templates/scopes/scope/projects/targets/index.hbs
- ui/desktop/tests/acceptance/projects/targets-test.js
This PR introduces targets filtering by projects in Desktop.
[Demo link](https://boundary-ui-desktop-cpk9hbg7d-hashicorp.vercel.app/scopes/global/projects/targets?filter-project=%5B%22s_xk1i4dk50v2%22%5D)
> Add targets filtering by projects in Desktop

- ui/admin/app/components/copyable/index.js
- ui/desktop/app/components/copyable/index.js
In an effort to remove uses of ember-concurrency in preparation for Ember 4.0, this PR refactors the copyable components to use pure Ember code instead.  Using `later()`, the same effect is achieved with no third-party dependency.
This PR has no user-facing effect.
> refactor: 💡 copyable component no longer uses ember-concurrency

- ui/desktop/app/controllers/scopes/scope.js
- ui/desktop/app/routes/scopes/scope.js
- ui/desktop/app/routes/scopes/scope/projects/targets/target.js
- ui/desktop/app/templates/application.hbs
- ui/desktop/app/templates/scopes/scope.hbs
- ui/desktop/app/templates/scopes/scope/projects/targets/target.hbs
- ui/desktop/package.json
- yarn.lock
This PR removes `renderTemplate` usage from routes in Desktop.  This API is now deprecated:  https://deprecations.emberjs.com/v3.x/#toc_route-render-template
> refactor: 💡 remove deprecated renderTemplate usage in desktop

- addons/rose/addon/components/rose/form/radio/radio/index.hbs
- addons/rose/addon/components/rose/form/radio/radio/index.js
- ui/admin/app/templates/scopes/scope/auth-methods/index.hbs
This pr migrates the main component class `rose-form-radio` from a static hard-coded value in the template to a component class attribute. this update allows passing in different class names to support radioCard field (upcoming pr)
> updates to rose radio component

- addons/api/addon/generated/models/host-catalog.js
- addons/api/addon/models/host-catalog.js
- addons/api/mirage/generated/factories/host-catalog.js
- addons/api/tests/unit/models/host-catalog-test.js
- ui/admin/app/templates/scopes/scope/host-catalogs/index.hbs
Add host catalog type basic support. Delete previous conditional rendering to just render static types.
This PR already adds this model changes within Mirage.
[Direct link](https://boundary-ui-23zp7iqbu-hashicorp.vercel.app/scopes/s_xk1i4dk50v2/host-catalogs)
Screenshot:
> feat: 🎸 Add host catalog type basic support

- addons/api/addon/adapters/application.js
- addons/api/addon/models/fragment-target-attributes.js
- addons/api/addon/models/target.js
- addons/api/addon/serializers/application.js
- addons/api/app/models/fragment-target-attributes.js
- addons/api/tests/unit/serializers/target-test.js
- ui/admin/app/components/form/target/index.hbs
Boundary UI has generally relied on ember model fragments to support nested fields (e.g. under `attributes`).  However this approach is complex (requiring additional models and serialisers) and couples Boundary to another third-party dependency.  This PR introduces first-class support for nested attributes by hoisting them up into the payload body at normalisation time.  It then serialises them back out to the nested attributes field.  To start, the **Target** resource is refactored to use the new approach.
For example in a model:
```js
@attr('string', { isNestedAttribute: true }) fieldName;
```
> Support nested attributes with no dependencies

- ui/admin/app/templates/scopes/scope/host-catalogs/host-catalog/host-sets/index.hbs
Add type badges for host-set.
When `type` === `static`:
When `type` is plugin (`aws` or `azure`):
> feat: 🎸 Add type badges for host-set

- addons/api/addon/abilities/host-catalog.js
- addons/api/addon/models/host-catalog.js
- addons/api/app/abilities/host-catalog.js
- addons/api/mirage/factories/host-catalog.js
- addons/api/mirage/generated/factories/host-catalog.js
- addons/api/mirage/scenarios/default.js
- addons/api/tests/unit/models/host-catalog-test.js
- addons/core/translations/resources/en-us.yaml
- ui/admin/app/templates/scopes/scope/host-catalogs/index.hbs
This PR introduces support for "unknown" typed dynamic host catalogs.  This could occur if a third-party plugin is installed that is unsupported by the UI.  While we can display such a catalog in an index, we cannot link to a details route or allow editing.  As such, unknown catalogs are always "list only" in the UI.
> Add support for "unknown" dynamic host catalogs

- ui/admin/app/templates/scopes/scope/host-catalogs/host-catalog/hosts/index.hbs
Add type badges to host
- [Link to Azure host list](https://boundary-ui-git-feat-add-type-badges-host-hashicorp.vercel.app/scopes/s_xk1i4dk50v2/host-catalogs/1/hosts).
- [Link to Aws host list](https://boundary-ui-git-feat-add-type-badges-host-hashicorp.vercel.app/scopes/s_xk1i4dk50v2/host-catalogs/4/hosts).
- [Link to Static host list](https://boundary-ui-git-feat-add-type-badges-host-hashicorp.vercel.app/scopes/s_xk1i4dk50v2/host-catalogs/2/hosts).
`Static` type host list:
`aws` type host list:
`azure` type host list:
> feat: 🎸 Add type badges to host

- addons/api/mirage/factories/host-catalog.js
- addons/api/mirage/factories/host-set.js
- addons/api/mirage/factories/host.js
- ui/admin/app/abilities/host-catalog.js
- ui/admin/app/templates/scopes/scope/host-catalogs/host-catalog/-navigation.hbs
This PR disallows navigation from dynamic host catalogs directly to hosts, since there may be too many hosts (the existence of which is also dynamic) to be of practical value.  This PR also corrects the grant mocks for dynamic host catalogs to be more realistic.
Static host catalog navigation:
Dynamic host catalog navigation:
> Disable non-static hosts navigation

- addons/core/translations/form/en-us.yaml
- ui/admin/app/components/form/host-catalog/aws/index.hbs
- ui/admin/app/components/form/host-catalog/azure/index.hbs
currently these are not supported: `access_key_id` and `secret_access_key` 
link [here](https://boundary-ui-kkx8779mx-hashicorp.vercel.app/scopes/s_xk1i4dk50v2/host-catalogs/new?type=aws)
The POST request to the API is serialized properly, but we are missing these two fields (`access_key_id` and `secret_access_key` ) in the normalization.  This will be covered in a separate PR
> chore: host catalog form- add rest of the AWS and Azure fields

- ui/admin/app/routes/scopes/scope/host-catalogs/new.js
This PR modifies _new host catalog_ behavior such that `name` and `description` are retained when switching among instance types.
> chore: 🤖 reuse name/description when changing instance type

- addons/api/addon/generated/models/host.js
- addons/api/addon/models/fragment-host-attributes.js
- addons/api/addon/models/host.js
- addons/api/app/models/fragment-host-attributes.js
- addons/api/tests/unit/serializers/host-test.js
Add new fields to host and refactor field address to use no more `fragment-host-attribute-model`.
**Be aware:** These changes does NOT include these new fields in mirage, that will come in a separate PR.
> feat: 🎸 Add new fields to host

- addons/api/addon/serializers/application.js
- addons/api/addon/serializers/host-catalog.js
- addons/api/tests/unit/serializers/host-catalog-test.js
Refactor app normalize to deal with nestedAttributes and nestedSecrets as expected, before it was not working as expected. Refactor the host catalog normalize method. Add normalize test on host catalog to validate changes on normalize methods.
> refactor: 💡 Refactor app normalize and host catalog normalize

- addons/api/mirage/factories/host-set.js
Fix the filter field for host-set in mirage. It was returning an error rather than a string.
> fix: 🐛 Fix filter field for host-set in mirage

- addons/api/addon/models/host-set.js
- addons/api/tests/unit/models/host-set-test.js
- ui/admin/app/components/form/target/add-host-sets/index.hbs
- ui/admin/app/components/host-catalog-type-badge/index.hbs
- ui/admin/app/templates/scopes/scope/host-catalogs/host-catalog/host-sets/host-set/hosts.hbs
- ui/admin/app/templates/scopes/scope/host-catalogs/host-catalog/host-sets/index.hbs
- ui/admin/app/templates/scopes/scope/host-catalogs/index.hbs
- ui/admin/app/templates/scopes/scope/targets/target/host-sources.hbs
This PR moves type badges for host catalogs, host sets, and hosts to a component for consistency.
> refactor: 💡 consolidate host catalog type badges to component

- addons/api/addon/adapters/host-catalog.js
- addons/api/app/adapters/host-catalog.js
- addons/api/mirage/config.js
- addons/api/tests/unit/adapters/host-catalog-test.js
The API requires us to send ?plugin_name on create. This is how we set the type for dynamic host catalogs. It does not accept this via the payload.
> fix: append ?plugin_name to dynamic host catalog create requests

- addons/core/translations/form/en-us.yaml
- ui/admin/app/components/form/host-catalog/aws/index.hbs
- ui/admin/app/components/form/host-catalog/aws/index.js
- ui/admin/app/components/form/host-catalog/azure/index.hbs
- ui/admin/app/routes/scopes/scope/host-catalogs/host-catalog/host-sets/new.js
- ui/admin/app/routes/scopes/scope/host-catalogs/new.js
- ui/admin/app/templates/scopes/scope/host-catalogs/host-catalog/host-sets/new.hbs
This PR exposes the `disable_credential_rotation` field for dynamic host catalogs.  For AWS it is editable.  For Azure, it is always `true`.
Demo:
https://boundary-ui-git-feature-disable-credential-rotation-hashicorp.vercel.app/scopes/s_xk1i4dk50v2/host-catalogs/new?type=aws
> Expose disable credential rotation field

- addons/api/mirage/factories/host.js
- addons/api/mirage/generated/factories/host.js
Refactor `ip_addresses`, `dns_names` and `external_id` to not be nested under `attributes: {}` when generating mock data.
> fix: 🐛 Fix host mock data attributes

- ui/admin/app/components/form/host/aws/index.hbs
this fixes multiple label issues in AWS host latest IP addresses
AWS:
https://boundary-ui-git-fix-labels-hashicorp.vercel.app/scopes/s_xk1i4dk50v2/host-catalogs/host-catalog-id-5/hosts/host-id-50
Azure: https://boundary-ui-git-fix-labels-hashicorp.vercel.app/scopes/s_xk1i4dk50v2/host-catalogs/host-catalog-id-3/hosts/host-id-30
> fix: 🐛 multiple labels

- ui/admin/app/templates/scopes/scope/host-catalogs/host-catalog/host-sets/host-set/-actions.hbs
Refactor host-set actions dropdown separator to not be show when there is just 1 option.
[Jira ticket](https://hashicorp.atlassian.net/browse/ICU-3477)
Before the fix:
After the fix:
> fix: 🐛 Refactor host-set dropdown separator

- ui/admin/app/components/form/host-catalog/azure/index.hbs
client_secret_value was empty due to missing a value field on the input element. 
https://boundary-ui-git-fix-val-hashicorp.vercel.app/scopes/s_xk1i4dk50v2/host-catalogs/host-catalog-id-3
> fix: 🐛 missed value field

- ui/desktop/app/templates/scopes/scope/projects/targets/target/hosts.hbs
Fix address missing field for static hosts in the host list.
Before:
After:
> fix: 🐛 Fix host list table missing address field

- addons/api/addon/serializers/host-set.js
This PR adds (temporary) support for host set `filters` when it is returned by the API as a string.  It is converted to an array in normalisation.  Eventually this can be rolled back once the API consistently returns an array.
> chore: support `filters` when it is a string by converting to an array

- ui/desktop/app/templates/scopes/scope/projects/targets/target/hosts.hbs
Delete unnecessary else clause in host list within targets.
> Delete unnecessary else clause in host list within targets

- ui/desktop/app/templates/scopes/scope/projects/targets/target/hosts.hbs
Host address field shows Dynamic value on list when it is not type static.
[Direct link to feature](https://boundary-ui-desktop-git-fix-host-address-field-2f79ac-hashicorp.vercel.app/scopes/global/projects/targets/1/hosts)
Before:
After:
> fix: 🐛 Host address field shows value for type plugin

- addons/rose/package.json
- yarn.lock
Update `@storybook/ember-cli-storybook` dependency from `0.4.0` to `0.5.0`.
Risk:
As per [the changelog](https://github.com/storybookjs/ember-cli-storybook/blob/master/CHANGELOG.md) there is no risk.
> chore: 🤖 Update ember-cli-storybook dep

- addons/api/package.json
- addons/auth/package.json
- addons/core/package.json
- addons/rose/package.json
- ui/admin/package.json
- ui/desktop/package.json
Update ember-cli-htmlbars from `5.7.1` to `6.0.1`.
As [per changelog](https://github.com/ember-cli/ember-cli-htmlbars/blob/master/CHANGELOG.md) no risk on the update.
> chore: 🤖 Update ember-cli-htmlbars

- addons/rose/package.json
- yarn.lock
Update babel-plugin-ember-modules-api-polyfill from `2.12.0` to `3.5.0`.
As [per changelog](https://github.com/ember-cli/babel-plugin-ember-modules-api-polyfill/blob/master/CHANGELOG.md), no risk on the update.
> chore: 🤖 Update babel-plugin-ember-modules-api-polyfill

- addons/api/package.json
- addons/auth/package.json
- addons/core/package.json
- addons/rose/package.json
- ui/admin/package.json
- ui/desktop/package.json
- yarn.lock
Update @ember/test-helpers from `2.4.2` to `2.6.0`.
[As per changelog ](https://github.com/emberjs/ember-test-helpers/blob/master/CHANGELOG.md)there is no risk.
> feat: 🎸 Update @ember/test-helpers

- addons/api/package.json
- addons/auth/package.json
- addons/core/package.json
- addons/rose/package.json
- package.json
- ui/admin/package.json
- ui/desktop/package.json
- yarn.lock
Update doctoc from `2.0.1` to `2.1.0`. No risk on the update.
> chore: 🤖 Update doctoc

- addons/rose/addon/components/rose/nav/breadcrumbs/index.hbs
- addons/rose/addon/components/rose/nav/link/index.hbs
- addons/rose/addon/components/rose/nav/link/index.stories.mdx
- addons/rose/addon/components/rose/nav/sidebar/index.hbs
- addons/rose/addon/components/rose/nav/tabs/index.hbs
- addons/rose/addon/styles/rose/components/nav/_breadcrumbs.scss
- addons/rose/app/components/rose/nav/link.js
- addons/rose/tests/integration/components/rose/nav/breadcrumbs-test.js
- addons/rose/tests/integration/components/rose/nav/link-test.js
This PR introduces a simple proxy component `<Rose::Nav::Link>` to replace usage of `(component "link-to" class=…)`, due to [the `ember.built-in-components.legacy-attribute-arguments` deprecation](https://deprecations.emberjs.com/v3.x/#toc_ember-built-in-components-legacy-attribute-arguments).
> refactor: 💡 resolve legacy-attribute-arguments deprecations

- ui/admin/app/components/bread-crumbs.js
- ui/admin/package.json
- yarn.lock
This PR pulls the source of ember-breadcrumbs local and eliminates the dependency.  This was necessary in order to refactor breadcrumbs to support newer versions of Ember going forward.
> Refactor breadcrumbs component

- package.json
- yarn.lock
Update version of `follow-redirects` in resolutions as per [dependabot alert](https://github.com/hashicorp/boundary-ui/security/dependabot/21).
> chore: 🤖 Update resolutions follow-redirects

- addons/api/package.json
- addons/auth/package.json
- addons/core/package.json
- addons/rose/package.json
- ui/admin/package.json
- ui/desktop/package.json
- yarn.lock
Update `ember-page-title` from `6.2.2` to `7.0.0` as [per changelong](https://github.com/ember-cli/ember-page-title/blob/master/CHANGELOG.md), there is no risk on the update.
> chore: 🤖 Update ember-page-title

- addons/core/translations/form/en-us.yaml
- ui/admin/app/components/form/host/aws/index.hbs
The test cases need to be updated to handle the different types of host-catalogs properly. Test will be updated and added in a later PR. @joshuaogle[](https://user-images.githubusercontent.com/29386339/155749672-b574bcf9-b533-4825-bf64-339600c44d71.png)[](https://user-images.githubusercontent.com/29386339/155749700-a952b76f-68ef-46d2-99e7-3bf3d83144e5.png) the wireframe didn't have a suggested name for the title so I went with "DNS Names". Let me know if you have another suggestion.
Old:
New:
> feat: 🎸 Display DNS names for AWS hosts in Admin UI

- addons/api/package.json
- addons/auth/package.json
- addons/core/package.json
- addons/rose/package.json
We are not using `ember-source-channel-url`. We were using it in `ember-try` (deprecated) config file, [here](https://github.com/hashicorp/boundary-ui/pull/1002/files#diff-4d75bd18581f5d1a73ba9e1019b68dc4abbd7d5f9ff521e1cc82b142b0029889L3).
The only reason still appearing in `yarn-lock` file because it is a sub-dependency of `ember-cli`.
> chore: 🤖 Deprecate ember-source-channel-url

- addons/core/translations/form/en-us.yaml
- ui/desktop/app/templates/scopes/scope/projects/targets/target/hosts.hbs
Combine the columns `name` and `id` into a new column call `Host`.
[Link to feature](https://boundary-ui-desktop-git-feature-combine-column-7b5dac-hashicorp.vercel.app/scopes/global/projects/targets/1/hosts).
Screenshot before:
Screenshot after:
> feat: 🎸 Combine columns on target host list for desktop

- addons/api/addon/generated/models/host-set.js
- addons/api/addon/serializers/host-set.js
- addons/api/mirage/factories/host-set.js
- addons/api/tests/unit/serializers/host-set-test.js
this pr adds the missing attribute `sync_interval_seconds` to plugin host-sets. 
displaying this field in the host-set forms will be handled in a separate PR.
> feat: 🎸 add sync_interval_seconds to plugin host-sets

- .github/workflows/monorepo-validate.yaml
Update node version from `12.x` LTS to `16.x` LTS for the github action workflow validate-monorepo.
As per [Node release schedule](https://nodejs.org/en/about/releases/) the active and supported LTS is `16.x`. `12.x` It is just in mantainance mode and the EOL `2022-04-30`
> chore: 🤖 Update node version used in GH actions

- addons/api/addon/models/target.js
- addons/api/tests/unit/models/target-test.js
This pr adds TCP and SSH type check methods to the target model. This is required to support both the target types.
> feat: 🎸 add type check helper methods to target model

- .github/workflows/monorepo-validate.yaml
Refactor the cache for dependencies within the CI.
**How the cache used to work:**
- Cache was working JUST at PR/branch level. So a workflow running on branch A, could not access any other cache that the one generated by branch A.
- Per each new PR we have no cache available (reasons mentioned above), so every PR at first run will need to install all dependencies, after that it generated a cache for that PR.
- The cache could not be shared within the same workflow if the runner Operating System changed.
- Every job of the workflow (3 in this case) were installing dependencies 3 times (but simultaneously).
**How the cache works now:**
- Cache works at project level. So any workflow running within the project, doesn't matter what head the PR is pointing to, has access to the cache.
- Cache …
> chore: 🤖 Refactor cache for dependencies within CI

- package.json
- yarn.lock
Update `git-cz` from `4.3.1` to `4.8.0`. As [per changelong](https://github.com/streamich/git-cz/blob/master/CHANGELOG.md) there is no risk on the update.
> chore: 🤖 Update git-cz

- ui/desktop/electron-app/package.json
- ui/desktop/electron-app/yarn.lock
Update plist version resolutions on desktop as per [dependabot alert](https://github.com/hashicorp/boundary-ui/security/dependabot/31).
> chore: 🤖 Update plist version resolutions on desktop

- ui/admin/config/environment.js
- ui/admin/tests/acceptance/targets/create-test.js
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-3845)
:technologist: [Admin preview](https://boundary-ui-git-ssh-target-tests-hashicorp.vercel.app/scopes/s_xk1i4dk50v2/targets)
This PR adds SSH target specific tests that verify our `ssh-target` feature flag is showing or hiding the correct UI elements.
Currently we are using [this ember addon](https://github.com/kategengler/ember-feature-flags) to manage feature flags in our tests using `enableFeature`. There is a [disableFeature](https://github.com/kategengler/ember-feature-flags#enablefeature--disablefeature) function but it is not included in the most recent release we are using. However, I was able to mimic the same functionality in these new tests. There is an …
> Ssh target tests

- ui/admin/tests/acceptance/targets/update-test.js
✅ Closes: ICU-3892
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-3892)
Add to existing test that the worker filter input field can be edited on an existing target.
:technologist: [Admin preview](https://boundary-ui-git-icu-3892-edit-worker-filter-in-b400ec-hashicorp.vercel.app/scopes/s_xk1i4dk50v2/targets/1)
> test: 💍 Verify target worker filter can be edited

- ui/admin/tests/acceptance/targets/create-test.js
✅ Closes: ICU-3893
:tickets: [Jira ticket]()
Add to existing tests that the worker filter fields are saved correctly when creating a new target
:rose: [Rose preview](PATH_TO_FEATURE)
> test: 💍 Verify target worker filter is created correctly

- addons/api/mirage/scenarios/default.js
- ui/admin/app/routes/scopes/scope/sessions.js
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-3952)
Disabling sessions polling due to UI not showing a large amount of sessions data
:technologist: [Admin preview](https://boundary-arfi0qvqw-hashicorp.vercel.app/scopes/s_xk1i4dk50v2/sessions?filter-status=%5B%5D)
:rose: [Rose preview](PATH_TO_FEATURE)
> disable polling in admin UI

- .github/pull_request_template.md
In most cases we have a Jira ticket number in our commit description via the "✅ Closes: ICU-****". I have included the base url for Jira so we just have to copy over the ticket number to finish off the `:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/)` portion of our PR template. Thoughts on this?
> chore: 🤖 Updated pr-template to include Jira base url

- ui/desktop/app/routes/scopes/scope/projects/targets.js
Reverts hashicorp/boundary-ui#1059
> Revert "fix: 🐛 Disable polling for targets on Desktop"

- addons/core/translations/resources/en-us.yaml
- addons/rose/addon/styles/rose/components/form/_fieldset.scss
- addons/rose/addon/styles/rose/components/form/_radio-card.scss
- ui/admin/app/components/form/target/details/index.hbs
✅ Closes: ICU-4014
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-4014)
Update Radio card help text for TCP and SSH targets. Please let me know if there is a better solution to the text spacing issue seen in the screenshots below.
:technologist: [Admin preview - View/Edit Target](https://boundary-7debbjpfy-hashicorp.vercel.app/scopes/s_xk1i4dk50v2/targets/1)
🎯 [Admin preview - New Target](https://boundary-7debbjpfy-hashicorp.vercel.app/scopes/s_xk1i4dk50v2/targets/new)
🌹 [Rose preview - Wide Radio Card](https://boundary-ui-storybook-mtwi3jy5m-hashicorp.vercel.app/?path=/story/rose-form-radio-radio-card--wide)
Below is the new changes. Radio card has been changed to a `tile` layout to make room for TCP help text.
New Target screen:
View/Edit Target screen:
Below has the …
> feat: 🎸 Update Target types help text

- ui/desktop/electron-app/package.json
- ui/desktop/electron-app/yarn.lock
Update Electron from `12.1.2` to `13.6.7`.
Reason behind this update:
- Security vulnerability, more [info here](https://github.com/hashicorp/boundary-ui/security/dependabot/29).
- Performance improvements.
**Testing:**
- The build process has been tested locally within the 3 environments: `MacOS (arm)`, `Windows (amd64)` and `Linux (amd64)`.
- The CI also when through the build process successfully, [build here](https://app.circleci.com/pipelines/github/hashicorp/boundary-ui-releases/989/workflows/1c7c0e9a-ad90-4803-bd05-c1712cfe2527).
- Staged builds are available within tag `1.111.11-beta`.
> chore: 🤖 Update Electron from 12.x to 13.x

- ui/admin/app/components/form/target/index.hbs
✅ Closes: ICU-4047
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-4047)
Fix issue where trying to leave the new target form via the discard
changes dialog would cause the user to have to refresh screen.
:technologist: [Admin preview](https://boundary-ui-git-icu-4047-discard-unsaved-chang-09c10d-hashicorp.vercel.app/scopes/s_xk1i4dk50v2/targets/new)
Discard changes issue:
Discard changes fixed:
> fix: 🐛 Fix new target navigation issue

- ui/desktop/electron-app/src/index.js
**BLOCK BY:** https://github.com/hashicorp/boundary-ui/pull/1066
This PR fix the Mac OS Bug for managing window lifecycle.
Mac OS behaviour when closing the main window differs from Linux or Windows.
After closing the main window, macOS apps generally continue running even without any windows open, and activating the app (click in the Boundary icon on the dock) when no windows are available should open a new one.
Tested this in `mac os (arm64)` and on `Linux (amd64)`. In Linux, I just tested that nothing is broken since the behaviour should not change in Linux or Windows.
Within `boundary-ui/ui/desktop` run `yarn start:desktop` and check we got the desired behaviour while no exceptions are throw in the console.
> fix: 🐛 Mac os window lifecycle

- addons/core/addon/components/relative-datetime-live/index.js
- ui/desktop/app/components/toolbar-refresher/index.hbs
- ui/desktop/app/components/toolbar-refresher/index.js
- ui/desktop/app/templates/scopes/scope/projects/sessions/index.hbs
:desktop_computer: [Desktop preview](https://boundary-ui-desktop-git-feature-last-refreshed-time-hashicorp.vercel.app/scopes/global/projects/sessions)
This PR introduces a component to Desktop that composes the loading button and the live relative datetime components.
> feature: add toolbar refresher component

- package.json
- ui/desktop/electron-app/package.json
- ui/desktop/electron-app/yarn.lock
- yarn.lock
It would be great if a few people could pull this down and verify this has no side effects for running the app locally.
This change is to fix my ability to run `yarn install` for this project.
> chore: 🤖 Add lzma-native and appdmg to resolutions

- .github/workflows/build-admin-ui.yaml
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-4219)
Refactor UI generated artifacts creation. Now we generate 2 artifacts: `admin-ui-oss` and `admin-ui-enterprise`.
As per deprecation procedure, we will keep generating `admin-ui` per 2 more weeks after the merge of this PR.
We wanted to keep it simple, both UI's oss and enterprise use the exact same dependencies, the only difference is the build procedure.
Because that we decided to refactor the current build job adding two more steps. 
- Clean the /dist folder after OSS built.
- Build enterprise
After working on the first approach and discard it, this approach embrace splitting each build in a separate job but running parallel, so no ime is wasted.
This screenshot represent the last test build on the refactor branch.
> Refactor UI generated artifacts creation.

- ui/admin/app/components/form/target/details/index.hbs
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-4362)
This pr hides ssh targets from the target creation form in OSS edition.
**To test:** 
OSS: 
1. download the recent OSS binary 
2. [build OSS](https://github.com/hashicorp/boundary-ui/blob/main/package.json#L18) assets on your terminal within boundary-ui
3. run boundary dev instance by following [these steps ](https://github.com/hashicorp/boundary#ui-development) (make sure the assets are pointed to your relative path from step 2)
4. go to http://127.0.0.1:9200 and inspect the ember app, which should show you the `production` mode of the assets we just built in step 2.  
5. you should not see the `ssh target` radioCard in the creation form
Enterprise: 
1. download the recent enterprise binary from the boundary …
> fix: 🐛 add featureflag to target creation template

- ui/desktop/electron-app/src/models/runtime-settings.js
✅ Closes: ICU-4238
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-4238)
If the result from netRequestPromise is successful but a not a 200
response, validateOrigin will throw an error
:desktop_computer: [Desktop preview](https://boundary-ui-desktop-git-icu-4238-enhancement-u-b49f83-hashicorp.vercel.app/origin) Note: I do not think this is able to be replicated with mirage.
> fix: 🐛 Update validateOrigin to throw error on bad request

- ui/desktop/app/styles/app.scss
- ui/desktop/app/templates/scopes/scope/authenticate.hbs
- ui/desktop/electron-app/src/index.js
Simple PR to display auth method names in the Desktop login form, when available.  This is how admin UI has worked for some time, but Desktop only showed auth method type.
> chore: 🤖 display auth method names in auth form, if available

- addons/api/addon/serializers/application.js
Use `hasOwnProperty` instead of `hasOwn`. The latter only recently received support in some browsers such as Safari, take a look [here](https://caniuse.com/mdn-javascript_builtins_object_hasown). Probably too early to use as of right now.
Also stopped modifying the payload directly.
> fix: 🐛 Use more common hasOwnProperty and don't modify payload

- ui/admin/app/routes/onboarding/quick-setup/create-resources.js
- ui/admin/tests/acceptance/onboarding/create-resource-test.js
This allows the user to be directed to the Host Catalog page if they do not provide an IP or port for the target. If we do not need this we can just close this PR.
> refactor: 💡 Remove default value for IP address and port

- addons/api/addon/models/session.js
- addons/api/mirage/scenarios/ipc.js
- addons/core/translations/resources/en-us.yaml
- ui/desktop/app/templates/scopes/scope/projects/targets.hbs
This pr updates `credential library` to `credential sources`
tested this against the latest 0.9 staged binary and set up credentials using the vault brokering guide
https://hashicorp.atlassian.net/browse/ICU-4874 
:desktop_computer: [Desktop preview](https://boundary-ui-desktop-fnijuxf9w-hashicorp.vercel.app/scopes/global/projects/targets)
> chore: 🤖 update to credential source

- ui/desktop/electron-app/package.json
- ui/desktop/electron-app/yarn.lock
Upgrade:
- `semver` to `7.3.7`.
- `shell-quote` to `1.7.3`.
Tested run Circle CI:
Successful run:
> Chore upgrade desktop dependencies 2

- ui/desktop/app/styles/app.scss
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-4894)
This pr fixes the dropdown being cut off by removing `overflow: auto`. This change doesn't seem to affect anywhere on the desktop CLI UI on Mac OS. 
Help needed to test on Win and Linux: 
1. run a boundary instance to connect to target and sessions, and check if the project/sessions dropdown is displayed without being cut off 
2. create around 10-15 sessions, and ensure that there are no overflow issues when the dropdown is open/closed on the target page when you scroll the page
**Tested on mac OS:** 
**Dropdown with just single session:**  
**Dropdown open when there are multiple sessions:**
> fix: 🐛 overflow dropdown ui issue

- .husky/prepare-commit-msg
Update the git hook to not run commitizen on merge commits or squashes.
You can test this by checking out an older commit and merging another branch or main back in. Or doing a rebase -i
> chore: 🤖 Update git hook to not use commitizen on merges

- addons/api/addon/generated/models/target.js
- addons/api/tests/unit/serializers/target-test.js
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-5127)
Refactor default value of `session_connection_limit`.
New behaviour: if the user does not specify a limit, at creation time the backend will assign `-1` (unlimited) as default. So the UI does not deal with default values anymore for this field.
With the latest `0.9.1` binary, I used `BOUNDARY_DEV_UI_PASSTHROUGH_DIR` to passthrough the UI in my local env to the binary running, [here more info how to use it](https://github.com/hashicorp/boundary#ui-development).
New target form before being send, no value specified for `session_connection_limit`:
New target form after being created with the response from BE, notice now it shows `-1` in `session_connection_limit`:
> refactor: 💡 Refactor default values for target creation

- ui/admin/config/environment.js
✅ Closes: ICU-5203
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-5203)
The static-credentials feature flag was added and set to true only for
dev and test modes.
> feat: 🎸 Added the static-credentials feature flag

- package.json
- yarn.lock
Add Hawk to resolution as [per dependabot](https://github.com/hashicorp/boundary-ui/security/dependabot/36) complain.
Hawk is used on the desktop client.
Test I performed succesfully:
- Build desktop client locally (macOS & ubuntu).
- Run all the tests.
- Test run on the releasing pipeline.
Screenshots to prove the run on release pipeline:
> fix: 🐛 Add Hawk to resolutions

- addons/core/translations/resources/en-us.yaml
- ui/admin/app/components/form/credential-store/index.hbs
✅ Closes: ICU-5171
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-5171)
🧑‍💻: [Admin preview](https://boundary-ui-git-icu-5171-refactor-existing-vau-37b194-hashicorp.vercel.app/scopes/s_1sheljmjgm/credential-stores/cs_ucau082vov)
Refactored existing vault form field to use radio card instead. This
change is seen on details tab of a static credential store.
> refactor: 💡 existing vault form field to radio group

- addons/api/addon/abilities/credential-store.js
- addons/core/translations/resources/en-us.yaml
✅ Closes: ICU-5173
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-5173)
:technologist: [Admin preview](https://boundary-ui-git-icu-5173-read-a-credential-store-hashicorp.vercel.app/scopes/s_1sheljmjgm/credential-stores)
This change includes making static type credential stores clickable when
listing all credential stores, along with viewing the individual credential
store.
> feat: 🎸 Read a credential store

- ui/admin/app/components/credential-stores/credential-store/header/index.hbs
- ui/admin/app/templates/scopes/scope/credential-stores/new.hbs
- ui/admin/tests/acceptance/credential-store/create-test.js
- ui/admin/tests/acceptance/credential-store/list-test.js
- ui/admin/tests/acceptance/credential-store/read-test.js
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-5335)
I added tests to verify that the docs link is present and referencing the correct URL. I would like to not have to use the full URL in the future, maybe create a helper test method but I wanted to get feedback about including these tests from the team first. Let me know your thoughts.
Add DocLink component to new Credential Screen and the read Credential Store screen.
> Icu 5335 add doc link for credential store screens

- ui/admin/app/templates/scopes/scope/credential-stores/credential-store/credentials/credential/index.hbs
- ui/admin/app/templates/scopes/scope/credential-stores/credential-store/credentials/new.hbs
- ui/admin/config/environment.js
✅ Closes: ICU-5317
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-5317)
The redirect for Credential does not work right now. This is a brand new redirect on the boundaryproject.io website as well so the redirect will not work until our next release when those changes are pushed to production.
Here is the [PR](https://github.com/hashicorp/boundary/pull/2272) that added the redirect to the boundaryproject.io website.
:technologist: [Admin preview](https://boundary-ui-git-icu-5317-create-a-new-doc-link-cccbec-hashicorp.vercel.app/scopes/s_1sheljmjgm/credential-stores/cs_20nu3mgl4y/credentials/cred_hzrxf5z5za)
> feat: 🎸 Add doc link to Credential screens

- ui/admin/config/environment.js
Fixes the redirect for the "Learn about Boundary Desktop app" link.
> fix: 🐛 spelling error in getting started on desktop redirect

- ui/admin/app/components/form/credential/index.hbs
✅ Closes: ICU-5180
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-5180)
:technologist: [Admin preview](https://boundary-ui-git-icu-5180-edit-a-credential-hashicorp.vercel.app/scopes/s_1sheljmjgm/credential-stores/cs_20nu3mgl4y/credentials/cred_hzrxf5z5za)
Password input field is now only viewable after user clicks on "Edit
Form"
> refactor: 💡 Edit a credential

- ui/desktop/electron-app/src/models/runtime-settings.js
Fix a bug introduced with the `origin` to `clusterURL` refactor. We should NOT access the private var directly
> Fix runtime-settings to not access directly the private variable

- .github/workflows/build-admin-ui.yaml
This new job mirrors the enterprise build job, but lets us keep the existing logic laid out in https://github.com/hashicorp/boundary/blob/main/.github/workflows/build.yml#L136 to download the right UI artifacts based on the boundary variant/edition. This is needed for the release on August 1st. 🙏  Thanks
> [CI-only] Add build job for HCPb variant

- addons/core/translations/resources/en-us.yaml
- ui/admin/app/components/form/credential/index.hbs
✅ Closes: ICU-5459
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-5459)
:technologist: [Admin preview](https://boundary-ui-git-icu-5459-remove-helper-text-fo-f7e341-hashicorp.vercel.app/scopes/s_1sheljmjgm/credential-stores/cs_20nu3mgl4y/credentials/cred_hzrxf5z5za)
Remove helper text for username and password fields in Credential form
as requested in a previous conversation.
> refactor: 💡 Remove helper text for Username & Password

- ui/admin/app/components/form/target/add-credential-sources/index.hbs
- ui/admin/app/components/form/target/add-credential-sources/index.js
Remove submit action from form component and pass selected credential IDs directly to the submit method
Update toggle action to accept the credential source ID instead of the whole model.
:technologist: [Admin preview](https://boundary-ui-git-refactor-add-credential-source-submit-hashicorp.vercel.app/scopes/s_1sheljmjgm/targets/t_4uga1n9zdm/add-credential-sources)
> refactor: 💡 update onSubmit for add-credential-sources

- addons/api/addon/serializers/credential.js
- addons/api/tests/unit/serializers/credential-test.js
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-5646)
Updated serialize/normalize for static credentials.
Username & Password: After creation, we don't keep track of the `password` field. We only display the `username` when reading.
SSH Private Key: After creation, we don't keep track of the `private key` or `passphrase` field. We only display the `username` when reading.
Mirage updates will be in the next PR.
> Icu 5646 serializer

- addons/core/translations/resources/en-us.yaml
Add missing translation for the new credential type within the target route
Before:
After:
> fix: 🐛 add translation for the new credential type within target route

- addons/core/addon/helpers/relative-datetime-live.js
- ui/admin/app/components/form/worker/index.hbs
Refactor detailed worker to not hide read-only fields when editing, but
leave them disabled
✅ Closes: ICU-5902
ICU-5902
Previous logic was  when user clicks on `edit` for `detailed-worker-view` it hides the `read-only` fields for the page and only displays the editable field. Current logic is when a user clicks on `edit` for `detailed-worker-view` it will no longer hide the `read-only` fields but they will keep their `disabled` state and stay on page.
> refactor: 💡 Disable read-only fields when editing worker

- ui/admin/config/environment.js
Add feature flags for development and test environments.
Feature flags gives us the avility to turn `ON` or `OFF` different feature flags depending on the Boundary UI edition (OSS, enterprise and HCP) we want to build/deploy.
Within development and test environments not all the feature flags are turned `ON`.
This makes more difficult some of the development tasks. 
Also makes Admin UI Vercel deployment to not show all the features. Remember Vercel deployment reflects a development environment.
Override all the new feature flags: `static-credentials`, `byow` and `ssh-target` within `development` and `test` environments.
This way ALL features will be available at development and test time. Also Admin UI Vercel deployment will have all these features available.
On the screenshots you can see …
> chore: 🤖 Add feature flags for dev and test environments

- addons/core/translations/form/en-us.yaml
- ui/admin/app/components/form/worker/index.hbs
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-6046)
- Update `detailed-worker-view` to show Boundary resource `release_version` in a read-only input field
> ICU 6044 Update detailed worker view

- addons/api/addon/serializers/credential-library.js
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-6159)
Fixes a bug where credential libraries incorrectly serialize a `scope_id` on save.
> fix: 🐛 stop sending scope_id on cred libraries - ICU-6159

- ui/admin/app/routes/scopes/scope/workers/index.js
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-6185)
The CLI doesn't return workers in any order. This is to help provide the user with a consistent order when refreshing workers.
> feat: 🎸 Update workers list to be sorted

- ui/admin/app/templates/scopes/scope/workers/index.hbs
Fix an issue with the tag badge not correctly wrapping to a new line. Removed a div by accident which caused the tag to become inline when there's no description for the worker.
> fix: 🐛 Add back div to fix tag icon badge layout

- ui/admin/app/routes/scopes/scope/workers/index.js
Quick change to make sure workers are also sorted when filtering. Currently only unfiltered workers are sorted. 
This change will allow filtered workers to also have a stable order when refreshing workers, the filter should preserve order.
> fix: 🐛 Sort workers when filtering is enabled as well

- addons/rose/addon/modifiers/code-mirror.js
- ui/desktop/app/templates/scopes/scope/projects/targets.hbs
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-6249)
Fixes the raw API output not displaying properly. The issue seems to be a quirk of `code-mirror`. Code mirror listens in on resizing the editor and will handle it accordingly but if it's initialized when the element is hidden initially, it won't know to refresh itself to display properly. Code mirror provides an [autorefresh addon](https://codemirror.net/5/doc/manual.html#addon_autorefresh) to help with this.
This could also have been handled by manually calling refresh whenever we reveal it, but this would require exposing the underlying editor and correctly calling it by knowing when it's visible from our `reveal` component.
> fix: 🐛 Fix raw api output not displaying codemirror properly

- ui/admin/app/templates/scopes/scope/host-catalogs/host-catalog/host-sets/host-set/hosts/index.hbs
This is a transitory PR while working on `refactor-deprecate-renderTemplate`.
PR Fixes template host-catalog/host-sets/host-set/hosts template.
We are refactoring templates and the current implementation (named outlets) assumes some parent templates nesting parts of the child (like header, actions or navigation). 
With the new implementation, we need to refactor from top to bottom, so from parent to child. In the meantime, some child views (i.e. hosts/host/new) look broken for missing the mentioned nested parts.
Some Acceptance tests are not passing either due to side effects caused by the reasons mentioned above.
BE AWARE this will NOT be merge to `main` but to `refactor-deprecate-rendertemplate`.
> Refactor host-catalog/host-sets/host-set/hosts template

- ui/desktop/electron-app/config/cli.js
This will allow using the arm64 cli for m1 macs. This can sometimes be a painpoint as using the `amd64` cli on m1 macs can sometimes return a rosetta error and if you're using the desktop client it will silently fail and you won't know what the issue is. 
See this [thread](https://hashicorp.slack.com/archives/C012GTH1C4E/p1664381734699799) for more info.
There was some hesitancy as this might enable building for arm64 but it looks like we're _already_ doing that with `electron-forge`. I was originally going to flag the arch for the boundary CLI based off of maybe a production env variable or flag but the default setting in `electron-forge` won't let us set the `arch` anyways so didn't see much point, see this [documentation](https://www.electronforge.io/configuration#packager-config). I …
> chore: 🤖 Allow retrieval of arm64 cli

- ui/desktop/README.md
Add how to debug desktop client documentation.
Changes on the table of contents are result of running `doc:toc`
> docs: ✏️ Add debug desktop client documentation

- addons/api/package.json
- addons/auth/package.json
- addons/core/package.json
- addons/rose/package.json
- ui/admin/package.json
- ui/desktop/package.json
- yarn.lock
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-6330)
Update `ember-cli-dependency-checker` to the latest version, so it does not use `bowerDependencies` anymore and we do not get any more deprecation messages.
Addon/api deprecation message before the changes:
Addon/api with no more deprecation message after the changes:
Addon/auth deprecation message before the changes:
Addon/auth with no more deprecation message after the changes:
Addon/core deprecation message before the changes:
Addon/core with no more deprecation message after the changes:
Addon/rose deprecation message before the changes:
Addon/rose with no more deprecation message after the changes:
Admin UI deprecation message before the changes:
Admin UI with no more deprecation message after the changes: …
> Chore update ember cli dependency checker addon

- ui/admin/config/content-security-policy.js
- ui/desktop/electron-app/src/config/content-security-policy.js
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-6348)
Adds [frame-ancestors directive](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors) to the CSP headers.
> [ICU-6448] Update CSP to add frame-ancestors: self

- ui/desktop/electron-app/config/cli.js
Fix intel mac downloading the cli. It also names its arch `x64` instead of `amd64`
> fix: 🐛 Fix mac intel cli download

- ui/admin/app/styles/app.scss
- ui/desktop/app/styles/app.scss
✅ Closes: ICU-4330
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-4330)
Refresh spinning animation is removed when user specifies reduced motion in local settings.
:technologist: [Admin preview](https://boundary-ui-git-icu-4330-refactor-prefers-redu-3a79ae-hashicorp.vercel.app/scopes/global/workers)
:desktop_computer: [Desktop preview](https://boundary-ui-desktop-git-icu-4330-refactor-pref-42d767-hashicorp.vercel.app/scopes/global/projects/targets)
Demo in Admin UI: 
https://user-images.githubusercontent.com/107949262/196240761-fbe29ce3-0fdf-4efc-a016-9210993f6849.mov
Demo in Desktop UI:
https://user-images.githubusercontent.com/107949262/196240891-0733d108-4175-4fad-a86f-a2d699084c98.mov
> feat: 🎸 remove animation when user specifies reduced motion

- addons/core/ember-cli-build.js
Forgotten ember auth session setup method
Deprecation message in browser console before changes:
NO Deprecation message in browser console after changes:
> fix: 🐛 Forgotten session setup method in core

- addons/core/addon/services/scope.js
- addons/core/tests/unit/services/scope-test.js
- ui/admin/app/components/header-nav/index.hbs
- ui/admin/app/components/header-nav/index.js
- ui/admin/app/routes/application.js
- ui/admin/app/routes/scopes/scope.js
- ui/admin/app/templates/application.hbs
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-6017)
Deprecate the usage of `renderTemplate` in the application `header-nav`.
Created a `header-nav` component to get rid of named outlets and `renderTemplate`. Add Organizations list and Projects list to `scope` service, so the new `header-nav` component can consume the data.
[Link to Vercel deployment of this PR](https://boundary-ui-git-refactor-deprecate-rendertempl-db50f8-hashicorp.vercel.app/) free of `renderTemplate` deprecation messages in browser console.
> refactor: 💡 Deprecate renderTemplate in header-nav

- addons/rose/index.js
- addons/rose/package.json
This PR works around [a limitation](https://github.com/ember-cli/ember-cli/issues/4475) in how ember treats nested addons and their `contentFor` hooks by manually finding and running that hook as part of rose's `contentFor` hook. Note, it is also important for `@hashicorp/ember-flight-icons` to be listed in rose's `dependencies` otherwise `this. findOwnAddonByName()` can't see it.
For context, the way `@hashicorp/ember-flight-icons` inserts the sprite into the dom is by using the `contentFor` hook like [this](https://github.com/hashicorp/design-system/blob/954566adcb84900c949941530fc0f8bf757c1b84/packages/ember-flight-icons/index.js#L14). The problem here is that because `@hashicorp/ember-flight-icons` is a dependency of `@hashicorp/design-system-components` and not of rose directly, this …
> chore: 🤖 explicitly call @hashicorp/ember-flight-icons` contentFor hook

- addons/rose/ember-cli-build.js
- addons/rose/index.js
- addons/rose/package.json
- addons/rose/tests/dummy/app/styles/app.scss
- ui/admin/package.json
- ui/desktop/package.json
- yarn.lock
Initial setup of HDS:
- Adds the HDS dependency to Rose
- Auto-includes CSS import path for tokens, so that consuming applications do not need further build configuration
- Removes existing flight-icons dependency, migrating over to flight-icons provided by HDS
- Removes incompatible `ember-cli-template-lint` dependency from admin and desktop
Note:  consuming UIs like admin and desktop must still explicitly import HDS into their styles:
```
@import '@hashicorp/design-system-components';
```
:rose: [Rose preview](https://boundary-ui-storybook-git-chore-hds-install-hashicorp.vercel.app/?path=/story/rose-anonymous--page)
:technologist: [Admin preview](https://boundary-ui-git-chore-hds-install-hashicorp.vercel.app)
:desktop_computer: [Desktop …
> chore: 🤖 initial setup of HDS

- ui/admin/package.json
- ui/desktop/package.json
- yarn.lock
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-6582)
Delete `ember-cli-template-lint`. More info about on the jira ticket (link above).
Before deleting it, we get lots of deprecation messages after starting the UI:
No more deprecation messages, after changes are applied starting the UI:
> refactor: 💡 Delete ember-cli-template-lint

- addons/api/mirage/scenarios/ipc.js
When using the desktop client locally with mirage enabled, the appearance is wonky due to us mocking functions that are needed to determine the appearance.
Before:
After:
> fix: 🐛 Fix electron appearance for desktop with mirage locally

- addons/rose/app/styles/rose/components/header/_dropdown.scss
Fixes the small header icon CSS
> fix: 🐛 Fix styling for header icon CSS

- addons/rose/addon/styles/hds/themes/dark-mode/_color-tokens-tier-2.scss
- addons/rose/addon/styles/hds/themes/dark-mode/index.scss
- addons/rose/package.json
This fixes a minor issue in Rose where the "addon" folder was not included in the `yarn format:sass` command.
> fix: 🐛 inlcude "addon" folder in rose style formatting command

- ui/admin/app/templates/scopes/scope/auth-methods/auth-method/accounts/index.hbs
- ui/admin/app/templates/scopes/scope/auth-methods/auth-method/managed-groups/managed-group/members.hbs
As part of the auth method model fragment refactor, I noticed that accounts and members are currently not correctly displaying their info. It looks like we refactored the account `attributes` and hoisted them up with `isNestedAttribute` but never updated the usage of accounts in auth methods.
:technologist: [Admin preview](https://boundary-ui-git-bugfix-fix-account-displays-in-cf579e-hashicorp.vercel.app/scopes/s_id6ozx3wue/auth-methods/am_wtbbeizy0q/accounts)
Befeore:
After:
> fix: 🐛 Fix accounts not displaying correctly in auth methods

- addons/api/addon/generated/models/credential.js
- addons/api/addon/models/credential.js
- addons/api/addon/serializers/credential.js
- addons/api/mirage/serializers/credential.js
- addons/api/tests/unit/serializers/credential-test.js
- addons/core/translations/resources/en-us.yaml
✅ Closes: ICU-6653, ICU-6684, ICU-6685, ICU-6802, ICU-6803
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-6653) [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-6684) [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-6685) [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-6802) [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-6803) 
Added json type to credential model, created `json_object` attribute for `json` type, updated credential serializer to handle `json_object` attribute data being sent to backend and updated normalizer to handlle secret untracked 'json_object'.
> chore: 🤖 JSON credential data modeling

- ui/admin/app/components/form/auth-method/oidc/index.js
This fixes the claims map `to` field not having a default value when adding a claim map even though it looks like it's selected
> fix: 🐛 Fix claims map dropdown not having a default value

- addons/api/package.json
- yarn.lock
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-7034)
Be aware this PR is merging to long living branch `refactor-upgrade-ember-4`.
Upgrade ember-can to latest version (`4.2.0`) within `addons/api`.
> chore: 🤖 Upgrade Ember-can within addons/api

- addons/api/addon/models/base.js
- addons/api/package.json
- addons/api/tests/unit/models/base-test.js
- ui/admin/app/routes/scopes/scope/auth-methods/new.js
- ui/admin/app/routes/scopes/scope/credential-stores/new.js
- ui/admin/app/routes/scopes/scope/groups/new.js
- ui/admin/app/routes/scopes/scope/host-catalogs/new.js
- ui/admin/app/routes/scopes/scope/roles/new.js
- ui/admin/app/routes/scopes/scope/targets/new.js
- ui/admin/app/routes/scopes/scope/users/new.js
- ui/admin/app/routes/scopes/scope/workers/new.js
- yarn.lock
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-6896)
This upgrades ember data to the latest `3.x` version. There was an error occurring after upgrading to `3.28.0` and any subsequent version (including the `4.x` versions).
It appears that ember-data had changed some of their internal state management and introduced a bug. Setting the `stateModel` (which is an object) as part of the `createRecord` call causes ember to error out (possibly because of their own ember run loop? seems like it assumes the model is ready before it's actually set, couldn't figure this out).
However setting the `stateModel` after creating the record works fine. As a workaround, that is what I do in this PR.
I also had to cherry-pick a fix from our ember 4 api upgrade branch.
> Icu 6896 upgrade ember data

- ui/admin/app/components/form/credential-store/static/index.hbs
- ui/admin/app/components/form/credential-store/vault/index.hbs
- ui/admin/app/components/form/credential/json/index.hbs
- ui/admin/app/components/form/credential/ssh_private_key/index.hbs
- ui/admin/app/components/form/credential/username_password/index.hbs
- ui/admin/app/components/form/target/details/index.hbs
- ui/admin/app/styles/app.scss
- ui/admin/tests/integration/components/info-field-test.js
Overall context of how the `<InfoField/>` was changed to the correct order.  Corrected css grid to have the order of
`label,input-field,helper-text`. Also refactored all component instances affected by the change.
> fix: 🐛 refactor info-field component

- package.json
- yarn.lock
Resolve 3 dependabot security alerts: [first](https://github.com/hashicorp/boundary-ui/security/dependabot/56), [second](https://github.com/hashicorp/boundary-ui/security/dependabot/61), [third](https://github.com/hashicorp/boundary-ui/security/dependabot/60)
`yarn why` says it's used by `css-loader`, `webpack`, a few loaders from `storybook`, `babel`, and a few more.
Tested storybook, UI, and desktop against boundary dev and they all looked good.
> chore: 🤖 Bump loader-utils to 2.0.4

- addons/api/addon/models/target.js
- addons/api/mirage/factories/target.js
- addons/api/mirage/generated/factories/target.js
- addons/api/tests/unit/models/target-test.js
- addons/api/tests/unit/serializers/auth-method-test.js
- addons/api/tests/unit/serializers/target-test.js
- ui/admin/app/components/form/target/details/index.js
- ui/admin/app/routes/onboarding/quick-setup/create-resources.js
- ui/admin/app/routes/scopes/scope/targets/new.js
- ui/admin/tests/acceptance/targets/create-test.js
- ui/admin/tests/acceptance/targets/injected-application-credential-sources-test.js
- ui/admin/tests/acceptance/targets/read-test.js
- ui/desktop/tests/acceptance/projects/targets-test.js
This pr introduces constants to represent available target types, as opposed to strings.  This is an improvement over duplicated strings for several reasons:
- Ties all instances of a resource type to a single source of truth:  its constant.
- Eliminates duplication of identical string values.
- Strings are error prone, since many tests may silently accept strings which are not valid types.
- This is a step toward the formalization of resource types, resulting in greater convenience and reliability of resource typing in the future (beginning with targets).
- Simplifies future refactors of resource types.  Where previously a search for an ambiguous string was required `'tcp'`, an unambiguous search may now be used `TYPE_TARGET_TCP`.
For example, in cases where target type previously was …
> refactor: 💡 use constants for target types

- addons/api/addon/abilities/managed-group.js
- addons/api/addon/abilities/role.js
- addons/api/app/abilities/managed-group.js
- addons/api/tests/unit/abilities/role-test.js
Introduces a convenience ability for roles, `readPrincipal`.  The ability accepts Role, Group, or ManagedGroup models and returns the `read` ability check for that model.
Since principals are polymorphic, the benefit of this ability is that it allows a read check without knowing the principal type ahead of time.
For example, these checks on the `role` resource:
`can('readPrincipal role', principal1)  // principal1 is a user`
`can('readPrincipal role', principal2)  // principal2 is a group`
`can('readPrincipal role', principal3)  // principal3 is a managed group`
Are equivalent to these checks when the resource type is known:
`can('read user', user)`
`can('read group', group)`
`can('read managedGroup', managedGroup)`
> chore: 🤖 add role readPrincipal ability

- addons/api/mirage/config.js
- addons/api/mirage/factories/role.js
- addons/api/mirage/models/role.js
- addons/api/mirage/scenarios/default.js
- addons/api/mirage/serializers/role.js
- addons/core/translations/resources/en-us.yaml
- ui/admin/tests/acceptance/roles/principals-test.js
This PR adds mocks for managed groups in `role/principals list` and `add to principals` view for both global and org-level scope. 
This is part of https://hashicorp.atlassian.net/browse/ICU-7102 
global scope: 
org Scope:
> Add mirage support principal managed groups

- package.json
- yarn.lock
Removed `engine.io` from our resolutions and upgraded the package manually from our yarn.lock. This is to fix an `engine.io` security vulnerability as noted [here](https://github.com/hashicorp/boundary-ui/security/dependabot/62).
`yarn why` indicates it's only used by `socket.io` which is used by `testem` in `ember-cli`.
> chore: 🤖 Update engine.io version to fix security vulnerability

- package.json
- yarn.lock
Pinned request to the latest version as it was forcing `qs` to a vulnerable version. This is to fix [this](https://github.com/hashicorp/boundary-ui/security/dependabot/67) dependabot alert.
`yarn why` indicates it's mainly used by storybook and its addons as well as ember-cli
> chore: 🤖 Pin request to latest version to fix qs vulnerability

- package.json
- ui/desktop/package.json
- yarn.lock
This is to resolve [this dependabot](https://github.com/hashicorp/boundary-ui/security/dependabot/51) alert. 
Updated `electronegativity` which upgrades their mocha version which was using the old minimatch version.
Pinned the minimatch version scoped under a package so we limit what the packages the yarn `resolutions` affects and so we know what package we need to update in the future so it can be unpinned.
> chore: 🤖 Update dependencies to fix minimatch vulnerability

- addons/api/mirage/scenarios/ipc.js
Now when connecting to a target a JSON credential will be included as one of the credential sources via mirage.
It will be the second credential source in the list. Keep in mind that nested secrets still are not rendered correctly here. That is fixed in this [PR](https://github.com/hashicorp/boundary-ui/pull/1551).
:desktop_computer: [Desktop preview](https://boundary-ui-desktop-git-add-json-credential-to-62bfa9-hashicorp.vercel.app/scopes/global/projects/targets)
> chore: 🤖 add json credential to desktop mirage scenario

- ui/admin/config/content-security-policy.js
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-7038)
**Tested with a prod build locally**
when CSP meta is disabled in prod env: 
(meta tag with CSP is removed)
when CSP meta is enabled in prod env: 
(meta tag with CSP can be seen)
> chore: 🤖 disable csp meta for prod

- ui/admin/app/components/ordered-series-diagram/group/index.hbs
- ui/admin/app/components/ordered-series-diagram/index.hbs
- ui/admin/app/components/ordered-series-diagram/item/index.hbs
- ui/admin/app/styles/app.scss
Refactor ordered series diagram to better conform to HDS and to support arbitrary HDS semantic colors in groups.
Usage:
```hbs
<OrderedSeriesDiagram as |D|>
<D.Item @icon='user'>Client</D.Item>
<D.Item @icon='settings'>Ingress Worker</D.Item>
<D.Group @title='Private Network' @color='highlight'>
<D.Item @icon='settings'>Egress Worker</D.Item>
<D.Item @icon='server'>Host</D.Item>
</D.Group>
</OrderedSeriesDiagram>
```
> refactor: 💡 refactor series diagram

- ui/admin/app/routes/application.js
- ui/admin/app/templates/application.hbs
While working on the network address feature in targets, I noticed our `application` template has unnecessary duplication of the dialog after adding the ability to change the confirmation button wording.
The goal of this PR is to simplify the template.
> refactor: 💡 Simplify template for confirmation dialog

- addons/core/translations/resources/en-us.yaml
- ui/admin/app/components/form/target/details/index.hbs
- ui/admin/app/components/worker-diagram/dual-filter/hcp/index.hbs
- ui/admin/app/components/worker-diagram/dual-filter/index.hbs
- ui/admin/app/components/worker-diagram/single-filter/index.hbs
- ui/admin/app/styles/app.scss
Create a element that will explain what the filters and diagrams meaning,  when filter is toggled and when diagram is on screen..
:technologist: [Admin preview](https://www.figma.com/file/XtdzHl6GAXkgEiHaOYALFa/Multi-hop-ingress%2Fegress-filters?node-id=2259%3A15452&t=IetlKI6rfIF4ygi7-0)
> chore: 🤖 create target worker explainer element

- addons/core/translations/resources/en-us.yaml
- ui/admin/app/routes/scopes/scope/targets.js
This PR separates `saveWithAddress` into two steps:  one to remove host sources and another to save as normal.
> refactor: 💡 logically separate save steps for targets

- ui/admin/app/components/form/credential-library/vault-ssh-certificate/index.hbs
It seems like the `key_type` field and `key_bits` field are required in the backend but have [default values](https://github.com/hashicorp/boundary/blob/llb-vault-ssh-cert-injection/internal/credential/vault/repository_ssh_certificate_credential_library.go#L51) if we don't provide one so it's technically optional from our perspective.
> fix: 🐛 Change fields to optional as they get default by backend

- ui/admin/app/templates/onboarding/success.hbs
Change how we define color to an icon. We stop usign `@color` and passing a `--token-color` to use a class `ds-foreground-success`.
> Change the way we declare icon color

- addons/core/addon/helpers/relative-datetime-live.js
- addons/core/tests/integration/helpers/relative-datetime-live-test.js
- ui/admin/app/components/form/worker/index.hbs
This fixes when a worker doesn't properly connect and you try to view the details page for the worker and it errors out due to not having a date time.
> fix: 🐛 Fix null date time erroring out

- addons/api/addon/services/resource-filter-store.js
- addons/core/addon/decorators/resource-filter.js
There can be a bug in workers when you have an active filter on a worker that is deleted and it is the only worker with the active tag being filtered. When we return to the workers route, the `resource-filter` tries to find that tag from the list of tags from the workers but it doesn't find it anymore. 
This aims to fix it by filtering out the `undefined` tags that result from not finding the resources.
> fix: 🐛 Fix undefined values from resource filter

- ui/admin/app/components/form/account/password/change-password/index.hbs
- ui/admin/app/components/form/account/password/set-password/index.hbs
- ui/admin/app/components/form/credential-library/vault-generic/index.hbs
- ui/admin/app/components/form/role/index.hbs
- ui/admin/app/components/form/scope/index.hbs
- ui/admin/app/components/form/target/details/index.hbs
- ui/admin/app/components/form/target/worker-filter/index.hbs
this PR cleans up the text field `isRequired/isOptional` argument. We don't need to pass the argument if it's false. 
[for reference](https://hds-website-hashicorp.vercel.app/components/form/text-input?tab=code#formtextinputfield)
> chore: 🤖 clean up isRequired/isOptional boolean in text field

- ui/desktop/README.md
_Be aware changes on table of contents are result of running doc:toc, not manual changes._
Add how to debug the Desktop Client binary to the debug documentation.
> docs: ✏️ Add how to debug binary to docs

- ui/admin/app/styles/app.scss
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-8022)
**NOTE: This is only to fix the UI bug. Not addressing any other style changes or refactors.**
We removed extra divs around the ordered-series-diagram and helper text component for the higher level `WorkerDiagram::DualFilter` and `WorkerDiagram::DualFilter::Hcp` components. This matched how we created the `WorkerDiagram::SingleFilter` component. However, we removed the div wrapper that was keeping the ordered-series-diagram and helper text component stacked on vertically. Now the helper text component has room to move next to the ordered-series-diagram while viewing in full screen. Solution is to give the ordered-series-diagram component full width of the form to prevent the helper text from moving up.
:technologist: …
> fix: 🐛 fix diagram width so explainer text stays below it

- ui/admin/app/components/ordered-series-diagram/index.hbs
- ui/admin/app/components/worker-diagram/dual-filter/hcp/index.hbs
- ui/admin/app/components/worker-diagram/dual-filter/index.hbs
- ui/admin/app/components/worker-diagram/index.hbs
- ui/admin/app/components/worker-diagram/single-filter/index.hbs
- ui/admin/app/styles/app.scss
Remove `div` wrapping the ordered series diagram component. Wrap the worker diagram component in a `div` to give it a min-height that will account for the height of grouped items that will have a highlighted background.
:technologist: [Admin preview](https://boundary-ctgujg4wd-hashicorp.vercel.app/scopes/s_1sheljmjgm/targets/t_h4m3u5vfzm)
No highlighted group:
Highlighted group:
> refactor: 💡 rename div around ordered-series-diagram

- ui/desktop/package.json
- ui/desktop/tests/end2end/authentication.spec.js
- ui/desktop/tests/end2end/targets.spec.js
- yarn.lock
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-7564)
Playwright documentation recommends to use @playwright/test now as the only playwright package.
**Why this change?**
@moduli is working on adding e2e to Admin UI. While working on the PoC we realize desktop client was using `playwright` yarn package and Admin UI `@playwright/test`, which caused name collisions within the monorepo.
After digging in Palywright documentation and changelog, seems like the recommended way to go is to use `@playwright/test`. Change that on the Desktop app and now both e2e test can be run without name collision.
Tested on @moduli  branch `moduli-e2e-tests-ICU-7418` succesfully 😉
> test: 💍 Swap playwright to @playwright/test package

- .github/workflows/build-admin-ui.yaml
- .github/workflows/monorepo-validate.yaml
- yarn.lock
Changes this PR introduces:
- Change` node-version` definition from`'16.x'` to `16`. Both do the same, provide the greatest node 16 version. **THIS CHANGE** does not fix any problem, neither causes it, is 100% to simplify it. Feel free to argue this change and ask for the previous definition to be back.
- Deletes a conditional that was making the workflow to skip run the jobs with the specific setup. This was introduce it by mistake when we implement cache for the build job in CI. Until now it worked because the GH action `actions/setup-node@v3` was using node `v16` as default. Now `actions/setup-node@v3` is using node `v18` by default, so is when issues start popping and we realize about this.
- Fixes an outdated `yarn.lock`.
More context on the reasons under this PR [this slack …
> fix: 🐛 Fix failure in GH Actions Workflows

- addons/api/addon/generated/models/credential-library.js
- addons/api/addon/serializers/credential-library.js
- addons/api/tests/unit/serializers/credential-library-test.js
✅ Closes: ICU-8141
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-8141)
There was a regression introduced in 0.12.0 where we can't save the generic-vault type for credential libraries. The issue is we were sending extra `null` fields from the `vault-ssh-certificate` type and it's erroring out.
> fix: 🐛 Fix generic-vault getting extra null fields when saving

- ui/admin/tests/e2e/tests/dynamic-host-catalog.spec.js
- ui/admin/tests/e2e/tests/target.spec.js
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-7564)
This PR adds another test to the Admin UI e2e test suite (https://github.com/hashicorp/boundary-ui/pull/1637). 
This test does the following...
- Creates an AWS Dynamic Host Catalog
- Creates a Host Set in that Dynamic Host Catalog and confirms that it sees the appropriate number of hosts
- Creates another Host Set in that Dynamic Host Catalog and confirms that it sees the appropriate number of hosts
Note: This video cuts out when it's adding AWS Credentials just to be extra safe
https://user-images.githubusercontent.com/2474253/220957841-15f4fd0b-e1c8-435e-a4ce-de31402b735f.mp4
> test(admin/e2e): Add test for AWS Dynamic Host Catalogs

- ui/admin/tests/e2e/helpers/vault-cli.js
- ui/admin/tests/e2e/tests/credential-store-static.spec.js
- ui/admin/tests/e2e/tests/credential-store-vault.spec.js
- ui/admin/tests/e2e/tests/fixtures/boundary-controller-policy.hcl
- ui/admin/tests/e2e/tests/fixtures/kv-policy.hcl
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-7564)
This PR adds more tests to the Admin UI e2e test suite (https://github.com/hashicorp/boundary-ui/pull/1637). There are two tests added in this PR.
One test does the following...
- Creates a Static Credential Store
- Stores a Username/Key Pair credential in the store and attaches the credential to a target
- Uses the CLI to authorize a session and retrieve the credentials
- Confirms that the credentials match
The other test does something similar, but with Vault...
- Uses the Vault CLI to set up a Vault server
- Creates a Username/Key Pair credential in Vault
- Creates a Vault Credential Store
- Creates a Vault Credential Library pointing to the Vault credential and attaches the library to a target
- Uses the CLI to …
> test(admin/e2e): Add tests for Credential Stores

- ui/admin/tests/e2e/tests/login.spec.js
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-7564)
This PR adds more tests to the Admin UI e2e test suite (https://github.com/hashicorp/boundary-ui/pull/1637). These tests revolve around logging in.
The tests include the following...
- Log in, log out, and then log back in
- Attempt to log in with an invalid password
- Attempt to log in with only a username
- Attempt to log in with only a password
> test(admin/e2e): Add login tests

- ui/admin/tests/e2e/tests/credential-store-static.spec.js
- ui/admin/tests/e2e/tests/credential-store-vault.spec.js
- ui/admin/tests/e2e/tests/dynamic-host-catalog.spec.js
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-8268)
This PR updates the AWS Dynamic Host Catalog test to catch an issue detailed here: https://github.com/hashicorp/boundary-ui/issues/1644 (Summary: Users get a blank screen when trying to access the "host details" page in a Dynamic Host Catalog host set).
> test(admin/e2e): Update DHC test to catch host issue

- ui/admin/tests/e2e/helpers/vault-cli.js
- ui/admin/tests/e2e/tests/credential-store-static.spec.js
- ui/admin/tests/e2e/tests/credential-store-vault.spec.js
- ui/admin/tests/e2e/tests/fixtures/boundary-controller-policy.hcl
- ui/admin/tests/e2e/tests/fixtures/kv-policy.hcl
- ui/admin/tests/e2e/tests/login.spec.js
This PR is a follow-up to https://github.com/hashicorp/boundary-ui/pull/1617 (Add Compliance and License Headers).
There were some additional files that didn't make it in the original PR. This PR adds the appropriate compliance and license headers to the new files.
> chore(admin/e2e): Add missing compliance headers

- addons/rose/addon/styles/hds/themes/dark-mode/index.scss
Refactored boundary custom colors to be included in root instead of unused mixin for `light-mode`.
> refactor: 💡 refactored dark-mode styling for `HDS`

- ui/desktop/electron-app/package.json
- ui/desktop/electron-app/yarn.lock
Update `electron-forge/*` packages. [As per changelog](https://github.com/electron/forge/releases) there are no breaking changes.
- After upgrade test build process locally with Ubuntu and Mac osx.
- Run `boundary-ui-release` CI to validate the Desktop client CI runs succesfully after the change. [Succesful builds in 3 OS's](https://github.com/hashicorp/boundary-ui-releases/actions/runs/4671937216)
> chore: 🤖 Update electron-forge/* packages

- addons/api/addon/models/host.js
- addons/api/mirage/factories/host.js
- addons/api/mirage/generated/factories/host.js
- addons/core/translations/form/en-us.yaml
- addons/core/translations/resources/en-us.yaml
- ui/admin/app/components/form/host/aws/index.hbs
- ui/admin/app/components/form/host/azure/index.hbs
- ui/admin/app/templates/scopes/scope/host-catalogs/host-catalog/host-sets/host-set/hosts/index.hbs
✅ Closes: ICU-8795
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-8795)
Added support for dynamic host catalogs to display the external name for hosts. Take a look at the mockup [here](https://hashicorp.atlassian.net/browse/ICU-7472), and the [PRD](https://docs.google.com/document/d/181RpEqvKAg-BWNEOEgPCRuu64_GWHBYZmT5Cjbf1uTA/edit#).
I kept the same behavior as we currently have but instead display the external name if there's no boundary name (~~I think there can only be a boundary name if a user manually updates the host's name from the CLI? Not sure since it looks like name isn't populated by default with dynamic hosts~~ Dynamic hosts won't have a name).
The name column for dynamic hosts will now be `External Name`
Desktop:
> feat: 🎸 Add support to display external name for dynamic hosts

- addons/rose/package.json
- yarn.lock
[jira](https://hashicorp.atlassian.net/browse/ICU-8875)
Boundary UI uses [1.5](https://github.com/hashicorp/boundary-ui/blob/main/addons/rose/package.json#L37), which is quite behind the recent design system version. 
This update will allow us to access the new components, such as dropdown.
**Release notes:** 
https://github.com/hashicorp/design-system/releases
Performed a smoke test and checked against the release notes, and boundary UIs do not need any changes with the update
> chore: 🤖 update design system package

- addons/rose/package.json
- package.json
- yarn.lock
✅ Closes: ICU-6588
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-6588)
NOTE: I am assuming `emberx-select` has already been deprecated since I did not find an instance of it in the repo. (This is in reference to the comment in the jira ticket.
-- upgrade `@storybook/ember-cli-storybook` to ^0.6.0
-- remove `css-what` resolution 
Upgrade of `@storybook/ember-cli-storybook` from 0.5.0 to 0.6.0 caused `yarn run storybook` to break. Storybook wouldn't build or run. This was caused by `css-what` resolving to the wrong version (^5.0.1) when `css-what` used by `css-select` is ^6.1.0. 
Context: 
`css-select` was using `SelectorType` [enums](https://github.com/fb55/css-what/commit/65121fec7ef6f4165cc609ba14a58b78f78eb2ea#diff-c54113cf61ec99691748a3890bfbeb00e10efb3f0a76f03a0fd9 …
> chore: 🤖 upgrade @storybook/ember-cli-storybook to 0.6.0

- ui/desktop/electron-app/package.json
- ui/desktop/electron-app/yarn.lock
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-8811)
Audit 3 resolutions within `ui/desktop/electron-app`
`Highlight.js` is used by `devtron`. Devtron is currently unmaintained, receiving it's last change 3 years ago. so there are no expectations of this issue being fix. Since `devtron` is key for our development process we will have to keep `highlight.js` within resolutions.
`@electron-forge > maker-deb > electron-installer-debian > yargs` still resolving` yargs-parser@18.1.3`. [As per synk database](https://security.snyk.io/package/npm/yargs-parser/18.1.3), 18.1.3 has no vulnerabilities, so we can use it and remove yargs-parser from resolutions.
**Testing procedure:**
- Build linux (ubuntu) debian package to confirm still working no problem.
- Desktop client release …
> Chore audit 3 resolutions desktop

- addons/rose/addon/styles/hds/overrides.scss
- ui/admin/app/components/form/group/add-members/index.hbs
- ui/admin/app/styles/app.scss
✅ Closes: ICU-5986
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-5986)
Removed whitespace from layout in `add-members` view for groups by replacing `Rose::Table` with `Hds::Table`.  We were able to achieve the same look as the previous whitespace formatting hack by using  a `Hds::Table ` and a `<HelperText>` to wrap the badge for `account_name` instead of custom `css`.  
There will be a small bit of `override` css that will globally remove margin from form-fields when uses inside of an `Hds::Table`
> refactor: 💡 removed whitespace from layout in add-members view

- ui/admin/app/components/form/role/add-principals/index.hbs
✅ Closes: ICU-5987
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-5987)
Removed whitespace from layout in add-principals view for roles by replacing Rose::Table with Hds::Table. We were able to achieve the same look as the previous whitespace html formatting by using a Hds::Table  and a <HelperText> to wrap the badge for account_name instead of custom css.
> refactor: 💡 refactored whitespace from layout

- package.json
- yarn.lock
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-8810)
Audit 3 resolutions within `./package.json`.
After running `$ yarn why pm-registry-fetch` no matches were found, I assume this dependency is not used anymore.
After performing the changes, `yarn.lock` file does not show any other package depending on `npm-registry-fetch` so its deletion seems safe.
**Testing procedure:**
- Build Admin UI and Desktop client.
- Desktop client release CI test run to provet the change does not affect the CI.
This was add to the audit by mistake since it is pretty new addition. I audit anyways and seems not safe to delete from resolutions yet.
`tunnel-agent` is used by: `ember-electron` > `@electron-forge` > `core` > `nugget` > `request` > `tunnel-agent`.
After removing `tunnel-agent` …
> ICU-8810: Audit 3 resolutions

- addons/api/package.json
- addons/auth/package.json
- addons/core/package.json
- addons/rose/package.json
- yarn.lock
Update `@embroider/test-setup` from `0.48.1` and `1.6.0` to `2.1.1`. As [per Changelog](https://github.com/embroider-build/embroider/blob/main/CHANGELOG.md) there are no breaking changes. 
_When review the Changelog, be aware they deliver different `@embroider/*` packages, so check the changes just for `@embroider/test-setup`_
**Testing procedure:**
- Run the tests within the root project.
- Run build procedures for the addons that suffered changes succesfully.
> Chore update embroider test setup

- ui/admin/app/components/form/worker/create-worker-led/index.js
- ui/admin/tests/acceptance/workers/create-test.js
✅ Closes: ICU-7265
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-7265)
Changed the worker config commands to just download the latest HCP boundary binary. 
Used the `/latest` endpoint from the hashicorp releases and grabbed the URL to be used in a command substitution.
Note that our edition feature switching doesn't properly update the worker page since ember isn't aware of any changes as we use the feature check in getters. You can update it just by filling out a field on the page.
> feat: 🎸 Download latest HCP binary for worker config commands

- ui/admin/app/instance-initializers/feature-edition.js
This fix adds support for fetching `metadata.json` from an arbitrary API host as specified by the `API_HOST` env var.  This is expected to affect only development environments where the UI and controller are running on different hosts/ports.
> fix: 🐛 support metadata access on another API host

- yarn.lock
🚨 [Dependabot Alert #101](https://github.com/hashicorp/boundary-ui/security/dependabot/101)
Added `yaml ^2.2.2` to resolutions in `package.json` then removed it in order to force `yaml` version in `yarn.lock` to resolve to patched version.
> chore: 🤖 upgrade yaml version to fix security alert

- yarn.lock
🚨 [Dependabot Alert #102](https://github.com/hashicorp/boundary-ui/security/dependabot/102)
Added `socket.io ^4.6.1` to resolutions in `package.json` then removed it in order to force `socket.io` version in `yarn.lock`  to resolve to newer version. As a result `engine.io` now resolves to patched version `6.4.2` and this fixes the security alert.
`engine.io` is only used by `socket.io`
> chore: 🤖 upgrade engine.io version to fix security alert

- ui/admin/config/features.js
The work in this [PR](https://github.com/hashicorp/boundary-ui/pull/1688) is being separated in order to increase readability. This is the first part which just includes adding the feature flag for ldap auth-methods. It will stay disabled for Phase 1 of implementation. It will be used in the abilities for auth-methods and accounts in order to disallow for any actions involving ldap auth methods and accounts.
> feat: 🎸 add ldap-auth-methods feature flag

- ui/desktop/app/templates/scopes/scope/projects/targets/index.hbs
✅ Closes: ICU-9375
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-9375)
Target descriptions were not displaying due to some previous refactoring.  Corrected `description` and `isActive` references.
> fix: 🐛 fix descriptions for targets list for desktop

- addons/api/addon/generated/models/auth-method.js
- addons/api/tests/unit/serializers/auth-method-test.js
We are currently serializing client secrets in the OIDC auth methods form even if they're null. Annotated it as a secret so it won't get serialized if it doesn't exist 
See this [thread](https://hashicorp.slack.com/archives/C012GTH1C4E/p1685109648980819) for more details.
> fix: 🐛 Fix serializing client secrets in oidc auth methods

- ui/admin/app/components/form/worker/create-worker-led/index.js
- ui/admin/tests/acceptance/workers/create-test.js
✅ Closes: ICU-9570
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-9570)
The binary name we use to create a worker needs to be updated to `boundary` as `boundary-worker` won't be a thing anymore in 0.13.
I also updated where we pull the latest binary from in HCP, we'll be grabbing the enterprise binary now as HCP won't exist anymore.
See this [thread](https://hashicorp.slack.com/archives/C033EGCF0RL/p1685718648284049) for more details.
> chore: 🤖 Update worker binary name to just boundary

- ui/desktop/app/styles/app.scss
The Desktop cluster URL and auth card widths were too narrow.  This PR increases it.
After:
Before:
> fix: 🐛 increase auth form width, which was too narrow

- addons/rose/addon/styles/hds/overrides.scss
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-9682)
Add bottom margin for `HDS button set`
Before: 
After:
> fix: 🐛 add margin for button sets

- ui/admin/app/components/form/worker/create-worker-led/index.hbs
- ui/admin/app/routes/scopes/scope/workers.js
- ui/admin/app/routes/scopes/scope/workers/worker/index.js
- ui/admin/app/templates/scopes/scope/workers/new.hbs
- ui/admin/tests/integration/components/form/worker/create-worker-led-test.js
[Jira](https://hashicorp.atlassian.net/browse/ICU-9709)
Show `done` only when a worker is registered successfully, otherwise show cancel and navigate to workers list
> fix: 🐛 worker form navigation

- package.json
- yarn.lock
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-9072)
- After running `yarn why caniuse-lite` is used by different deps.
- After deleting `caniuse-lite` from resolutions, resolves a higer version than the one we had in resolutions. We can delete safely from resolutions `caniuse-lite`.
How to test:
- Build API and Rose addons succesfully.
- After running `yarn why immer` is used by storybook deps.
- Unfortunetly, if we delete `immer` in resolutions, we start resolving a version `8.0.1` which has a security vulnerability.
- We will keep `immer` in resolutions but being very specific, just affects the `immer` within `@storybook`.
No need to test, because there are no changes within `yarn.lock` neither on the version resolved.
- After running `yarn why node-notifier` is …
> Chore icu 9072 audit resolutions

- package.json
- yarn.lock
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-9073)
Delete next dependencies from `resolutions`.
- After running `yarn why highlight.js` is used by `react-syntax`(3rd party dep).
- After deleting `highlight.js` from resolutions shows no updates within `yarn.lock`, it is safe to delete.
- After running `yarn why hoek` no matches were found, so it is not used.
- After deleting `hoek` from resolutions, `yarn.lock` shows no one is depending on it (no changes).
- After running `yarn why elliptic` is used by `webpack`.
- After deleting `elliptic` from resolutions, we still resolving `6.5.4` which has no security vulnerabilities, as per [synk info](https://security.snyk.io/package/npm/elliptic).
CI test run with all these changes, [link …
> Chore icu 9073 audit resolutions

- package.json
- yarn.lock
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-9074)
Delete next dependencies from `resolutions`.
- After running `yarn why yargs-parser` is used by `rose` & `desktop`.
- After deleting `yargs-parser` from resolutions, we still resolving `20.2.9` which has no security vulnerabilities, as per [synk info](https://security.snyk.io/package/npm/yargs-parser/20.2.9). We also see the newolution of `21.1.1` which means we were blocking deps from using this newer version.
- After running `yarn why merge` is used by core addon, for a couple of 3rd party deps.
- After deletin `merge` from resolutions, we see no changes within `yarn.lock`. Also, stills resolving the `2.1.1` which has no security vulnerabilities, as per [synk info](https://security.snyk.io/package/npm/merge).
- …
> Chore icu 9074 audit resolutions

- package.json
- yarn.lock
This solved a recently introduced issue where hosted-git-info resolves intermittent different versions, causing constant changes in `yarn.lock`.
Delete `hosted-git-info` from resolutions. After deletion we are resolving `2.8.9` which has NO security vulnerabilities as [per synk information](https://security.snyk.io/package/npm/hosted-git-info).
> Delete hosted-git-info from resolutions

- ui/desktop/package.json
- yarn.lock
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-9878)
Deprecate cross-os and use shx. More information on the jira ticket.
- Running the DC building process within mac, linux and windows succesfuly.
- [Release CI run succesfully](https://github.com/hashicorp/boundary-ui-releases/actions/runs/5339628541)
> chore: 🤖 Deprecate cross-os

- package.json
- yarn.lock
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-9078)
- After running `yarn why normalize-url` one dep is using it.
- After deleting `normalize-url` from resolutions, we resolve now a much newer version `6.1.0` which as per [synk information](https://security.snyk.io/package/npm/normalize-url) has no security vulnerabilities.
- After running `yarn why glob-parent` a lot of deps use it.
- After deleting `glob-parent` from resolutions, 2 deps still resolving `glob-parent@3.1.0` which has security vulnerabilities, as per [synk information](https://security.snyk.io/package/npm/glob-parent). We will add more specific resolutions.
- After running `yarn why tar` a lot of deps use it.
- After deleting `tar` from resolutions, we do resolve newer version without security …
> Chore icu 9078 audit resolutions

- ui/desktop/electron-app/package.json
- ui/desktop/electron-app/yarn.lock
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-9906)
Upgrade `semver` from `7.3.7` to `7.5.2` as per dependabot complain. Check Jira ticker for more information.
- `semver` is used within the desktop client build process. Tested running succesfully the desktop client.
> chore: 🤖 Upgrade semver within electron-app

- package.json
- yarn.lock
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-9079)
- After running `yarn why path-parse` different deps use it.
- After deleting `path-parse` from resolutions the `yarn.lock` shows no changes, and we still resolving `1.0.7` which  has no security vulnerabilities, as per [snyk information](https://security.snyk.io/package/npm/path-parse). It is safe to delete `path-parse` from resolutions.
- After running `yarn why nth-check` different deps use it.
- After deleting `nth-check` from resolutions, a dep starts resolving `nth-check@1.0.2` which has security vulnerabilities, as per [snyk information](https://security.snyk.io/package/npm/nth-check). We will add an specific resolution.
- After running `yarn why tmpl` is used by one dep.
- After deleting `tmpl` from …
> Chore icu 9079 audit resolutions

- package.json
- patches/ember-intl+6.0.0-beta.4.patch
- yarn.lock
✅ Closes: ICU-9914
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-9914)
Added `patch-package` to manually patch the `ember-intl` [issue](https://github.com/ember-intl/ember-intl/issues/1451) that causes our windows builds to not properly produce a binary with correct translations. This also resolves https://github.com/hashicorp/boundary-ui/issues/1708. 
Tested a windows build and translations works as expected.
> chore: 🤖 Add patch-package to fix ember-intl for windows builds

- .github/workflows/jira.yml
✅ Closes: ICU-9815
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-9815)
The `atlassian/gajira-comment` github action was onboarded onto TSCCR via PR.
Then the entry in `jira.yml` was updated using via the cli  using this command `tsccr-helper -pin-workflow=./.github/workflows/jira.yml`
Checkout ticket for more details.
> chore: 🤖 use trusted SHA for atlassian/gajira-comment

- ui/admin/app/components/host-catalogs/host-catalog/host-sets/host-set/hosts/host/header/index.hbs
- ui/admin/app/components/host-catalogs/host-catalog/host-sets/host-set/hosts/host/navigation/index.hbs
- ui/admin/app/templates/scopes/scope/host-catalogs/host-catalog/host-sets/host-set/hosts/host/index.hbs
✅ Closes: ICU-9629
Added a header for the hosts page in dynamic host catalogs.
:technologist: [Admin preview](https://boundary-ui-git-icu-9629-fe-dhc-host-set-missi-0cc208-hashicorp.vercel.app/scopes/s_1sheljmjgm/host-catalogs/hc_tf6wuazt5y/host-sets/hs_siob9t77b1/hosts/h_n0k6xy7x84)
> fix: 🐛 Add header for dynamic host catalog hosts page

- ui/desktop/electron-app/package.json
- ui/desktop/electron-app/yarn.lock
Just updating semver in the yarn.lock file since it looks like this dependabot [alert](https://github.com/hashicorp/boundary-ui/pull/1738) wasn't fully resolved as we still had some versions still resolving to `7.3.5`.
> chore: 🤖 Update semver

- addons/core/addon/components/form/authenticate/details/index.hbs
- addons/core/addon/components/form/authenticate/oidc/index.hbs
- addons/rose/addon/components/rose/form/actions/edit-toggle/index.hbs
- addons/rose/addon/components/rose/form/actions/index.hbs
- ui/admin/app/styles/app.scss
- ui/desktop/app/styles/app.scss
- ui/desktop/app/templates/cluster-url.hbs
✅ Closes: ICU-9507
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-9507)
Add support for named block content in rose form actions.
Checkout ticket for details.
:technologist: [Admin preview](https://boundary-ui-git-icu-9507-add-support-for-block-cef1e7-hashicorp.vercel.app/scopes/global/authenticate/am_3enprm7y2t)
:desktop_computer: [Desktop preview](https://boundary-ui-desktop-git-icu-9507-add-support-f-74fad1-hashicorp.vercel.app/cluster-url)
> refactor: 💡 add support for named block content in form actions

- package.json
- yarn.lock
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-9080)
- After running `yarn why set-value` some deps use it.
- After deleting `set-value` from resolutions, all deps start resolving older version `2.0.1` which has security vulnerabilities as per [snyk information](https://security.snyk.io/package/npm/set-value). We add an specific resolution to fix this and avoid collisions in the future.
- After running `yarn why ansi-regex` lots of deps use it.
- After deleting `ansi-regex` from resolutions, we start resolving older version than `5.0.1` but almost of them has no security vulnerabilitiesas per [snyk information](https://security.snyk.io/package/npm/ansi-regex). We will add an specific resolution to avoid resolve any version with security vulnerabilities.
- After running …
> Chore icu 9080 audit resolutions

- package.json
- ui/desktop/electron-app/package.json
- ui/desktop/electron-app/yarn.lock
- yarn.lock
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-9081)
- After running `yarn why jsonpointer` no dependencies use it.
- After deleting `jsonpointer` from resolutions, yarn.lock does not resolve it anymore, so it is safe to delete from resolutions.
- After running `yarn why json-schema` ui/desktop uses it.
- After deleting `json-schema` from resolutions, we resolve an older version with security vulnerabilities, as per [snyk information](https://security.snyk.io/package/npm/json-schema). We will clean up `json-schema` resolution for `electron-app/package.json` project, and modify to a more specific resolutions within root `package.json`.
- After running `yarn why follow-redirects` one dep uses it.
- After deleting `follow-redirects` from resolutions, we keep resolving …
> Chore icu 9081 audit resolutions

- package.json
- yarn.lock
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-9082)
- After running `yarn why node-fetch` different deps use it.
- After deleting `node-fetch` from resolutions, we resolve `node-fetch@2.6.11` which has no security vulnerabilities as per [snyk information](https://security.snyk.io/package/npm/node-fetch).
- After running `yarn why shelljs` one dep uses it.
- After deleting `shelljs` from resolutions, we keep resolving `shelljs@0.8.5` which has no security vulnerabilities as per [snyk information](https://security.snyk.io/package/npm/shelljs).
- After running `yarn why ember-template-recast` onde dep uses it.
- After deleting `ember-template-recast` from resolutions, we are reproducing a weir third party dependencies side effects. Even tho we have specific resolutions …
> Chore icu 9082 audit resolutions

- ui/admin/config/environment.js
✅ Closes: ICU-10091
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-10091)
Enables feature flag in dev environment. LDAP auth-method will still be non-readable and non-actionable in prod env. 
:technologist: [Admin preview](https://boundary-ui-git-icu-10091-ldap-feature-flag-hashicorp.vercel.app/scopes/global/auth-methods)
After Enabling in dev env.
> feat: 🎸 enable feature flag in dev environment

- ui/admin/app/templates/scopes/scope/auth-methods/index.hbs
- ui/admin/tests/acceptance/auth-methods/create-test.js
✅ Closes: ICU-10071
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-10071)
Adds ldap option to New dropdown in list view. 
Note: Clicking the ldap option won't work until the form is added.
:technologist: [Admin preview](https://boundary-ui-git-icu-10071-ldap-auth-methods-list-view-hashicorp.vercel.app/scopes/global/auth-methods)
when feature flag is enabled:
when feature flag is disabled:
> feat: 🎸 add ldap type to dropdown in list view

- ui/desktop/electron-app/package.json
- ui/desktop/electron-app/yarn.lock
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-9087)
- After running `yarn why normalize-url` a dep uses it.
- After deleting `normalize-url` from resolutions, we resolve `normalize-url@6.1.0` wich is newer than before and has no security vulnerabilities as per [snyk information](https://security.snyk.io/package/npm/normalize-url).
- After running `yarn why jszip` a dep uses it.
- After deleting `jszip` from resolutions there are no changes within `yarn.lock` and we keep resolving `jszip@3.10.1` which has no security vulnerabilities as per [snyk information](https://security.snyk.io/package/npm/jszip).
- After running `yarn why path-parse` a couple of deps use it.
- After deleting `path-parse` from resolutions there are no changes within `yarn.lock` and we keep …
> Chore icu 9087 audit resolutions electron app

- ui/desktop/app/templates/scopes/scope/projects/sessions/index.hbs
- ui/desktop/app/templates/scopes/scope/projects/targets/index.hbs
✅ Closes: ICU-10149
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-10149)
Updates to the Targets list "Connect" button and the Sessions list "Cancel" button to use `<Hds::Button />` instead of `<Rose::Button />`
:desktop_computer: [Desktop preview](https://boundary-ui-desktop-git-icu-10149-adoption-hds-0f45a7-hashicorp.vercel.app/scopes/global/projects/targets)
Before:
After:
> refactor: 💡 migrate two rose buttons to hds in desktop client

- ui/admin/package.json
- ui/desktop/package.json
- yarn.lock
Forked https://github.com/randallmorey/ember-pollster into our hashicorp repo. Turns out you can't fork a public repo into the org right off the bat so I had to first create an internal repo and mirror push the repo. It's located [here](https://github.com/hashicorp/ember-pollster/) now
We're now pointing to a specific commit of the repo.
> chore: 🤖 Point ember-pollster to new hashicorp repo

- addons/rose/package.json
- yarn.lock
✅ Closes: ICU-10270
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-10270)
update HDS to v2.8.0 from v2.7.0
There is one technical breaking change mentioned in the [release notes](https://github.com/hashicorp/design-system/releases/tag/%40hashicorp%2Fdesign-system-components%402.8.0) for `<Hds::Card::Container />`. After reviewing the change, it looks like we don't need to specify `@overflow` for our use.
> chore: 🤖 update HDS to v2.8.0

- ui/admin/tests/e2e/tests/target.spec.js
✅ Closes: ICU-9772
:tickets: [ICU-9772](https://hashicorp.atlassian.net/browse/ICU-9772)
This PR adds a UI test that verifies that TCP target can be updated.
The test does the following:
- creates an organisation
- creates a project
- creates a target
- updates target's fields
- saves the changes
- verifies 'Success' alert is displayed
- deletes the organization
:rose: [Rose preview](PATH_TO_FEATURE)
[ICU-9772]: https://hashicorp.atlassian.net/browse/ICU-9772?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> test: 💍 Add TCP target update test

- addons/api/addon/models/auth-method.js
- addons/api/addon/serializers/auth-method.js
- addons/core/translations/resources/en-us.yaml
- ui/admin/app/components/auth-methods/auth-method/actions/index.hbs
- ui/admin/app/components/form/auth-method/ldap/index.hbs
- ui/admin/app/components/form/auth-method/ldap/index.js
- ui/admin/app/routes/scopes/scope/auth-methods/auth-method.js
- ui/admin/tests/acceptance/auth-methods/delete-test.js
- ui/admin/tests/acceptance/auth-methods/update-test.js
✅ Closes: ICU-10078 & 10079
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-10078)
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-10079)
Allows state change for ldap auth-method.
Verifies that cancelling changes rolls back attributes.
Verifies that deleting ldap auth method is successful.
Verifies that editing an ldap auth method is successful.
Acceptance tests for delete and update.
:technologist: [Admin preview](https://boundary-ui-git-icu-10078-enable-edit-mode-hashicorp.vercel.app/scopes/global/auth-methods/am_ec8st2tp51)
> refactor: 💡 update to allow state change & update edit action

- ui/admin/app/templates/scopes/scope/auth-methods/auth-method/accounts/index.hbs
- yarn.lock
During the recent HDS migration, the account IDs were incorrectly added.
before
after:
> fix missing account ids

- ui/desktop/electron-app/src/index.js
[jira](https://hashicorp.atlassian.net/browse/ICU-10505)
replace deprecated `substr` with `substring`. 
To learn more see [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr)
**Test**: 
- the desktop app works as expected
[workflow](https://github.com/hashicorp/boundary-ui-releases/actions/runs/5744870337)
> fix: 🐛 replace deprecated substr with substring

- addons/api/addon/generated/models/account.js
- addons/api/tests/unit/serializers/account-test.js
- ui/admin/app/templates/scopes/scope/auth-methods/auth-method/accounts/index.hbs
✅ Closes: ICU-10503
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-10503)
Changed `type` and `auth_method_id` on the `accounts` model to `readOnly` so they are not sent in API payload.
> fix: 🐛 accounts update refactor

- .husky/prepare-commit-msg
There's an annoying (at least to me) behavior from the commit hooks where when rebasing, commitizen will execute on _every_ commit that is getting rebased ontop of the branch. If you've been working on a branch for a while or on a long living branch, this can be very annoying as you might have quite a few commits to go through. If I am changing the commit messages, I normally would be doing that during the interactive rebase rather than having commitizen running on every individual commit. 
In the same way merge commits don't cause commitizen to run, I don't think rebases should cause commitizen to run.
Let me know if you think we shouldn't change this or it affects your workflow.
> chore: 🤖 Update prepare-commit-msg to not execute when rebasing

- addons/core/translations/resources/en-us.yaml
- ui/desktop/app/router.js
- ui/desktop/app/routes/scopes/scope/projects/sessions/session.js
- ui/desktop/app/styles/app.scss
- ui/desktop/app/templates/scopes/scope/projects/sessions/session.hbs
- ui/desktop/app/templates/scopes/scope/projects/targets/target.hbs
- ui/desktop/tests/unit/routes/scopes/scope/projects/sessions/session-test.js
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-10491) Route creation
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-10492) Header
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-10493) Layout
Create route for session/session-id
Add base header and layout for screen
**_No logic routing logic for ending the session or redirecting away from detail screen_**
_**Also no direct route for user, requires direct url manipulation, add `/session-id` to end of sessions route**_
:desktop_computer: [Desktop preview](https://boundary-ui-desktop-git-icu-10491-create-route-4609f4-hashicorp.vercel.app/scopes/global/projects/sessions/ss_69vzrnh490)
> Icu 10491 create route for session/session-id

- addons/core/translations/resources/en-us.yaml
- ui/desktop/app/styles/app.scss
- ui/desktop/app/templates/scopes/scope/projects/targets/target.hbs
- ui/desktop/tests/acceptance/projects/targets-test.js
- ui/desktop/tests/acceptance/scopes-test.js
✅ Closes: ICU-10302
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-10302)
add target details sidebar panel to target detail page
I did limited styling for the copy button of the target ID. This will be replaced by the [HDS Copy Snippet](https://helios.hashicorp.design/components/copy/snippet?tab=code) component.
:desktop_computer: [Desktop preview](https://boundary-ui-desktop-git-icu-10302-add-side-pan-ee97de-hashicorp.vercel.app/scopes/global/projects/targets/t_l5fhet6083)
> feat: 🎸 add target details sidebar panel to target detail page

- addons/api/addon/abilities/session.js
- addons/api/addon/models/session.js
- addons/api/app/abilities/session.js
- addons/api/tests/unit/abilities/session-test.js
- ui/desktop/app/styles/app.scss
- ui/desktop/app/templates/scopes/scope/projects/sessions/index.hbs
- ui/desktop/tests/acceptance/projects/sessions-test.js
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-10521)
add route logic from sessions list to session detail screen
only `active` and `pending` sessions can be visited and will have a link
:desktop_computer: [Desktop preview](https://boundary-ui-desktop-git-icu-10521-add-route-lo-7b9fa0-hashicorp.vercel.app/scopes/global/projects/sessions)
> Icu 10521 add route logic from sessions list to session detail screen

- addons/rose/addon/components/rose/code-editor/toolbar/index.hbs
- addons/rose/package.json
- package.json
- yarn.lock
update hds to 2.10.0
HDS v2.9.0 introduced Copy components that use `ember-cli-clipboard@1.0.0`. This introduced a dependency issue with `ember-arg-types` that uses `prop-types@15.7.1` but it needs to be at v15.8.1. Added a resolution for that now and will remove if HDS fixes this.
> chore: 🤖 update hds to 2.10.0

- addons/core/addon/initializers/deprecations.js
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-10577)
this pr will silence the `deprecate_early_static` [warning](https://rfcs.emberjs.com/id/0741-ember-data-deprecate-model-static-field-access-without-lookup/), which affects only when mocks are used. This is due to the discoverEmberDataModels method that accesses the static fields of the model directly.
> chore: 🤖 silence `deprecate_early_static` warnings

- ui/admin/app/routes/scopes/scope/roles/role/index.js
- yarn.lock
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-10635)
This pr gets rid of the [promiseArray deprecation warning](https://api.emberjs.com/ember-data/4.12/classes/CurrentDeprecations/properties?anchor=DEPRECATE_PROMISE_PROXIES)
Since the listed methods in the link above return a promise now, we need to resolve this object before we access them in the templates.
[preview](https://boundary-ui-git-icu-10635-fix-proxy-promises-warning-hashicorp.vercel.app/scopes/global/roles/r_22a3qt99e6)
> fix: 🐛 proxy promise deprecation

- .copywrite.hcl
- .gitignore
noticed we still have some storybook-related files in the repo, since storybook is removed from our apps, these should be deleted as well.
> chore: 🤖 remove storybook related files

- ui/desktop/.ember-cli
- ui/desktop/package.json
Made a change to set the port in the package script rather than ember-cli so it doesn't change the default ports when running just `ember test`
> chore: 🤖 Change port to be set in package script

- ui/admin/app/routes/scopes/scope/authenticate.js
- ui/admin/app/routes/scopes/scope/index.js
[jira](https://hashicorp.atlassian.net/browse/ICU-10657)
This PR fixes the `filterby` [deprecation](https://rfcs.emberjs.com/id/0848-deprecate-array-prototype-extensions/) warning.
[preview](https://boundary-ui-git-icu-10657-fix-filterby-deprecation-hashicorp.vercel.app/) [check console logs for the warning]
> fix: 🐛 filterby deprecation warning

- ui/desktop/app/styles/app.scss
add flex-shrink to flight-icon to avoid icon shrinking
before:
after:
> fix: 🐛 add flex-shrink to flight-icon to avoid icon shrinking

- addons/core/addon/initializers/deprecations.js
- ui/admin/app/routes/scopes/scope/roles/role/add-principals.js
- ui/admin/app/routes/scopes/scope/targets/target/enable-session-recording/index.js
- ui/admin/app/routes/scopes/scope/users.js
- ui/admin/app/routes/scopes/scope/users/user.js
[jira](https://hashicorp.atlassian.net/browse/ICU-10578)
[deprecation](https://rfcs.emberjs.com/id/0848-deprecate-array-prototype-extensions/)
this pr fixes `toArray` deprecation warning, I had to silence the warnings due to HDS table's [usage](https://github.com/hashicorp/design-system/blob/dcd881a217a7d9eaee50f9830db28f9f80db0b9d/packages/components/addon/components/hds/table/index.hbs#L50) of sort-by ember-composable-helpers which [internally](https://github.com/DockYard/ember-composable-helpers/blob/62fb18314e563d70c6588d733df4d26fd4b14aa1/addon/helpers/sort-by.js#L112) used `toArray` method. I raised it with the HDS team, but for now we will silence the warning as it happening in quite a few places.
> fix: 🐛 toarray deprecation warning

- ui/desktop/app/routes/scopes/scope/projects/sessions.js
- ui/desktop/tests/acceptance/projects/sessions/index-test.js
- ui/desktop/tests/acceptance/projects/sessions/session-test.js
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-10760)
redirect to targets list when canceling from the sessions detail screen
✅ Closes: ICU-10760
:desktop_computer: [Desktop preview](https://boundary-ui-desktop-git-icu-10760-route-user-t-ed6945-hashicorp.vercel.app/scopes/global/projects/targets)
When you establish a connection, click "End Session" from the sessions detail screen and user will be redirected to the targets list screen. If you click "Cancel" on a session from the sessions list screen, you should stay in the same location.
> feat: 🎸 redirect to targets list when canceling

- ui/desktop/app/routes/scopes/scope/projects/sessions/session.js
- ui/desktop/app/styles/app.scss
- ui/desktop/electron-app/package.json
- ui/desktop/electron-app/src/index.js
- ui/desktop/electron-app/src/ipc/handlers.js
- ui/desktop/electron-app/src/preload.js
- ui/desktop/electron-app/yarn.lock
- ui/desktop/ember-cli-build.js
- ui/desktop/package.json
- yarn.lock
This lets us keep sandboxing on and `nodeIntegration` off in the renderer process.
We still only have one pty process which is shared across the entire browser window and need to do proper cleanup.
> refactor: 💡 Turn on sandboxing for renderer process

- ui/admin/tests/e2e/helpers/boundary-ui.js
- ui/admin/tests/e2e/tests/group-role.spec.js
✅ Closes: ICU-10557
:tickets: [ICU-10557](https://hashicorp.atlassian.net/browse/ICU-10557)
This PR adds a new UI e2e test that does the following:
1. Create a new group
2. Adds user to the group
3. Creates a new role
4. Adds principle (i.e. the group) to the role
5. Assigns grants to the role
6. Verifies the grants are assigned
[ICU-10557]: https://hashicorp.atlassian.net/browse/ICU-10557?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> test: 💍 Add create group and roles e2e UI test

- ui/admin/tests/e2e/helpers/boundary-ui.js
- ui/admin/tests/e2e/tests/credential-store-static.spec.js
- ui/admin/tests/e2e/tests/credential-store-vault.spec.js
- ui/admin/tests/e2e/tests/target.spec.js
:tickets: [ICU-8678](https://hashicorp.atlassian.net/browse/ICU-8678)
This PR renames some environment variables used in the Admin UI test suite to improve clarity. This is an outcome from some work adding a test in the BE e2e test suite: https://github.com/hashicorp/boundary/pull/3671
[ICU-8678]: https://hashicorp.atlassian.net/browse/ICU-8678?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> test(admin/e2e): Rename variables for clarity

- ui/desktop/app/controllers/scopes/scope/projects/targets/target.js
- ui/desktop/app/routes/scopes/scope/projects/targets.js
- ui/desktop/app/routes/scopes/scope/projects/targets/target.js
- ui/desktop/app/templates/scopes/scope/projects/targets/index.hbs
- ui/desktop/app/templates/scopes/scope/projects/targets/target.hbs
- ui/desktop/tests/acceptance/projects/targets/index-test.js
- ui/desktop/tests/acceptance/projects/targets/target-test.js
- ui/desktop/tests/acceptance/scopes-test.js
- ui/desktop/tests/unit/controllers/scopes/scope/projects/targets/target-test.js
✅ Closes: ICU-10430
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-10430)
Update connect logic for targets with static addresses. This does technically break the connect workflow for targets with hosts but that is the next 2 stories I will be working on.
[Route Logic: Target with Static Hosts](https://hashicorp.atlassian.net/browse/ICU-10431)
[Route Logic: Target with Dynamic Hosts](https://hashicorp.atlassian.net/browse/ICU-10432)
Steps to test:
The **_third Target in the list_** will have a static address that you can establish a connection with.
1. Visit a Target
- Click on the target name and you should see the target details screen with the "Connect" button in the top right.
2. Connect to a Target
- Option 1: Click on the "Connect" button at the end of the row for …
> feat: 🎸 update connect logic for targets with static addresses

- ui/desktop/electron-app/package.json
- ui/desktop/electron-app/src/index.js
- ui/desktop/electron-app/tests/index.js
- ui/desktop/electron-app/yarn.lock
[Jira](https://hashicorp.atlassian.net/browse/ICU-10886)
This PR gets rid of [devtron](https://github.com/electron-userland/devtron) package, as it is not being maintained and looks outdated. This also fixes the log failures on desktop app start-up
`failed to install devtron: typeerror: electron.browserwindow.adddevtoolsextension is not a function `
> chore: 🤖 remove devtron

- ui/desktop/electron-app/package.json
- ui/desktop/electron-app/yarn.lock
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-9089)
- After running `yarn why jsonpointer` is used by 1 dep.
- After deleting `jsonpointer` from resolutions we start resolving a version with security vulnerabilities. We add a more specific resolution for `jsonpointer@^5`. So we resolve a version with no security vulnerabilities as per [snyk](https://security.snyk.io/package/npm/jsonpointer).
- After running `yarn why node-fetch` is used by some deps, within `electron-app` and outside.
- After deleting `node-fetch` resolution, we resolve `node-fetch@2.6.7` within `electron-app` and `node-fetch@2.6.11` neither of these version have security vulnerabilities as per [snyk information](https://security.snyk.io/package/npm/node-fetch). It is safe to delete `node-fetch` from …
> Chore icu 9089 audit resolutions desktop

- ui/desktop/app/components/session/tabs/index.hbs
- ui/desktop/app/styles/app.scss
Fix proxy url positioning to be above the credentials panel and sidebar details
> refactor: 💡 fix proxy-url to render above body and sidebar

- ui/desktop/app/components/session/tabs/index.js
We had a suggestion to add the `-o` flag when sending the SSH command and auto connecting which is a great UX improvement.
https://github.com/hashicorp/boundary-ui/assets/5783847/c9a0b6cd-fd3a-4a80-bead-b95ceea133ad
Automatically connect to an SSH target and it should not prompt for trusting the known hosts.
> feat: 🎸 Add flag to ssh command to not prompt for known hosts

- package.json
- ui/desktop/electron-app/package.json
- yarn.lock
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-9090)
- After running `yarn why plist` is used by some deps.
- After deleting `plist` from resolutions, we still resolving `plist@3.1.0` which has no security vulnerabilities as per [snyk information](https://security.snyk.io/package/npm/plist).
- After running `yarn why lzma-native` is used by some deps, within electron-app and at the root of boundary-ui.
- After deleting `lzma-native` from both resolutions, we still resolving `lzma-native@8.0.6` which has no security vulnerabilities as per [snyk information](https://security.snyk.io/package/npm/lzma-native).
- After running `yarn why minimist` is used by some deps.
- After deleting `minimist` from resolutions, we still resolving `minimist@1.2.8` which has no security …
> Chore icu 9090 audit resolutions desktop

- ui/desktop/app/routes/scopes/scope/projects/sessions.js
fix cancel session failing after shell has started
✅ Closes: ICU-11035
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-11035)
https://github.com/hashicorp/boundary-ui/assets/29386339/f1983454-10d4-42c9-a1a5-1c8985cc4405
Cancel session will always work with mirage data. To really test this, you need to setup a dev instance, create all the needed resources (target, credentials, etc). Connect to that target, start the shell in the desktop client, then try to end the session. This should now work.
> fix: 🐛 fix cancel session failing after shell has started

- ui/desktop/electron-app/package.json
- ui/desktop/electron-app/yarn.lock
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-11041)
Upgrade Electron to 26.x version as per security concerns.
- Build successfully desktop client in local env.
- Build successfully `boundary-ui-release`. [Build here](https://github.com/hashicorp/boundary-ui-releases/actions/runs/6241322216)
> chore: 🤖 Upgrade Electron to 26.x

- ui/desktop/app/components/session/tabs/index.js
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-11108)
I decided to dynamically set the height of the container for the terminal as there is no better solution for this that I could think of. Using a standard `80vh` causes a really annoying issue with two scroll bars at smaller resolutions and bigger gaps at larger heights due to the fixed height of our other elements.
Before: 
After: 
https://github.com/hashicorp/boundary-ui/assets/5783847/7cbd8750-c688-4e0f-8c96-76b243248bec
Resize the window in electron
> feat: 🎸 Resize terminal container dynamically

- ui/desktop/app/styles/app.scss
This only removes the `border-radius` and `padding` changes, not the height changes. These changes were conflicting with OS level themes and behaved different if you use a mouse or a trackpad on Mac computers. The plan is to revisit custom themes after release and allow the theme to update dependent on the user's OS theme. There is a way to hide the scrollbar entirely but that felt like a bad trade off for user experience.
Before:
After:
Connect to target and click on shell tab
:desktop_computer: [Desktop preview](https://boundary-ui-desktop-git-remove-custom-xterm-styles-hashicorp.vercel.app/scopes/global/projects/targets)
> refactor: 💡 remove custom xterm styles

- addons/core/addon/authenticators/oidc.js
It seems like we weren't properly calling the DELETE route for the tokens in OIDC authentications.
Before:
After:
Use boundary dev and test that that the tokens in boundary are deleted (by listing the tokens) after signing out. 
> fix: 🐛 Fix not calling delete properly in OIDC

- ui/admin/config/environment.js
- ui/admin/config/features.js
enable ldap feature flag for prod
Make sure ldap auth method is still viewable in admin UI.
> chore: 🤖 enable ldap feature flag for all envs

- ui/desktop/app/components/session/tabs/index.js
- ui/desktop/electron-app/src/cli/path.js
✅ Closes: ICU-11209
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-11209)
When a user initiates a session from the CLI, we won't be aware of the proxy details so can't automatically initiate an SSH connection. We need to prevent trying to automatically connect in these scenarios.
Initiate a connection from the CLI and then open the shell for that session in the desktop client.
> fix: 🐛 Stop sending ssh command when session initiated in CLI

- ui/admin/package.json
- ui/desktop/package.json
- yarn.lock
✅ Closes: ICU-11211
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-11211)
The main fix was in this [PR](https://github.com/hashicorp/boundary-ui/pull/1926) to add a polyfill. However, it wasn't correctly getting activated because we didn't have the right dependencies. 
Before:
After:
I tested this by running against boundary dev with a local build running and setting up ngrok to deliver an http only tunnel (no TLS) to confirm that we are getting a crypto.randomUUID() error when trying to create a new resource.
> fix: 🐛 Fix polyfill not working correctly

- addons/api/addon/models/storage-bucket.js
- addons/api/tests/unit/models/storage-bucket-test.js
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-11218)
Fixes the issue where storage buckets that use dynamic credentials are showing up as static after creation and reloading the screen.
Before:
After:
Need to setup a worker running in aws to test this. I will be testing this against a real boundary instance but wanted to get the PR ready.
> fix: 🐛 dynamic storage bucket showing as static

- ui/desktop/app/components/target/host-modal/index.hbs
- ui/desktop/app/controllers/scopes/scope/projects/targets/target.js
- ui/desktop/app/routes/scopes/scope/projects/targets/target.js
- ui/desktop/app/templates/scopes/scope/projects/targets/target.hbs
- ui/desktop/tests/acceptance/projects/targets/index-test.js
- ui/desktop/tests/integration/components/target/host-modal-test.js
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-11231)
If the `connect` action were to cause an error then an error modal would render (when connecting from target list view). However, the choose hosts modal would also, incorrectly, render. 
Before: 
After:
1. Start a boundary dev instance.
2. Create a ssh target with a valid address but no hosts and no injected credentials.
3. Attempt to connect to the ssh target using the "connect" button in target list view (targets table).
4. Only an error modal should render. The choose hosts modal should not render.
:desktop_computer: [Desktop preview](https://boundary-ui-desktop-git-icu-11231-host-modal-r-a2c005-hashicorp.vercel.app/scopes/global/projects/targets)
> fix: 🐛 host modal renders whenever there is an error during connection

- ui/admin/tests/e2e/helpers/boundary-ui.js
- ui/admin/tests/e2e/tests/credential-store-static.spec.js
- ui/admin/tests/e2e/tests/credential-store-vault.spec.js
- ui/admin/tests/e2e/tests/dynamic-host-catalog.spec.js
- ui/admin/tests/e2e/tests/target.spec.js
This PR updates some locators in the Admin UI e2e test suite to get it to pass again. There were 3 areas to update.
1. The "New" link was not getting detected. We needed to update the locator from...
```
await page.getByRole('link', { name: 'New' }).click();
-> 
await page.getByRole('link', { name: 'New', exact: true }).click();
```
2. The "New" button in the top-right was not getting detected. 
```
await page.getByTitle('New', { exact: true }).click();
-> 
await page.getByRole('button', { name: 'New' }).click();
```
3. The Worker Filter textbox was not getting detected (Note: Not sure how I feel about this one...)
```
.getByRole('textbox', { name: 'Filter', exact: true })
-> 
getByRole('textbox', { name: 'Filter\n (Optional)', exact: true })
```
> test(admin/e2e): Fixes for Admin UI test suite

- ui/desktop/app/routes/scopes/scope/projects/targets/target.js
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-11285)
If a user clicks retry when an error occurs during connection, we never reset our error connection flag which will prevent any further host modals from appearing or 
Setup two targets with hosts where one will error out when connecting. Hit retry and try connecting to the other target and the host modal should still appear.
> fix: 🐛 Fix edge case with showing host modal

- addons/rose/addon/styles/hds/overrides.scss
✅ Closes: ICU-11292
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-11292)
There seems to be a bug causing extra whitespace/scrollbars when an accessible class is applied in conjunction with icon only badges in HDS. I'm adding a temporary hack to remove the CSS that's causing it. 
Not sure if this is the best approach, open to other ideas or possibly using rose icons again?
Before:
After:
Create some sessions in desktop client and make the window small enough so the table is larger than the viewport. It should not have two scrollbars with whitespace at the bottom.
> fix: 🐛 Fix an issue with HDS css causing scrollbars/whitespace

- ui/desktop/electron-app/package.json
- ui/desktop/electron-app/src/index.js
- ui/desktop/electron-app/src/utils/fixPath.js
- ui/desktop/electron-app/yarn.lock
It turns out electron does not properly inherit the path variable from process.env.PATH in production. This presents a problem as users won't have access to many of their binaries that they normally would have on their path.
If you're wondering why I didn't use the `fix-path` package directly, it's because they switched over to ESM and we can't directly use it. Their previous version doesn't fix linux so I had to manually use it.
Before:
After:
Create a production build locally and confirm your path gets loaded correctly when opening a shell in boundary.
> fix: 🐛 Fix electron not inheriting path variable in production

- .husky/prepare-commit-msg
- changelog.config.js
Updated commitizen hook to automatically pull the issue and construct a jira URL from it. Also added a config file to remove the breaking changes question in commitizen.
Create a branch that starts with ICU-### to test 
> chore: 🤖 Update commitizen hook to add jira link automatically

- ui/desktop/electron-app/src/index.js
By default electron's security policy blocks all write requests and we need to allow `clipboard-sanitized-write` for the `HDS copy::snippet` copy action to not fail in desktop app
some relevant links [here](https://www.electronjs.org/docs/latest/tutorial/security#5-handle-session-permission-requests-from-remote-content) and [here](https://www.electronjs.org/docs/latest/api/session#sessetpermissionrequesthandlerhandler)
before:
after:
- click the port address copy button. You should not see the red icon and no errors in the logs. 
- the screen should look like the `after` image above to indicate that the copy action is successful.  …
> Fix electron clipboard action

- ui/desktop/app/styles/app.scss
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-11368
We have a bug where brokered credentials overflow currently. Copying still works correctly and doesn't introduce new line breaks.
Before:
After:
Create a target with some brokered credentials that have long secrets and make sure when showing them that they do not overflow.
> fix: 🐛 Fix issue with brokered credentials that overflow

- ui/desktop/app/controllers/scopes/scope/projects/targets/index.js
- ui/desktop/app/routes/scopes/scope/projects/targets/target.js
- ui/desktop/app/templates/scopes/scope/projects/targets/index.hbs
- ui/desktop/tests/acceptance/projects/targets/index-test.js
If a user can connect to a target but not read, we will allow them to connect now.
Connect logic has moved back to the `scopes.scope.projects.targets.index` route and we call the main `connect` method on that route as well from the child route. Connect no longer handles the error states, each route which has unique error handling implements that logic in it's own route. As we move away from `route-actions` all of this logic will likely move to the controllers for each route.
If you have a user (not admin) that you can remove the `read` permission from for targets, you can test this build locally.
> refactor: 💡 allow target connection even with no read ability

- addons/api/addon/handlers/client-daemon-handler.js
- addons/api/app/handlers/client-daemon-handler.js
- addons/api/mirage/scenarios/ipc.js
- ui/desktop/app/services/store.js
- ui/desktop/electron-app/src/ipc/handlers.js
- ui/desktop/electron-app/src/services/client-daemon-manager.js
- ui/desktop/tests/acceptance/authentication-test.js
- ui/desktop/tests/acceptance/cluster-url-test.js
- ui/desktop/tests/acceptance/projects/sessions/index-test.js
- ui/desktop/tests/acceptance/projects/sessions/session-test.js
- ui/desktop/tests/acceptance/projects/targets/index-test.js
- ui/desktop/tests/acceptance/projects/targets/target-test.js
- ui/desktop/tests/acceptance/scopes-test.js
- ui/desktop/tests/helpers/window-mock-ipc.js
- ui/desktop/tests/unit/services/store-test.js
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-11691
Added a handler just to the desktop client to integrate with the client daemon.
Build a binary from the `llb-client-daemon` branch and use that binary in your local dev environment. You can confirm in the DC that we're now not making any requests to the controller in the network tab and see the request logs in the main thread in electron.
> feat: 🎸 Add handler to make search requests to client daemon

- ui/desktop/electron-app/src/config/content-security-policy.js
While Cameron and I were pairing, he noticed the ember reloading script gets blocked by CSP headers. Fixing this enables correctly hot reloading on desktop client again so you don't have to manually refresh the client.
Make a code change in desktop client and it should auto reload.
> fix: 🐛 Fix broken hot reloading for desktop client

- ui/desktop/package.json
- yarn.lock
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-11736)
Upgrade playwright within desktop as blocker to run node 18 within gh runners
- Deploy `enos`. Run the e2e test suite BEFORE the changes successfully.
- Perform playwright upgrade.
- Run e2e test suite AFTER the changes successfully.
This upgrade was need because the `playwright` version within `ui/desktop` was old and not compliance with node 18, therefore the gh self-hosted runner was failing to run `boundary-ui-release` CI.
As a test this upgrade fixes the issue, we run a `boundary-ui-release` with node 18 using the `boundary-ui` branch `1.2.3-beta.playwright.upgrade` (which is a copy of `chore-ICU-11736-upgrade-playwright-desktop`) successfully, [here the …
> Upgrade playwright within desktop

- addons/api/addon/adapters/application.js
- addons/api/addon/serializers/application.js
- ui/admin/app/routes/scopes/scope/targets.js
- ui/admin/app/routes/scopes/scope/users.js
- ui/admin/tests/acceptance/authentication-test.js
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-11688)
Backend introduced pagination for all resources, and they have a default page_size of 1000, which means if there are more than 1k resources, the UI will not get the full list unless we pass in the `refresh_token` of the current result list. 
The goal of this PR is to simply return the full result set from the API
[Note: you need to run the `llb/pagination` to test this]
- Add 4 targets, and in the routes/target set a page_size of 1(this is to mock the API default page_size limit). You should still see all 4 on the UI 
- ~[] I have added before and after screenshots for UI changes~
- ~[ ] I have added steps to …
> chore: 🤖 Add support for pagination in query method

- ui/desktop/package.json
- yarn.lock
[bug] - after updating `desktop` UI to Ember 4.12.2, the `yarn start:desktop` build process was erroring out with a reference to the `instantiate Watcher with (await Watcher.build()).watcher, not new Watcher()` error message.  After searching we found out that between Ember 4.4.1 and 4.12.2 they changed the way builds were imported in ember-cli.
https://github.com/ember-cli/ember-cli/blob/master/lib/models/watcher.js
[fix] - upgrade `ember-electron` to 4.12.2 to match the Watcher API
https://github.com/adopted-ember-addons/ember-electron/blob/main/lib/tasks/electron.js
- [] cd into `ui/desktop' and run `yarn start:desktop` against Mirage or use `ENABLE_MRAG=false yarn start:desktop, if you have a `boundary dev` instance running
- desktop app should start up as normal
~~- [ ] I have added …
> fix: 🐛 Desktop yarn start:desktop build fix

- addons/api/addon/adapters/application.js
- addons/api/tests/dummy/app/routes/application.js
- addons/api/tests/unit/adapters/application-test.js
- addons/api/tests/unit/models/scope-test.js
- ui/admin/app/routes/scopes.js
- ui/desktop/app/routes/scopes.js
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-11825)
Refactor `store.findAll` to use `store.query`. Most list endpoints use store.query to retrieve `items` array. The only resources that use `findAll` are scopes. Scopes resource is also paginated so instead of modifying the adapter findAll method to handle pagination we decided to remove it and use query instead. The reason is that findAll is being deprecated by Ember v5. 
Initiate a boundary dev instance using the `llb-list-pagination` branch and make sure no new errors or warnings are generated. 
- ~[ ] I have …
> Icu 11825 replace `store.findAll` method with `store.query`

- ui/desktop/app/components/session/tabs/index.js
- ui/desktop/electron-app/src/ipc/handlers.js
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-11474)
Add custom key handler only for Windows OS so we achieve Ctrl+C to copy within the embedded terminal.
Used `attachCustomKeyEventHandler` from xterm.js. Info [here](https://github.com/xtermjs/xterm.js/blob/4375b3cdb9e36cd2746ff9a101fbeb48f7d0b794/typings/xterm.d.ts#L473-L482) and [here](https://xtermjs.org/docs/guides/hooks/)
Selecting text + (ctrl+c):
Ctrl+v:
- Run desktop client within windows machine.
- Stablish an ssh or tcp session with a target.
- Go to the shell tab and: select text + (ctrl+c) + (ctrl+v).
- Expected result: the selected text is pasted on the terminal.
- ~~[ ] My changes generate no new warnings~~
> chore: 🤖 Add custom key handler for windows

- addons/rose/app/styles/rose/components/_message.scss
- addons/rose/app/styles/rose/components/dialog/_dialog.scss
- addons/rose/app/styles/rose/components/header/_index.scss
- addons/rose/app/styles/rose/components/header/_nav.scss
- addons/rose/app/styles/rose/components/layout/_body-content.scss
- addons/rose/app/styles/rose/components/layout/_page.scss
- addons/rose/app/styles/rose/components/layout/_sidebar.scss
- addons/rose/package.json
- ui/admin/app/styles/_notify.scss
- ui/admin/app/styles/app.scss
- ui/admin/package.json
- ui/desktop/app/styles/_notify.scss
- ui/desktop/app/styles/app.scss
- ui/desktop/package.json
- yarn.lock
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-11818
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-11818)
- Updated `styelint-config-standard-scss` to fix incorrect peer dependency warning for `styelint`
- Upgrading to `11.0.0`  introduced a new rule for writing media ranges for media queries.  Instead of using `prefix` style  notation(`max-width: 668px`), the new configuration wants us to use `context` style notation(`width <= 668px`)
- Tested the new style of notation by adding a white background to the `.ember-notify-cn` attribute and it works as expected.
https://github.com/hashicorp/boundary-ui/assets/24277002/cf035cd6-cbc4-4759-a9cb-6cd3f2d8454c
https://github.com/hashicorp/boundary-ui/assets/24277002/df11308e-e256-4889-8413-b3f45ca4736a
:technologist: …
> chore: 🤖 Update stylelint config dependency

- ui/desktop/app/controllers/scopes/scope/projects/targets/index.js
- ui/desktop/tests/acceptance/projects/sessions/session-test.js
This fixes the issue mentioned within [this slack thread](https://hashicorp.slack.com/archives/C012GTH1C4E/p1701384535719469?thread_ts=1701372005.384369&cid=C012GTH1C4E).
The test checks that a user with NO permission to read a session, but with permission to connect can establish a connection to the target, then been redirect succesfully to Session detail page. Regardless the permissions, the user expect a minimum information on the session detail page.
Behaviour:
- User clicks connect to a specific target.
- When the user stablish the connection, we read important information of the session and aggregate that to the session store.
- Once the connection is stablished, user gets redirected to the session page.
- Because the user can not read the session, relies only on the important …
> fix: 🐛 Fix add expiration_time when user has no grants to read

- addons/api/addon/handlers/client-daemon-handler.js
- ui/desktop/app/services/store.js
- ui/desktop/tests/acceptance/authentication-test.js
- ui/desktop/tests/acceptance/cluster-url-test.js
- ui/desktop/tests/acceptance/projects/sessions/index-test.js
- ui/desktop/tests/acceptance/projects/sessions/session-test.js
- ui/desktop/tests/acceptance/projects/targets/index-test.js
- ui/desktop/tests/acceptance/projects/targets/target-test.js
- ui/desktop/tests/acceptance/scopes-test.js
This refactors the client daemon handler to be a native class instead of just a simple function that is bound with the store's context. It turns out the handlers can take any object that just has a `request` function on it. This enables us to move the services to the class and have the directly injected with ember aware of their usage.
This fixes the issue where tests would error out when we try to use any service from within the handler (e.g. the IPC invoke methods) even when we try to mock the service out. This enables us to be able to properly mock out the client daemon searching. 
- …
> refactor: 💡 Use a native class for the client daemon handler

- ui/desktop/electron-app/src/services/client-daemon-manager.js
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-11932
This PR is to handle the scenario where the client daemon was already running when the desktop client is started. We don't want to stop the client daemon if we the desktop client wasn't the one to start up the client daemon.
Start the daemon before running the DC and then close the desktop client. Confirm that the daemon is still running. Likewise, if the daemon wasn't started beforehand, confirm that the daemon is stopped once the DC is closed.
> feat: 🎸 Do not stop client daemon if it was already started

- yarn.lock
Upgrade `caniuse-list`as suggested on terminal warning when running tests.
Run `npx update-browserslistdb@latest` as suggested to upgrade.
Run Admin or desktop tests without seeing warning on terminal about `caniuse-list` or `browserslist` being outdated.
- ~~[ ] I have added before and after screenshots for UI changes~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
> chore: 🤖 Upgrade browserslist

- addons/api/addon/utils/mqlQuery.js
Forgot to add support for not equals as part of our MQL filter expressions.
> fix: 🐛 Add support for not equals in MQL expression parsing

- ui/admin/tests/e2e/global-setup.js
- ui/admin/tests/e2e/helpers/boundary-ui.js
- ui/admin/tests/e2e/tests/credential-store-static.spec.js
- ui/admin/tests/e2e/tests/credential-store-vault.spec.js
- ui/admin/tests/e2e/tests/dynamic-host-catalog.spec.js
- ui/admin/tests/e2e/tests/login.spec.js
This PR updates some Admin UI e2e tests to account for some changes in 0.14.3
1. The introduction of  the `Show Password` button resulted in a conflict with how we were finding the Password textbox. 
2. The breadcrumbs used to be links for all elements, but it seems like the currently active page is no longer a link (In this example, the project name/id is no longer a link)
> test(admin/e2e): Update tests to account for changes in 0.14.3

- addons/api/mirage/scenarios/ipc.js
- ui/desktop/app/controllers/scopes/scope/projects/targets/index.js
- ui/desktop/app/styles/app.scss
- ui/desktop/app/templates/scopes/scope/projects/sessions/session.hbs
- ui/desktop/tests/acceptance/projects/sessions/session-test.js
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-10487
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-10487)
- Implement `time-remainig` helper to display duration of a session for desktop app.
-  Moved the header elements into a `div` to enforce current styling for items.
- 
https://github.com/hashicorp/boundary-ui/assets/24277002/78ca5ffd-f8a9-4ee3-8177-e98852662d3e
---
---
---
- `id=*;type=session;actions=list,cancel:self`
- `id=*;type=target;actions=list,authorize-session`
---
~~- [ ] I have added tests that prove my fix is effective or that …
> feat: 🎸 Implement time-remaining helper into desktop UI

- addons/api/addon-test-support/handlers/client-daemon-search.js
- addons/api/addon/handlers/client-daemon-handler.js
- addons/rose/addon/components/rose/pagination/index.hbs
- addons/rose/addon/components/rose/pagination/index.js
- addons/rose/app/components/rose/pagination.js
- ui/desktop/app/controllers/scopes/scope/projects/targets/index.js
- ui/desktop/app/routes/scopes/scope/projects/sessions.js
- ui/desktop/app/routes/scopes/scope/projects/targets/index.js
- ui/desktop/app/styles/app.scss
- ui/desktop/app/templates/scopes/scope/projects/targets/index.hbs
- ui/desktop/electron-app/src/ipc/handlers.js
- ui/desktop/tests/acceptance/projects/sessions/index-test.js
- ui/desktop/tests/acceptance/projects/sessions/session-test.js
- ui/desktop/tests/acceptance/projects/targets/index-test.js
- ui/desktop/tests/acceptance/projects/targets/target-test.js
- ui/desktop/tests/acceptance/scopes-test.js
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-11905
This adds the pagination component for targets in the desktop client. I created a thin wrapper around the HDS pagination so for the `paginationQueryParams` as it should be the same for every usage we have.
Still working on having a test harness for our client daemon now.
https://github.com/hashicorp/boundary-ui/assets/5783847/6749bb35-097b-4716-a938-811ad36dcf20
> feat: 🎸 Add pagination component to targets

- ui/admin/app/routes/scopes/scope/targets/target/add-brokered-credential-sources.js
- ui/admin/app/routes/scopes/scope/targets/target/add-injected-application-credential-sources.js
https://hashicorp.atlassian.net/browse/ICU-12046
This PR fixes the error caused when the `add/remove credential sources` process was repeated.
Note: When we `return` within the `await.all`, the peekAll method on L53& L54 adds duplicate stale IDs from the previous iteration with no `type`, causing the error. 
Add an injected credential source to a target
Remove the credential source from the target
Repeat 1-2 more times
you should not see any error
- ~[ ] I have added tests that prove my fix …
> fix: 🐛 target cred sources association

- ui/desktop/app/controllers/scopes/scope/projects/targets/index.js
- ui/desktop/tests/acceptance/projects/targets/target-test.js
Some tests starting to fail after rebasing onto main. The root cause of the issue is a recent PR added some calls to get sessions in the targets route which adds them to the store so the following call to retrieve the session is returning cached data from the store (which for some reason didn't have expiration_time).
Some of the stubbed client daemon calls were also not being setup correctly as they were returning target data for session calls. 
> fix: 🐛 Fix failing tests from rebase onto main

- ui/desktop/app/controllers/scopes/scope/projects/targets/index.js
- ui/desktop/app/routes/scopes/scope/projects/targets/index.js
- ui/desktop/app/templates/scopes/scope/projects/targets/index.hbs
Changed when we retrieve targets so it's only when the user first enters the route. This may need to change in the future but for now it helps greatly with loading times. Ideally, we'd lazy load all the targets when needed which we can evaluate in the future. 
Also fixed a bug where the search box for targets didn't show the value if you changed routes and came back. 
Before:
After:
You can see the extra call adds about ~1s to searching/filtering.
Setup the search daemon with 20 to 30k targets and see the performance of searching or filtering.
- ~[ ] I have added tests that …
> refactor: 💡 Optimize the retrieval of targets for scopes filter

- ui/admin/app/templates/scopes/scope/host-catalogs/host-catalog/hosts/index.hbs
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-11729
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-11729)
- Migrate `host-catalog/host-list` to use `Hds::Table`
---
---
:technologist: [Admin preview](https://boundary-ui-git-icu-11729-admin-ui-use-hds-tab-8dfcb2-hashicorp.vercel.app/)
> refactor: 💡 Migrate `host-catalog/host-list` to use `Hds`

- addons/api/addon-test-support/handlers/client-daemon-search.js
This PR fixes two issues in tests:
1. We weren't properly serializing the data (using our mirage serializers to rename some properties to snake case and serializing the scope object)
2. We were returning the data raw which includes any JS objects such as date objects. We need to return this data as standard JSON so our ember data can properly normalize the data it receives.
> fix: 🐛 Fix returning mirage data from client daemon mock

- addons/api/addon-test-support/handlers/client-daemon-search.js
- addons/api/addon/utils/mqlQuery.js
- addons/core/translations/resources/en-us.yaml
- ui/desktop/app/controllers/scopes/scope/projects/targets/index.js
- ui/desktop/app/routes/scopes/scope/projects/targets/index.js
- ui/desktop/app/templates/scopes/scope/projects/targets/index.hbs
- ui/desktop/tests/acceptance/projects/targets/index-test.js
- ui/desktop/tests/acceptance/projects/targets/target-test.js
- ui/desktop/tests/acceptance/scopes-test.js
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-11803
Added active sessions filter. I had to modify how we generate the MQL queries as I realized I need the filter's to be `AND`ed together when searching for no active sessions as I needed the inverse logic.
Note there's currently a bug when searching with filters and search text, see this [thread](https://hashicorp.slack.com/archives/C05DR8P3N5T/p1702921157577639)
With no results, no search text, and active filter:
With no results, search text, and active filter:
https://github.com/hashicorp/boundary-ui/assets/5783847/59457635-474e-49aa-8617-342e087a8790
- ~[ ] I have added tests that prove my …
> feat: 🎸 Add active session filter

- ui/desktop/app/controllers/scopes/scope/projects/sessions/index.js
- ui/desktop/app/controllers/scopes/scope/projects/targets/index.js
- ui/desktop/app/routes/scopes/scope/projects/targets/index.js
- ui/desktop/app/templates/scopes/scope/projects/sessions/index.hbs
- ui/desktop/app/templates/scopes/scope/projects/targets/index.hbs
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-11804)
Add type filter to targets list view page
Add filter tags component to sessions list view page
Refactor `showFilters` getter for targets so that filters don't disappear when no filtered results are returned.
1. Use llb-pagination-2 be branch and start boundary dev
2. Copy newly made binary into ui/desktop/electron-app/cli
3. Checkout this branch and run ENABLE_MIRAGE=false BYPASS_CLI_SETUP=true yarn start:desktop
> Icu 11804 filter targets by type

- ui/admin/app/templates/scopes/scope/credential-stores/credential-store/credentials/index.hbs
- ui/admin/tests/acceptance/credential-store/credentials/list-test.js
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-11725
- Migrate `credentials-list` to `Hds::Table`
- Migrated `Copyable` components to `Hds::Copy::Snippet` component
- Migrated `p` and unwrapped elements with `Hds::Text` component
- Could not use the `.data` key to access `@model` for credentials because the model is being returned as a `Proxy(Array)`
---
--- 
:technologist: [Admin preview](https://boundary-ui-git-icu-11725-admin-ui-use-hds-tab-e7a4c8-hashicorp.vercel.app/)
> refactor: 💡 Migrate `credentials-list` to `Hds::Table`

- ui/desktop/app/controllers/scopes/scope/projects/targets/index.js
The type filter wasn't showing the correct status when no results were returned.
Before:
After:
Filter using types with no results.
> fix: 🐛 Fix display of no results from type filter

- .github/labeler.yml
- .github/workflows/labeler.yml
The github [labeler](https://github.com/actions/labeler) broke when upgrading to v5 from the [automated](https://github.com/hashicorp/boundary-ui/pull/2065) workflow pin upgrade.
The check for labeler in this PR will still fail as it's using the workflow and config file from `main`
> chore: 🤖 Fix breaking change in labeler when upgrading to v5

- addons/core/addon/styles/addon.scss
- addons/core/translations/states/en-us.yaml
- ui/desktop/app/routes/application.js
- ui/desktop/app/routes/scopes/scope/projects/sessions/index.js
- ui/desktop/app/routes/scopes/scope/projects/targets/index.js
- ui/desktop/app/styles/app.scss
- ui/desktop/app/templates/scopes/scope/projects/sessions.hbs
- ui/desktop/app/templates/scopes/scope/projects/sessions/index.hbs
- ui/desktop/app/templates/scopes/scope/projects/sessions/loading.hbs
- ui/desktop/app/templates/scopes/scope/projects/targets.hbs
- ui/desktop/app/templates/scopes/scope/projects/targets/index.hbs
- ui/desktop/app/templates/scopes/scope/projects/targets/loading.hbs
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-12025
Added loading indicators for the initial long loads coming from the client daemon. Originally, I was thinking I would have to poll and check the status of the daemon to know if we got any results back since normally the daemon returns cached results immediately but calling with `force_refresh` is blocking and waits enough time to get all the results back.
https://github.com/hashicorp/boundary-ui/assets/5783847/299bbbde-fc13-4c4f-bc5f-55e7d6279560
Use a binary with a client daemon and add at least 10k targets. You should be able to see a load time that's noticeable now. 
- ~[ ] I have added …
> feat: 🎸 Add loading indicators for initial loads of resources

- ui/admin/app/templates/scopes/scope/credential-stores/credential-store/credential-libraries/index.hbs
- ui/admin/tests/acceptance/credential-library/read-test.js
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-11724
- Migrate `credential-libraries-list` to `Hds::Table` instead of `Rose::Table`
- Migrated Copyable components to Hds::Copy::Snippet component
- Migrated p and unwrapped elements with Hds::Text component
--- 
--- 
- Click on Vercel link for Admin UI or pull down PR and run it locally using `yarn start`
- Click on any "Orgs" card created by mirage
- Click on any "Projects" card created by mirage and "Host Catalogs" will appear in the sidebar navigation.
- Click on "Credential Stores" in the sidebar navigation.
- Click on any credential store from list.
- Navigate to "Credential Libraries" via tab and view list.
- Ensure clicking on a `credential …
> refactor: 💡 Migrate `credential-libraries-list` to `Hds::Table`

- ui/admin/app/components/form/worker/create-worker-led/index.hbs
- ui/admin/app/components/form/worker/create-worker-led/index.js
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-11722
- Migrate `workers-tags` in `worker-create` form to use  `Form::Field::ListWrapper` instead of `Rose::Table`
- Now that we are using the `Form::Field::ListWrapper` we can pass the `worker_tags` object directly into the options for table, which tracks the `newOptionKey` and `newOptionValue`.  We removed the tracked properties for `newKeyWorker` and `newValueWorker`
- Refactored the `addWorkerTag` method .
- 
--- 
---
https://github.com/hashicorp/boundary-ui/assets/24277002/32d4b39e-4c9e-4c9d-b578-277c1d26d604
- Click on Vercel link for Admin UI or pull down PR and run it locally using `yarn start`
- Click on "Workers" in the sidebar navigation.
- …
> refactor: 💡 Migrate `workers-tags` over to use `Hds::Table`

- ui/desktop/app/routes/scopes/scope/projects/sessions/index.js
- ui/desktop/app/routes/scopes/scope/projects/targets/index.js
- ui/desktop/app/templates/scopes/scope/projects/sessions/index.hbs
- ui/desktop/app/templates/scopes/scope/projects/targets/index.hbs
- ui/desktop/tests/acceptance/projects/sessions/index-test.js
- ui/desktop/tests/acceptance/projects/targets/index-test.js
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-12205
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-12205)
If a user selects an org it will now only show targets that belong to that org scope.
https://github.com/hashicorp/boundary-ui/assets/29386339/e09445a0-f280-41af-a5a8-4b6240502ebf
Run `ENABLE_MIRAGE=false BYPASS_CLI_SETUP=true yarn start:desktop` to run against a local binary built off the main branch of the boundary repo. Create a second org with a project and target for listing purposes. After loading all targets when logging in from the global scope, select the second org in the header of the desktop client. The targets listed should only belong to the org you selected from the header of the desktop client.
> feat: 🎸 target list will update according to org scope selected

- addons/api/addon/handlers/client-daemon-handler.js
- ui/desktop/app/routes/scopes/scope/projects/sessions/index.js
- ui/desktop/app/routes/scopes/scope/projects/targets/index.js
- ui/desktop/app/templates/scopes/scope/projects/sessions/index.hbs
- ui/desktop/app/templates/scopes/scope/projects/targets/index.hbs
- ui/desktop/electron-app/src/ipc/handlers.js
- ui/desktop/tests/acceptance/projects/sessions/index-test.js
- ui/desktop/tests/acceptance/projects/targets/index-test.js
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-12026
Added a fallback to handle the scenario where the client daemon errors out or is down. We will just retrieve everything for _each_ call (which is crazy inefficient but fine as long as it doesn't crash our application). If the daemon is down, I also prevent showing the filters/searching since that can't be done anymore. That can be removed if we add a fallback to the indexed db solution in the future. 
It's actually still quite usable as long as there aren't tens of thousands of resources.
https://github.com/hashicorp/boundary-ui/assets/5783847/78147a08-d378-4968-a670-5293f324c3a2
Start up the desktop client and then kill the client daemon while the DC is still running by running `boundary daemon stop`
- ~[ ] I have added JSON …
> feat: 🎸 Add fallback if client daemon is down or errors

- addons/core/addon/components/filter-tags/index.js
- addons/core/tests/integration/components/filter-tags/index-test.js
- ui/desktop/app/controllers/scopes/scope/projects/sessions/index.js
- ui/desktop/app/controllers/scopes/scope/projects/targets/index.js
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-12137)
Default queryParam values are [pruned](https://github.com/emberjs/ember.js/blob/v5.5.0/packages/%40ember/routing/router.ts#L1032) when a transition from one route to another is made. Therefore, the RouteInfo object for the current route doesn't show the existing default queryParams. In order to work around not being able to access default query param values through the router service, we pass in the filters as an object named `selectedFilters`.
https://github.com/hashicorp/boundary-ui/assets/107949262/cc3cefb8-e243-47b2-869d-c3440481846d
1. Use llb-pagination-2 be branch and start boundary dev
2. Copy newly made binary into ui/desktop/electron-app/cli
3. Checkout this branch and run ENABLE_MIRAGE=false …
> Icu 12137 add additional session sorting and add default filters

- addons/core/translations/resources/en-us.yaml
- ui/admin/app/components/form/policy/index.js
- ui/admin/app/components/form/policy/policy-selection/index.js
- ui/admin/app/templates/scopes/scope/policies/policy/index.hbs
this pr adds more options to the retention policy based on this [thread](https://hashicorp.slack.com/archives/C012GTH1C4E/p1705001194264479?thread_ts=1704997089.212949&cid=C012GTH1C4E)
> Add more options retain

- ui/admin/app/components/form/policy/policy-selection/index.hbs
- ui/admin/app/styles/app.scss
overridable toggle should be visible for all options in the select list
before: 
after:
> chore: 🤖 move overridable next to select

- addons/api/addon/handlers/client-daemon-handler.js
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-12301
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-12301)
When queries are being passed to the controller, we were sending through `scope_id` and `recursive` but realized that there is also a `filter` query param that should be getting passed to the controller as well. Now we will remove client daemon related params and sending the `remainingQuery` to the controller. See attached images below that show the `type` filter that was not being applied to the `v1/scopes` request to fetch all projects under a specific org scope.
To test this, start a `boundary dev` instance and start the desktop client. Verify in the network request that one of the `v1/scopes` requests has `filter: ("/item/type" == "project")` as one of …
> fix: 🐛 remove client daemon params and pass remaining params

- addons/core/translations/resources/en-us.yaml
- ui/admin/app/components/form/policy/index.js
- ui/admin/app/components/form/policy/policy-selection/index.hbs
- ui/admin/app/components/form/policy/policy-selection/index.js
- ui/admin/app/components/form/scope/add-storage-policy/create.hbs
- ui/admin/app/routes/scopes.js
- ui/admin/app/routes/scopes/scope/add-storage-policy/create.js
- ui/admin/app/styles/app.scss
- ui/admin/app/templates/scopes/scope/add-storage-policy/create.hbs
- ui/admin/app/templates/scopes/scope/edit.hbs
- ui/admin/app/templates/scopes/scope/policies/index.hbs
- ui/admin/app/templates/scopes/scope/policies/policy/index.hbs
- ui/admin/tests/acceptance/policy/create-test.js
- ui/admin/tests/acceptance/policy/delete-test.js
- ui/admin/tests/acceptance/policy/update-test.js
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-12299)
This PR fixes a few things
- UI behavior when the user clears the custom text input
- some minor card updates
- disabled overridable based on a recent API update
- use a current scope while creating a policy within scope settings
https://github.com/hashicorp/boundary-ui/assets/15043878/046bf3ac-ed8e-4913-9c80-5984a3d21837
- create storage policy using staged binary ent
> fix: 🐛 policy UI bug fix

- ui/desktop/electron-app/src/helpers/request-promise.js
Client daemon errors weren't correctly getting propagated up to the desktop client which meant they were getting interpreted as search results and erroring out.
A quick way is to start the desktop client, then stop the client daemon and restart it. The DC should now be getting `403` responses from the daemon and it shouldn't error out.
> fix: 🐛 Fix errors not getting propagated up from client daemon

- ui/desktop/electron-app/src/helpers/app-updater.js
- ui/desktop/electron-app/src/index.js
Added a warning when upgrading to the newest version since it's a breaking change. 
Build the normal desktop client and it should prompt to upgrade with the warning. 
> feat: 🎸 Add warning when upgrading to 2.0 for desktop client

- addons/api/addon/generated/models/session-recording.js
- addons/core/translations/resources/en-us.yaml
- ui/admin/app/routes/scopes/scope/add-storage-policy/index.js
This PR fixes a bug where the old value was retained when the field becomes null/zero from the API, this is due to ember-data not updating the old value if the field was removed from the API, so we explicitly set these `readonly` fields to null. For more context - check [this](https://github.com/hashicorp/boundary-ui/blob/3f4beaada88d62a813a45c978e42ae3e10504b9c/addons/api/addon/serializers/application.js#L302)
And also https://hashicorp.atlassian.net/browse/ICU-12323
1. run ENT staged binary, 
2. and create a few org and global policies, 
3. you should be able to see both global and org at org setting 
4. only global policies at the global scope
- ~[ ] I have added before and after …
> fix: 🐛 delete and retain_until should be readonly and Scope level policies

- ui/desktop/app/templates/scopes/scope/projects/sessions/index.hbs
Update sessions table to match new designs
Before:
After:
You can use the vercel link to verify that sessions no longer have the `entry-point` icon.
:desktop_computer: [Desktop preview](https://boundary-ui-desktop-git-update-sessions-table-hashicorp.vercel.app/scopes/global/projects/sessions)
> refactor: 💡 remove icon from sessions table for session id

- ui/admin/app/routes/scopes/scope/session-recordings/session-recording/channels-by-connection.js
- ui/admin/app/templates/scopes/scope/session-recordings/session-recording/channels-by-connection/index.hbs
This PR updates the label on the session recording page when it is a forever retention period and updates the translation check based on end_time instead of state to identify the error states correctly. 
1. go to a recording using enterprise build  
2. click on reapply at completed/recording/error status, you should see the appropriate translated message on success. 
> chore: 🤖 translation check and label

- ui/admin/app/routes/scopes/scope/storage-buckets/storage-bucket.js
- ui/admin/tests/acceptance/storage-buckets/create-test.js
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-12402
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-12404
https://github.com/hashicorp/boundary-ui/assets/107949262/68597391-900e-4d25-b409-7f5b943d6ac5
1. Run `boundary dev` on the latest ent binary
2. Create a storage bucket with an org scope successfully.
> fix: 🐛 fix transition aborted error on storage bucket creation

- ui/desktop/electron-app/src/services/client-daemon-manager.js
This [PR](https://github.com/hashicorp/boundary/pull/4312) added the `-addr` flag to the `boundary daemon add-token` command which allows us to pass it in via a flag and not set it as an env variable.
> refactor: 💡 add -addr flag to add-token command

- addons/api/mirage/factories/role.js
- ui/admin/app/routes/onboarding.js
- ui/admin/tests/acceptance/roles/grants-test.js
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-12412
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-12412)
update id to ids for target onboarding creation
https://github.com/hashicorp/boundary-ui/assets/29386339/12edefca-e0ee-4300-9e32-83b96dfca553
Start a `boundary dev` instance and delete the org scope; this will remove all resources. Navigate back to the global scope and you will enter the onboarding workflow. Enter the target address and port, click Save followed by Done and a target will be created for you. Navigate back to that project level and view the `SecOps` org role named `test_target_role`. View the grants on that role and it should now say `ids=ttcp_xxx`.
> fix: 🐛 update id to ids for target onboarding creation

- addons/api/mirage/config.js
- ui/desktop/app/routes/scopes.js
- ui/desktop/tests/acceptance/scopes-test.js
update how we determine is pagination is supported
Start a `boundary dev` instance and remove the Generated Org. This will remove all scopes but global. The user should still be able to log in to the desktop client and will see a "no targets|sessions" message. It should not error out or display the unsupported controller modal.
> refactor: 💡 update how we determine is pagination is supported

- addons/core/addon/styles/addon.scss
- addons/rose/app/styles/rose/components/toolbar/_info.scss
- ui/desktop/app/routes/scopes/scope/projects/sessions/index.js
- ui/desktop/app/routes/scopes/scope/projects/targets/index.js
- ui/desktop/app/templates/scopes/scope/projects/sessions/index.hbs
- ui/desktop/app/templates/scopes/scope/projects/targets/index.hbs
- ui/desktop/tests/acceptance/projects/sessions/index-test.js
Add refresh back with some optimizations for how we handle retrieving all targets/sessions. I removed the transition check so we don't ever reload all targets or sessions if it's been previously loaded even if we switch between routes to help improve performance a bit. Now that the user can manually refresh, it's not needed and they can force the refresh.
Start up the DC and add some scopes and sessions while the DC is running. Manually refresh and they should now be in the table and filters.
> fix: 🐛 Add refresh button back

- addons/rose/package.json
- yarn.lock
This PR updates HDS to the latest version:
- `@hashicorp/design-system-components` to ~~`3.4.1`~~ `3.5.0`
- `@hashicorp/ember-flight-icons` to ~~`4.0.5`~~ `4.0.6`
The motivation behind this PR (aside from keeping up to date) is to follow up on https://github.com/hashicorp/boundary-ui/pull/2020#discussion_r1412315581 where a limitation in the `CodeBlock` component didn't allow for the content to be dynamically changed. After this gets merged it will raise a PR to replace the remaining `Rose::CodeEditor` instance in `ui/admin/app/components/form/worker/create-worker-led/index.hbs`
[Release notes](https://helios.hashicorp.design/whats-new/release-notes#350)
> chore: 🤖 update HDS to 3.5.0

- addons/core/translations/resources/en-us.yaml
- ui/admin/app/components/form/worker/create-worker-led/index.hbs
- ui/admin/app/styles/app.scss
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/HDS-2827)
Follow-up on https://github.com/hashicorp/boundary-ui/pull/2020#discussion_r1412315581. 
We replace the `Rose::CodeEditor` instances with `Hds::CodeBlock` on the new worker page. In the previous attempt, we discovered an issue where the `Hds::CodeBlock` crashed when the associated content was dynamically updated.
While at it, I updated the inline code style in the instructions for creating a worker. This is only a suggestion, so if you'd like to address it separately I can drop the last commit.
<table>
<tr><th>Before</th><th>After</th></tr>
<tr><td>
</td><td>
</td></tr>
<tr><td>
</td><td>
</td></tr>
</table>
- go to `/scopes/global/workers/new`
- check the instructions are correct and the code block renders as …
> chore: 🤖 replace `Rose::CodeEditor` with `Hds::CodeBlock` on new worker page

- addons/core/translations/form/en-us.yaml
- ui/admin/app/components/form/worker/index.hbs
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-12409
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-12409)
remove Type of Worker from worker details page
Before:
After:
Click on the Admin preview and navigate to the workers tab and click into a worker. There should be no `Type of Worker` field.
:technologist: [Admin preview](https://boundary-ui-git-icu-12409-remove-field-worker-f592c8-hashicorp.vercel.app/scopes/global/workers/w_rx3btr6y2a)
> feat: 🎸 remove Type of Worker from worker details page

- ui/admin/app/routes/scopes/scope/authenticate.js
- ui/admin/app/templates/scopes/scope/authenticate.hbs
- ui/admin/tests/acceptance/authentication-test.js
- ui/desktop/app/routes/scopes/scope/authenticate.js
- ui/desktop/app/templates/scopes/scope/authenticate.hbs
- ui/desktop/tests/acceptance/authentication-test.js
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-2355
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-2355)
Before:
After:
Start a `boundary dev` instance and start the desktop client with the cluster URL pointing to `http://localhost:9200`. The only scope you should see in the dropdown is `Global` as the generated org will have no auth methods by default.
> refactor: 💡 only show scopes with auth methods at authenticate

- ui/desktop/electron-app/src/services/client-daemon-manager.js
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-12557)
Fix for this issue: https://github.com/hashicorp/boundary-ui/issues/2130
Before: 
After (tested in native windows env not in utm):
https://github.com/hashicorp/boundary-ui/assets/107949262/f22c6eec-54e6-46f7-aa8e-787275651962
Ideally test in windows env, if not pull this change and remove isWindows() check.
1. start boundary 0.15.0 instance
2. run cmd `BYPASS_CLI_SETUP=true ENABLE_MIRAGE=false yarn start:desktop`
3. check that sessions appear immediately after connecting.
> Icu 12557 refresh not working as intended on windows

- ui/admin/app/components/form/credential/json/index.hbs
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-9427
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-9427)
- Migrate last `form.fieldset` for `json` type over to use `Hds::FormFieldset`
---
---
- Click on Vercel link for Admin UI or pull down PR and run it locally using yarn start
- Click on "Credential Stores" in sidebar navigation.
- Click on a "static" store from the list.
- Use the "Manage" dropdown on view to create a new "credential"
- Click on the "JSON" card and ensure that the secret field exists and is functional.
- Click on the "credentials" tab on the single static store view and click on your newly created JSON credential to view details.
~~- [ ] …
> refactor: 💡 Migrate last `form.fieldset` over to use Hds

- addons/api/mirage/config.js
- ui/admin/tests/acceptance/credential-library/update-test.js
This PR fixes the mock data when a vault credential library is updated with mapping_overrides
1. go to credential-library->vault
2. edit an existing vault credential library and include mapping override attributes
3. click save
4. the form should reflect only the attributes you added in the above steps 
> Fix credential library mocks

- ui/admin/tests/e2e/helpers/boundary-ui.js
- ui/admin/tests/e2e/tests/fixtures/ssh-certificate-injection-role.json
- ui/admin/tests/e2e/tests/fixtures/ssh-policy.hcl
- ui/admin/tests/e2e/tests/ssh-certificate-injection-vault-ent.spec.js
- ui/admin/tests/e2e/tests/ssh-credential-injection-vault-ent.spec.js
This PR adds an Admin UI e2e test for validating the setup for [SSH certification injection](https://developer.hashicorp.com/boundary/tutorials/credential-management/hcp-certificate-injection)
> test(e2e): Add test for SSH certification injection

- ui/desktop/electron-app/src/helpers/app-updater.js
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-12878
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-12878)
Our update process in the desktop client was running into conflicts with our ASAR changes we made for the `1.7.0` release. The autoUpdater workflow was trying to store update specific data in a directory that no longer exist. We changed the destination for the update specific data and the workflow is no longer erroring out. We also moved the destination logic inside the try catch so we can catch the error if one is thrown.
To properly test this, you will need a signed build of the desktop client. AutoUpdater will not work without it. Please use a signed artifact from this [build](https://github.com/hashicorp/boundary-ui-releases/actions/runs/8255809808) to …
> fix: 🐛 update destination path for autoUpdater workflow

- ui/admin/tests/e2e/playwright.config.js
- ui/admin/tests/e2e/tests/credential-store-vault.spec.js
This PR addresses 2 issues in the Admin UI test suite
- The timeout for each test was bumped from 60s to 90s. It was observed that one of the tests (deleting resources) was sometimes taking longer than the current timeout and failing.
- Adds a missing import to a test
> test(e2e): Admin UI test fixes

- ui/admin/tests/e2e/helpers/boundary-cli.js
- ui/admin/tests/e2e/helpers/boundary-ui.js
- ui/admin/tests/e2e/tests/session-recording-ent.spec.js
- ui/admin/tests/e2e/tests/ssh-credential-injection-vault-ent.spec.js
- ui/admin/tests/e2e/tests/target-ent.spec.js
✅ Closes: ICU-12883
:tickets: [ICU-12883](https://hashicorp.atlassian.net/browse/ICU-12883)
This PR adds an e2e-test for storage policies. The test scenario is the following:
- Create Storage Bucket
- Create SSH Target
- Enable session recording for the Target
- Create Storage Policy: keep forever
- Establish connection to the Target
- Delete Session Recording: expect failure
- Update Storage Policy: do not protect from deletion
- Re-apply Storage Policy for the Session Recording
- Delete Session Recording: expect success
This PR also adjusts the required env variables for the `ssh-credential-injection-vault-ent.spec.js` and `target-ent.spec.js` as they now set ingress worker tag for SSH targets in their scenarios.
[ICU-12883]: https://hashicorp.atlassian.net/browse/ICU-12883?atlOrigin=eyJ …
> test: 💍 Add storage policies e2e-test

- addons/api/addon/generated/models/alias.js
- addons/api/addon/models/alias.js
- addons/api/app/models/alias.js
- addons/api/mirage/config.js
- addons/api/mirage/factories/alias.js
- addons/api/mirage/factories/scope.js
- addons/api/mirage/generated/factories/alias.js
- addons/api/mirage/models/alias.js
- addons/api/mirage/scenarios/default.js
- addons/api/tests/unit/models/alias-test.js
- ui/admin/app/router.js
- ui/admin/app/routes/scopes/scope/aliases.js
Jira - https://hashicorp.atlassian.net/browse/ICU-12932, https://hashicorp.atlassian.net/browse/ICU-12934
This PR adds an initial list route and mirage support for alias resources. 
- Using mirage, go to /scopes/global/aliases and look at the dev console to see the generated mirage data
> feat: 🎸 mirage support and initial route for aliases

- addons/core/translations/resources/en-us.yaml
- ui/admin/app/controllers/scopes/scope/aliases/alias/index.js
- ui/admin/app/controllers/scopes/scope/aliases/index.js
- ui/admin/app/controllers/scopes/scope/aliases/new.js
- ui/admin/app/routes/scopes/scope/aliases/alias.js
- ui/admin/app/routes/scopes/scope/aliases/index.js
- ui/admin/app/routes/scopes/scope/aliases/new.js
- ui/admin/app/templates/scopes/scope.hbs
- ui/admin/app/templates/scopes/scope/aliases.hbs
- ui/admin/app/templates/scopes/scope/aliases/alias.hbs
- ui/admin/app/templates/scopes/scope/aliases/alias/index.hbs
- ui/admin/app/templates/scopes/scope/aliases/index.hbs
- ui/admin/app/templates/scopes/scope/aliases/new.hbs
- ui/admin/tests/unit/controllers/scopes/scope/aliases/alias/index-test.js
- ui/admin/tests/unit/controllers/scopes/scope/aliases/index-test.js
- ui/admin/tests/unit/controllers/scopes/scope/aliases/new-test.js
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-12936)
This PR adds new routes for aliases, also controllers to support new route action pattern
> chore: Add routes for aliases

- ui/admin/tests/e2e/helpers/boundary-cli.js
- ui/admin/tests/e2e/helpers/boundary-ui.js
- ui/admin/tests/e2e/tests/auth-method-ldap.spec.js
- ui/admin/tests/e2e/tests/auth-method-password.spec.js
- ui/admin/tests/e2e/tests/credential-store-static.spec.js
- ui/admin/tests/e2e/tests/credential-store-vault.spec.js
- ui/admin/tests/e2e/tests/delete-resources-ent.spec.js
- ui/admin/tests/e2e/tests/delete-resources.spec.js
- ui/admin/tests/e2e/tests/group-role.spec.js
- ui/admin/tests/e2e/tests/session-recording-ent.spec.js
- ui/admin/tests/e2e/tests/ssh-certificate-injection-vault-ent.spec.js
- ui/admin/tests/e2e/tests/ssh-credential-injection-vault-ent.spec.js
- ui/admin/tests/e2e/tests/target-ent.spec.js
- ui/admin/tests/e2e/tests/target.spec.js
This PR does some refactoring in the Admin UI e2e test suite to move any direct use of environment variables outside of helper methods to make it consistent and explicit where they are used within tests.
> refact(e2e): Move env outside of helper methods

- ui/admin/tests/e2e/helpers/boundary-ui.js
- ui/admin/tests/e2e/tests/auth-method-password.spec.js
This PR updates a "create" helper method in the Admin UI e2e test suite to follow the convention established in this PR: https://github.com/hashicorp/boundary-ui/pull/2191
> refact(e2e): Convert to match "create" helper convention

- ui/desktop/app/routes/scopes.js
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-12543
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-12543)
A user has configured their boundary cluster to not allow listing all scopes when not authenticated. When checking to see if the controller is a supported version for the desktop client, we were using the `recursive: true` queryParam which was causing the API to return a `500` response which causes the desktop client to assume the controller is unsupported. Simply removing the `recursive: true` queryParam and only list the `global` scope, we remove that issue and properly determine if the controller is supported.
Follow steps mentioned [here](https://github.com/hashicorp/boundary-ui/issues/2192#issuecomment-2014765882).
> fix: 🐛 remove recursive param from list scopes endpoint

- ui/desktop/app/templates/scopes/scope/authenticate.hbs
- ui/desktop/tests/acceptance/authentication-test.js
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-13133
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-13133)
While this should never happen, if the permissions are misconfigured the user will see no auth methods available to sign in with. If this happens, the "Change cluster URL" action will not be displayed either. It has now been updated to show up no matter what to give the user a way out of this error state without having to shutdown the desktop client.
Before:
After:
Start up `boundary dev` and modify the `Login Grants` Role at the global scope. Delete the auth-method grant: `ids=*;type=auth-method;actions=list,authenticate`. Now start the desktop using `ENABLE_MIRAGE=false BYPASS_CLI_SETUP=true yarn start:desktop` and after you enter the cluster URL you …
> fix: 🐛 show change cluster url when no auth methods

- ui/admin/tests/e2e/helpers/boundary-ui.js
- ui/admin/tests/e2e/tests/credential-store-static.spec.js
- ui/admin/tests/e2e/tests/dynamic-host-catalog.spec.js
After merging https://github.com/hashicorp/boundary-ui/pull/2169/files, we can update an e2e test that uses the vault credential library form.
This PR also includes some other locator fixes due to some other form changes (using commit `9843310dfbf6fa7710a9e65dba89a8ff7e05fd2a`)
> test(e2e): Update credential library form behavior

- ui/admin/app/routes/scopes/scope/sessions/index.js
Add `parentScope.id` to `this.getAssociatedUsers` in the `refreshAll` action
Start `boundary dev` and connect to a few targets to create sessions. In the Admin UI, navigate to the sessions list view and click the refresh button. This should trigger 4 more network requests for sessions (x2), users, and targets.
> fix: 🐛 add parentScope.id to refresh action for sessions

- addons/api/addon/models/host-catalog.js
- addons/api/addon/models/host-set.js
- addons/api/addon/models/host.js
- addons/api/addon/services/indexed-db.js
- addons/api/mirage/config.js
- ui/admin/app/components/form/host-catalog/aws/index.js
- ui/admin/app/components/form/host-catalog/azure/index.js
- ui/admin/app/components/form/host-catalog/static/index.js
- ui/admin/app/controllers/scopes/scope/host-catalogs/index.js
- ui/admin/app/routes/scopes/scope/host-catalogs.js
- ui/admin/app/routes/scopes/scope/host-catalogs/index.js
- ui/admin/app/routes/scopes/scope/targets/target/add-host-sources.js
- ui/admin/app/templates/scopes/scope/host-catalogs/index.hbs
- ui/admin/tests/acceptance/host-catalogs/create-test.js
- ui/admin/tests/acceptance/host-catalogs/delete-test.js
- ui/admin/tests/acceptance/host-catalogs/list-test.js
- ui/admin/tests/acceptance/host-catalogs/read-test.js
- ui/admin/tests/acceptance/host-catalogs/update-test.js
- ui/admin/tests/unit/controllers/scopes/scope/host-catalogs/index-test.js
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-12781
Adds search support for host catalogs. User can search by id, name, description, scope, plugin type.
No filters are added here as we display in the table the plugin name (aws and azure) as also a "type". It's quite hard to form the correct filters for both the type and plugin name in one filter dropdown. An alternative is to have both a type and a provider dropdown but after [talking about it with design](https://hashicorp.slack.com/archives/C0647GX0TLJ/p1712005802193929), we decided not to include any filters.  
https://github.com/hashicorp/boundary-ui/assets/5783847/1a8b789b-cfdc-481d-b0f9-9478f12e2f36
1. Start boundary dev instance
2. Test search on host catalogs
5. Validate searching works as expected
- ~[ ] I have added JSON …
> Icu 12781 add filtering pagination support for host catalogs

- ui/admin/app/templates/scopes/scope/sessions/index.hbs
- ui/admin/app/templates/scopes/scope/targets/index.hbs
- ui/admin/tests/acceptance/targets/list-test.js
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-13085
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-13085)
Add active sessions column to targets table. The link should take user to sessions list view with appropriate target pre selected.
https://github.com/hashicorp/boundary-ui/assets/107949262/f52b01b4-c9a7-4e73-8fc3-a7587fd7af7a
1. start boundary dev env
2. create a session
3. login to admin ui -> navigate to targets
4. validate that the active sessions column is correctly populated
5. validate that correct target is pre selected when user clicks "Yes" link in active sessions column
> refactor: 💡 add active sessions column to targets table

- ui/admin/app/routes/scopes/scope/sessions/index.js
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-13130
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-13130)
Add `include_terminated` param to sessions query in Admin UI. In desktop we don't need this as the client daemon is handling it for us. I did not include this param in the targets list route as we only care about active and pending sessions in that route. 
Here you can see when refreshed (or searched), the session that is now terminated is returned.
Connect to a target via the cli or desktop client. In the Admin UI visit the sessions list route to view the active or pending session. Cancel the session, then refresh the data in Admin UI and you should see the status change to canceling. After a few minutes the status will change to `terminated`. Refresh the …
> refactor: 💡 add include_terminated param to sessions query

- addons/api/addon/adapters/application.js
- addons/api/addon/handlers/indexed-db-handler.js
- addons/api/addon/utils/hash-code.js
- addons/api/tests/unit/utils/hash-code-test.js
- ui/admin/app/routes/scopes/scope/credential-stores/index.js
- ui/admin/app/routes/scopes/scope/groups/index.js
- ui/admin/app/routes/scopes/scope/host-catalogs/index.js
- ui/admin/app/routes/scopes/scope/roles/index.js
- ui/admin/app/routes/scopes/scope/sessions/index.js
- ui/admin/app/routes/scopes/scope/targets/index.js
- ui/admin/app/routes/scopes/scope/users/index.js
- ui/admin/app/templates/scopes/scope/targets/index.hbs
- ui/admin/tests/acceptance/targets/create-test.js
Added logic to make the list tokens stored in indexed DB more granular. I get a hash of the query parameters that will get sent to the controller and use that as the id for the token. This also means extra logic for when a token is invalid as we will need to delete all tokens of the same resource type.
Go through all the resources that will used indexed DB and confirm that tokens are being correctly added. Delete or add new scopes to test invalid list tokens for scope resources. 
> feat: 🎸 Update how we store tokens in indexed-db

- ui/admin/app/components/header-nav/index.hbs
- ui/admin/app/routes/scopes/scope.js
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-13106
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-13106)
Fixes the "Discard unsaved changes?" modal from popping up when the user made no changes to the model. Bug was seen in the global settings page when trying to navigate away.
Before:
https://github.com/hashicorp/boundary-ui/assets/107949262/ac34d865-f60c-4959-946a-8e0b8283b3c7
After:
https://github.com/hashicorp/boundary-ui/assets/107949262/f9ad6e4b-c007-4ca8-8d91-dfbd226bd2e9
1. start boundary dev instance.
2. login in
3. navigate to "Global settings"
4. Attempt to navigate to a different route, and validate that "Discard unsaved changes?" modal does not pop up.
( look at slack thread in jira ticket for additional details if necessary )
> fix: 🐛 modal bubbling up when user has not updated model

- addons/api/addon/handlers/indexed-db-handler.js
- addons/api/addon/serializers/role.js
- addons/api/addon/services/indexed-db.js
- addons/api/tests/unit/utils/indexed-db-query-test.js
- ui/admin/app/controllers/scopes/scope/credential-stores/index.js
- ui/admin/app/controllers/scopes/scope/groups/index.js
- ui/admin/app/routes/scopes/scope/groups/group/add-members.js
- ui/admin/tests/acceptance/aliases/list-test.js
- ui/admin/tests/acceptance/credential-store/create-test.js
There were some broken tests after rebasing onto main. This mainly fixes the issues. There was one interesting issue that arose from this [PR](https://github.com/hashicorp/boundary-ui/pull/2214). The model was changed to now use a tracked array instead of a normal array. I had originally made the assumption we wouldn't have any ember-like arrays in our models but this is now obviously not a valid assumption so we have to handle cleaning those up before sending it to indexed db.
Most likely we will encounter a similar type of error with tracked objects in the future but none of our current models use those yet.
> Fix tests from rebase

- ui/admin/app/routes/scopes/scope/scopes.js
- ui/admin/app/templates/scopes/scope/scopes.hbs
Fix bug causing breadcrumbs on scopes route to not show.
BEFORE: 
AFTER:
1. open admin-ui
2. navigate to scopes.scope.scopes routes and make sure that breadcrumbs are appearing correctly
:technologist: [Admin preview](https://boundary-ui-git-fix-scopes-breadcrumb-not-showing-hashicorp.vercel.app/scopes/global/scopes)
> fix: 🐛 breadcrumbs on scopes route not showing since model moved

- addons/api/addon/generated/models/storage-bucket.js
- addons/api/addon/models/storage-bucket.js
- addons/api/addon/serializers/storage-bucket.js
- addons/api/mirage/factories/storage-bucket.js
- addons/api/tests/unit/serializers/storage-bucket-test.js
First iteration of model & mirage support for MinIO.
After discussion on Tech time (Thursday April the 4th) I decided to keep this as simple as possible until we progress a bit more on the initiative: add routes, a way to change providers and such. BUT happy to change approach if reviewers suggest so.
Be aware this PR do NOT need a boundary instance since is changing models/mirage, on coming PR's, the usage of a boundary instance will be mandatory. [LINK to Vercel deployment](https://boundary-ui-git-chore-13335-model-support-minio-hashicorp.vercel.app/scopes/global/storage-buckets).
Open storage buckets list, validate we generate some storage buckets with minio as provider.
- Open storage bucket, click new …
> chore: 🤖 Model & Mirage support for MinIO

- addons/api/.eslintrc.js
- addons/api/addon/handlers/client-daemon-handler.js
- ui/desktop/.eslintrc.js
- ui/desktop/electron-app/package.json
- ui/desktop/electron-app/src/index.js
- ui/desktop/electron-app/src/services/client-daemon-manager.js
- ui/desktop/electron-app/src/utils/jsonify.js
- ui/desktop/electron-app/yarn.lock
Added initial logging for desktop client.
Example log statements:
```
[2024-04-10 19:24:27.664-04:00] [info]  Search request took 220 ms { query: '', force_refresh: true, resource: 'targets' }
[2024-04-10 19:27:45.446-04:00] [info]  Search request took 219 ms { force_refresh: true, query: '', resource: 'targets' }
[2024-04-10 19:27:45.841-04:00] [info]  Search request took 31 ms {
query: '(user_id = "u_1234567890") and (status = "active" or status = "pending")',
force_refresh: true,
resource: 'sessions'
}
[2024-04-10 19:27:46.079-04:00] [info]  Search request took 204 ms { query: '', force_refresh: true, resource: 'targets' }
```
Run desktop client for a bit and check the desktop logs.
On mac it's at `~/Library/Logs/Boundary/main.log`
> feat: 🎸 Add initial logging for desktop client

- ui/admin/app/routes/scopes/scope/targets/target/add-host-sources.js
Accidentally removed the scope ID query param when refactoring the call to use indexed DB.
Add a host set from a target and it shouldn't error out.
> fix: 🐛 Add back scope_id as part of request query parameter

- ui/admin/app/controllers/scopes/scope/groups/index.js
fix: 🐛 transition aborted error when deleting group
Before:
After:
https://github.com/hashicorp/boundary-ui/assets/29386339/fd3240fd-62a1-49d5-81b8-bf3b41dbc193
Start a boundary instance, create a group, then delete. You should see no errors.
> fix: 🐛 transition aborted error when deleting group

- ui/admin/app/components/form/storage-bucket/aws/index.hbs
- ui/admin/app/components/form/storage-bucket/minio/index.hbs
Add field validation for scope within Storage bucket creation. Storage buckets did not have implemented field validation for Scope select.
- Using a Boundary instance + MinIO try to create a storage bucket without filling any field in the form.
- You should see Scope field showing required field error.
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
> Fix scope field validation on storage buckets

- ui/admin/tests/e2e/helpers/boundary-cli.js
- ui/admin/tests/e2e/helpers/boundary-ui.js
- ui/admin/tests/e2e/tests/credential-store-static.spec.js
- ui/admin/tests/e2e/tests/credential-store-vault.spec.js
- ui/admin/tests/e2e/tests/session-recording-ent.spec.js
This PR makes some adjustments to the Admin UI e2e test suite based on changes for 0.16.0.
- The "New Storage Bucket" page no longer defaults to a `global` scope, so we now have to specify a scope. The test now creates the bucket within the created org scope, and the respective changes 
- Multiple tests were modified to create a target with an address associated with it to reduce the number of actions needed. We still have one test that creates a target and associated a host source to it.
- The Sessions page no longer shows the Refresh button in its empty state. Needed to modify the logic of `waitForSessionToBeVisible` accordingly
- Some link locators were modified (removed a `.getByRole('article')`)
> test(e2e): Fixes for 0.16.0

- ui/admin/app/components/form/auth-method/oidc/index.hbs
Update required fields with "Required" label
1. run boundary dev instance
2. save oidc auth method without inputting anything to see required fields.
> fix: 🐛 required & optional labels in oidc auth-methods form

- addons/core/translations/form/en-us.yaml
- ui/admin/app/components/form/host-set/aws/index.hbs
- ui/admin/app/components/form/host-set/azure/index.hbs
The sync interval field was mistakenly changed in https://github.com/hashicorp/boundary-ui/pull/2147. This changes the label and helper text back.
Before:
After:
Go to the AWS and azure host sets and confirm the field is correct.
> fix: 🐛 Fix HDS labels and helpers in host sets

- ui/admin/app/routes/scopes/scope/targets/target/add-brokered-credential-sources.js
- ui/admin/app/routes/scopes/scope/targets/target/add-host-sources.js
- ui/admin/app/routes/scopes/scope/targets/target/add-injected-application-credential-sources.js
There seems to be an error similar to https://github.com/hashicorp/boundary-ui/pull/2040 where repeatedly adding and removing a resource causes an error.
https://github.com/hashicorp/boundary-ui/assets/5783847/0a938d98-4f2a-4fae-b82b-bfff92e41b5f
Start up boundary dev and go to a target. Add a host set and remove it a few times to see the error.
> fix: 🐛 Fix adding host set error in targets

- addons/core/translations/resources/en-us.yaml
This PR updates the example text for an LDAP server address. This was noted by a Solutions Engineer.
- The field does require a scheme (i.e. `ldap://`)
- `ldaps://` was selected since most production environments will use SSL
- `636` is the default port for `ldaps://`
_BEFORE_
_AFTER_
:technologist: [Admin preview](https://boundary-ui-git-moduli-update-ldap-example-hashicorp.vercel.app)
> fix: Update LDAP address example

- ui/admin/app/controllers/scopes/scope/auth-methods/index.js
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-13624
There was an issue with deleting an auth method where we tried to access a model field after deleting it. Weirdly enough ember only throws the error when we make the auth method primary and then removing it as primary.
* Create a password auth method in an org
* Mark it as primary
* Remove it as primary
* Delete it
* Should not error 
> fix: 🐛 Fix error when deleting auth method

- ui/admin/app/components/form/worker/create-worker-led/index.hbs
Fix regression due to [input box refactor](https://github.com/hashicorp/boundary-ui/pull/2151).
https://github.com/hashicorp/boundary-ui/assets/107949262/2afd9c57-6856-47f0-a4bb-7c927430b45c
1. Go to Wokers List View
2. Click New
3. Toggle Enable Recording Storage
4. Enter in a value for the storage path & text editor should update with inputed value
> fix: 🐛 recording storage path not being set

- .github/workflows/jira.yml
This PR updates some GitHub Actions to use a Node20 version of the Action in order to avoid deprecation warnings.
In this case, `atlassian/gajira-*` actions are no longer maintained, but they are using node16, which is soon to be deprecated. This change removes the use of those actions. (This borrows changes from https://github.com/hashicorp/vault-workflows-common/pull/64)
> chore: Update to use Node20 version of Actions

- .github/workflows/jira.yml
After merging https://github.com/hashicorp/boundary-ui/pull/2283 and testing with https://github.com/hashicorp/boundary-ui/issues/2288, there was an error when reopening the issue
```
Run transitions="$(curl --silent \
transitions="$(curl --silent \
--url "***rest/api/3/issue/ICU-13742/transitions" \
--user "***:***" \
--header "Accept: application/json")"
id="$(echo "${transitions}" | jq -r '.transitions[] | select(.name == "'To Do'") | .id')"
curl --silent \
--url "***rest/api/3/issue/ICU-13742/transitions" \
--user "***:***" \
--header "Accept: application/json" \
--header "Content-Type: application/json" \
--data "$(printf '{"transition": {"id": "%s"}}' "${id}")"
shell: /usr/bin/bash -e {0}
jq: error: syntax error, unexpected $end, expecting QQSTRING_TEXT or QQSTRING_INTERP_START or …
```
> chore: Fix error in Jira Sync workflow

- ui/admin/app/components/form/scope/add-storage-policy/create.hbs
- ui/admin/app/controllers/scopes/scope/add-storage-policy/create.js
- ui/admin/app/controllers/scopes/scope/add-storage-policy/index.js
- ui/admin/app/controllers/scopes/scope/policies/index.js
- ui/admin/app/controllers/scopes/scope/policies/new.js
- ui/admin/app/controllers/scopes/scope/policies/policy/index.js
- ui/admin/app/routes/scopes/scope/add-storage-policy/create.js
- ui/admin/app/routes/scopes/scope/add-storage-policy/index.js
- ui/admin/app/routes/scopes/scope/policies.js
- ui/admin/app/templates/scopes/scope/add-storage-policy/create.hbs
- ui/admin/app/templates/scopes/scope/add-storage-policy/index.hbs
- ui/admin/app/templates/scopes/scope/policies/index.hbs
- ui/admin/app/templates/scopes/scope/policies/new.hbs
- ui/admin/app/templates/scopes/scope/policies/policy/index.hbs
- ui/admin/tests/unit/controllers/scopes/scope/add-storage-policy/create-test.js
- ui/admin/tests/unit/controllers/scopes/scope/add-storage-policy/index-test.js
- ui/admin/tests/unit/controllers/scopes/scope/policies/index-test.js
- ui/admin/tests/unit/controllers/scopes/scope/policies/new-test.js
- ui/admin/tests/unit/controllers/scopes/scope/policies/policy/index-test.js
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-12607
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-12607)
remove route-action usage for storage policies routes
1. start boundary dev instance
2. test crudl for policies in org and global levels
3. test attaching a storage policy to a scope
> refactor: 💡 remove route-action usage for storage-policies

- .github/pull_request_template.md
Made some small changes to the PR template. 
- Removed the `PATH_TO_FEATURE` links as we no longer use them
- Updated headers to all match
- Move "Description" header to top level
- comment out JIRA ticket link since link is typically added automatically now (thanks @ZedLi)
> chore: 🤖 update PR template

- yarn.lock
We got a warning on the terminal everytime we run yarn commands regarding `browserlists` being outdated, run the command to update it `npx update-browserslist-db@latest`.
> As per warning updated browserslist

- addons/api/addon/handlers/client-daemon-handler.js
- addons/api/mirage/scenarios/ipc.js
- addons/core/addon/decorators/notify.js
- addons/core/translations/errors/en-us.yaml
- addons/core/translations/notifications/en-us.yaml
- ui/admin/app/templates/application.hbs
- ui/desktop/app/routes/application.js
- ui/desktop/app/routes/cluster-url.js
- ui/desktop/app/routes/scopes/scope/projects.js
- ui/desktop/app/routes/scopes/scope/projects/sessions/session.js
- ui/desktop/app/routes/scopes/scope/projects/targets/index.js
- ui/desktop/app/services/client-agent-sessions.js
- ui/desktop/app/services/session.js
- ui/desktop/app/templates/application.hbs
- ui/desktop/electron-app/src/index.js
- ui/desktop/electron-app/src/ipc/handlers.js
- ui/desktop/electron-app/src/services/client-agent-daemon-manager.js
- ui/desktop/electron-app/src/utils/generateErrorPromise.js
- ui/desktop/tests/helpers/window-mock-ipc.js
- ui/desktop/tests/unit/services/client-agent-sessions-test.js
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-13831
Added functionality to poll the new `boundary ferry sessions` API. Still trying to figure out how to test this.
* Setup ferry and boundary according to the docs [here](https://github.com/hashicorp/ferry?tab=readme-ov-file#ferry).
* Copy over the new CLI to our cli folder and use `BYPASS_CLI_SETUP=true`
* Add a brokered credential to the `Generated localhost ssh target with an alias` target.
* SSH to the default `ssh.boundary.dev` alias and you should get a notification (though you might need to also enable it on your OS). 
* Clicking the notification should open up the correct session with credentials displayed.
- ~[ ] I have added steps to reproduce and test for bug fixes …
> feat: 🎸 Add support for polling transparent sessions

- ui/admin/tests/e2e/helpers/boundary-cli.js
- ui/admin/tests/e2e/helpers/boundary-ui.js
- ui/admin/tests/e2e/tests/delete-resources-ent.spec.js
- ui/admin/tests/e2e/tests/delete-resources.spec.js
- ui/admin/tests/e2e/tests/dynamic-host-catalog.spec.js
This PR updates the Admin UI e2e test suite based on results from testing Boundary 0.16.1. There are two changes here
1. Updates the test suite to utilize the AWS region specified in the environment. The end-to-end test suite can now run against different AWS regions, and this change uses the information passed from infra creation
2. Updates a locator for a label that was used to attach a storage bucket to a target.
> test(e2e): 0.16.1 updates

- ui/desktop/electron-app/config/forge.config.js
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-13931
Sets an Info.plist key for our app ([NSUserNotificationAlertStyle](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW19)) to use alerts by default.
More context [here](https://hashicorp.slack.com/archives/C05EHAH84HE/p1717011178082889).
Run the build [here](https://github.com/hashicorp/boundary-ui-releases/actions/runs/9293151768) to confirm that boundary notifications are using alerts by default now. (Not sure of behavior if you've already changed the setting, I don't think it is likely to change?)
- ~[ ] …
> feat: 🎸 Change the default notification on mac to be alert

- ui/desktop/app/routes/scopes/scope/projects/sessions/session.js
Fix an error where sessions with no brokered credentials errored out. 
SSH to a target without brokered credentials using the client agent and go to the session in DC. It shouldn't error out.
> fix: 🐛 Fix session erroring out when getting session from ferry

- addons/api/addon/generated/models/role.js
- addons/api/addon/models/role.js
- addons/api/addon/serializers/role.js
- addons/api/tests/unit/models/role-test.js
- addons/api/tests/unit/serializers/role-test.js
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-12709
Adds `grant_scope_ids` to the role model and adds `setGrantScopes` and `removeGrantScopes` methods to make use of the `:set-grant-scopes` and `:remove-grant-scopes` actions in the API.
> feat: 🎸 add grant_scope_ids to role model

- addons/api/mirage/config.js
- addons/api/mirage/factories/role.js
- addons/api/mirage/serializers/role.js
- ui/admin/app/components/form/role/index.js
- ui/admin/app/routes/onboarding.js
Context: `this` is what a role's grant scope will default to when created now. I update mirage to reflect that.
Update mirage to use `grant_scope_ids`. I also updated the onboarding workflow and `updateGrantScopeID` so that the update will work correctly with mirage.
NOTE: I am keeping `grant_scope_id` for now and it will all be removed at the same time to maintain functionality. 
Role generated by mirage when first visiting the roles route
Role created while using mirage
Start the Admin UI with mirage. Visit the roles route and view the "network request" in the console tab of your browser to see new values.
> Icu 12707 update role mirage

- ui/admin/tests/e2e/helpers/boundary-ui.js
- ui/admin/tests/e2e/tests/session-recording-aws-ent.spec.js
- ui/admin/tests/e2e/tests/session-recording-minio-ent.spec.js
This PR is a follow-up to https://github.com/hashicorp/boundary-enterprise/pull/1112.
This PR adds an Admin UI e2e test to validate session recording using a MinIO storage bucket. This test is fairly similar to the existing session recording test using an AWS storage bucket outside of the creation of a storage bucket using a different provider.
https://hashicorp.atlassian.net/browse/ICU-13930
> test(e2e): Add test for minio storage bucket

- addons/api/.eslintrc.js
- addons/api/addon/handlers/client-daemon-handler.js
- ui/desktop/.eslintrc.js
- ui/desktop/electron-app/package.json
- ui/desktop/electron-app/src/helpers/request-promise.js
- ui/desktop/electron-app/src/index.js
- ui/desktop/electron-app/src/ipc/handlers.js
- ui/desktop/electron-app/src/services/client-daemon-manager.js
- ui/desktop/electron-app/src/utils/jsonify.js
- ui/desktop/electron-app/yarn.lock
This adds desktop client logging on all environments with an initial pass of things to log. 
By default, the logs are written to:
~/.config/Boundary/logs/desktop-client.log
~/Library/Logs/Boundary/desktop-client.log
%USERPROFILE%\AppData\Roaming\Boundary\logs\desktop-client.log
[desktop-client.log](https://github.com/user-attachments/files/15539786/desktop-client.log)
Run the desktop client and experiment with generating errors. You'll have to manually do this usually by throwing manual errors. You can `tail -f` the log file to watch for new log entries.
To test log rotation, you can set the [maxSize](https://github.com/megahertz/electron-log/blob/master/docs/transports/file.md#maxsize-number) to something smaller.
- ~[ ] I have …
> Icu 13451 desktop client logging

- ui/desktop/app/routes/scopes/scope/projects/targets/index.js
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-13981
There's a small display bug where if you cancel a session outside of the desktop client, refreshing the targets doesn't remove the corresponding active session on the target. This is just a display bug as filtering still works as expected but can be very confusing. See this [thread](https://hashicorp.slack.com/archives/C012GTH1C4E/p1717183385186269) for more details.
The underlying issue is the cache is correctly returning no sessions but they're not getting removed from the ember data store. So the target (which does a `peekAll` on sessions) still thinks there are sessions. 
1. Start boundary dev and connect to a target, navigate back to the targets page
2. Cancel the target using admin ui or the CLI
3. Refresh the targets page, …
> fix: 🐛 Fix active session display in targets table

- LICENSE
- changelog.config.js
- docker-compose-embedding.yml
- ui/admin/app/components/form/field/list-wrapper/key-value/select.hbs
- ui/admin/app/components/form/field/list-wrapper/key-value/text.hbs
- ui/admin/tests/acceptance/storage-buckets/selectors.js
- ui/admin/tests/e2e/tests/session-recording-minio-ent.spec.js
This PR updates LICENSE txt for the UI repo and fixes some of the old license to BUSL 1.1 
- you can install copyright [repo](https://github.com/hashicorp/copywrite) and using the CLI command, run copyright license and it should be valid 
`copywrite license`
**result:** 
> Licensing under the following terms: BUSL-1.1
> Using year of initial copyright: 2024
> Using copyright holder: HashiCorp, Inc.
> 
> Validated file: LICENSE
> Validating presence of license header
> Copyright statement is valid!
- ~[ ] I have …
> chore: 🤖 update LICENSE txt and fix license

- ui/desktop/app/routes/scopes/scope/projects.js
- ui/desktop/electron-app/src/index.js
Persists windows notifications so they don't go to windows action center and fix the text in the notification.
See this [thread](https://hashicorp.slack.com/archives/C05EHAH84HE/p1717200501817919) for more details.
1. Use windows vm in parallels and setup ferry + dev instance.
2. Have a target with brokered credentials and an alias and ssh to the alias
3. Check that the notification looks correct
> feat: 🎸 Fix text and persist windows notification

- addons/api/addon/abilities/role.js
- addons/api/mirage/factories/role.js
- addons/api/mirage/serializers/role.js
- addons/api/tests/unit/abilities/role-test.js
- addons/core/translations/resources/en-us.yaml
- ui/admin/app/routes/scopes/scope/roles/role/scopes.js
- ui/admin/app/styles/app.scss
- ui/admin/app/templates/scopes/scope/roles/role/scopes.hbs
- ui/admin/tests/acceptance/roles/scopes-test.js
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-13878
If a role has no grant scopes, we will display a simple message with an action to direct the user to add scopes. I will update the route once we have a route for it to navigate to.
Start a `boundary dev` instance and remove all grant scope ids via the CLI. Now you should see the "no scopes added" message.
> feat: 🎸 add No scopes add to roles/role/scopes route

- ui/admin/app/components/form/worker/create-worker-led/index.hbs
- ui/admin/tests/e2e/tests/worker-ent.spec.js
- ui/admin/tests/e2e/tests/worker.spec.js
This PR adds an e2e test for the worker page. There are two tests (the worker page is slightly different on the enterprise version). The test does the following
- Populate the config fields
- Validate that the example config is auto-populated with the right information
- Try to register an invalid worker token  
https://hashicorp.atlassian.net/browse/ICU-13030
> test(e2e): Add test for worker

- ui/admin/tests/e2e/helpers/boundary-ui.js
- ui/admin/tests/e2e/tests/dynamic-host-catalog-aws.spec.js
- ui/admin/tests/e2e/tests/session-recording-aws-ent.spec.js
- ui/admin/tests/e2e/tests/session-recording-minio-ent.spec.js
- ui/admin/tests/e2e/tests/target-ent.spec.js
- ui/admin/tests/e2e/tests/target.spec.js
This PR updates some Admin UI e2e tests to add/remove additional host sources to a target. 
- The existing test (CE only) was updated to add and remove a second host source to a target
- A second test (ENT only) mirrors the existing test, but uses SSH targets
There are two tests modified in this PR
- One is a CE test that can be run on either Docker or AWS infra
- One is an ENT test that can be run on either Docker or AWS infra
```
yarn run e2e:ce:docker 
yarn run e2e:ent:docker
```
https://hashicorp.atlassian.net/browse/ICU-14009
> test(e2e): Add check for multiple host sources

- ui/admin/tests/e2e/tests/auth-method-ldap.spec.js
- ui/admin/tests/e2e/tests/credential-store-static.spec.js
- ui/admin/tests/e2e/tests/credential-store-vault.spec.js
- ui/admin/tests/e2e/tests/dynamic-host-catalog-aws.spec.js
This PR updates an Admin UI e2e test to check for the population of LDAP account attributes.
This test works on both CE and ENT, but only on docker scenarios
```
yarn run e2e:ce:docker
yarn run e2e:ent:docker
```
https://hashicorp.atlassian.net/browse/ICU-14065
> test(e2e): Add checks for LDAP account attributes

- addons/api/addon/models/worker.js
- addons/api/tests/unit/models/worker-test.js
- ui/admin/app/routes/scopes/scope/workers/index.js
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-13891
This is some of the initial api/model changes for worker tag improvements. We have a story that will need data organized in a specific way from how it is returned from the API. The `getAllTags` method will combine the config and api tags into a single list that also denotes their tag type. Here is the [design](https://www.figma.com/design/ZzeL7kAVjNENx6kzZutua3/Worker-Tags-Improvements?node-id=803-24752&t=EH3Wc78KnpSAImBa-0) of how this data will be used in a table.
> feat: 🎸 create get allTags method that includes tag type

- addons/api/addon-test-support/handlers/cache-daemon-search.js
- addons/api/addon/handlers/cache-daemon-handler.js
- addons/api/addon/utils/mql-query.js
- addons/api/app/handlers/client-daemon-handler.js
- addons/api/mirage/scenarios/ipc.js
- ui/desktop/app/routes/application.js
- ui/desktop/app/routes/scopes/scope/projects/sessions/index.js
- ui/desktop/app/routes/scopes/scope/projects/targets/index.js
- ui/desktop/app/services/session.js
- ui/desktop/app/services/store.js
- ui/desktop/app/templates/scopes/scope/projects/sessions/index.hbs
- ui/desktop/app/templates/scopes/scope/projects/targets/index.hbs
- ui/desktop/electron-app/src/helpers/request-promise.js
- ui/desktop/electron-app/src/helpers/spawn-promise.js
- ui/desktop/electron-app/src/index.js
- ui/desktop/electron-app/src/ipc/handlers.js
- ui/desktop/electron-app/src/services/cache-daemon-manager.js
- ui/desktop/tests/acceptance/projects/sessions/index-test.js
- ui/desktop/tests/acceptance/projects/sessions/session-test.js
- ui/desktop/tests/acceptance/projects/targets/index-test.js
- ui/desktop/tests/acceptance/projects/targets/target-test.js
- ui/desktop/tests/acceptance/scopes-test.js
- ui/desktop/tests/helpers/window-mock-ipc.js
Renamed the client agent to cache daemon as backend has updated their naming of dameons. 
> refactor: 💡 Rename client daemon to cache daemon

- addons/rose/addon/styles/addon.scss
- addons/rose/index.js
Previous [PR](https://github.com/hashicorp/boundary-ui/pull/2350) to upgrade to hds v4 broke our [build workflows](https://github.com/hashicorp/boundary-ui/actions/runs/9555072433/job/26337734431) 😭
Due to the errors encountered we are opting to import all hds styles manually like we were doing before. In addition to also importing the styles for flight-icons. If we don't include the style path for the icons we get an error so it is necessary to include.
1. run all admin-ui build commands locally: `yarn run build:ui:admin:oss` `yarn run build:ui:admin:enterprise` `yarn run build:ui:admin:hcp`
2. start ui/admin and ui/desktop apps locally and make sure there are no unexpected warnings or errors
> fix: 🐛 styles import file not being found

- ui/desktop/electron-app/config/cli.js
- ui/desktop/electron-app/package.json
- ui/desktop/electron-app/yarn.lock
This fixes the issue @calcaide reported in this [thread](https://hashicorp.slack.com/archives/C02CGB68P8S/p1717535140624269).
It turns out, our new unzipping library doesn't properly preserve permissions from the zip archive and removes the executable file permissions on the CLI. This is a known issue for this [library](https://github.com/ZJONSSON/node-unzipper/issues/216).
I swapped to `adm-zip` which can properly handle the original file permissions and also has no dependencies while still being maintained. 
Before:
After:
Delete your current CLI and let the script download a new one either through building or starting dev. Confirm that the CLI permissions are correct. 
- ~[ ] I have added tests that prove my fix is effective or …
> fix: 🐛 Fix unzipping changing cli permissions

- ui/admin/app/components/breadcrumbs/container/index.hbs
- ui/admin/app/components/breadcrumbs/item/index.hbs
- ui/admin/app/templates/scopes/index.hbs
- ui/desktop/app/components/session/proxy-url/index.hbs
noticed some warnings due to this copyright syntax in some of the files 
- do yarn run test and you should not see the warnings anymore
> fix: 🐛 copyright syntax

- ui/admin/tests/e2e/tests/session-recording-aws-ent.spec.js
- ui/admin/tests/e2e/tests/session-recording-minio-ent.spec.js
This PR updates some Admin UI e2e tests to add a check to detach a storage bucket from a target.
The tests that are affected by this include...
- Session Recording (AWS)
- Session Recording (MinIO)
To be able to run all of the tests, you'll need to use the boundary-enterprise and run tests against 2 different scenarios.
```
yarn run e2e:ent:docker
enos scenario launch e2e_ui_aws_ent builder:local
yarn run e2e:ent:aws
```
https://hashicorp.atlassian.net/browse/ICU-14076
> test(e2e): Add check to detach bucket from target

- addons/api/mirage/factories/worker.js
- addons/core/translations/resources/en-us.yaml
- ui/admin/app/controllers/scopes/scope/workers/index.js
- ui/admin/app/routes/scopes/scope/workers/index.js
- ui/admin/app/styles/app.scss
- ui/admin/app/templates/scopes/scope/workers/index.hbs
- ui/admin/tests/acceptance/workers/list-test.js
When viewing the workers table, you can now quickly view the tags on a worker with an Hds Flyout
https://github.com/hashicorp/boundary-ui/assets/29386339/d8534048-50ce-46e0-b763-94ca83620a99
Example of a key that is longer than 16 characters
Visit vercel build and view workers. You should be able to click on the tags count in a table row and view the tags for that specific worker. If there are 10 or more tags, it should only show 10 and navigate the user to the worker route.
> Icu 13889 update tags column to action that opens hds flyout and add link to tags tab if more than 10 tags

- addons/core/translations/resources/en-us.yaml
- ui/admin/app/components/workers/worker/actions/index.hbs
- ui/admin/app/components/workers/worker/header/index.hbs
- ui/admin/app/components/workers/worker/nav/index.hbs
- ui/admin/app/controllers/scopes/scope/workers/worker/tags.js
- ui/admin/app/router.js
- ui/admin/app/routes/scopes/scope/workers/worker/tags.js
- ui/admin/app/templates/scopes/scope/workers/index.hbs
- ui/admin/app/templates/scopes/scope/workers/worker/index.hbs
- ui/admin/app/templates/scopes/scope/workers/worker/tags.hbs
- ui/admin/tests/acceptance/workers/delete-test.js
- ui/admin/tests/acceptance/workers/list-test.js
- ui/admin/tests/acceptance/workers/tags-test.js
- ui/admin/tests/integration/components/workers/worker/actions/index-test.js
- ui/admin/tests/integration/components/workers/worker/header/index-test.js
- ui/admin/tests/integration/components/workers/worker/nav/index-test.js
- ui/admin/tests/unit/controllers/scopes/scope/workers/worker/tags-test.js
- ui/admin/tests/unit/routes/scopes/scope/workers/worker/tags-test.js
This PR adds the new `/workers/worker/tags` route and table view for displaying worker tags.
NOTE: This does not include removing tags from the details view of a worker yet. That will come in a later PR.
https://github.com/hashicorp/boundary-ui/assets/29386339/5d6c388a-5226-4139-bc35-dc4ba17a60e0
Using the vercel deployment:
Navigate to a worker that has tags and click on the new "Tags" tab of a worker.
> Icu 13892 create tags tab route and view

- ui/desktop/electron-app/config/cli.js
- ui/desktop/electron-app/package.json
- ui/desktop/electron-app/yarn.lock
The previous PR https://github.com/hashicorp/boundary-ui/pull/2356 fixed the permissions issue but had a memory overflow issue again in our build pipeline. Unfortunately it seems like that's a much harder issue to solve for so for now I just fixed the permissions issue from unzipping manually and reverted the other change. 
Here's a [workflow run](https://github.com/hashicorp/boundary-ui-releases/actions/runs/9620711437) to test with and confirm it builds correctly (keep in mind the CLI will still error out when calling the cache daemon currently due to the rename)
Delete your current CLI and let the script download a new one either through building or starting dev. Confirm that the CLI permissions are correct.
- ~[ ] I have …
> chore: 🤖 Fix unzip permissions part 2: electric boogaloo

- ui/desktop/app/routes/scopes/scope/projects/targets/index.js
This reverts commit fc82980d6849e7a747d8cd3f48fd05eaf816afbd.
It turns out this change caused another issue when switching between sessions and targets if there's any active ones.
Before:
https://github.com/hashicorp/boundary-ui/assets/5783847/107c3c8f-b3bc-42ef-a51e-a5974e766fb0
Start up boundary dev and connect to a target. Switch between targets and sessions a few times to confirm it doesn't error out.
- [x I have added before and after screenshots for UI changes
> Revert "fix: 🐛 Fix active session display in targets table (#2321)"

- ui/admin/tests/e2e/helpers/boundary-cli.js
- ui/admin/tests/e2e/helpers/boundary-ui.js
- ui/admin/tests/e2e/tests/alias-ent.spec.js
- ui/admin/tests/e2e/tests/alias.spec.js
- ui/admin/tests/e2e/tests/auth-method-ldap.spec.js
- ui/admin/tests/e2e/tests/auth-method-password.spec.js
- ui/admin/tests/e2e/tests/credential-store-static-ent.spec.js
- ui/admin/tests/e2e/tests/credential-store-static.spec.js
- ui/admin/tests/e2e/tests/session-recording-aws-ent.spec.js
- ui/admin/tests/e2e/tests/session-recording-minio-ent.spec.js
This PR adds some Admin UI e2e tests for Aliases. It attempts to create aliases using 3 different methods
- Create an alias from the target details page
- Create an alias from a new target page
- Create an alias from the aliases page
There were 6 tests added in total, 3 for each edition (CE, ENT).
```
yarn run e2e:ce:docker
yarn run e2e:ent:docker
```
https://hashicorp.atlassian.net/browse/ICU-14084
> test(e2e): Add alias test

- ui/admin/tests/e2e/global-setup.js
- ui/admin/tests/e2e/playwright.config.js
- ui/admin/tests/e2e/tests/pagination.spec.js
This PR adds an e2e test for search and pagination. The test creates 15 targets and interacts with a variety of elements on the targets list page to search and paginate through the list of targets.
Additionally, support for HTTP requests to Boundary was added. The new test makes use of HTTP requests to quickly generate the 15 targets. 
One test was added that works for both CE and Enterprise
```
yarn run e2e:ce:docker
```
https://hashicorp.atlassian.net/browse/ICU-14123
> test(e2e): Add test for search and pagination

- addons/api/addon/abilities/worker.js
- addons/api/addon/models/worker.js
- addons/api/addon/serializers/worker.js
- addons/api/mirage/config.js
- addons/api/mirage/factories/worker.js
- addons/api/mirage/generated/factories/worker.js
- addons/api/tests/unit/abilities/worker-test.js
- addons/api/tests/unit/models/worker-test.js
- addons/api/tests/unit/serializers/worker-test.js
- addons/core/translations/resources/en-us.yaml
- ui/admin/app/components/form/worker/create-tags/index.hbs
- ui/admin/app/components/form/worker/create-tags/index.js
- ui/admin/app/components/form/worker/create-worker-led/index.js
- ui/admin/app/components/form/worker/tag.js
- ui/admin/app/components/workers/worker/actions/index.hbs
- ui/admin/app/controllers/scopes/scope/workers/worker/create-tags.js
- ui/admin/app/router.js
- ui/admin/app/routes/scopes/scope/workers/worker/create-tags.js
- ui/admin/app/styles/app.scss
- ui/admin/app/templates/scopes/scope/workers/worker/create-tags.hbs
- ui/admin/tests/acceptance/workers/create-tags-test.js
- ui/admin/tests/acceptance/workers/tags-test.js
- ui/admin/tests/integration/components/form/worker/create-tags/index-test.js
- ui/admin/tests/integration/components/workers/worker/actions/index-test.js
- ui/admin/tests/unit/controllers/scopes/scope/workers/new-test.js
- ui/admin/tests/unit/controllers/scopes/scope/workers/worker/create-tags-test.js
- ui/admin/tests/unit/routes/scopes/scope/workers/worker/create-tags-test.js
This PR adds the worker tag creation workflow.
~The test, `cannot visit worker create tags without proper permissions`, is still failing and I am not sure why. I am opening this PR for review while I dig into this more. I will push up a fix asap.~
Test has been fixed!
NOTE: I have not added the "no tags" view yet. That will be a later PR.
https://github.com/hashicorp/boundary-ui/assets/29386339/1ecdaf23-e20f-41d1-87ff-a34f0ee5b740
Payload sent to `POST /v1/workers/<workerID>:set-worker-tags`
Visit a worker in the vercel deployment. From here you can create new tags via the "Manage" dropdown and create new tags.
> Icu 13895 create create new tags route and view

- ui/admin/app/templates/scopes/scope/aliases/index.hbs
- ui/admin/app/templates/scopes/scope/auth-methods/index.hbs
- ui/admin/app/templates/scopes/scope/policies/index.hbs
- ui/admin/app/templates/scopes/scope/session-recordings/index.hbs
- ui/admin/app/templates/scopes/scope/session-recordings/session-recording/channels-by-connection/index.hbs
- ui/admin/app/templates/scopes/scope/storage-buckets/index.hbs
- ui/desktop/app/templates/scopes/scope/projects/sessions/index.hbs
- ui/desktop/app/templates/scopes/scope/projects/targets/index.hbs
This PR adds `isVisuallyhidden` attr to the empty columns header in the tables. These empty headers throw accessibility errors when doing yarn upgrade. 
screenshots: 
there shouldn't be any visual changes due to this update 
> fix: 🐛 add visuallyhidden attr to empty table columns

- ui/desktop/electron-app/config/forge.config.js
This PR introduces changes to the DC binary built process. These changes should be merged along with this boundary-ui-releases PR. Otherwise, the pipeline runs will fail.
Changes:
When the `arch` is x64 (electron-forge default) change it to amd64.
When the `platform` is win32 (electron-forge default) change it to `windows`. Otherwise, if win32 is present in the artifact name, the signature process fails because it just accepts windows.
> Add a postMake arch conversion from x64 to amd64

- addons/rose/addon/components/rose/pagination/index.hbs
- addons/rose/addon/components/rose/pagination/index.js
It seems `onPageSizeChange` is now required for pageSize changes. When I had read the [breaking changes](https://helios.hashicorp.design/whats-new/release-notes#400) in HDS originally, I took it as it's only an issue if you didn't manage the query parameters outside of the component but it turns out this was happening with internal logic regardless. The pages themselves work as they were just `a` links with query parameters. 
I added our own function to handle page size changes.
https://github.com/user-attachments/assets/4fcb5da6-8451-4a84-9f97-5af431bcc20b
Use or start up an instance with many resources. Confirm that changing the page sizes works. 
- …
> fix: 🐛 Fix breaking change for changing page size

- ui/admin/app/components/form/worker/create-tags/index.js
🐛 There was a bug when creating new tags for a worker. The `values` array did not have trimmed values to remove the empty space.
https://github.com/user-attachments/assets/6f41b62b-5147-48b8-b2c4-edab6ea01eec
Navigate to the create tags route and create an api tag with a comma separated value `dev, qa` and the request should return a 200.
> fix: 🐛 add trim() to values when creating tags

- ui/desktop/electron-app/src/index.js
- ui/desktop/electron-app/src/services/cache-daemon-manager.js
Added debug statements to allow a user to see how long search requests are taking. Also added a `BOUNDARY_DESKTOP_LOG_LEVEL` which they can set when starting DC to change log levels for now.
Create a build either with a CLI from main or 0.17. Run the DC from your terminal with the `BOUNDARY_DESKTOP_LOG_LEVEL` set to `debug`. 
My binary for mac is located at `boundary-ui/ui/desktop/electron-app/out/Boundary-darwin-arm64/Boundary.app/Contents/MacOS/` and I just run `BOUNDARY_DESKTOP_LOG_LEVEL=debug ./Boundary`
Also running the pipeline for a build [here](https://github.com/hashicorp/boundary-ui-releases/actions/runs/10012570932). Will need to test windows.
- ~[ ] I have added steps to reproduce and test for bug fixes in the …
> feat: 🎸 Add debug logging for search times

- ui/admin/tests/e2e/helpers/boundary-ui.js
- ui/admin/tests/e2e/tests/delete-resources-ent.spec.js
- ui/admin/tests/e2e/tests/delete-resources.spec.js
- ui/admin/tests/e2e/tests/dynamic-host-catalog-aws.spec.js
- ui/admin/tests/e2e/tests/pagination.spec.js
- ui/admin/tests/e2e/tests/session-recording-aws-ent.spec.js
- ui/admin/tests/e2e/tests/session-recording-minio-ent.spec.js
- ui/admin/tests/e2e/tests/ssh-credential-injection-vault-ent.spec.js
- ui/admin/tests/e2e/tests/target-ent.spec.js
- ui/admin/tests/e2e/tests/target.spec.js
This PR updates the Admin UI e2e tests to account for some of changes to the UI
- Worker filters for targets are no longer assigned on creation. They are added separately in a new "Workers" section of the page.
- On some pages, the "Manage" button is no longer a link. It is actually a `button` now, and so one of the selectors for that needed to be updated (it wasn't being caught by `getByTitle`)
Changes affected tests in all 4 scenarios
```
yarn run e2e_ce:docker
enos scenario launch e2e_ui_aws builder:local
yarn run e2e_ce:aws
yarn run e2e_ent:docker
enos scenario launch e2e_ui_aws_ent builder:local
yarn run e2e_ent:aws
```
https://hashicorp.atlassian.net/browse/ICU-14454
> test(e2e): Update tests due to 0.17.0 changes

- addons/api/addon/generated/models/worker.js
- addons/api/addon/models/worker.js
- addons/api/tests/unit/models/worker-test.js
Before:
After:
1. start boundary dev instance
2. create an api tag that has the same key and value as an existing config tag
3. make sure that the count in list view for workers is accurate.
> fix: 🐛 tag count in list view

- ui/desktop/electron-app/package.json
- ui/desktop/electron-app/yarn.lock
Upgrade electron-forge from `7.2.0` to `7.4.0`.
Be aware this PR brings new warnings regarding `node-pty` & friends. But this PR is going to be merge `llb/dc-dependencies-upgrade` were we will fix the mentioned issues in coming PR's.
- Run the desktop client build process locally.
- Run the boundary-ui-releases successfully.
> Upgrade electron-forge from 7.2.0 to 7.4.0

- ui/desktop/electron-app/src/helpers/app-updater.js
Fixes an issue we were seeing where intel macs weren't properly getting auto-updated. We were returning `x64` instead of `amd64` and being unable to find the URL because of that. 
Creating a build [here](https://github.com/hashicorp/boundary-ui-releases/actions/runs/10170588076) and will test on our mac instance.
> fix: 🐛 Fix intel macs not getting proper auto-update prompt

- ui/desktop/app/routes/scopes/scope/projects/sessions/index.js
- ui/desktop/app/routes/scopes/scope/projects/targets/index.js
The main issue is that the daemon returns empty array for targets since it times out. But even after the targets are finished getting cached, they are not displayed in the UI. That is because in first attempt to load the `this.allTargets` variable got set to empty array which was causing the `this.makeAllTargetsQuery` to not even run. As a result the `this.showFilters` check in the template was coming back as false.
Before:
https://github.com/user-attachments/assets/77e9eb06-5f21-4e42-8780-f85bac467e52
After:
https://github.com/user-attachments/assets/0bee5a97-74ae-4b68-bd06-a0719cc0e78c
> fix: 🐛 targets not displaying even after they are cached

- addons/core/translations/errors/en-us.yaml
- ui/desktop/app/components/settings-card/application/index.hbs
- ui/desktop/app/routes/scopes/scope/projects/settings/index.js
- ui/desktop/electron-app/src/utils/generateErrorPromise.js
- ui/desktop/tests/integration/components/settings-card/application-test.js
Displayed errors from cache daemon status for resources that aren't just from the actual status command erroring out. 
I used an old version of the controller that doesn't support resolvable aliases (0.15.x) version and added enough targets where the initial load times out to generate two errors.
> feat: 🎸 Show cache daemon errors from status

- ui/admin/tests/acceptance/storage-buckets/create-test.js
- ui/admin/tests/acceptance/storage-buckets/selectors.js
- ui/admin/tests/acceptance/storage-buckets/update-test.js
follow up to address TODO from this [PR](https://github.com/hashicorp/boundary-ui/pull/2414)
remove duplicate selectors from storage buckets and use common selectors in their place
> Icu 14834 remove duplicate selectors and use common selectors instead

- ui/admin/app/controllers/scopes/scope/session-recordings/session-recording/channels-by-connection/index.js
- ui/admin/app/routes/scopes/scope/session-recordings.js
- ui/admin/app/routes/scopes/scope/session-recordings/session-recording/channels-by-connection.js
- ui/admin/app/templates/scopes/scope/session-recordings/session-recording/channels-by-connection/index.hbs
- ui/admin/tests/unit/controllers/scopes/scope/session-recordings/index-test.js
- ui/admin/tests/unit/controllers/scopes/scope/session-recordings/session-recording/channels-by-connection/index-test.js
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-12620
Remove route-action usage for session recordings
https://github.com/user-attachments/assets/6c64a83f-a7e2-4324-afa6-d05fcc8eb84a
1. Create a session recording using DC & ssh Target
2. Create a storage policy that allows deletion
3. Apply that storage policy to the global scope
4. Navigate to session-recording
5. Click "Manage" -> "Re-apply storage policy"
6. Card should update with correct time in "Delete after" row
7. Click "Manage" -> "Delete"
8. Session recording should be removed
> refactor: 💡 remove route-action usage for session recordings

- addons/core/translations/en-us.yaml
- ui/desktop/app/components/settings-card/server/index.hbs
This pr removes the `connected` label to avoid confusion when the controller gets disconnected and the page isn't refreshed. see this slack [thread](https://hashicorp.slack.com/archives/C012GTH1C4E/p1724096649298689) 
https://hashicorp.atlassian.net/browse/ICU-14885
> fix: 🐛 remove connected label

- ui/admin/tests/e2e/global-setup.mjs
- ui/admin/tests/e2e/helpers/boundary-http.mjs
- ui/admin/tests/e2e/helpers/boundary-http/scopes.mjs
- ui/admin/tests/e2e/helpers/boundary-http/targets.mjs
- ui/admin/tests/e2e/pages/login.mjs
- ui/admin/tests/e2e/pages/roles.mjs
- ui/admin/tests/e2e/pages/session-recordings.mjs
- ui/admin/tests/e2e/pages/targets.mjs
- ui/admin/tests/e2e/tests/auth-method-ldap.spec.mjs
- ui/admin/tests/e2e/tests/auth-method-password.spec.mjs
- ui/admin/tests/e2e/tests/login.spec.mjs
- ui/admin/tests/e2e/tests/pagination.spec.mjs
- ui/admin/tests/e2e/tests/session-recording-aws-ent.spec.mjs
- ui/admin/tests/e2e/tests/session-recording-minio-ent.spec.mjs
- ui/admin/tests/e2e/tests/target.spec.mjs
This PR has some additional refactoring of the Admin UI e2e test suite
- HTTP API requests were moved to helper methods. The plan is for these methods to be shared with the Desktop e2e test suite
- Some additional page object methods were created
https://hashicorp.atlassian.net/browse/ICU-14776
> refact(e2e): Create HTTP methods and more page objects

- ui/desktop/electron-app/yarn.lock
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-14212
Manually force `is-my-json-valid@^2.20.0` to resolve to v2.20.6 which upgrades its dependency on `jsonpointer` to v5.
Resolves:
[#127](https://github.com/hashicorp/boundary-ui/security/dependabot/127)
[#78](https://github.com/hashicorp/boundary-ui-enterprise/security/dependabot/78)
1. `yarn start` in `ui/admin`
2. `yarn start:desktop` in `ui/desktop` 
3. [Release workflow passes](https://github.com/hashicorp/boundary-ui-releases/actions/runs/10587718918) using this [branch](https://github.com/hashicorp/boundary-ui/tree/1.2.3-beta.lyalvare)
> chore: 🤖 upgrade jsonpointer to v5

- ui/desktop/README.md
- ui/desktop/electron-app/config/cli.js
Add CLI_SETUP and delete BYPASS_CLI_BUILD.
Note: This PR needs to be sync [with a counterpart within boundary-ui-releases](https://github.com/hashicorp/boundary-ui-releases/pull/107), since the BYPASS_CLI_BUILD is use there.
Note 2: This is merging to a LLB which will contain all the changes to achieve Desktop Client with no CLI
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-14904)
- Navigate to `electron-app/cli` and clean up the directory.
- Run `SETUP_CLI=true`
- Desktop client should download the CLI and start.
- To validate CLI has been downloaded, navigate to `electron-app/cli` and confirm the CLI is present.
- Run `yarn start:desktop`, in the terminal you should see a warning: `WARNING: Bypassing cli setup`.
- Desktop client should start no problem.
> Add CLI_SETUP and delete BYPASS_CLI_BUILD

- package.json
- yarn.lock
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-14214
Used `yarn why request` and that dependency wasn't being used anywhere.
Remove `request` resolution and as a result dependency on `tough-cookie` also was removed.
1. go to vercel deployments and make sure everything is running as it should.
2. run `yarn` locally and validate no new warnings appear.
3. [boundary-ui-releases run passed](https://github.com/hashicorp/boundary-ui-releases/actions/runs/10619247404) using this [branch](1.2.3-beta.toughcookie)
> chore: 🤖 remove request unused dependency resolution

- ui/desktop/app/components/settings-card/client-agent/index.js
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-14963
The pr fixes session getting unauthorized on the route refresh, I noticed the session data becomes empty during the application route's beforemodel [hook](https://github.com/hashicorp/boundary-ui/blob/0cfa814cdd05e7ca83d05179d601887d4bcf9610/ui/desktop/app/initializers/cluster-url.js#L20) when an HCP cluster URL is used, causing an abrupt logout. 
Passing in the full route name fixes the issue. 
https://github.com/user-attachments/assets/cd66f581-da98-4cc9-b477-f60edc3fd20d
[Use the 0.20.0 installer](https://github.com/hashicorp/boundary-installer/actions/runs/10635747837). It contains DC 2.2.0-beta.ts.1, which has 0.17.0 CLI.
Open DC and connect to an HCP cluster. [let me know if you need one to test]
Wait until targets load. …
> fix: 🐛 pass current url to maintain session

- addons/core/translations/resources/en-us.yaml
Jeff noticed a typo in our description for vault ssh certificates cred library page. 
> style: 💄 Fix text description

- addons/core/translations/actions/en-us.yaml
- ui/desktop/app/components/settings-card/application/index.hbs
- ui/desktop/app/components/settings-card/client-agent/index.hbs
- ui/desktop/app/styles/app.scss
- ui/desktop/app/templates/scopes/scope/projects/settings/index.hbs
- ui/desktop/tests/integration/components/settings-card/application-test.js
- ui/desktop/tests/integration/components/settings-card/client-agent-test.js
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-14961
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-14962
Hide the initial errors behind a `reveal` so they don't distract the user if they don't care about them. Also moved the user and server cards up.
Use this [50k cluster](https://27425825-515c-4d8c-beb6-aa91cbc20c5a.boundary.hcp.to) which should time out loading the cache daemon initially or use a CE boundary edition to generate errors for the client agent daemon. 
> feat: 🎸 Hide daemon errors initially

- ui/desktop/electron-app/yarn.lock
- yarn.lock
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-14213
This is related to this [dependabot alert](https://github.com/hashicorp/boundary-ui/security/dependabot/114) to upgrade semver.
I cleaned up `core-js-compat` to remove some of the odd versions of semver.
[release pipeline test](https://github.com/hashicorp/boundary-ui-releases/actions/runs/10708975652)
> chore: 🤖 upgrade semver versions

- addons/api/addon-test-support/handlers/cache-daemon-search.js
- addons/api/addon/handlers/cache-daemon-handler.js
- addons/core/addon/styles/addon.scss
- addons/core/translations/states/en-us.yaml
- ui/desktop/app/controllers/scopes/scope/projects/sessions/index.js
- ui/desktop/app/controllers/scopes/scope/projects/targets/index.js
- ui/desktop/app/routes/scopes/scope/projects/sessions/index.js
- ui/desktop/app/routes/scopes/scope/projects/targets/index.js
- ui/desktop/app/templates/scopes/scope/projects/sessions/index.hbs
- ui/desktop/app/templates/scopes/scope/projects/targets/index.hbs
- ui/desktop/electron-app/src/helpers/request-promise.js
- ui/desktop/electron-app/src/utils/generateErrorPromise.js
- ui/desktop/tests/acceptance/projects/sessions/index-test.js
- ui/desktop/tests/acceptance/projects/targets/index-test.js
- ui/desktop/tests/acceptance/projects/targets/target-test.js
- ui/desktop/tests/acceptance/scopes-test.js
There have been quite a few changes to how we handle responses. The cache daemon will now truncate any response that returns more than 250 items. They will also now return a `incomplete` response to indicate that the response was truncated as well as a `refresh_status` to indicate if they're still building the cache in the background. The latter will also be used eventually when partial results are returned.
These two new fields are independent which means for example we could have an incomplete response and still be refreshing in the background or a complete response and still be refreshing in the background. 
I've also made a change to always show the filters so the user has access to the refresh button. This is mainly needed as we will eventually return partial responses and for users …
> Use updated cache daemon

- ui/desktop/electron-app/src/services/cache-daemon-manager.js
I missed a check when the client daemon was renamed to cache daemon. This accidentally caused us to kill a user started cache daemon. 
Start the daemon before the DC and close the DC after logging in. The daemon should still be running. 
> fix: 🐛 Fix daemon getting killed if started before DC

- package.json
- yarn.lock
Adding resolution for micromatch removes the need for resolution on braces since braces is a dep. of micromatch. 
Below are the dependencies that use micromatch:
- micromatch@^3.1.4 -> anymatch@^2.0.0 -> sane@^4.0.0 -> broccoli@^3.5.2 -> **ember-cli@^4.12.2**
- micromatch@^3.1.4 -> sane@^4.0.0 -> broccoli@^3.5.2 -> **ember-cli@^4.12.2**
- micromatch@^3.1.4 -> find-yarn-workspace-root@^1.2.1 -> **ember-cli-dependency-checker@^3.3.2**
We should def. update ember-cli to v5 (i added as a techtime topic). Resolution will still be needed because we are already using newest version of **ember-cli-dependency-checker**.
Resolve dependabot alerts [#156](https://github.com/hashicorp/boundary-ui/security/dependabot/156l) && [#106](https://github.com/hashicorp/boundary-ui-enterprise/security/dependabot …
> chore: 🤖 add resolution for micromatch

- yarn.lock
Resolve dependabot alerts: [#159](https://github.com/hashicorp/boundary-ui/security/dependabot/159) [#160](https://github.com/hashicorp/boundary-ui/security/dependabot/160) [#161](https://github.com/hashicorp/boundary-ui/security/dependabot/161)
1. path-to-regexp@0.1.7 -> **express@^4.18.1** -> ember-cli@^4.12.2
* Forced `express@^4.10.7, express@^4.18.1` to resolve to `v4.20.0` & fixed path-to-regexp issue
3. path-to-regexp@0.1.7  -> **express@^4.10.7** -> testem@^3.10.1 -> ember-cli@^4.12.2
* Forced `express@^4.10.7, express@^4.18.1` to resolve to `v4.20.0` & fixed path-to-regexp issue
4. path-to-regexp@^6.2.1 -> **nise@^6.0.0** -> sinon@^18.0.0
* Forced `nise@^6.0.0` to resolve to `v6.0.1` to fix path-to-regexp issue
5. forced `body-parser@1.20.3, body-parser@^1.17.0, …
> Chore resolve path to regexp vulnerability

- addons/core/addon/helpers/format-time-duration.js
- addons/core/addon/helpers/time-remaining.js
- addons/core/addon/utils/seconds-to-duration.js
- addons/core/app/utils/seconds-to-duration.js
- addons/core/package.json
- addons/core/tests/integration/helpers/time-remaining-test.js
- addons/core/tests/unit/utils/seconds-to-duration-test.js
- yarn.lock
NOTE: I did upgrade webpack in this branch to verify that this fixed the build issues and it... DOES! Once this PR is merged, I will get the webpack PR updated and verify it is working.
This PR is replacing `intl-unofficial-duration-unit-format` with `@formatjs/intl-durationformat`. This is to help us get the [webpack upgrade](https://github.com/hashicorp/boundary-ui/security/dependabot/158) ([PR](https://github.com/hashicorp/boundary-ui/pull/2466)) into a working state.
The issue with `intl-unofficial-duration-unit-format` is due to an [export path](https://github.com/piuccio/intl-unofficial-duration-unit-format/issues/33) format in the released versions. Instead of patching this fix, we took this time to replace this package with the newer `@formatjs/intl-durationformat` polyfill.
One …
> Add duration unit format

- ui/desktop/electron-app/src/ipc/handlers.js
This is a fix for an issue found in a security audit. (see ticket for more details).
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-13242
My thinking here is we cannot check the whole `href` as the port is dynamic. However, adding a `:` at the end should prevent someone from using a clusterURL similar to these: `http://localhost.somedomain.com/`, `http://localhostdomain.com/`.
Using the Desktop Client, authenticate using an OIDC auth-method and it should still be able to trigger opening a window in your browser if using `http://localhost:xxxx`.
> fix: 🐛 add regex literal for isLocalHost check

- addons/core/translations/resources/en-us.yaml
- ui/admin/app/routes/scopes/scope/session-recordings/session-recording/channels-by-connection/channel/index.js
- ui/admin/app/templates/scopes/scope/session-recordings/session-recording/channels-by-connection/channel/index.hbs
- ui/admin/tests/acceptance/session-recordings/session-recording/channels-by-connection/channel-test.js
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-11148
[slack thread for context](https://hashicorp.slack.com/archives/C012GTH1C4E/p1726092296630819)
Add alert messages for api errors when failing to download recording.
Update app state title to be more generic.
https://github.com/user-attachments/assets/daa10214-b2fb-4362-88f9-017cb8fe7c15
1. Create a session-recording
2. Modify any one of the session-recording files in the aws s3 storage bucket
3. Navigate to the session-recording channel
4. Attempt to play the recording and observe the error being displayed as an alert.
> refactor: 💡 change channel app state title & add alert msg

- package.json
- yarn.lock
Upgrade git-cz from 4.8.0 to 4.9.0. [As per git-cz changelog](https://github.com/streamich/git-cz/blob/master/CHANGELOG.md), there are no breaking changes
- This dependency is used when we commit, so no need for the boundary-ui-releases run.
- The test of this change is the PR itself. The committ has been performed under `4.9.0` without issues. The PR title and description were generated with it.
> chore: 🤖 Upgrade git-cz

- package.json
- patches/lodash.template+4.5.0.patch
- ui/desktop/electron-app/package.json
- ui/desktop/electron-app/patches/lodash.template+4.5.0.patch
- ui/desktop/electron-app/yarn.lock
- yarn.lock
This is a patch for `lodash.template` that is vulnerable to Command Injection via the template function.
There is a second patch for the electron-app project as well.
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-14208)
🤖 [Dependabot Alert](https://github.com/hashicorp/boundary-ui/security/dependabot/143)
🤖 [Electron Dependabot Alert](https://github.com/hashicorp/boundary-ui/security/dependabot/143)
> Icu 14208 vulnerabilities in boundary UI enterprise lodash template 4 5 0 in yarn lock

- package.json
- yarn.lock
Fixes dependabot alert [#163](https://github.com/hashicorp/boundary-ui/security/dependabot/163)
We can probably get rid of the resolution on `send` once we upgrade `ember-cli`
`send@0.18.0 -> serve-static@1.16.0 -> express@^4.10.7 -> testem@^3.10.1 -> ember-cli@^4.12.2`
`send@0.18.0 -> serve-static@1.16.0 -> express@^4.18.1 -> ember-cli@^4.12.2`
* Exact versions of send are used so adding a resolution was only option. Attempting to force a resolution on the dependencies that use `send` didn't change anything.
1. `yarn start` in `ui/admin`
2. `yarn start:desktop` in `ui/desktop`
3. [boundary-ui-releases test run](https://github.com/hashicorp/boundary-ui-releases/actions/runs/10853523515) using branch `1.2.3-beta.send`
> chore: 🤖 add resolution for send

- ui/desktop/app/components/credentials-panel/index.hbs
- ui/desktop/app/components/credentials-panel/index.js
- ui/desktop/app/helpers/order-by.js
- ui/desktop/tests/integration/helpers/order-by-test.js
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-15105
This PR moves up `username` field  
before:
after:
with a JSON blob: 
> fix: show username first and then password when credentials are listed

- ui/desktop/app/components/settings-card/application/index.js
- ui/desktop/tests/integration/components/settings-card/application-test.js
- ui/desktop/tests/integration/components/settings-card/client-agent-test.js
- ui/desktop/tests/integration/components/settings-card/logs-test.js
- ui/desktop/tests/integration/components/settings-card/server-test.js
- ui/desktop/tests/integration/components/settings-card/user-test.js
I found a bug where the theme selector dropdown wasn't properly selecting the saved theme when revisiting the page. The issue was this line:
https://github.com/hashicorp/boundary-ui/blob/ba2b62ba5fa7977393f244c5780339b0bc84fb0c/ui/desktop/app/components/settings-card/application/index.hbs#L78
didn't have access to the session service.
> fix: 🐛 Fix theme selector not properly selecting option

- addons/api/addon/handlers/cache-daemon-handler.js
- addons/core/addon/components/loading-button/index.hbs
- addons/core/addon/components/toolbar-refresher/index.hbs
- addons/core/addon/components/toolbar-refresher/index.js
- addons/core/addon/styles/addon.scss
- addons/core/tests/integration/components/loading-button-test.js
- addons/core/translations/states/en-us.yaml
- ui/admin/app/templates/scopes/scope/sessions/index.hbs
- ui/desktop/app/routes/scopes/scope/projects/targets/index.js
- ui/desktop/app/templates/scopes/scope/projects/sessions/index.hbs
- ui/desktop/app/templates/scopes/scope/projects/targets/index.hbs
Changed the two alerts at the top of the page to a tooltip and nearer pagination.
I also updated the toolbar refreshing tool to use HDS components which will also affect admin UI.
﻿Before:
After:
Admin UI:
Start up desktop client with a CLI built from the [boundary cache speedup llb](https://github.com/hashicorp/boundary/tree/llb-cache-speedup). Test against a cluster with at least 50k targets, you can use my HCP cluster [here](https://27425825-515c-4d8c-beb6-aa91cbc20c5a.boundary.hcp.to), or I can whitelist you on my 1M targets cluster. 
Also confirm the refresh button works in admin UI on the sessions and workers page.
- ~[ ] I have added tests that …
> feat: 🎸 Update alert designs

- addons/api/addon/services/indexed-db.js
- addons/api/mirage/config.js
- addons/api/tests/unit/utils/indexed-db-query-test.js
- addons/core/translations/actions/en-us.yaml
- addons/core/translations/resources/en-us.yaml
- ui/admin/app/controllers/scopes/scope/session-recordings/index.js
- ui/admin/app/routes/scopes/scope/session-recordings.js
- ui/admin/app/routes/scopes/scope/session-recordings/index.js
- ui/admin/app/routes/scopes/scope/session-recordings/session-recording/channels-by-connection/channel.js
- ui/admin/app/templates/scopes/scope/session-recordings/index.hbs
- ui/admin/tests/acceptance/session-recordings/list-test.js
- ui/admin/tests/acceptance/session-recordings/read-test.js
- ui/admin/tests/acceptance/session-recordings/session-recording/channels-by-connection/channel-test.js
- ui/admin/tests/unit/controllers/scopes/scope/session-recordings/index-test.js
This adds pagination support for Session Recordings along with search for `session-recording.id` and filters for user and target.
Another change that is made in this PR is how we handle redirects for the `scopes.scope.session-recordings.session-recording.channels-by-connection.channel` route. If the user has entered a URL where the session recording ID is wrong, we redirect the user back to the list view and display a toast message.
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-15181)
Search and filter:
https://github.com/user-attachments/assets/8c748e27-898f-4443-a978-e01f571824c7
Redirect change:
https://github.com/user-attachments/assets/41eb6cde-7e64-4c94-96dc-619da173683a
Create sessions with targets that have recording enabled. After creating a few, you should …
> Icu 15181 add pagination to session recordings

- ui/admin/tests/e2e/pages/workers.mjs
- ui/admin/tests/e2e/tests/worker-tags.spec.mjs
This PR adds an e2e test worker API tags. 
- It adds an API tag to a worker
- Edits the API tag
- Deletes the API tag
https://github.com/user-attachments/assets/81de7fa0-ad3c-483e-a12b-6b647c841ae9
One test was added that works for both CE and Enterprise using either docker or AWS infrastructure
```
yarn run e2e:ce:docker
enos scenario launch e2e_ui_aws builder:local
yarn run e2e:ce:aws
```
https://hashicorp.atlassian.net/browse/ICU-14505
> test(e2e): Add test for worker tags

- ui/desktop/electron-app/src/cli/index.js
- ui/desktop/electron-app/src/cli/path.js
- ui/desktop/electron-app/src/helpers/app-updater.js
- ui/desktop/electron-app/src/helpers/spawn-promise.js
[ICU-15109](https://hashicorp.atlassian.net/browse/ICU-15109)
Add check on the appUpdater to skip it if the Desktop client is NOT using the built in CLI.
**IMPORTANT**
The first approach I tried was to use node [fs.lstatSync](https://nodejs.org/api/fs.html#fslstatsyncpath-options). The issue I encounter is that the lstat object returned, in POSIX systems, the key `file` always `false` value.
This happens because on POSIX system, the binary name we return is `boundary` without file extension, therefore the lstat object mark it as directory, whatever we were passing `boundary` or `electron-app/cli/boundary`.
Decided to rely on [parsing the path](https://nodejs.org/api/path.html#pathparsepath). If the parsed object returns values for the keys `dir` and `root`, means it is indeed the CLI …
> appupdater cli check

- ui/desktop/electron-app/src/cli/path.js
[ticket](https://hashicorp.atlassian.net/browse/ICU-15235) 
This PR fixes the app crashing on launch in windows
- pull this branch to a Windows machine/parallels/ec2 instance
- install CLI locally using [this](https://github.com/hashicorp/boundary-installer/actions/runs/10966402384) click on the Windows build and follow the instructions to install
- delete `CLI` folder from `ui/desktop/electron-app` to make sure we don't package cli in our DC build 
- build it locally `yarn build` within ui/desktop
- go to the directory where the out/boundary binary is stored and click on boundary.exe app 
- the app should run as expected and not crash 
note: Plz reach out to me if you need a cluster for testing
- ~[ ] I have added JSON …
> Fix windows no cli crash

- ui/admin/tests/e2e/pages/auth-methods.mjs
- ui/admin/tests/e2e/tests/alias-ent.spec.mjs
- ui/admin/tests/e2e/tests/alias.spec.mjs
This PR updates some Admin UI e2e tests based on testing it against Boundary 0.18.0. There were two changes here
- On the Auth Methods page, the `Manage` button and some of its options were not being found by the current selectors. Those selectors were updated.
- On the Alias test, for some reason, it was starting to fail more often due to what seems like a timing issue. The test's intention is to navigate from the Target details page to the associated Alias details page in order to clear its value. What seems like is happening...
- Test is on Target details page
- Test clicks on associated Alias to go to Alias details page
- Test clicks Manage button
- It seems like the test is clicking the Manage button on the Target details page (before the Alias page finishes loading)
- The PR now …
> test(e2e): Updates from 0.18.0 testing

- ui/admin/app/controllers/scopes/scope/authenticate/method/oidc.js
- ui/admin/app/templates/scopes/scope/authenticate/method/oidc.hbs
- ui/admin/tests/unit/controllers/scopes/scope/authenticate/method/oidc-test.js
- ui/desktop/electron-app/src/index.js
- ui/desktop/electron-app/src/ipc/handlers.js
- ui/desktop/electron-app/src/utils/isLocalhost.js
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-15250
retry was broken for both admin & desktop.
Admin retry was broken due to this [refactor](https://github.com/hashicorp/boundary-ui/pull/2385)
Desktop retry has been broken for quite some time already.
Uploading Screen Recording 2024-10-07 at 4.46.03 PM.mov…
1. spin up local dev instance
2. use existing oidc auth method to sign in.
3. retry link should cause new browser to open.
> fix: 🐛 cannot retry oidc authentication in desktop & admin

- ui/desktop/app/routes/scopes/scope/projects/sessions/index.js
Fixes the bug here described in this slack [thread](https://hashicorp.slack.com/archives/C05EHAH84HE/p1728507679515329).
As users can now start sessions with transparent sessions, we aren't guaranteed that they have navigated to the target first in the DC so it may not yet be in the store.
Before:
After:
Use the installer to install the client agent. Make sure you're using a cluster that has enough targets where it won't be able to load all targets on one page. (Use my [int cluster](https://27425825-515c-4d8c-beb6-aa91cbc20c5a.boundary.hcp.to) if you'd like). 
Connect to a generic TCP target (make sure it wasn't loaded on the first page) transparently and go to sessions (use www.hashicorp.com in your browser if using my int cluster). It should have the target name displayed. 
- ~[ ] I …
> fix: 🐛 Push associated targets in sessions to ember store

- ui/desktop/package.json
Clean up Desktop out directory before perform a build.
- Have the `electron-app/out` directory fill with a test.txt file (or any other file none related to the build).
- Perform a `yarn build` from `boundary-ui/ui/desktop` and validate the `out` directory just contains build output.
> chore: 🤖 Clean up Desktop out directory

- ui/desktop/electron-app/yarn.lock
- yarn.lock
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-14207
forcing `socks` package to resolve to newest version removed the need for the `ip` package that has security vulnerabilities. 
This will close out alert [#145](https://github.com/hashicorp/boundary-ui/security/dependabot/145) & [#146](https://github.com/hashicorp/boundary-ui/security/dependabot/146)
1. Validate admin ui builds and runs as expected locally
2. Validate desktop ui builds and runs as expected locally
3. boundary-ui-releases: [Test Run](https://github.com/hashicorp/boundary-ui-releases/actions/runs/11413318125)
> chore: 🤖 resolve socks to new version to fix ip vulnerability

- ui/desktop/.template-lintrc.js
- ui/desktop/app/controllers/scopes/scope/projects/sessions/index.js
- ui/desktop/app/controllers/scopes/scope/projects/sessions/session.js
- ui/desktop/app/controllers/scopes/scope/projects/targets/index.js
- ui/desktop/app/controllers/scopes/scope/projects/targets/target.js
- ui/desktop/app/routes/scopes/scope/projects/sessions.js
- ui/desktop/app/routes/scopes/scope/projects/targets/target.js
- ui/desktop/app/templates/scopes/scope/projects/sessions/index.hbs
- ui/desktop/app/templates/scopes/scope/projects/sessions/session.hbs
- ui/desktop/app/templates/scopes/scope/projects/targets/index.hbs
- ui/desktop/app/templates/scopes/scope/projects/targets/target.hbs
- ui/desktop/tests/unit/controllers/scopes/scope/projects/sessions/index-test.js
- ui/desktop/tests/unit/controllers/scopes/scope/projects/sessions/session-test.js
- ui/desktop/tests/unit/controllers/scopes/scope/projects/targets/index-test.js
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-15040
remove route action usage for targets and sessions
Connecting from targets list view "Connect" button && targets details view "Connect" button
1. Navigate to targets list view or details view
2. Connect to a target with address
3. Connect to a target with 1 host
* no modal should pop up
4. Connect to a target with 2 hosts (also test quick connect)
* modal with all hosts in host set should appear
5. Connect to a target with no address & no host set
* error modal with retry and cancel button should appear
* test retry and test cancel
* Host modal should **not** appear
6. Test that "Refresh" button works as expected.
Sessions
1. Navigate to existing session details page
2. Click "End Session", and validate session is canceling
3. …
> refactor: 💡 remove route-action usage for targets and sessions

- ui/admin/app/abilities/storage-bucket.js
- ui/admin/app/controllers/scopes/scope/storage-buckets/index.js
- ui/admin/app/templates/scopes/scope/storage-buckets/storage-bucket/index.hbs
- ui/admin/tests/acceptance/storage-buckets/delete-test.js
https://hashicorp.atlassian.net/browse/ICU-15625
this PR enables storage bucket deletion in the UI 
- create a storage bucket either on mirage or using ent binary
- should be able to successfully delete the bucket that was created
> Enable storage bucket deletion 

- ui/admin/tests/acceptance/groups/delete-test.js
- ui/admin/tests/acceptance/host-catalogs/hosts/create-test.js
- ui/admin/tests/acceptance/host-catalogs/hosts/selectors.js
- ui/admin/tests/acceptance/roles/delete-test.js
- ui/admin/tests/acceptance/users/delete-test.js
- Update test selectors for host-catalog -> create host.
- A couple of files were missing the format, so add them within this PR after running `(ui/admin$): yarn format`
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-15497)
Run the test suite successfully within `ui/admin`: `(ui/admin)$: yarn test`
> Update test selectors for create hosts

- addons/api/package.json
- addons/auth/package.json
- addons/core/package.json
- addons/rose/package.json
- ui/admin/package.json
- ui/desktop/package.json
- yarn.lock
- Upgrade qunit-dom from `2.0.0` to `3.2.1`.
- Upgrade quunit from `2.19.4` to `2.22.0`.
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-15660)
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-15661)
- Run test suite successfully, since `qunit-dom` is use in our tests.
> chore: 🤖 Upgrade qunit-dom

- addons/core/translations/en-us.yaml
- ui/admin/app/components/worker-filter/index.hbs
- ui/admin/app/components/worker-filter/index.js
- ui/admin/app/templates/scopes/scope/targets/target/edit-egress-worker-filter.hbs
- ui/admin/app/templates/scopes/scope/targets/target/edit-ingress-worker-filter.hbs
- ui/admin/config/environment.js
- ui/admin/tests/integration/components/worker-filter/index-test.js
Add show filter generator toggle.
This PR excludes radio button group functionality.
https://github.com/user-attachments/assets/db41c2ac-3dc6-49c8-819e-5166f3ce38cf
1. Go to target details
2. Click on "Workers" tab
3. Click on "Edit egress worker filter"
4. Toggle should work as expected and be visible.
> Icu 15741 add show filter generator toggle to worker filter component

- .husky/pre-commit
- .husky/prepare-commit-msg
- package.json
- yarn.lock
Upgrade and migrate Husky from `v8` to `v9.1.6`
Followed the [migration guide](https://github.com/typicode/husky/releases/tag/v9.0.1).
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-15773)
- Run any task that requires Husky, a `commit` for example.
> chore: 🤖 Upgrade and Migrate husky from v8 to v9

- addons/core/translations/resources/en-us.yaml
- ui/admin/app/components/credential-stores/credential-store/nav/index.hbs
- ui/admin/app/controllers/scopes/scope/credential-stores/credential-store/worker-filter.js
- ui/admin/app/router.js
- ui/admin/app/routes/scopes/scope/credential-stores/credential-store/worker-filter.js
- ui/admin/app/styles/app.scss
- ui/admin/app/templates/scopes/scope/credential-stores/credential-store/worker-filter.hbs
- ui/admin/tests/unit/controllers/scopes/scope/credential-stores/credential-store/worker-filter-test.js
- ui/admin/tests/unit/routes/scopes/scope/credential-stores/credential-store/worker-filter-test.js
This PR adds a new route for Credential Stores > Worker Filters when state is empty. See Jira [ticket](https://hashicorp.atlassian.net/browse/ICU-15718).
> [ICU-15718] Add worker filter route, template for empty state

- ui/desktop/app/templates/cluster-url.hbs
- ui/desktop/package.json
- yarn.lock
Migrate embe-autofocus-modifier to HTML autofocus standard. [More info within the Jira ticket](https://hashicorp.atlassian.net/browse/ICU-15798)
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-15798)
Before:
After:
- Run the desktop client, navigate to the change cluster page and make sure at loading, it autofocus the cluster url input.
> Migrate embe-autofocus-modifier to HTML autofocus standard

- addons/core/translations/resources/en-us.yaml
- ui/admin/app/components/form/credential-store/vault/index.hbs
This PR removes the `worker_filter` input field from the vault credential store form.
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-15721)
Before:
After:
> [ICU-15721] Remove worker filter input field

- ui/desktop/tests/acceptance/application-test.js
- ui/desktop/tests/acceptance/authentication-test.js
- ui/desktop/tests/acceptance/cluster-url-test.js
- ui/desktop/tests/acceptance/projects-test.js
- ui/desktop/tests/acceptance/projects/sessions/index-test.js
- ui/desktop/tests/acceptance/projects/targets/index-test.js
- ui/desktop/tests/acceptance/scopes-test.js
Add await to `invalidSession` from `ember-simple-auth` within `ui/desktop`.
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-15875)
- Run desktop tests successfully
> refactor: 💡 Add await to invalidSession within desktop

- ui/admin/app/templates/scopes/scope/targets/target/workers.hbs
The icon in the accordion for Target egress worker filter was only showing the `edit` icon. Update adds logic to dynamically change the icon depending if the egress worker filter has been set or not.
Before:
After:
> refactor: 💡 update icon logic for egress worker filter

- addons/core/translations/form/en-us.yaml
- ui/admin/app/components/form/alias/index.hbs
- ui/admin/app/components/form/credential-library/vault-generic/index.hbs
- ui/admin/app/components/form/credential-library/vault-ssh-certificate/index.hbs
- ui/admin/app/components/form/credential-store/static/index.hbs
- ui/admin/app/components/form/credential-store/vault/index.hbs
- ui/admin/app/components/form/credential/json/index.hbs
- ui/admin/app/components/form/credential/ssh_private_key/index.hbs
- ui/admin/app/components/form/credential/username_password/index.hbs
- ui/admin/app/components/form/host-catalog/aws/index.hbs
- ui/admin/app/components/form/host-catalog/azure/index.hbs
- ui/admin/app/components/form/host-catalog/static/index.hbs
- ui/admin/app/components/form/storage-bucket/aws/index.hbs
- ui/admin/app/components/form/storage-bucket/minio/index.hbs
- ui/admin/app/components/form/target/details/index.hbs
- ui/admin/tests/acceptance/host-catalogs/create-test.js
- ui/admin/tests/acceptance/storage-buckets/create-test.js
- ui/admin/tests/acceptance/storage-buckets/selectors.js
- ui/admin/tests/acceptance/targets/create-test.js
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-15676
This fixes an a11y audit issue where the `name` attribute for our radio card groups did not match. In a few places, the name matched the value but the name should be the same for all radio options.
I opted to simply use `Type` as the name value in most cases, except `plugin_type` which I created a new translation entry for. If we feel we need to be more specific for each resource type I can make that refactor.
Before:
After:
To test you can use the vercel build and create a new credential store. When you inspect the input for the Radio Cards the `name` attribute should be the same for both now.
> fix: 🐛 update @name attribute for RadioCard Groups

- e2e-tests/.gitignore
- e2e-tests/desktop/fixtures/electronTest.js
- e2e-tests/desktop/playwright.config.js
- e2e-tests/desktop/tests/sessions.spec.js
- e2e-tests/desktop/tests/targets.spec.js
- e2e-tests/global-setup.js
- e2e-tests/package.json
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-14778
Added more session tests. Also added support for dotenv which lets us use .env files and removed usages of relative paths which makes it difficult to run if you're not in the root.
Let me know if you get any test failures, there were flaky tests at times due to sessions being canceled/terminated which can affect other test runs but it _should_ be consistent now.
Run `yarn desktop` in the e2e folder.
> Icu 14778 add more sessions tests

- ui/admin/tests/acceptance/credential-library/delete-test.js
- ui/admin/tests/acceptance/credential-library/list-test.js
- ui/admin/tests/acceptance/credential-library/selectors.js
delete and list
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-15468 (Delete)
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-15469 (List)
> test: 💍 update selectors for credential-library tests

- ui/admin/app/components/form/field/list-wrapper/key-value/index.hbs
- ui/admin/app/components/form/field/list-wrapper/key-value/select.hbs
- ui/admin/app/components/form/field/list-wrapper/key-value/text.hbs
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-15701
I noticed this slight naming issue while investigating one of our a11y audit issues. The main issue of no `aria-label` has already been taking care of but the naming of the attributes was a little off. I updated it to say `aria-labelledby` to reduce confusion on what is actually be used when rendering new inputs for the key/value component.
> refactor: 💡 rename arialabel to aria-labelledby for key/value

- addons/rose/app/styles/rose/components/_index.scss
- ui/admin/app/templates/application.hbs
- ui/admin/tests/acceptance/auth-methods/delete-test.js
- ui/admin/tests/acceptance/credential-library/update-test.js
- ui/admin/tests/acceptance/credential-store/credentials/delete-test.js
- ui/admin/tests/acceptance/credential-store/credentials/update-test.js
- ui/admin/tests/acceptance/credential-store/update-test.js
- ui/admin/tests/acceptance/host-catalogs/delete-test.js
- ui/admin/tests/acceptance/host-catalogs/host-sets/update-test.js
- ui/admin/tests/acceptance/host-catalogs/hosts/update-test.js
- ui/admin/tests/acceptance/host-catalogs/update-test.js
- ui/admin/tests/acceptance/roles/global-scope-test.js
- ui/admin/tests/acceptance/roles/org-scope-test.js
- ui/admin/tests/acceptance/scopes/delete-test.js
- ui/admin/tests/acceptance/scopes/update-test.js
- ui/admin/tests/acceptance/storage-buckets/delete-test.js
- ui/admin/tests/acceptance/targets/delete-test.js
- ui/admin/tests/acceptance/targets/host-sources-test.js
- ui/admin/tests/acceptance/targets/update-test.js
- ui/admin/tests/acceptance/targets/workers-test.js
- ui/admin/tests/acceptance/users/delete-test.js
- ui/admin/tests/acceptance/users/update-test.js
- ui/admin/tests/acceptance/workers/create-tags-test.js
- ui/admin/tests/helpers/selectors.js
Replace `Rose::Dialog` component with `Hds::Modal` component in admin ui.
This change caused 63 tests to fail, which have also been fixed in this PR.
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-15647)
Before 👇 
After 👇 
https://github.com/user-attachments/assets/e25f49ce-7820-4592-8014-c4af4734af65
1. Navigate to Targets
2. Enter any text in a required field
3. Navigate to another section in navbar to trigger modal
> [ICU-15647] Replace Rose::Dialog with Hds::Modal in admin ui only

- ui/admin/app/components/form/storage-bucket/aws/index.hbs
- ui/admin/app/components/form/storage-bucket/minio/index.hbs
Fix hds code block error manifesting itself when model is saving and code block is empty.
Error msg:
After fix:
https://github.com/user-attachments/assets/00fc504d-228b-4a59-8ae3-4eb89daa74c1
1. Go to new storage bucket form
2. Try to save without a value in the code editor
3. Make sure no error is in the console.
> fix: 🐛 code block error in console when value is empty on save

- e2e-tests/admin/pages/auth-methods.js
- e2e-tests/admin/tests/auth-method-ldap.spec.js
- e2e-tests/admin/tests/auth-method-oidc-vault.spec.js
- e2e-tests/admin/tests/fixtures/auth-policy.hcl
- e2e-tests/helpers/vault-cli.js
This PR adds an e2e test for creating an OIDC auth method. This test can be run using CE and ENT editions against either docker or AWS infrastructure. 
https://github.com/user-attachments/assets/602db01e-779a-430a-8d0f-84d9d1fa353b
https://hashicorp.atlassian.net/browse/ICU-16068
> test(e2e): Add Admin UI test for OIDC auth method

- e2e-tests/admin/pages/host-catalogs.js
- e2e-tests/admin/pages/sessions.js
- e2e-tests/admin/playwright.config.js
- e2e-tests/admin/tests/alias-ent.spec.js
- e2e-tests/admin/tests/alias.spec.js
- e2e-tests/admin/tests/auth-method-ldap.spec.js
- e2e-tests/admin/tests/auth-method-password.spec.js
- e2e-tests/admin/tests/credential-store-static-ent.spec.js
- e2e-tests/admin/tests/credential-store-static.spec.js
- e2e-tests/admin/tests/credential-store-vault-ent.spec.js
- e2e-tests/admin/tests/credential-store-vault.spec.js
- e2e-tests/admin/tests/delete-resources-ent.spec.js
- e2e-tests/admin/tests/delete-resources.spec.js
- e2e-tests/admin/tests/dynamic-host-catalog-aws-ent.spec.js
- e2e-tests/admin/tests/dynamic-host-catalog-aws.spec.js
- e2e-tests/admin/tests/global-settings.spec.js
- e2e-tests/admin/tests/group-role.spec.js
- e2e-tests/admin/tests/login.spec.js
- e2e-tests/admin/tests/pagination.spec.js
- e2e-tests/admin/tests/session-recording-aws-ent.spec.js
- e2e-tests/admin/tests/session-recording-minio-ent.spec.js
- e2e-tests/admin/tests/ssh-certificate-injection-vault-ent.spec.js
- e2e-tests/admin/tests/ssh-credential-injection-vault-ent.spec.js
- e2e-tests/admin/tests/target-ent.spec.js
- e2e-tests/admin/tests/target.spec.js
- e2e-tests/admin/tests/worker-ent.spec.js
- e2e-tests/admin/tests/worker-tags.spec.js
- e2e-tests/admin/tests/worker.spec.js
- e2e-tests/helpers/boundary-cli/connect.js
This PR is a follow-up to this comment: https://github.com/hashicorp/boundary-ui/pull/2563#discussion_r1842641348
This PR adds additional assertions to UI tests, specifically, ensuring that a session is successfully created after setting up resources via the Admin UI. 
Run e2e tests
https://hashicorp.atlassian.net/browse/ICU-15765
> test(e2e): Add additional assertions to UI tests

- ui/admin/app/controllers/scopes/scope/authenticate/method/oidc.js
- ui/admin/app/routes/scopes/scope/authenticate/method/oidc.js
- ui/admin/app/templates/scopes/scope/authenticate/method/oidc.hbs
- ui/desktop/app/controllers/scopes/scope/authenticate/method/oidc.js
- ui/desktop/app/routes/scopes/scope/authenticate/method/oidc.js
- ui/desktop/app/templates/scopes/scope/authenticate/method/oidc.hbs
- ui/desktop/electron-app/src/index.js
Looks like I missed a case when fixing the retry bug.
So the retry link was only working when using localhost env and this needs to be tested with secure oidc auth.
https://github.com/user-attachments/assets/b58786a9-eeda-4916-b1ca-0b5fc9cab3d4
1. Use hcpb cluster w/ oidc auth method configured
2. Click sign in
3. Authentication Pending should appear.
4. Clicking "Retry" link should open new window.
> fix: 🐛 oidc retry not working for secure links in desktop ui

- addons/api/addon/generated/models/host-catalog.js
- addons/api/mirage/factories/host-catalog.js
- addons/api/tests/unit/serializers/application-test.js
- addons/api/tests/unit/serializers/host-catalog-test.js
- addons/core/translations/resources/en-us.yaml
- ui/admin/app/components/form/host-catalog/aws/index.hbs
- ui/admin/app/components/form/host-catalog/gcp/index.hbs
- ui/admin/config/features.js
- ui/admin/tests/acceptance/host-catalogs/create-test.js
This PR adds `worker_filter` field and updates the copy for `private_key` field 
> chore: Updates to gcp hc form

- addons/rose/app/styles/rose/variables/color/_css.scss
Looks like the dark mode css property was not being overridden causing the text in the hds dialog box to be the wrong color when system color mode was set to dark but admin ui was set to light mode.
After:
https://github.com/user-attachments/assets/66db146f-6f49-4e5b-aec2-0de2f9b04af5
Before:
https://github.com/user-attachments/assets/ec98e1d9-6e84-470f-974a-a2eb8ea8c128
1. Turn on "Dark mode" in system.
2. Have light mode enabled in admin ui
3. Go to a resource form
4. Click "Edit Form"
5. Make a trivial change
6. Navigate away from form to trigger "Discard unsaved changes?" modal
7. Validate Modal text appears as it should.
8. Repeat steps with different color setting combinations.
> fix: 🐛 hds modal text wrong color when system mode is dark

- ui/admin/app/components/credential-stores/credential-store/actions/index.hbs
Fix HDS deprecation message for HDS Dropdown interactive component using @text rather than yielding it.
Before:
After:
- Open the manage dropdown within a Credential store with the browser console open.
- Run admin ui tests successfully.
> fix: 🐛 Fix HDS deprecation message

- e2e-tests/admin/pages/storage-buckets.js
- e2e-tests/admin/pages/targets.js
- e2e-tests/admin/tests/auth-method-ldap.spec.js
- e2e-tests/admin/tests/auth-method-oidc-vault.spec.js
- e2e-tests/admin/tests/target.spec.js
This PR updates the Admin UI e2e tests to account for some updates in Boundary 0.19.0. 
- updates the auth method "inactive" locator 
- updates locators due to the worker filter changes
- fixes a flake in a test to make sure we want for the orgs page to load before clicking the auth methods link (since there's also an auth methods link on the global page)
Run all Admin UI e2e tests
> test(e2e/admin): Updates for 0.19.0

- ui/admin/app/components/form/credential-store/vault/index.hbs
- ui/admin/app/components/form/storage-bucket/aws/index.hbs
- ui/admin/app/components/form/storage-bucket/minio/index.hbs
- ui/admin/app/styles/app.scss
- ui/admin/app/templates/scopes/scope/credential-stores/credential-store/worker-filter.hbs
- ui/admin/tests/acceptance/credential-store/create-test.js
- ui/admin/tests/acceptance/credential-store/selectors.js
This PR adds the worker filter generator to the form when creating a new vault credential store.
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-16281)
Before 👇 
After 👇 
1. Create a new vault credential store
2. Confirm that the worker filter generator exists on the form upon creation
3. Save the form
4. Confirm that the worker filter generator is no longer visible on the form after creation
5. Confirm that you are able to edit the worker filter via the `Worker Filter` tab
> Vault cred store filter create

- ui/admin/app/components/form/worker-filter/index.hbs
- ui/admin/app/components/worker-filter-generator/index.js
- ui/admin/tests/integration/components/worker-filter-generator/index-test.js
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-16282
This change makes it so we can determine if the "Show filter generator" is toggled on by default or not. When the generator is used in a longer form like creating a Vault credential store or storage bucket, we want to hide the generator. This keeps the form from being overly long. In places like the Worker Filter tab for Target for Vault credential store, we have a route dedicated to updating the worker filter where showing the generator by default makes more sense.
New Storage Bucket:
https://github.com/user-attachments/assets/629e6f7a-c9a5-465e-bd20-902035b4c422
New Vault credential store:
https://github.com/user-attachments/assets/f99bfc22-db29-425f-b6b5-f4cf60b2a3b0
Editing Vault credential store worker filter: …
> feat: 🎸 add showFilterGenerator to WorkerFilterGenerator comp

- ui/admin/tests/acceptance/auth-methods/delete-test.js
- ui/admin/tests/acceptance/auth-methods/selectors.js
BE AWARE: this PR is not release dependant. Does not need to be included in the current release.
Refactor auth-method delete test selectors
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-15462)
- Run `yarn test` within `boundar-ui/ui/admin`.
> Refactor auth-method delete test selectors

- e2e-tests/desktop/tests/credentials.spec.js
This pr adds more test cases to e2e credentials display test 
- Follow the e2e readme to use enos and then cd into e2e-tests and run `yarn run desktop` 
> chore: add more test cases to credential display e2e test

- addons/api/addon/adapters/application.js
- addons/api/addon/mixins/adapter-build-url.js
- addons/api/addon/models/session-recording.js
- ui/admin/app/abilities/session-recording.js
- ui/admin/app/controllers/scopes/scope/session-recordings/session-recording/channels-by-connection/index.js
- ui/admin/app/templates/scopes/scope/session-recordings/session-recording/channels-by-connection/index.hbs
- ui/admin/tests/unit/abilities/session-recording-test.js
When a delete fails on a session-recording, the `isDeleted` attribute is set to `true` but `isDestroyed` is set to `false` so when we try to use `this.save` on model it sends another `DELETE` request instead of a `POST` request for the `reapply-storage-policy` method. Solution was to `rollbackAttributes` after a failed `DELETE`.
Additionally, hide delete button when storage policy is retain "forever" on a session recording.
BEFORE:
https://github.com/user-attachments/assets/5d841191-f87e-4690-8914-211765132526
AFTER:
https://github.com/user-attachments/assets/0fbd3f9b-b003-49e1-9b24-9c9d6ba1ef7f
hide delete button when retain policy is "Forever"
Uploading Screen Recording 2025-02-04 at 1.23.35 PM.mov…
> fix: 🐛 reapply storage policy errors out after a failed delete

- ui/desktop/electron-app/yarn.lock
- yarn.lock
Fix the [dependabot alerts](https://github.com/hashicorp/boundary-ui/security/dependabot) for `cross-spawn`. I believe when we were cleaning up the security alerts last time there was no version that had the updated fix yet.
> chore: 🤖 Upgrade cross-spawn versions to resolve security alert

- addons/api/addon/generated/models/host-set.js
- addons/api/addon/generated/models/storage-bucket.js
- addons/api/addon/serializers/application.js
- addons/api/addon/serializers/storage-bucket.js
- addons/api/tests/unit/serializers/application-test.js
- addons/api/tests/unit/serializers/host-set-test.js
- addons/api/tests/unit/serializers/storage-bucket-test.js
This PR  adds the `trimWhitespace` property to **storage bucket** and **host set** model attrs, and trims whitespace on serializer values before sending to the backend.
Context:
A bug was reported on the storage bucket and host set forms. The fields that will err if the values are not trimmed are: `role_arn`, `region`, and `preferred_endpoints`. We are handling this at the application level to account for the possibility that there may be other form fields that need to be trimmed in the future.
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-15403)
Before: 👇 
After: 👇 
1. Spin up an env using: `ENABLE_MIRAGE=false API_HOST=http://localhost:9200 yarn start`
2. Navigate to Storage Bucket in left side navbar
3. Create a new storage bucket and make sure to fill either …
> [ICU-15403] Trim whitespace on storage buckets and host sets json attrs serializers

- e2e-tests/admin/tests/credential-store-vault-ent.spec.js
- e2e-tests/admin/tests/credential-store-vault.spec.js
- e2e-tests/admin/tests/delete-resources-ent.spec.js
- e2e-tests/admin/tests/delete-resources.spec.js
- e2e-tests/admin/tests/ssh-certificate-injection-vault-ent.spec.js
- e2e-tests/admin/tests/ssh-credential-injection-vault-ent.spec.js
- e2e-tests/desktop/tests/credentials.spec.js
Prefer `afterEach` for vault resource cleanup. This leaves the state clean and ready for the next test or test suite. If this wasn't done, the next following test or test suite would also rely on `beforeEach` tests for clean up before running.
Setup scenarios for ce/ent by docker/aws by admin/desktop and run the corresponding tests changed in this PR:
```
Running 3 tests using 1 worker
✓  1 [chromium] › tests/credential-store-vault.spec.js:40:1 › Vault Credential Store (User & Key Pair) @ce @aws @docker (11.1s)
✓  2 [firefox] › tests/credential-store-vault.spec.js:40:1 › Vault Credential Store (User & Key Pair) @ce @aws @docker (13.0s)
✓  3 [webkit] › tests/credential-store-vault.spec.js:40:1 › Vault Credential Store (User & Key Pair) @ce @aws @docker (12.0s)
3 passed (38.9s)
```
``` …
```
> test: update e2e tests with `afterEach` cleanup

- e2e-tests/.eslintrc.cjs
- e2e-tests/admin/tests/alias-ent.spec.js
- e2e-tests/admin/tests/alias.spec.js
- e2e-tests/admin/tests/auth-method-ldap.spec.js
- e2e-tests/admin/tests/auth-method-oidc-vault.spec.js
- e2e-tests/admin/tests/dynamic-host-catalog-aws-ent.spec.js
- e2e-tests/admin/tests/dynamic-host-catalog-aws.spec.js
- e2e-tests/admin/tests/login.spec.js
- e2e-tests/admin/tests/worker-tags.spec.js
- e2e-tests/desktop/tests/authentication.spec.js
- e2e-tests/desktop/tests/credentials.spec.js
- e2e-tests/desktop/tests/scope.spec.js
- e2e-tests/desktop/tests/sessions.spec.js
- e2e-tests/desktop/tests/settings.spec.js
- e2e-tests/desktop/tests/targets.spec.js
- e2e-tests/package.json
- yarn.lock
This prs adds the [`eslint-plugin-playwright`](https://github.com/playwright-community/eslint-plugin-playwright) eslint rule with the recommended rules applied.
There are 110 new warnings reported, most of which are either:
* `Avoid having conditionals in tests  (playwright/no-conditional-in-test)`
* `Test has no assertions (playwright/expect-expect)`
We could:
1. leave these warnings
2. ignore them individually
3. ignore them globally within our eslint config
I think these are good warnings to have though so I'd recommend either option 1. or 2.
1. Add an `async` to a describe block callback
6. Error should be reported by `yarn lint` and/or within the editor
~~- [ …
> chore: add `eslint-plugin-playwright` rules for e2e tests and fix errors

- e2e-tests/admin/tests/alias-ent.spec.js
- e2e-tests/admin/tests/alias.spec.js
- e2e-tests/admin/tests/auth-method-ldap.spec.js
- e2e-tests/admin/tests/auth-method-oidc-vault.spec.js
- e2e-tests/admin/tests/auth-method-password.spec.js
- e2e-tests/admin/tests/credential-store-static-ent.spec.js
- e2e-tests/admin/tests/credential-store-static.spec.js
- e2e-tests/admin/tests/credential-store-vault-ent.spec.js
- e2e-tests/admin/tests/credential-store-vault.spec.js
- e2e-tests/admin/tests/delete-resources-ent.spec.js
- e2e-tests/admin/tests/delete-resources.spec.js
- e2e-tests/admin/tests/dynamic-host-catalog-aws-ent.spec.js
- e2e-tests/admin/tests/dynamic-host-catalog-aws.spec.js
- e2e-tests/admin/tests/global-settings.spec.js
- e2e-tests/admin/tests/group-role.spec.js
- e2e-tests/admin/tests/login.spec.js
- e2e-tests/admin/tests/pagination.spec.js
- e2e-tests/admin/tests/session-recording-aws-ent.spec.js
- e2e-tests/admin/tests/session-recording-minio-ent.spec.js
- e2e-tests/admin/tests/ssh-certificate-injection-vault-ent.spec.js
- e2e-tests/admin/tests/ssh-credential-injection-vault-ent.spec.js
- e2e-tests/admin/tests/target-ent.spec.js
- e2e-tests/admin/tests/target.spec.js
- e2e-tests/admin/tests/worker-ent.spec.js
- e2e-tests/admin/tests/worker-tags.spec.js
- e2e-tests/admin/tests/worker.spec.js
- yarn.lock
This PR updates the Admin UI e2e test suite to use the new playwright tag syntax on tests. More info about the change can be found here: https://dev.to/playwright/tagging-your-playwright-tests-3omm
The amount of lines changed is a little deceptive. My only changes are taking out the tags from the test name and adding it to the tag field
```
'Set up alias from target details page @ent @aws @docker'
```
```
'Set up alias from target details page',
{ tag: ['@ent', '@aws', '@docker'] },
```
The rest of the changes are spacing changes coming from the auto-formatter.
https://hashicorp.atlassian.net/browse/ICU-16048
Ran e2e tests and compared results against `main`. The same tests were run in both cases. 
```
❯ yarn admin:ent:docker --project=chromium …
```
> test(e2e): Use new tags syntax

- addons/api/package.json
- addons/auth/package.json
- addons/core/package.json
- addons/rose/package.json
- e2e-tests/.eslintignore
- e2e-tests/desktop/tests/credentials.spec.js
- e2e-tests/package.json
- ui/admin/package.json
- ui/desktop/package.json
This pull request fixes two eslint-related issues found from #2680, and one discovered follow up in investigating how an auto-fixable eslint change could have been missed by`lint-staged`.
1. An eslintignore is added to e2e to ignore the reports directory from playwright that may contain javascript (from @calcaide 's [comment](https://github.com/hashicorp/boundary-ui/pull/2680#issuecomment-2654318107))
2. An [auto-fixable changes](https://github.com/hashicorp/boundary-ui/compare/hashicc/e2e-tests-eslintignore?expand=1#diff-411688c020c9741d39b6c48029c502b7b4c831aa55f11a0f40dbfbe496bf7c77) that wasn't committed from [#2680](https://github.com/hashicorp/boundary-ui/pull/2680)
3. Avoid race conditions when `lint-staged` is running based on their …
> chore: fix eslint-related issues

- e2e-tests/admin/tests/session-recording-aws-ent.spec.js
- e2e-tests/admin/tests/session-recording-minio-ent.spec.js
In the Admin UI test suite, the session recording tests would attempt to delete a session recording when the policy did not allow it and expect an error. However, it seems there was a [recent UI change](https://github.com/hashicorp/boundary-ui/pull/2674) that removed that ability altogether (the delete option isn't shown), so this PR removes this check.
https://hashicorp.atlassian.net/browse/ICU-16377
```
❯ yarn admin:ent:docker --project=chromium tests/session-recording-minio-ent.spec.js        
yarn run v1.22.22
$ yarn run admin --grep "(?=.*@ent)(?=.*@docker)" --project=chromium tests/session-recording-minio-ent.spec.js
$ yarn playwright test --config admin/playwright.config.js --grep '(?=.*@ent)(?=.*@docker)' --project=chromium tests/session-recording-minio-ent.spec.js
$ …
```
> test(e2e): Remove attempt to delete session recording due to UI change

- addons/api/addon/handlers/cache-daemon-handler.js
- addons/core/.eslintrc.js
- addons/core/addon/decorators/notify.js
- ui/desktop/.eslintrc.js
- ui/desktop/app/controllers/cluster-url.js
- ui/desktop/app/routes/application.js
- ui/desktop/app/routes/scopes/scope/projects.js
- ui/desktop/app/routes/scopes/scope/projects/sessions/session.js
- ui/desktop/app/routes/scopes/scope/projects/targets/index.js
- ui/desktop/app/services/cluster-url.js
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-16334
I took this approach to make adding error logs for desktop client easier. The plan is if we need add logs, we can simply add `log: true` to the options object of the `notifyError` decorator. 
The scope of this PR is just to add this logging. I am reaching out to product about which errors we show in the desktop compared to the logs. They likely should be the same now and if product is good with that I will update this specific instance to show the error to the user and record it to the log file.
> feat: 🎸 add logging to notifyError decorator

- ui/desktop/electron-app/config/desktop.js
Currently building the DC fails if you don't set the `RELEASE_COMMIT` env which usually happens when building in development. I just also set a dummy `0.0.0` for the raw release version variable.
Building DC works without setting any env variables. 
> fix: 🐛 Fix development build for desktop client

- yarn.lock
This resolves 3 dependabot alerts: 
https://github.com/hashicorp/boundary-ui/security/dependabot/177
https://github.com/hashicorp/boundary-ui/security/dependabot/173
https://github.com/hashicorp/boundary-ui/security/dependabot/175
The fourth alert doesn't have a released version that fixes it yet. 
* `solid-js`
* Able to just directly upgrade to a patched version
* `path-to-regexp`
* Upgraded `express` to `4.21.2` which pulls in the patched version
* `nanoid`
* Able to directly upgrade to a patched version
> chore: 🤖 audit security alerts

- e2e-tests/README.md
- e2e-tests/admin/playwright.config.js
- e2e-tests/admin/tests/alias-ent.spec.js
- e2e-tests/admin/tests/alias.spec.js
- e2e-tests/admin/tests/auth-method-ldap.spec.js
- e2e-tests/admin/tests/auth-method-oidc-vault.spec.js
- e2e-tests/admin/tests/auth-method-password.spec.js
- e2e-tests/admin/tests/credential-store-static-ent.spec.js
- e2e-tests/admin/tests/credential-store-static.spec.js
- e2e-tests/admin/tests/credential-store-vault-ent.spec.js
- e2e-tests/admin/tests/credential-store-vault.spec.js
- e2e-tests/admin/tests/delete-resources-ent.spec.js
- e2e-tests/admin/tests/delete-resources.spec.js
- e2e-tests/admin/tests/dynamic-host-catalog-aws-ent.spec.js
- e2e-tests/admin/tests/dynamic-host-catalog-aws.spec.js
- e2e-tests/admin/tests/global-settings.spec.js
- e2e-tests/admin/tests/group-role.spec.js
- e2e-tests/admin/tests/session-recording-aws-ent.spec.js
- e2e-tests/admin/tests/session-recording-minio-ent.spec.js
- e2e-tests/admin/tests/ssh-certificate-injection-vault-ent.spec.js
- e2e-tests/admin/tests/ssh-credential-injection-vault-ent.spec.js
- e2e-tests/admin/tests/target-ent.spec.js
- e2e-tests/admin/tests/target.spec.js
- e2e-tests/global-setup.js
This PR updates the Admin UI e2e test suite to support running against a local version of the Admin UI independent of the UI that's bundled with a Boundary binary. This required a decoupling of the address used by the browser vs the Boundary CLI. To accomplish this, this PR adds a new environment variable `BOUNDARY_ADDR_BRANCH`. If this is set, the test suite will use that address for the browser. That way, we can run 
```
ember serve 
BOUNDARY_ADDR_BRANCH=http://localhost:4200 yarn run ...
```
The README was updated to include instructions for how to use it.
https://hashicorp.atlassian.net/browse/ICU-16563
Follow instructions outlined in README updates
```
❯ export BOUNDARY_ADDR_BRANCH="http://localhost:4200" # This is the URL provided by the first terminal
❯ yarn admin:ent:docker …
```
> test(e2e): Enable Admin UI e2e tests to run against a local branch

- ui/admin/tests/acceptance/develop-test.js
Updated use of `data-test` selector and fix false positive test.
This test case is an example of a time when creating an external file called `selectors` does not make sense. The selector is only used 2 times and only in this file. Perfect example of when going against the new norm is ok.
> test: 💍 fix false positive test

- addons/rose/tests/dummy/config/environment.js
- ui/desktop/config/environment.js
Within Desktop Client, we never deprecated auto location, [more info about this deprecation here](https://deprecations.emberjs.com/id/deprecate-auto-location). Therefore, when running the DC in the browser we were seeing 2 deprecations messages:
1. Using `auto` as value has been deprecated. So only `hash` or `history` are accepted.
2. Using detection code at `locationType` setting.
To solve 1, we decide to change `auto` to use `history`. [As per documentation](https://guides.emberjs.com/release/configuring-ember/specifying-url-type/), `auto` will uses `history` if supported by the browsers and fallback to `hash` if not. Since we are pretty sure the browser used by electron supports `history`, is safe to directly uses `history`.
To solve 2, we decide to set a const with the value before we …
> Fix locationType deprecations.

- ui/admin/app/templates/scopes/scope/groups/group/members.hbs
- ui/admin/tests/acceptance/groups/delete-test.js
- ui/admin/tests/acceptance/groups/members-test.js
- ui/admin/tests/acceptance/groups/selectors.js
- ui/admin/tests/helpers/selectors.js
[jira](https://hashicorp.atlassian.net/browse/ICU-15485)
- [x ] I have added tests that prove my fix is effective or that my feature works
> refactor: 💡 use test selector in groups/members route

- ui/admin/app/components/breadcrumbs/container/index.hbs
- ui/admin/app/components/breadcrumbs/container/index.js
- ui/admin/app/components/breadcrumbs/item/index.hbs
- ui/admin/app/components/breadcrumbs/item/index.js
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-16535)
Remove usage of `{{did-insert}}` which is part of [ember-render-modifiers](https://github.com/emberjs/ember-render-modifiers) package. Usage of this was intended only for migrating off of classic ember components. `ember-modifier` can be[ easily used instead](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-at-ember-render-modifiers.md). Our use cases was limited to our breadcrumb components for accessing the dom element.
CI tests should be sufficient.
> Icu 16535 refactor usage of did insert modifiers

- .github/workflows/monorepo-validate.yaml
Our self hosted runner [images](https://github.com/hashicorp/crt-github-runners/releases/tag/ubuntu-22.04-x86_64-78abdae-13654489443) don't include chrome by default so we'll need to manually include it for our tests.
> chore: 🤖 Add chrome for self hosted runners when running tests

- ui/admin/app/controllers/scopes/scope/aliases/index.js
- ui/admin/app/controllers/scopes/scope/auth-methods/index.js
- ui/admin/app/controllers/scopes/scope/credential-stores/index.js
- ui/admin/app/controllers/scopes/scope/groups/index.js
- ui/admin/app/controllers/scopes/scope/host-catalogs/index.js
- ui/admin/app/controllers/scopes/scope/roles/index.js
- ui/admin/app/controllers/scopes/scope/roles/role/manage-scopes/manage-custom-scopes.js
- ui/admin/app/controllers/scopes/scope/roles/role/manage-scopes/manage-org-projects.js
- ui/admin/app/controllers/scopes/scope/roles/role/scopes.js
- ui/admin/app/controllers/scopes/scope/scopes/index.js
- ui/admin/app/controllers/scopes/scope/session-recordings/index.js
- ui/admin/app/controllers/scopes/scope/sessions/index.js
- ui/admin/app/controllers/scopes/scope/targets/index.js
- ui/admin/app/controllers/scopes/scope/users/index.js
- ui/admin/app/routes/scopes/scope/aliases/index.js
- ui/admin/app/routes/scopes/scope/auth-methods/index.js
- ui/admin/app/routes/scopes/scope/credential-stores/index.js
- ui/admin/app/routes/scopes/scope/groups/index.js
- ui/admin/app/routes/scopes/scope/host-catalogs/index.js
- ui/admin/app/routes/scopes/scope/roles/index.js
- ui/admin/app/routes/scopes/scope/roles/role/manage-scopes/manage-custom-scopes.js
- ui/admin/app/routes/scopes/scope/roles/role/manage-scopes/manage-org-projects.js
- ui/admin/app/routes/scopes/scope/roles/role/scopes.js
- ui/admin/app/routes/scopes/scope/scopes/index.js
- ui/admin/app/routes/scopes/scope/session-recordings/index.js
- ui/admin/app/routes/scopes/scope/sessions/index.js
- ui/admin/app/routes/scopes/scope/targets/index.js
- ui/admin/app/routes/scopes/scope/users/index.js
This is a follow up to https://github.com/hashicorp/boundary-ui/pull/2723 to also use tasks in admin UI to fix the search field debounce issue.
Try typing in the search field for various resources at different speeds.
> Fix Searchbar debouncing in admin UI

- ui/admin/app/templates/scopes/scope/roles/index.hbs
- ui/admin/tests/acceptance/roles/create-test.js
- ui/admin/tests/acceptance/roles/selectors.js
- ui/admin/tests/helpers/selectors.js
Start of using test selectors for roles in the create acceptance tests
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-16405)
> chore: 🤖 use test selectors for roles create tests

- ui/desktop/electron-app/package.json
- ui/desktop/electron-app/yarn.lock
Upgrade electron-forge to latest in preparation for electron upgrade.
[Pipeline test run](https://github.com/hashicorp/boundary-desktop-releases/actions/runs/13975391991)
> Upgrade electron forge from 7.5.0 to 7.7.0

- e2e-tests/global-setup.js
As a followup to PR https://github.com/hashicorp/boundary-ui/pull/2700 and this [thread](https://hashicorp.slack.com/archives/C012GTH1C4E/p1743185621713639), we should always be using the controller URL when making HTTP requests.
This PR overrides the `request` fixture with our own custom one that forces the baseURL to be the boundary controller URL, which fixes the issue in cases when testing against a local admin branch as the baseURL for requests would then be pointing incorrectly against the locally running server. 
Try running the tests against a local branch for admin UI.
> refactor: 💡 Force requests in playwright to use controller addr

- ui/desktop/electron-app/src/config/menu.js
This change ensures that the "Check for Updates" menu is only displayed if the CLI exists.
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-15297)
Before Changes:
After Changes:
As mentioned, the "Check for Updates" menu will only be visible if the built-in CLI is included.
The CLI is included based on the build command. By default, the CLI is not included. To include the CLI, use the following command:
`SETUP_CLI=true yarn build:desktop`
After building, navigate to the build folder and run the **Boundary** app from the following location:
`<your_repo_path>/boundary-ui/ui/desktop/electron-app/out/Boundary-darwin-arm64/Boundary.app`
The CLI folder can be found at:
`<your_repo_path>/boundary-ui/ui/desktop/electron-app/out/Boundary-darwin-arm64/Boundary.app/Contents/Resource …
> feat: Conditionally display 'Check for Updates' menu item based on built-in CLI

- addons/rose/app/styles/rose/components/toolbar/_toolbar.scss
- addons/rose/tests/dummy/app/templates/playground.hbs
- ui/admin/app/components/form/field/json-secret/index.hbs
- ui/admin/app/components/form/role/grants/index.hbs
- ui/admin/app/styles/app.scss
- ui/admin/app/templates/scopes/scope/groups/group/add-members.hbs
- ui/admin/app/templates/scopes/scope/roles/role/add-principals.hbs
- ui/admin/app/templates/scopes/scope/workers/index.hbs
- ui/admin/tests/acceptance/roles/selectors.js
- ui/admin/tests/integration/components/form/field/json-secret-skeleton-test.js
- ui/desktop/app/templates/error.hbs
- ui/desktop/app/templates/scopes/scope/projects/error.hbs
This PR replaces instances of `Rose::Button` with `Hds::Button`.
1. Verify the buttons across `ui/admin` and `ui/desktop`
> Replace Rose::Button with Hds::Button

- addons/api/addon/serializers/credential-library.js
- addons/api/tests/unit/serializers/credential-library-test.js
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-16880
A user reported a bug where changing the `key_type` of a Vault SSH Certificate credential library, the update was failing. This was due to the `key_bits` value not being set to null when changing from `rsa` or `ecdsa` to `ed25519`. When using `ed25519` the `key_bits` value needs to be cleared out (set to null).
https://github.com/user-attachments/assets/33222aee-4105-4d42-a69a-0946e6c45204
Create a Vault Credential Store then a SSH Certificates Credential Library (CL). 
First create the CL with a `key_type` of `ecdsa` and define the `key_bits` to `521`.
Next, change the `key_type` to `ed25519` and click Save. It should successfully update the CL.
> fix: 🐛 credential library serializer for SSH certificate

- ui/desktop/app/components/credentials-panel/index.hbs
- ui/desktop/app/styles/app.scss
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-16869
Fix overlapping elements when viewing credentials.
Before:
After:
1. Attach a brokered credential to a target. The credential has to have a long name with no spaces.
2. Connect to that target using the DC.
3. Validate there are no overlapping elements in the session details page.
> style: 💄 fix formatting for long credential names & description

- ui/admin/app/components/form/role/grants/index.hbs
- ui/admin/app/components/form/role/grants/index.js
- ui/admin/tests/acceptance/accounts/delete-test.js
This PR replaces instances of `<input.label>` with `Hds::Form::Label`, and those instances only exist on our role/grants form.
Update:
Usage of `input.field` cause a11y violations, so we agreed to expand the scope of this ticket to also refactor the input field.
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-16831)
Before 👇 
After 👇
> [Replace] Rose::Form::Label and <input.field> elements

- yarn.lock
**BE AWARE:** This PR introduces deprecation warning from Sass as a side effect of using a more recent version. TBD ([slack thread link](https://hashicorp.slack.com/archives/C012GTH1C4E/p1746605492680669)) if the Sass deprecations will be treat it in a separate PR.
- Deprecation 1: [@import and global built-in functions](https://sass-lang.com/documentation/breaking-changes/import/)
- Deprecation 2: [Mixed Declarations](https://sass-lang.com/documentation/breaking-changes/mixed-decls/)
Dedupe dependencies.
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-16734)
- Run Admin e2e test successfully.
- Run Desktop e2e test successfully.
> Dedupe dependencies

- ui/desktop/electron-app/src/index.js
This update sets a minimum width of 812px and a minimum height of 400px for the application window.
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-4430)
No minimum width or height was enforced, which could lead to the app being resized too small to be functional:
The app now maintains a minimum window size:
1. Run the app with `yarn start:desktop`.
2. Try resizing the window — it should not shrink below 812px wide or 400px tall.
> feat: 🎉 add minimum window size for the app

- ui/desktop/app/routes/scopes/scope/authenticate/method/oidc.js
- ui/desktop/tests/unit/routes/scopes/scope/authenticate/method/oidc-test.js
Display of incorrect UI error message when the user tries to login after unsuccessful attempt.
A [ticket](https://hashicorp.atlassian.net/browse/ICU-16227) has been raised with the issue where the user encounter an error message after attempting to log in to Boundary using OpenID Connect (OIDC) with Vault as the authentication provider. While the login flow works as expected when the token is valid, user experienced unexpected behavior once the token expires - despite re-authenticating successfully, an error is displayed.
**1. Handling Expiry of Tokens**
When a user's OIDC token (from Vault) expires, they are redirected to the Vault login page for re-authentication. However, Vault fails to return a valid token back to Boundary after this process. As a result, Boundary receives an invalid …
> feat: Clear flash messages during login

- ui/admin/app/templates/scopes/scope/targets/target/host-sources.hbs
While refactoring `p` tags during HDS migration, I missed the `model` portion when referencing the description of our host sources on a target.
Before:
After:
Go to the host sources tab on a target and you should see the description of the host source now.
> fix: 🐛 fix host source description reference

- ui/admin/app/controllers/scopes/scope/groups/index.js
- ui/admin/app/routes/scopes/scope/groups/index.js
- ui/admin/app/templates/scopes/scope/groups/index.hbs
- ui/admin/tests/acceptance/groups/list-test.js
This pull request adds sorting to the groups table in Boundary Admin.
_Name and ID headers are sortable_
[Jira ticket](https://hashicorp.atlassian.net/browse/ICU-16783)
1. Pull down this branch
2. `boundary dev`
3. API_HOST=http://localhost:9200 ENABLE_MIRAGE=false yarn start
4. Open a browser at the url of the running local ember server, and navigate to the path `/scopes/global/groups`
5. Create a few groups via the "New Group" button with varying data 
6. Click through the name and id headers to sort the data
> Add sorting to Groups in boundary admin

- addons/api/mirage/factories/target.js
- e2e-tests/desktop/tests/pagination.spec.js
- ui/desktop/app/controllers/scopes/scope/projects/targets/target.js
- ui/desktop/app/templates/scopes/scope/projects/targets/target.hbs
- ui/desktop/tests/acceptance/projects/targets/target-test.js
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-17093
This PR adds the ability to display a portion of the host sources (10 by default) and allow the user to click to the next page(s) if needed. Along with selecting different options for items per page.
**Note: This feature is not using `<Rose::Pagination />` because that component is tied to the API and utilized queryParams from the route. So I use the `<Hds::Pagination::Numbered />` component directly and the page and pageSize handling lives in the controller. This work will be removed and replaced by `<Rose::Pagination />` once the backend supports host source search and filtering.** 
https://github.com/user-attachments/assets/0540c44b-11fe-436e-b981-47f58e62b1c2
Spin up the desktop client and visit a target that has more than 2 …
> feat: 🎸 add pagination to host source table

- ui/admin/app/controllers/scopes/scope/users/index.js
- ui/admin/app/routes/scopes/scope/users/index.js
- ui/admin/app/templates/scopes/scope/users/index.hbs
- ui/admin/tests/acceptance/users/list-test.js
This pull request adds sorting for the list of users in Boundary Admin
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-16787)
1. Navigate to the `/scopes/global/users`
2. Create some users
3. Click on the _Name_ or _ID_ column headers and the table should sort accordingly. Each time a column is initially sorted, the page number should reset to the first page.
> ICU-16787 sort admin users

- ui/admin/app/components/form/account/index.hbs
- ui/admin/app/components/form/account/index.js
The dynamic `{{component}}` template helper allows to load a component dynamically with arguments. This makes it impossible for ember to know which components are being used:
> Using the {{component}} helper in traditional loose handlebars template can prevent your app or addon from being statically analyzed, which will prevent you from taking advantage of staticComponents and splitAtRoutes.
- [Embroider docs](https://github.com/embroider-build/embroider/blob/6801c113faf737a5a0276b768925b63fb9fe745b/docs/replacing-component-helper.md)
Static analysis of imports is an important step in our move to vite. What prevents static analysis specifically is the the technique we use (`{{component (concat 'some/component/path' @type)}}`) where `@type` can be anything.
It should been possible to use …
> refactor: 💡 remove dynamic `component` helper from `Form::Account` component

- ui/desktop/app/controllers/scopes/scope/projects/sessions/index.js
- ui/desktop/app/controllers/scopes/scope/projects/targets/index.js
- ui/desktop/app/routes/scopes/scope/projects/sessions/index.js
- ui/desktop/app/routes/scopes/scope/projects/targets/index.js
This PR enhances the user experience of the refresh loading state in the target screen.
Previously, the refresh button would indicate completion while the global linear loader continued, creating user confusion.
With the current solution all refresh operations are awaited in the target route
ensuring the parent and child route refreshes complete before ending loading state.
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-16235) 
https://github.com/user-attachments/assets/e1098171-cd4b-41dc-8afd-1db4c035cedd
In the above video, the linear loader on the header is still visible but the circular loader in the button is completed. This is due to internal loading in progress in the target route.
https://github.com/user-attachments/assets/4d57b750-172b-4e49-9a0e-17cca31ad19e …
> Enhanced the refresh functionality in targets route

- addons/rose/app/styles/rose/components/header/_index.scss
Fix a Sass breaking change. [More info about the mixed declarations](https://sass-lang.com/documentation/breaking-changes/mixed-decls/)
- Run Admin and Desktop UI, change to dark mode and check the header still working as expected.
Warnings on terminal before the change:
Only 1 warning left after the change:
> Fix SASS deprecation

- ui/desktop/app/templates/scopes/scope.hbs
This PR adds logic to conditionally render the [separator](https://helios.hashicorp.design/components/separator) component, only when non-global orgs exist.
Before:
After:
When only the global org exists, the separator should not render. The inverse being it should render when non-global orgs exist.
> [Desktop] Conditionally render separator in nav org dropdown

- ui/admin/app/controllers/scopes/scope/aliases/index.js
- ui/admin/app/controllers/scopes/scope/auth-methods/index.js
- ui/admin/app/controllers/scopes/scope/credential-stores/index.js
- ui/admin/app/controllers/scopes/scope/groups/index.js
- ui/admin/app/controllers/scopes/scope/host-catalogs/index.js
- ui/admin/app/controllers/scopes/scope/roles/index.js
- ui/admin/app/controllers/scopes/scope/targets/index.js
- ui/admin/app/controllers/scopes/scope/users/index.js
- ui/admin/app/controllers/scopes/scope/workers/index.js
When awaiting a transition to a resource list view that implements search/filtering the original transition gets aborted since there is some sort of reload going on.
For example when saving a resource that does not have `read` permissions a user is redirected to resource list view by default and in some resources the transition was erroring out via alert toast.
Additionally when deleting a user is also redirected to list view and in some resources this transition was also erroring out.
Example of buggy behavior w/ User resource.
Before:
https://github.com/user-attachments/assets/944fbe04-eb64-41c9-a2cf-419c04c15837
After:
https://github.com/user-attachments/assets/03570fed-6910-45aa-bb92-9231d7763ead
To test delete action for aliases, and workers:
1. Navigate to existing resource.
2. …
> fix: 🐛 transition aborted error when deleting or saving

- addons/api/addon/utils/sort-results.js
- addons/api/tests/unit/utils/sort-results-test.js
Modify the string sorting to benefit uppercase over lowercase at comparison.
https://github.com/user-attachments/assets/cf1d27eb-a3c7-4abd-a0b0-f1eb7ad47ce0
Sort targets by name and see the upperCase go before lowerCase and vice versa.
This array: `['orange', 'Orange', 'banana', 'apple', 'Banana']` should become `['apple','Banana','banana','Orange','orange']`.
> Modify string sorting to benefit upperCase

- addons/api/package.json
- addons/auth/package.json
- addons/core/package.json
- addons/rose/package.json
- package.json
- pnpm-lock.yaml
- ui/admin/package.json
- ui/desktop/package.json
Bump `@glimmer/component` to v2. The breaking changes for v2 do not require any changes from us:
> BREAKING: converted to V2 addon
> BREAKING: dropped support for ember < 4.10
[Changelog](https://github.com/emberjs/ember.js/blob/main/packages/%40glimmer/component/CHANGELOG.md#200-2024-10-29)
The V2 addon part is good! And we're already on ember >= 4.10 since we're on version 5
This is such a low-level dependency for our apps that the main way to test this is for builds and CI continues to pass
~~- [ ] I …
> chore: 🤖 update `@glimmer/component` to v2

- ui/desktop/.gitignore
- ui/desktop/config/environment.js
- ui/desktop/package.json
- ui/desktop/testem.js
- ui/desktop/tests/test-helper.js
This pull request sets up the `ui/desktop` for improved a11y testing for dark and light mode:
`pnpm test-a11y` for light and `pnpm test-a11y:dark` for dark.
Also within a regular ember test the a11y can be toggled on within testem to include a11y tests.
1. Check `pnpm test-a11y` (add `-s` to launch chrome so it's not headless) (ui should be in light even in system preferences is dark)
2. 1. Check `pnpm test-a11y:dark` (add `-s` to launch chrome so it's not headless) (ui should be in dark even in system preferences is light)
3. Try `pnpm ember s`, go to `localhost:4200/tests`, and toggle the a11y checkbox toggle included a11y tests
4. Try `pnpm ember test -s`, chrome browser should launch, and toggle the a11y checkbox toggle included a11y tests
Examples of changes to security controls …
> (HACK WEEK 2025) a11y desktop test helper

- .github/workflows/a11y-tests.yaml
Update the label to trigger a11y tests from `a11y-test` to `a11y-tests`
> (HACK WEEK 2025) Fix `a11y-tests` label

- addons/api/addon/services/sqlite-db.js
- addons/api/addon/workers/shared-service.js
- addons/api/addon/workers/sqlite-worker.js
- addons/api/addon/workers/utils/shared-service.js
- addons/api/addon/workers/web-worker.js
- addons/api/broccoli-plugins/build-workers.js
- addons/api/package.json
- pnpm-lock.yaml
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-17409
This PR is the foundation to allowing multiple tab access to SQLite. We add a `shared-service` (not to be confused with an ember service) that is shared among all web workers. This allows multiple tabs to interact with SQLite by only allowing one tab to be active as the "provider" at a time. All other tabs funnel requests to the provider tab and do so by using  the shared proxy where the actual SQLite methods will live. 
It might help to test using PR #2933 to be able to interact with targets. 
A simplified example sequence diagram for a user trying to fetch a resource from a tab that doesn't have direct access to SQLite, note that the adding of event listeners is not indicated here. 
Confirm that opening another tab doesn't …
> feat: 🎸 Add a shared service between web workers

- .github/workflows/a11y-tests.yaml
- ui/admin/package.json
- ui/desktop/package.json
This pull request does a few things:
* Filters tests ran for a11y purposes to acceptance tests only
* Generates an a11y report
* Outputs the summarized version of the a11y report in CI
* Uploads the a11y report as a github artifact so that it can be downloaded from the workflow summary (and used with the codemod to ignore rules if needed)
* Fails CI if any of the reports contain an a11y violation (see https://github.com/hashicorp/boundary-ui/pull/2949/files#r2246412084 for why this is necessary)
Note: "A11y Tests / Run A11y Tests" should be failing on this PR because there are a11y test failures. Once the current failures are ignored with the codemod from #2946 then we _should_ have a passing a11y workflow in CI
Look at the last run of the "A11y Tests / Run A11y Tests" workflow on this PR …
> (HACK WEEK 2025) Upload a11y reports in ci

- addons/api/addon/handlers/indexed-db-handler.js
- addons/api/tests/unit/handlers/indexed-db-handler-test.js
- ui/admin/app/routes/scopes/scope/aliases/index.js
- ui/admin/app/routes/scopes/scope/auth-methods/index.js
- ui/admin/app/routes/scopes/scope/credential-stores/index.js
- ui/admin/app/routes/scopes/scope/groups/index.js
- ui/admin/app/routes/scopes/scope/host-catalogs/index.js
- ui/admin/app/routes/scopes/scope/roles/index.js
- ui/admin/app/routes/scopes/scope/roles/role/manage-scopes/manage-custom-scopes.js
- ui/admin/app/routes/scopes/scope/roles/role/manage-scopes/manage-org-projects.js
- ui/admin/app/routes/scopes/scope/roles/role/scopes.js
- ui/admin/app/routes/scopes/scope/scopes/index.js
- ui/admin/app/routes/scopes/scope/session-recordings/index.js
- ui/admin/app/routes/scopes/scope/targets/index.js
- ui/admin/app/routes/scopes/scope/users/index.js
Change the `peekIndexedDB` parameter to be more generic so it can also be shared with sqlite. 
Try any of the resources and confirm that it still works by using searches that bring back no results.
> refactor: 💡 Change variable name for peeking db

- addons/api/addon/services/sqlite.js
- addons/api/addon/workers/utils/schema.js
- ui/admin/app/routes/scopes/scope/aliases/index.js
- ui/admin/tests/acceptance/aliases/create-test.js
- ui/admin/tests/acceptance/aliases/delete-test.js
- ui/admin/tests/acceptance/aliases/list-test.js
- ui/admin/tests/acceptance/aliases/read-test.js
- ui/admin/tests/acceptance/aliases/update-test.js
- ui/admin/tests/unit/controllers/scopes/scope/aliases/index-test.js
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-17420
Added schema to support aliases in sqlite. Initial loads are still <100ms. 
Use the same [cluster](http://boundary-alb-lswjurcf-1368391987.us-east-1.elb.amazonaws.com:9200/) with 400k aliases as a playground. DM me if you need the credentials again
> feat: 🎸 Add sqlite support for aliases

- addons/api/addon/workers/sqlite-worker.js
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-17516
Add checks to see if we're in a [secure context](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts) as the OPFS and weblock APIs require them.
If we're not in a secure context, just start up SQLite in memory so a user still can still get full functionality just without persistence. This would then allow us to remove indexed DB in the future as we wouldn't need to ever fallback.
Setup the branch in an http environment that's not localhost. 
You could do this using enos or using a tool like ngrok. If using ngrok, you'd need to force the scheme to be http with something like `ngrok http --scheme=http 4200`. Your browser might also try and force you onto HTTPS with ngrok's urls. For Firefox, I had to set …
> Icu 17516 use in memory sqlite in non secure contexts

- addons/api/addon/services/sqlite.js
- addons/api/addon/utils/sqlite-query.js
- addons/api/addon/workers/utils/schema.js
- addons/api/tests/unit/services/sqlite-test.js
- ui/admin/tests/acceptance/credential-store/create-test.js
- ui/admin/tests/acceptance/credential-store/credentials/create-test.js
- ui/admin/tests/acceptance/credential-store/delete-test.js
- ui/admin/tests/acceptance/credential-store/update-test.js
- ui/admin/tests/acceptance/targets/brokered-credential-sources-test.js
- ui/admin/tests/acceptance/targets/injected-application-credential-sources-test.js
- ui/admin/tests/unit/controllers/scopes/scope/credential-stores/index-test.js
- ui/admin/tests/unit/controllers/scopes/scope/targets/target/add-brokered-credential-sources-test.js
- ui/admin/tests/unit/controllers/scopes/scope/targets/target/add-injected-application-credential-sources-test.js
Add sqlite support for credential stores. 
Initial load when fully cached:
Use this [cluster](http://boundary-alb-dvtowfcd-362873315.us-east-1.elb.amazonaws.com:9200) and goto the proj that's indicated that has many credential stores.  
- ~[ ] I have added `a11y-tests` label to run a11y audit tests if needed~
Examples of changes to security controls include using new access control methods, adding or removing logging pipelines, …
> feat: 🎸 Add sqlite support for credential stores

- ui/desktop/electron-app/src/models/runtime-settings.js
This fixes a bug where a user tries to disconnect if we encountered an error with the cluster URL and are met with another error in trying to disconnect and cannot enter another URL.
Use the default `serve://boundary` and try to disconnect once it fails. 
- ~[ ] I have added `a11y-tests` label to run a11y audit tests if needed~
> fix: 🐛 Fix bug that prevents setting cluster URL

- e2e-tests/admin/pages/credential-stores.js
- e2e-tests/admin/pages/targets.js
- e2e-tests/admin/tests/alias-ent.spec.js
- e2e-tests/helpers/boundary-api-client.ts
The `apiClientTestAfter` noop fixture wasn't set up properly in #2964. The noop helped in one case but not when the the api client was actually used outside of the `api-client.spec.js`, and would end up waiting indefinitely because the noop didn't call `use` (this affected the pagination and sorting e2e tests).
There are a few tests that are failing in `credential-store-static.spec` because the username and password labels now have "Required" included (see [comment](https://github.com/hashicorp/boundary-ui/pull/2994/files#r2334116745)).
```
1 skipped
17 passed (1.4m)
```
```
boundary-ui/e2e-tests on  fix-api-client-fixture-noop-dependency [$!] via  v20.19.0
🍕 pnpm admin:ce:docker --project chromium --headed
Running 28 tests using 1 worker
✓  1 [chromium] › admin/tests/alias.spec.js:22:3 …
```
> fix: 🐛 fix bug with the `apiClientTestAfter` noop fixture hanging and update e2e label username, password locators with required text

- e2e-tests/package.json
- pnpm-lock.yaml
Resolves these security scans: 
https://github.com/hashicorp/boundary-ui/security/code-scanning/191
https://github.com/hashicorp/boundary-ui/security/dependabot/198
It's not a big concern since this is only used in e2e tests but it's an easy upgrade.  
Confirm you can still generate the e2e api client. 
- ~[ ] I have added `a11y-tests` label to run a11y audit tests if needed~
Examples of changes to security controls include using …
> chore: 🤖 Update dependency for security alert

- ui/desktop/electron-app/src/models/session.js
I wasn't passing the boundary address to the CLI when canceling sessions on quit which meant it assumed it was localhost and would 404 if you were on a non localhost address when canceling. 
Try connecting with a boundary address that's not localhost and confirm quitting/logging out properly cancels sessions. 
- ~[ ] I have added `a11y-tests` label to run a11y audit tests if needed~
> fix: 🐛 Pass the addr to CLI when canceling sessions

- ui/desktop/app/controllers/scopes/scope/projects/targets/index.js
- ui/desktop/electron-app/src/helpers/spawn-promise.js
- ui/desktop/electron-app/src/ipc/handlers.js
- ui/desktop/electron-app/src/models/session-manager.js
- ui/desktop/electron-app/src/models/session.js
✅ Closes: https://hashicorp.atlassian.net/browse/ICU-17701
Currently if a session expires, we don't keep track if it's still valid or not. This means if a session has expired our session manager will still think it's a valid session and prompt the user if they try to logout or quit the app. 
Make a target with a short session duration (e.g. 15s). Connect to the target and confirm you get prompted still. Wait until the session goes past the max session duration and try to logout and quit the app. You should not get prompted anymore.
Confirm this works in all 3 OS environments.
- ~[ ] I have …
> fix: 🐛 Pass in session time out when creating session

- .github/workflows/test-e2e-desktop.yaml
This PR updates the Desktop e2e tests github action workflow to use an environment variable to pass the boundary license information as opposed to needing to create an intermediary file.
This PR also includes a change to the workflow to allow it to run on any manual invocation to allow for easier testing of changes to this workflow.
Here is an example run with these changes: https://github.com/hashicorp/boundary-ui/actions/runs/18134805881/job/51610638515
https://hashicorp.atlassian.net/browse/ICU-17175
Run desktop e2e tests using this branch: https://github.com/hashicorp/boundary-ui/actions/workflows/test-e2e-desktop.yaml
> chore(e2e): Update desktop e2e test workflow to use new environment variable

- ui/admin/app/components/form/credential-library/index.hbs
- ui/admin/app/components/form/credential-library/index.js
This pr continues the migration away from the dynamic `{{component}}` helper. More information in https://github.com/hashicorp/boundary-ui/pull/2880. This pull request focuses on migrating the credential-library form component.
:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-17285) 
* Tests should pass
* Navigate to `/scopes/:project_id/credential-stores/:credential_store_id/credential-libraries` and create or edit credential libraries. The forms for all credential types should load correctly
> Migrate away from component helper in credential library form component
